### ISSUE TITLE
README file and windows build instructions

### ISSUE THREAD

**Issue by dumbledad** [supercollider/supercollider#1034]
In the main readme file README.md it states:

>Platform specific build and install instructions can be found in the following files:
>[...]
>• README_WINDOWS.md

But as far as I can make out README_WINDOWS.md only contains installation instructions and not any build instructions

**Comment by scztt** [comment]
Still a problem. Can someone who builds on Windows fill this in a little? Even something rough is better than nothing....

**Comment by bagong** [comment]
If nobody else steps in I'll do something, but I probably can't make it before tuesday...

**Comment by bagong** [comment]
Here is a starter, if somebody is willing to chime in, highly welcome.
https://gist.github.com/bagong/c8eae2dd9919db8b8f91
The new Quarks system isn't worked in yet, if it get's to the point to work like on other platforms, it might not be necessary to mention it much in the Readme.
Currently somebody is working on a VS12/2013 build, yay! When that is done the whole build description would be extended or even replaced...

**Comment by bagong** [comment]
Since the advent of msys2 and Lucas' Cornelisse work on the VS-build SC can be build nicely with msys/MinGW and VS/msbuild. Currently the limitations are: MinGW doesn't allow for a 64-bit build yet. VS doesn't work for sc3-plugins and supernova. And right now there is a serious bug in communication between IDE and sclang, that let's the interpreter crash every few key-strokes.

Build instructions are added to README_WINDOWS.md. For now this can only be found on the branch `winport` in https://github.com/bagong/supercollider.git, but in a few weeks it should make the move.
