### ISSUE TITLE
overriden switch method still causes compiler to try to "inline it" 

### ISSUE THREAD

**Issue by miguel-negrao** [supercollider/supercollider#1055]
If a class overrides the switch method to do something completely different the compiler should not apply optimizations which are meant for Object#switch. It's possible to see that this is happening because the code bellow is triggering the same bug as #1056 which has to do with inlining Object#switch.

```
Switchy {

    switch {|foo|
        "Hello!".postln;
    }
}

a = Switchy();

a.switch(1); // posts hello

a.switch({var a;}) // posts hello

a.switch({});  // crash!
```

**Comment by miguel-negrao** [comment]
From the discussion I can see this is tricky to fix in a proper way. Is there consensus on a solution ? Any thoughts on getting this fixed for 3.7 ?  It would be nice to get this fixed for 3.7...

**Comment by scztt** [comment]
At the very least, we should see if we can show a compiler warning in case of a non-class-method overrides of switch - basically, this call will have undefined behavior and should be avoided.

Ruby is the modern language that's most similar to SC (semantically almost identical, and uses a stack-based bytecode vm) - I'm REALLY curious how they handle this. I mean, I guess we could look at other smalltalk implementations as well...

**Comment by scztt** [comment]
Hahah, yeah, afaict Ruby doesn't optimize switch statements at all - so nothing to be learned there. My suspicion is - we could compile bytecode for both the optimized and unoptimized version, and choose one at runtime depending on whether we hit an overridden method or not - and the performance impact would be very minor. It's a little bit academic, since banning method overrides of switch also seems completely acceptable. There are many things in SC that one can't subclass or properly override, so it's not a particularly unusual restriction.

**Comment by vivid-synth** [comment]
I'd vote to close as "wontfix". Objections?

**Comment by brianlheim** [comment]
I also think this is a wontfix situation. It's not worth the loss in performance.

**Comment by vivid-synth** [comment]
If anyone would like to implement a warning on attempting to override "switch", or to add a note in the docs not to do that, feel free to open a separate issue!
