### ISSUE TITLE
server command 259 quits server

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1062]
Fuzzing the server, one can find that 

```
s.sendMsg(259);
```

crashes it.

**Comment by miguel-negrao** [comment]
Wouldn't this be fixed by properly getting an int32, with something like this ?

    uint32 index = OSCint(inData) 

from sc_msg_iter.h:
```
inline int32 OSCint(const char* inData)
{
	return (int32)sc_ntohl(*(uint32*)inData);
}
```

I guess the question is if it causes a noticeable loss of performance...  
Btw, I don't think type tags are involved here, I think that is related to the arguments while here we are dealing with the OSC Address Pattern. SC seems to abuse the OSC spec by sometimes interpreting the OSC Address Pattern as an int when it should be an ["OSC-string beginning with the character '/' "](http://opensoundcontrol.org/spec-1_0).

> But I don't understand that part of the code (why do we take the command to be the third byte of the char *inData? There is some signalling going on that isn't documented, or perhaps this is simply a result of the encoding of numbers?

It's not the third byte, but the 4th. An int32 is 4 bytes long and if one assumes [big-endian](https://en.wikipedia.org/wiki/Endianness) the byte corresponding to the lowest digits is the 4th one in terms of order in memory.  It seems ints are usually transported through networks using big-endian, that's why in OSCint ntohl is called: "The ntohl() function converts the unsigned integer netlong from network byte order to host byte order.".

**Comment by jamshark70** [comment]
How about, leave it alone? Users violate the server's programming interface at their own risk.

The correct commands are documented. It's not supposed to be a baby-proof chew toy.

**Comment by telephon** [comment]
… it looked like a crash when fuzzing the server. I'm not sure if that counts as violating the interface. But I don't insist.

**Comment by vivid-synth** [comment]
Fwiw there are a lot of invalid messages that crash the server. I don't know if that's something we want to fix.

**Comment by jamshark70** [comment]
IMO genuine crashes (unhandled exceptions, segfaults) should be fixed.

The present issue doesn't fall in that category. The server misinterprets 259 as a quit command, and then quits successfully. My suggestion is that sending an undefined command is an undefined behavior and, if you want defined, predictable behaviors, stick to known commands.

"Doc, it hurts when I move my arm like that."

"So, don't move your arm like that."

**Comment by telephon** [comment]
at least it should be documented that command numbers wrap around 256?

**Comment by jamshark70** [comment]
Documentation: Yes, yes, yes!

**Comment by miguel-negrao** [comment]
> at least it should be documented that command numbers wrap around 256?

Well, that's an implementation detail. I think that what should be documented is that any command number which is not part of the set of documented command numbers results in undefined behaviour. I suppose fuzzy tests should only test within the range of inputs which are considered valid.

**Comment by vivid-synth** [comment]
Closing this - I think if we want to fix things like this it'll be part of a larger project.
