### ISSUE TITLE
fixing asCompileString

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#1158]
AdC wrote on the dev-list:

```
// sketch how asCompileString, asString, and asStringPrec should work IMHO:
f = { |float, precision = 0.0|
    var str = float.round(precision).asString;
    if (str.every(_.isDecDigit)) {str = str ++ ".0";};
    str;
};
f.value(12.0);
f.value(123.456e-30);
f.value(12.3456, 0.01);
```

as some tests in my (recent) 3.7.0 build, OSX 10.8.5 :

```
x = 12.0;
x.asString ;        //  12, ok
x.asCompileString;  // 12.000000 - why not 12.0 to make sure
                    // it becomes a Float again?

x = 123.456e-10;
x.asString;         //   1.23456e-10, fine
x.asCompileString;  // 0.000000 - this is really wrong

x = 123.456e+20;
x.asString;         //   1.23456e+22, fine
x.asCompileString;  // 12345600000000000000000.000000
                    // - this is correct, but pretty inconvenient

x = 123.456e+30;
x.asString;         //   1.23456e+22, fine
x.asCompileString;  // 123455999999999994726699283513344.000000
                    // - this may be correct, but
                    // is misleading pseudo-precision.

123.01.asStringPrec(0.001) // 1e+02 ??? 
123.456e+30.asStringPrec(12300); // this is a simple user error, but crashes 
```

**Comment by telephon** [comment]
Looking for it, I suppse it must be in DumpParseNode.cpp in the method ````int asCompileString(PyrSlot *slot, char *str)````.

Here we get for floats:
````
default :
			sprintf(str, "%f", slotRawFloat(slot));
			break;
````
But I suppose that ````sprintf```` can't be to blame? Or maybe it can?

**Comment by timblechmann** [comment]
check the reference:
http://en.cppreference.com/w/cpp/io/c/fprintf

**Comment by telephon** [comment]
Interesting. So we'll have to try different hings out whether they will fit. 

But changing the ````asCompileString```` method in ````DumpParseNode.cpp```` doesn't change the behavior.  Probably it is caught somewhere else before reaching there.

````postString```` uses the format ````sprintf(str, "%.14g", slotRawFloat(slot));````.

**Comment by baconpaul** [comment]
The place where it gets caught before that is in Common/Math/Float.sc

```
        // the correct place to implement compileString for Float is in DumpParseNode.cpp
        // int asCompileString(PyrSlot *slot, char *str)
        // for now, solve it here.

        storeOn { |stream|
                var     str;
                if(this == inf) { stream << "inf"; ^this };
                if(this == -inf) { stream << "-inf"; ^this };
                str = super.asString;
                stream << str;
                // if it doesn't already have a . or is 1e-05 then add a .0 to force it to Float
                if(str.find(".").isNil and: { str.find("e").isNil }) {
                        stream << ".0";
                }
        }

        asCompileString {
                // do not rely on _ObjectCompileString, because precision is too low
                ^String.streamContents { |stream| this.storeOn(stream) }
        }
```

although I'm not sure why it isn't fixed in the C++.  I'll poke around.

**Comment by baconpaul** [comment]
OK so I spent a bit of time looking at this.

First of all with tag "master" I see that 1.23e-10 asCompileString actually doesn't get zero. The reason for that is the code I posted above points you to asString; asString goes to the postString method in DumpNode; and that method has been modified to have format flag %.14g rather than %f (and 'g' is basically 'e' or 'f' so exponent if you need to).

So you'd think you could just remove storeOn and asCompileString above and then fix DumpNode so that asCompileString uses %.14g but if you do that then 12.0.asCompileString becomes "12". That's why there's that string.find in the code above.

So if you want to you can make it the alternative version in DumpNode, %#.14g, which gives you something like 12.000000000 and 1.234500000e-10 - basically don't strip the trailing zeros. But that's a bit ugly.

So I think for a chunk of these errors the current code with that hack in place works fine, but we probably want to change DumpNode to have a %.14g in asCompileString just in case there's another path to that default: statement not intercepted by the above.

I didn't look at the .asStringPerc variations.

**Comment by baconpaul** [comment]
The .asStringPerc is because the argument to asStringPerc is sent directly to a format statement used to sprint into a 256 char string. So

```
1.asStringPerc( 100000 )
```

ends up calling

```
sprintf( str, "%.10000000g", 1 )
```

where str is a char[ 256 ]; overflow; blammo. I have a pull request to fix that I can add.

**Comment by antonhornquist** [comment]
What's the status on this? I cannot tell from the comments or links...

Object documentation for *readArchive states the following:

```
a = Array.fill(100, { 100.0.rand });
a.writeArchive(PathName.tmp ++ "myArray");
b = Object.readArchive(PathName.tmp ++ "myArray");
a == b // true
```

Has this ever worked?

**Comment by brianlheim** [comment]
@antonhornquist 
```
(
a=100.0.rand;
b=a.asCompileString;
a==b.asFloat;
)
```
Converting between a float and a string is not something you should rely on for floating-point consistency.

As far as the documentation of *readArchive goes, that should definitely be fixed. I'm guessing it's because floats are being written as single-precision and read as double-precision.

Closing, and opening a new issue for the documentation failure.
