### ISSUE TITLE
output syntax colorization changes color after newline

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1217]
Reproducer:

```

(
{ \this_line_is_green;
\this_line_is_black;
\this_one_too;
}.asCompileString;
)

```

**Comment by telephon** [comment]
The above problem remains. Somewhere I had mentioned the idea of using invisible characters as a begin and end delimiter for the different outputs.

**Comment by scztt** [comment]
The proper solution is actual event-based logging/output in SC, that can be formatted as-needed depending on the output and metadata. I'm fine to try out hiding the metadata in invisibles for the time being, if it makes the behavior better for this release.

Any suggestions on safe characters to use? And - any thoughts on how this would affect other IDE's that read / depend on the output of sclang (meaning - it would be bad if scvim shows garbage in place of invisible characters, for example)? I'm not really sure how to test that.

**Comment by brianlheim** [comment]
http://ascii.cl/control-characters.htm

ASCII codes 18, 20, 30, 31 (17 and 19 are sometimes used for XON and XOFF on old hardware) should be absolutely safe to use.

**Comment by telephon** [comment]
ho ok, so we could use them as a delimiter to mark these special outputs? hat would be a great solution.

**Comment by brianlheim** [comment]
Hmm.. on second thought, and since this only affects the IDE, it would probably be best to use codepoints from a [Unicode Private Area](https://en.wikipedia.org/wiki/Private_Use_Areas). That way we wouldn't be at risk of running out of colors, and it would be harder for someone to accidentally hit the exact UTF-8 codepoints for the colorization scheme.

As far as this affecting other IDEs, IMO the solution is simple—posting functions only add these characters when the current editor is SC-IDE, and SC-IDE is responsible for recognizing and responding to them.

Concurrent to changing this, it might be a good idea to come up with a standard set of names for the colorizations that could be made consistent with the idea of "verbosity" we've explored in other parts of SC. The other day I was using company X's in-browser console view, and they had clearly defined 6-7 levels of verbosity, which I found extremely helpful. They correspond pretty closely with the names Scott used in his PR (which are: text, warning, error, success, emphasis), but if we're going to propagate those names outward to the rest of the language, I think it merits further discussion.

**Comment by scztt** [comment]
I'd recommend against trying to bake in log filtering to the postln behavior via hidden characters etc. This is a recipe for unexplainable slowdowns when you log millions of e.g. invisible warnings. And, we have to keep in mind - sclang has three or four supported IDE's: vim, emacs, atom, and the built-in one - building a complex post metadata system means all of these clients would need to implement that system in order to properly filter log results. Better to add a real logging package to the core library, and handle filtering/verbosity/output on the sclang side - and keep the post window metadata as simple as possible.

The only bug I'm aware of w/ the coloring is related to multiline errors - having an additional non-newline delimiter to use as a separator between separate posts would be enough to fix this. Any additional hidden metadata characters aren't going to make a functional difference - I'm not convinced it's better to have a convention where errors start with `\u2016` rather than a convention where they start with `ERROR:` as is the case now. It would be different if we were going to have many different post item types (which we don't need), or if we wanted to have intra-line formatting (formatted logs is a much different feature than a standardized format for e.g. error lines) - in those cases, more kinds of delimiters might become more functionally useful?

**Comment by scztt** [comment]
@crucialfelix Is there any particular solution that would be helpful for you when parsing error messages in the Atom plugin? It's doing more w/r/t making post output readable than the IDE is at this point - if anything, we should facilitate the Atom plugin and copy it's features. :)

**Comment by brianlheim** [comment]
I like this development path much better @scztt!

**Comment by snappizz** [comment]
Machine-readable post output from sclang is a great idea. I've added it to the long-term projects list.

**Comment by telephon** [comment]
In any case it would be good to add a newline after the `->`, so that you can copy from the REPL. It would also be good to allow to call the interpreter from the post window (as it was in the old scapp). It is a REP`L` after all :)
