### ISSUE TITLE
dumpOSC method posts status messages when it shouldn't 

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1227]
When ````skipStatus```` is set to true, the method will still post status messages.

````
static bool dumpOSCmsg(int inSize, char* inData, bool skipStatus = false)
````

**Comment by vdonnefort** [comment]
Isn't scsynth superseeded by Supernova now?

**Comment by jamshark70** [comment]
Superseded? Please, **no**. It's good, and it works beautifully for Tim's purposes, but I don't think it's ready for that kind of prime time yet. Not if its performance is weak in OSX and -- on all platforms -- it drifts out of sync with sclang (so that 200ms latency gradually turns into a second or two).

Nope. No. Not until these issues are fixed.

**Comment by telephon** [comment]
The bug is fixed in the meantime.
