### ISSUE TITLE
Supernova not finding plugins on OS X

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#1281]
I've compiled most recent SC with supernova on OS X 10.9.

Supernova boots and plays, but doesn't seem to find plugins in the ~/Library/Application Support/SuperCollider/Extensions folder. I'm getting an "Exception when reading synthdef (...) Unit generator (...) not installed" when trying to use external plugins. 
However, they work fine when copied to SuperCollider.app/Contents/Resources/plugins

**Comment by telephon** [comment]
Works fine for me under OS X 10.10 (supernova compiles out of the box, too).

**Comment by bagong** [comment]
@telephon, possibly you didn't symlink the plugins into the extensions folder? I get the same error that @dyfer found when symlinking, and no error when copying/moving the plugins into the exensions folder.

Rather than adding symlink support, it might be nice to scan for plugins in all folders added by LangConfig? After .scdoc files in LangConfig include-folders are now found, that would seem like a nice addition?

**Comment by bagong** [comment]
Hmm, it seems supernova currently requires plugins in the extensions folder to be in a subfolder called "plugins".

**Comment by telephon** [comment]
>@telephon, possibly you didn't symlink the plugins into the extensions folder?

No, I copied them into the extensions folder.

**Comment by bagong** [comment]
Just tried again, among 'SC3plugins', 'SC3Plugins' and 'plugins' only 'plugins' work for me. This looks like a regression, I am pretty sure it used to work in any location scsynth-plugins could be, Tim even once told so.

**Comment by Xon77** [comment]
I confirm that renaming 'SC3plugins' by 'plugins' in the Applications folder makes work Supernova extensions on OS X.

**Comment by miczac** [comment]
from the moment I got a working binary of supernova on 10.9 I re-located the extensions to 
`~/Library/Application\ Support/SuperCollider.37x/Extensions/plugins/`
which works fine for scsynth _and_ supernova.
scsynth accepts (virtually?) everything from under `~/Library/Application\ Support/SuperCollider.37x/Extensions/` so that's an ok workaround, IMHO.

**Comment by bagong** [comment]
@miczac I think it is not documented that for supernova you are bound to the directory "plugins" in extensions. And I think it's not actually intended. Certainly not a big issue, but something somebody can easily fail at realizing. Isn't it, that you yourself are an example of missing out on it ;) ?
Btw, how do you make SC recognize SuperCollider.37x as userAppSupportDir? That is useful!

**Comment by miczac** [comment]
@bagong 
> how do you make SC recognize SuperCollider.37x as userAppSupportDir?
ah, sorry - copy'n'paste error: `~/Library/Application\ Support/SuperCollider.37x/` is a directory a symbolic link named `~/Library/Application\ Support/SuperCollider/` points at. I change this link and launch the desired version of SC via a simple Automator/bash script construct which then is an icon somewhere in the dock or on the desktop.

**Comment by dyfer** [comment]
This was fixed with https://github.com/supercollider/supercollider/pull/3815
