### ISSUE TITLE
OSCdef:free does not free OSCdef when (srcID != nil)

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#1306]
```[supercollider]
// A netAddr
n = NetAddr.localAddr;

// loopback messages to localhost
Routine{loop{
	n.sendMsg("/a", 1, 2, 3, 4, 5, 6, 7, 8, 9, 10);
	0.1.wait;
}}.play

OSCdef(\a, {|msg| msg.postln}, "/a"); // no srcID
OSCdef(\a).free; // works


OSCdef(\a, {|msg| msg.postln}, "/a", n); // specific srcID
OSCdef(\a).free; // does not free the OSCdef
```

**Comment by muellmusik** [comment]
Okay, issue seems to have been introduced by another fix. In the dispatcher's remove method:

```keys.do({|key| active[key] = active[key].copy.removeFunc(func) });```

Object::removeFunc tests if the receiver === func and returns nil. In the simple case of a function, it works because for a Function f ```f === f.copy``` returns true. Very fixable, just need to consider the best way to do it.

**Comment by muellmusik** [comment]
Possibly simplest and most efficient is to override removeFunc in AbstractMessageMatcher.

**Comment by LFSaw** [comment]
thanks, @muellmusik for looking into it. 
So, you mean that it breaks in ```AbstractWrappingDispatcher:remove```.
```AbstractMessageMatcher``` should therefore look like this, then?

This is a prepared chunk, just don't know what it should really do...
```
AbstractMessageMatcher {
	var <>func;

	value { this.subclassResponsibility(thisMethod) }

	valueArray {arg args; ^this.value(*args) } // needed to work in FunctionLists

// this would indeed just do what it normally does... unclear to me how to fix it...
	removeFunc { arg function; if(this.func === function) { ^nil } }
}
```

**Comment by muellmusik** [comment]
Not quite, I think. We should return nil if ```function``` is not equivalent to ```this```, i.e. if function is an AbstractMessageMatcher of the same type and with the same func. We need to be careful how we do this, since ```function``` could be a Function or some other type, like a Routine or something.

So maybe:
```
AbstractMessageMatcher {
    var <>func;

    value { this.subclassResponsibility(thisMethod) }

    valueArray {arg args; ^this.value(*args) } // needed to work in FunctionLists

    == {|anObject| ^(anObject.class === this.class && {anObject.func === this.func}) } // subclasses will need to implement == as well to test that instance vars match

    removeFunc { arg function; if(function == this) { ^nil } }
}
```
Not tested, but I think that is safe and should work.

The other way I could think of is to override copy for AbstractMessageMatcher to behave as it does for Function, but I think that should only be done for immutable objects, or?

Or rethink the previous fix. There are other approaches to that.

**Comment by muellmusik** [comment]
So I think options are:

1) override removeFunc in AbstractMessageMatcher, adding == there and in all subclasses
2) override copy in AbstractMessageMatcher. The setter for func is not needed and could be removed, which would make instances effectively immutable.
3) polymorphic: provide a copy variant, say 'copyIfCollection'

1 would work but is labour intensive, and puts a new requirement on subclasses. 2 is simple, saves a little on object creation, and seems okay, but unforeseen side effects? 3 is perhaps generally useful, perhaps just bloat.

I think I prefer 2 on balance, since these are IAC really 'private' classes. Thoughts?

**Comment by LFSaw** [comment]
I think, I like (2) best as well... maybe a comment in the sourcecode, pointing out the immutability of ```AbstractMessageMatcher``` instances?
We should create test cases for this.

**Comment by telephon** [comment]
Have a look here: 6ee21eec9baf17f70cb4c9fda15ce3e2f960c6b7
There is a new branch with a first implementation. I don't use these classes currently, so I'm not the right one to test. There seems to be a lot of combinatorial explosion, but there must be a good reason for that! :)

**Comment by muellmusik** [comment]
Hi Julian, that looks good, but we'd suggested option 2), which was just to override copy for AbstractMessageMatcher to return the receiver. As it's a 'private' class, and could be made effectively immutable, that would seem to be okay and simpler. But do you have a reason not to do that?

The variant wrappers are for the sake of speed, checking only what needs to be checked. The old responders were much slower and didn't scale well.

**Comment by muellmusik** [comment]
@telephon Any thoughts?

**Comment by telephon** [comment]
>Hi Julian, that looks good, but we'd suggested option 2), which was just to override copy for AbstractMessageMatcher to return the receiver. As it's a 'private' class, and could be made effectively immutable, that would seem to be okay and simpler. But do you have a reason not to do that?

No, not at all. I hadn't realized that that was the best solution (I don't understand the problem, so I was coding in the dark!).

>The variant wrappers are for the sake of speed, checking only what needs to be checked. The old responders were much slower and didn't scale well.

Yes, makes very much sense. A lot of the problem as far as I remember was the lack of matching against a hash. But maybe with a little bit of overhead added, one single class could do the matching against, say, a dictionary of properties? I'm not sure of course, this may be a bad idea for many reasons!

**Comment by telephon** [comment]
So I assume the branch  https://github.com/supercollider/supercollider/tree/topic-matcher-identity is quite useless, no?

**Comment by muellmusik** [comment]
> Yes, makes very much sense. A lot of the problem as far as I remember was the lack of matching against a hash. But maybe with a little bit of overhead added, one single class could do the matching against, say, a dictionary of properties? I'm not sure of course, this may be a bad idea for many reasons!

I don't know if it's a bad idea or not. But for a given class of messages the combinations are limited. So the problem can be a little complex, but bounded.

> So I assume the branch https://github.com/supercollider/supercollider/tree/topic-matcher-identity is quite useless, no?

Keep it for the moment. I'll do a few tests and add a new PR.

**Comment by telephon** [comment]
Is fixed in: https://github.com/supercollider/supercollider/tree/topic/function-list-copies-before-iteration
