### ISSUE TITLE
SendTrig TrigControl or udp comunication?

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#1315]
Hello,

testing server client comunication in sclang:

(
SynthDef(\help_loopcomm,{|t_gate=1,val=0|
 var sig = EnvGen.ar(Env.perc(0,0.0001,0.5),t_gate);
 SendTrig.kr(t_gate,23,val);
 Out.ar(0,sig.dup());
}).store
)

(
~node = s.nextNodeID;
OSCFunc({|msg| msg[3].postln;s.sendMsg("/n_set", ~node, \t_gate, 
1,\val,msg[3]+1);},'/tr');
s.sendMsg("/s_new", \help_loopcomm, ~node, 0, 0);
)

after some succeding loops it fails.
I am not sure if synth is not triggered or /tr is not arriving.

Any ideas?
victor

**Comment by jamshark70** [comment]
One thing to be aware of, when testing anything that iterates very quickly, is that `postln` is quite slow. This can create problems in itself that wouldn't exist otherwise.

I rewrote your example to save the incoming OSC message times and the values, without posting anything.

    (
    SynthDef(\help_loopcomm, { |t_gate=1,val=0|
    	var sig = EnvGen.ar(Env.perc(0, 0.0001, 0.5), t_gate);
    	SendTrig.kr(t_gate, 23, val);
    	Out.ar(0, sig.dup);
    }).add;
    )
    
    (
    ~node = s.nextNodeID;
    n = 1000;
    l = Array(n);
    o.free;
    o = OSCFunc({ |msg, time|
    	if(l.size < n) {
    		l.add(time).add(msg[3]);
    		s.sendMsg("/n_set", ~node, \t_gate, 1, \val, msg[3] + 1);
    	} {
    		s.sendMsg(\n_free, ~node);
    	};
    }, '/tr');
    s.sendMsg("/s_new", \help_loopcomm, ~node, 0, 0);
    )
    
    // test 'val' items    
    l.clump(2).flop[1] == (0..499)
    -> true     // no integers were skipped

    // average time?
    l.clump(2).flop[0].differentiate.drop(1).mean;
    -> 0.023220294589178

Apart from `postln`, another possible cause is if the iterations happen too quickly, in which case the server would get the next `/n_set` message before `t_gate` has reset to 0. On my machine, I'm getting approximately 23 ms per iteration. This is much longer than the default control block size (1.45 ms), thus much longer than a kr trigger's duration. AFAICS there is no chance of triggers being dropped with a local server.

**Comment by jamshark70** [comment]
When you set a `t_` control, it's nonzero for exactly one control block. With default settings, 64/44100 = 0.0014512471655329. The UDP round trip would have to be shorter than this.

What is the average round-trip time on your machine, as reported by my last line above? (My round-trip time is more than *six times* the control duration, so I think this scenario is extremely unlikely.)

**Comment by sonoro1234** [comment]
0.022256198993399 is the mean duration but we shoud check minimum duration to test this hipothesys. I will give it a try

**Comment by muellmusik** [comment]
> This is much longer than the default control block size (1.45 ms), thus much longer than a kr trigger's duration

Note that your messages will be executed at the start of the next hardware buffer, since they are not scheduled with latency, but ASAP. This is indeed possibly much larger than the default control block size. Not sure if that helps shed any light, but worth knowing.

Maybe a Timer UGen would be of some use here?

**Comment by sonoro1234** [comment]
m=l.clump(2).flop[0].differentiate.drop(1);
m[m.minIndex];

posts 0 so t_gate could not be reset!!
solution will be using s_new instead of n_set

(
SynthDef(\help_loopcomm, { |t_gate=1,val=0|
    var sig = EnvGen.ar(Env.perc(0, 0.0001, 0.5), t_gate,doneAction:2);
    SendTrig.kr(t_gate, 23, val);
    Out.ar(0, sig.dup);
}).add;
)

(
~node = s.nextNodeID;
n = 10000;
l = Array(n);
o.free;
o = OSCFunc({ |msg, time|
    if(l.size < n) {
        l.add(time).add(msg[3]);
        s.sendMsg("/s_new", \help_loopcomm, s.nextNodeID, 0, 0, \t_gate, 1, \val, msg[3] + 1);
    } {
        //s.sendMsg(\n_free, ~node);
    };
}, '/tr');
s.sendMsg("/s_new", \help_loopcomm, s.nextNodeID, 0, 0);
)

this is not failing so it seems that:
get the next /n_set message before t_gate has reset to 0 may be the cause

Thanks james and muellmusik
victor

**Comment by jamshark70** [comment]
That doesn't make any sense. If it reports a minimum delta of 0, something else must be going on.

The sequence of events should be:

1. Trigger gets set. As Scott points out, this will happen on the next hardware buffer boundary.
2. The synth responds by sending /tr back to the client. This cannot happen before the next hardware buffer.
3. Client receives the message. Since this takes non-zero time, the hardware buffer boundary has passed.
4. Client sends a new /n_set for the trigger. This will take effect on the next hardware buffer boundary.

To have a true 0 delta, the /n_set must be sent long enough before the *same* hardware buffer boundary to process on the same one... in other words, the computer would have to go back in time. That's obviously not possible.

The test must be flawed in some way, but I can't check now (not at the computer).

**Comment by jamshark70** [comment]
Back at the computer... when I run the test, I get:

    d = l.clump(2).flop[0];
    d.minItem;
    -> 0.022836999999999

Actually, rereading the code, the *only* way you could get zeros is if the OSCFunc gets called twice with the same `time` argument. As stated in my last email, there is no way this could happen with server messaging. It could happen, however, if you had two OSCFuncs registered, both adding data into `l` -- an easy situation to get into, if you're running tests quickly and losing track of objects.

Perhaps try again after recompiling the class library...?

**Comment by sonoro1234** [comment]
do you mean?
```
d = l.clump(2).flop[0].differentiate.drop(1);
d.minItem;
-> 0.022836999999999
```

**Comment by jamshark70** [comment]
Yes, you're right - I did the differentiate in SC but forgot to copy it into the github comment.

**Comment by sonoro1234** [comment]
I boot server 3.6.6 in win32. execute your test that not arrives to loop 500 and get minItem 0
There is not duplicated OSCFunc because it is first time I execute and basides in your test o.free() would avoid that.
Only left to say that test does not always fail but sometimes.

**Comment by jamshark70** [comment]
OK, I can reproduce the 0 deltas in Windows. There's no way it could be a "real" zero -- I don't have an explanation though.

Even in Windows, though, I always get all 500 counter values -- also proving that the 0 deltas are not true simultaneous triggers. In my environment, the synth *is* getting triggered 500 times, and the OSCFunc *is* updating the counter 500 times.

What is the use case? Maybe there's an alternate approach that's more reliable?

**Comment by sonoro1234** [comment]
This was a stress test of udp comunication for Lua2SC
Beasides that I would like to understand the behaviour I am getting.
Which windows and which sc are you using?

**Comment by jamshark70** [comment]
If it's a stress test, then the result is I guess that this scenario is not safe in Windows. It's not a typical use case, for sure. It's more common to trigger actions at regular intervals by patterns or Tasks in the client, or trigger UGens in the server (Impulse, Dust, TDuty).

I'm not going to do a lot more testing -- no time, and AFAICS "understand[ing] the behaviour I am getting" is a largely academic question. I'll suggest a couple of further tests, to check one-way communication. These might reveal whether UDP in Windows is just plain unreliable, or -- if one test succeeds and the other fails -- which direction is the problem.

Server-to-client -- messages arrive at the client in bursts, because the server evaluates several control blocks as fast as possible at each hardware buffer boundary. But I don't lose any in Linux (can't test Windows now, and I'm not excited enough about the question).

    (
    var n = 1000;
    
    a = {
    	var trig = Impulse.kr(ControlRate.ir * 0.25),
    	count = PulseCount.kr(trig);
    	SendTrig.kr(trig, 0, count);
    	FreeSelf.kr(count >= n);
    	Silent.ar(1)
    }.play;
    
    l = Array(n * 2);
    o.free;
    o = OSCFunc({ |msg, time| l.add(time).add(msg[3]) }, '/tr', s.addr);
    )
    
    l = l.clump(2).flop;
    l[1] == (1..1000)
    l[1]
    
    l[0].differentiate.drop(1).minItem;
    l[0].differentiate.drop(1).maxItem;
    l[0].differentiate.drop(1).mean;
    l[0].differentiate.drop(1).median;

Client-to-server -- omitting the 0.2 latency will definitely make the timing less reliable... but if you're sending rapid-fire messages, it would be silly to do it in an unreliable way, so I'm not going to bother to see how badly it breaks that way.

    b = Buffer.alloc(s, 1000, 2);
    
    b.zero;
    
    (
    a = { |t_trig = 0, value|
    	var phase = PulseCount.kr(t_trig) - 1,
    	timer = Latch.kr(Sweep.kr(phase >= 0), t_trig);
    	BufWr.kr([timer, value], b, phase, loop: 0);
    	Silent.ar(1)
    }.play;
    
    t = Task {
    	var delta = s.options.blockSize / s.sampleRate * 2;
    	1000.do { |i|
    		s.sendBundle(0.2, [n_set: a.nodeID, t_trig: 1, value: i]);
    		delta.wait;
    	};
    	"done".postln;
    	s.sendBundle(0.4, [n_free: a.nodeID]);
    }.play;
    )
    
    b.getToFloatArray(wait: -1, action: { |data| d = data });

    d = d.clump(2).flop;
    d[1] == (0..999);
    d[0].differentiate.drop(1)

**Comment by scztt** [comment]
@sonoro1234 @jamshark70 is there anything we can / need to do about this? otherwise, maybe close with a "known issue" label?

**Comment by jamshark70** [comment]
I honestly don't know how to troubleshoot this further. Sonoro1234 is right that it "should" work, and it does work in OSX and Linux.

Maybe muellmusik's work on clock timing would improve this in 3.7?

**Comment by telephon** [comment]
I can't reproduce it. Anyone else still can?

**Comment by vivid-synth** [comment]
Have we only repro-ed this on Windows?
