### ISSUE TITLE
same cubic icon with scide and sclang (OS X)

### ISSUE THREAD

**Issue by miczac** [supercollider/supercollider#1367]
scide shows the same cubic (non-whirl) icon as for sclang.
since now in OS X's "Force quit..." application list the same icons are shown, both listed with "SuperCollider", this is quite unhandy.
seen on OS X 10.8.5., Qt 5.4.1, built from branch 'master' [4bcab22]

**Comment by bagong** [comment]
Yea, and when you boot the server you get another bumping cube :) And if ever you start several servers, you'll get more of the same icon for each :)

**Comment by scztt** [comment]
There's two issues here --

1. The icon-difference issue is fixed in the topic/sclang-app branch.

2. The scsynth icon is more of a design thing... having a separate icon for scsynth is a side effect of putting the binary next to sclang and the ide in the app package (the OS creates one automatically). This was done more for build consistency than anything else, but the side-effect is that you can see when a server (or several) is running / force quit them if you need to. This avoids the phantom server problems that used to plague SC (since you can see if a server is running), and in general invisible background processes are never a great idea. That said, I almost never see phantom server problems in 3.7, and the additional icon is annoying - so, if there's consensus, it's easy to fix that part.

**Comment by bagong** [comment]
- As to the server icon: the way it is it's confusing, but even with a separate server icon I don't think many people would want to trade in the space it takes up.
- As to your sclang.app branch: how about discussing this on the dev-list? When you mentioned the possibility of a really separate sclang.app the other day, there seemed to be quite enthusiastic reactions. Maybe this could motivate some contributions?

**Comment by scztt** [comment]
I'll make a pull request for it tonight, so it can get proper discussion (I need to merge the current master in first). I'm agnostic as to whether it gets in this release or a later one, and I didn't want to muddy the waters too much unless people brought up *specific* problems that the branch could fix.

**Comment by bagong** [comment]
It seems to me quite a few of the Mac people are listening on sc-dev only. But maybe this can move them over :)

**Comment by miguel-negrao** [comment]
The ide, sclang and servers should at least have different names. They all appear now on Cmd-Tab as "SuperCollider". It's impossible to pick the right one from Cmd-Tab.

**Comment by crucialfelix** [comment]
```
2015-06-13 12:52:34.380 xcodebuild[40277:379979] warning:  The file reference for "icons/SCcube.icns" is a member of multiple groups ("SuperCollider" and "Resources"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
```

**Comment by miczac** [comment]
This seems to be fixed, but I can't find a dedicated commit? Was this some side effect?

**Comment by crucialfelix** [comment]
Nope, not fixed. That was julian closing a duplicate issue.

**Comment by crucialfelix** [comment]
It is fixed, not sure when. Booting the server still bounces forever, which is annoying.
