### ISSUE TITLE
document select popup misses key-up events

### ISSUE THREAD

**Issue by timblechmann** [supercollider/supercollider#1446]
fast `ctrl-tab` causes the widget to miss key-up events, causing the popup to keep the focus.

this was fixed via aa36eabe, but the fix was reverted again.

**Comment by bagong** [comment]
Can you give a bit more context? For me (OS X 10.10 latest SC master, using alt-tab) exactly the opposite of what you describe happens. If I insert

    QDialog(parent, Qt::Popup | Qt::FramelessWindowHint)

ie. replace Dialog by Popup,  the popup opens and cannot be closed any more from the keyboard. The only way to get rid of it is to double-click one of the entries. That could very well be caused by the "Popup" not receiving key-up events.

At the time you posted that pull-request I tested the change on Mac and Ubuntu and it broke a kind-of-working feature, so how could it not have been reverted... Do you have changes in your SC-IDE version that make it work properly for you? Maybe you want to post those as well? Maybe/Likely declaring the selector a Popup is the correct thing, but the way you posted it it became worse.

There is a problem with the document-select/switch as it currently is in master: if there is a  detached window, when opening the "Dialog" the focus will move there. When that happens it will also appear as if the popup got stuck.

**Comment by timblechmann** [comment]
ubuntu 14.10, qt-5.4.

**Comment by muellmusik** [comment]
Can somebody confirm if this is still an issue? I don't have a working linux machine at the moment. This seems like it should have a 'bug' label.

**Comment by jamshark70** [comment]
Just tried Linux and it seems OK to me (assuming that the expected behavior is that you should hold down ctrl while using the arrows, and then the document switches when you release ctrl).

I also tried many "fast `ctrl-tab`" strokes as mentioned in the initial comment, and I couldn't get the widget to stay open... so, seems fixed? But it might also depend on the window manager. Probably we should have somebody using the default Ubuntu WM test this as well (I'm on XFCE b/c of Ubuntu Studio).

**Comment by snappizz** [comment]
i can't repro this either. reopen if an issue.
