### ISSUE TITLE
Tab does not work in IDE (on OSX)

### ISSUE THREAD

**Issue by thormagnusson** [supercollider/supercollider#1453]
Bug description: Trying to inline code, but the Tab button doesn't work.

Steps to reproduce:
1. I'm not sure how I would be able to make this look good without hitting the space bar hundreds of times.

button = Button(w, Rect(20, 20, 340, 30))
.states_([
	["on", Color.black, Color.clear],
    ["off", Color.blue, Color.clear]
        ])
.action_({ arg butt
	butt.value.postln;
 if(butt.value == 1, {
	synth = Synth(\default);
}, {
	synth.release;
})
});

Actual result: Tab only works once.

Expected result: I can inline text into the documents as many times as I want.

**Comment by danstowell** [comment]
Hi Thor, this is by design: scide uses Tab for autoindent. You can use shift+Tab for manual indent.

(If you think that's unusual, well it's not my design, but there was definitely a lot of discussion about this decision, a while ago, so it's been hashed out by various interested people.)

**Comment by thormagnusson** [comment]
Thanks Dan. I haven't been following much and didn't see this discussion. Good to know about the shift+Tab trick. Perhaps it should be reversed? shift+Tab for autoindent? We really should aim at normal behaviour no? I'm glad we're not coding in Python.

**Comment by jamshark70** [comment]
The right way to handle this would be with a preference for the user to choose the desired tab behavior -- because, if you're annoyed about the current behavior, I would become at least as cross (or more) if you forced me to reach for another key to get auto-indent behavior.

No, no, a million times no, please DO NOT change the default. Fix the bugs in the auto-indenter, but do not assume that nobody likes auto-indentation.

**Comment by danstowell** [comment]
@thormagnusson actually Python is a really good example. When I first used Python I was like "what the heck? it won't let me choose how to indent? what an awkward constraint!" but now I use Python every day and my code looks lovely. Similarly in the case of scide: the auto-indent feature leads to very neat code, though on first encounter it's a constraint that may well irritate you, especially if it doesn't match your personal convention. But maybe by 3.8 you'll love it ;)

(just my 2p)

**Comment by jamshark70** [comment]
I agree with Dan, except that there is a glaring issue with auto-indent: #596. If this were addressed, it would erase Thor's objection. IMO fixing the other issue would be more meaningful -- it would improve auto-indentation, rather than just making it easier for users to avoid the flaws in the current behavior.

In that sense, closing this issue as a duplicate is appropriate.

**Comment by thormagnusson** [comment]
Tried using the Shift trick now, but I'm not very satisfied, as the next line (by hitting return) still starts at the first tab indent, not the level I set it to by hitting Shift+tab. Most code editors don't behave like this (just tried on Atom, Sublime Text, Processing, and BB Edit). However XCode does.

**Comment by thormagnusson** [comment]
Just saw James' comment now. Agreed, it would be good if this could be set in the preferences.
