### ISSUE TITLE
Ubuntu with unity 14.04-15.04: ctrl-. does not work in IDE

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#1478]
This issue only occurs on stock Ubuntu (verified versions 14.04-15.04) with ubuntu-patched Qt5.2.1.

So it's an Ubuntu bug, not sc, not Qt. Most power user in digital music use some other ubuntu flavor, but Ubuntu unity is still the distro default... :(

**Comment by miguel-negrao** [comment]
For release, wouldn't this be solved by the distributed binary being built with plain Qt from Qt website ?

**Comment by bagong** [comment]
Coming to think about it I don't actually know what a release is. If I remember correctly travis only checks if it builds. A release would probably be a package? Debian or Arch or whatever? If that's a release, I think you are not free to choose your own dependencies differing from the distribution... @Dan would know. Apart from that the other question is which bugs we *get* in exchange for switching Qt. Unfortunately the Ubuntu flavor matters. And we already have a report of a bug that occurs on Ubuntu 14.04 with Qt5.4.1 only :)

**Comment by danstowell** [comment]
As far as the "supercollider team" is concerned, a linux release is a source release.

Then downstream... for debian, ubuntu, fedora, the packages are typically installed as binaries which have been built against the standard lib packages provided by the platform. A maintainer could choose to include a patched lib inside the package, but that's a big job and a hard fight because the meta-maintainers, the people who look after debian ecosystem etc, don't like that bloat without good reason. I personally wouldn't want to be doing it either, it's hell for maintenance, especially if it's something as big as qt.

So that's all just for info. I agree that this seems like a Unity-and/or-Qt bug, therefore we can't do anything but wait for a fix. (And I don't mean pausing a release. Keep releasing stuff.) If you have the problem, send the bug to the relevant project (Unity?), then that'll get it fixed.

**Comment by timblechmann** [comment]
@danstowell if the debian/ubuntu maintainers don't like static linking, they have to make sure to provide a version of their library, which actually works. statically linking qt is not straight-forward as one needs to manually initialise the platform plugins, but it is also no rocket science. one just has to do it

**Comment by JordanHendersonMusic** [comment]
Closing because this refers to an old version of ubuntu, and was deemed to be an issue with ubunut/unity/qt bug and not something addressable in this project.
