### ISSUE TITLE
WebView does not play video in 3.7 alpha1.  Works in 3.6.6.

### ISSUE THREAD

**Issue by JVanBuskirk** [supercollider/supercollider#1502]
On a OSX 10.9.5, 3.7 alpha 1 does not play videos.   It does work in 3.6.6.

(
w = Window("WebView Example", Rect(256, 40, 900, 700)); 
w.front;
v = WebView(w, Rect(0,0, 900, 700)).url_("https://youtu.be/ntL8QDOhhL8");
)

The screen will load, but when you press play youtube shows an error.  I have also tried other sites like vimeo without success.

**Comment by nuss** [comment]
Works on my machine (Ubuntustudio 14.04, Qt 5.21, SC compiled from the latest commit to master)

**Comment by bagong** [comment]
> On 27 May 2015, at 14:47, Stefan Nussbaumer <notifications@github.com> wrote:
> 
> Works on my machine (Ubuntustudio 14.04, Qt 5.21, SC compiled from the latest commit to master
> 
Same here with slightly different setup: Linux (Ubuntu Studio 15.04) works, OS X (10.10.3) not.

**Comment by scztt** [comment]
This is an issue with Qt plugins. Various kinds of format support don't work w/o the right Qt plugins installed - on mac, neither JPG nor GIF seem to work either. I have this fixed in a local change, but it needs some cleanup. Bigger problem: I can't seem to get youtube.com to work at all (even loading the front page), and many common sites - vimeo, parts of google, twitter, etc, seem half functional. I havent yet figured out whats causing it...

**Comment by vivid-synth** [comment]
(can we add the "comp: QT GUI" label to this?)

**Comment by bagong** [comment]
I think the video part of this has to do with how QtWebkit is built. For Windows - where video never worked - I have a custom build of QtWebkit now, where video, and partially also webaudio work. It's a msys2 build that uses gstreamer as backend.

**Comment by muellmusik** [comment]
Fixed in 3.10, at least on OSX High Sierra. Can we close?
