### ISSUE TITLE
parser doesn't catch backward variable definitions

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1514]
currently, this doesn't throw a variable undefined error:

```
(
var size = output.size;
var output = [1, 2, 3];
output
)
```

**Comment by baconpaul** [comment]
It's even a little weirder than that. It looks like if you initialize with a subset of literals it actually does the back substitution. For instance, this code:

```
(
var early = middle;
var middle = s.name;
var late = middle;

[ early, late, middle ];
)
// returns [ nil, localhost, localhost ]

(
var early = middle;
var middle = 123;
var late = middle;

[ early, late, middle ];
)
// returns [123, 123, 123]
```

I haven't looked at the parser but I can imagine how a bug happens wherein this makes sense; if you scan for vars first including looking for literal assignments then evaluate second you would get exactly this behavior. 

But it does mean that changing the language to make both of those exceptions could break some existing code which relies on that bug. If someone fixes it is there a way you condition out code so that it can toggle on and off around a release or anything like that?

**Comment by jamshark70** [comment]
> It looks like if you initialize with a subset of literals it actually does the back substitution. ... if you scan for vars first including looking for literal assignments then evaluate second you would get exactly this behavior.

That's correct: http://doc.sccode.org/Classes/FunctionDef.html#-prototypeFrame holds default values that are literals, but it can't hold expressions.

http://doc.sccode.org/Reference/Functions.html#Arguments documents the way that expression-initializers are compiled.

I don't see this as a huge problem that desperately needs to be fixed, though. SC Server has been around for, what, 14 years without anyone stumbling onto this until now? User impact = minimal.

**Comment by baconpaul** [comment]
OK cool. I'm was just pursuing bugs in the 3.8 milestone seeing if I could figure them out. This one looks tricky, and I agree it's not a huge problem. Is there a workflow to close bugs with a  "yup, but no big deal" type flag?

**Comment by telephon** [comment]
goo idea – I've added a new label.

**Comment by crucialfelix** [comment]
That's how compilers work. First it syntax checks it, then it compiles it. When it compiles it all variables in scope are created in the current frame. Then it runs the code. All the variables exist and are allocated before execution starts.  It isn't reading it line by line.

https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch1.md

Closing because I think we should not be re-inventing wheels.

**Comment by baconpaul** [comment]
Totally agree you should close it but the sort of inconsistency in the paired example I figured out isn't really "how compilers work". A c++ or fortran compiler would give an error on the equivalent. And the fact that you tokenize then parse then compile is kinda distinct from the semantics of object scope and lifetime yeah? And it's fine to have the semantics of the language be "all variables declared in this scope are available anywhere in the scope even before declaration" but then the value assignment inconsistency is a bit tricky.

Again completely agree this isn't worth fixing. And it's kinda neat to see how you end up in this spot. Thanks for looking! Be well.
