### ISSUE TITLE
Scroll view issue in Qt -- no vertical scroll bar

### ISSUE THREAD

**Issue by edwardenixon** [supercollider/supercollider#1521]
Quarks.gui; brings up a window with no scroll bar. 

Apparently, scrolling works for users with scroll wheel mice. Act of scrolling via whell reveals a scroll bar which can then be grabbed. Felix thinks it's a Qt flag needing setting.

**Comment by scztt** [comment]
@edwardenixon - Which OS (and version) are you running?

**Comment by edwardenixon** [comment]
Sorry. OS X latest — 10.10.3.         …edN

**Comment by crucialfelix** [comment]
Yes, its some kind of auto-hiding setting. If you don't have a scroll wheel on your mouse then you can't scroll.  Probably it works fine with the clever mac trackpad.

**Comment by scztt** [comment]
There's an OS preference for this - I think the actual bug is that some of the lang views don't follow the OS pref. Documents in the IDE, for example, DO follow the OS preference.

**Comment by edwardenixon** [comment]
I’d be willing to bet (something) that a large majority of people, SC people at least, don’t know about an OS option to hide the scroll bar. And don’t care. I can’t imagine why one would want to do that. But then there’ve been some pretty bizarre things happening to the OS X interface in the last version: sliding pages, disappearing menus in full page, all happening auto-magically when someone simply wants the traditional behaviour of those three little dots in the upper left corner. I would hope that I don’t have to follow all that featuritis down its own particular rabbit hole.

…edN

**Comment by crucialfelix** [comment]
Here's the OS X system preference:

![screen shot 2015-06-05 at 09 45 11](https://cloud.githubusercontent.com/assets/218738/8001635/c4e3fecc-0b67-11e5-8c46-7fc5a67068a1.png)

I think we should be as normal as possible: its a system preference. On OS X it is smart: if your mouse can scroll then it uses auto. If your wheel is broken you can set it to Always.  That's great, that's what OS are supposed to do.

@scztt  this topic: https://github.com/supercollider/supercollider/commit/8a5476e3c3d7210a0dfcbcdf393d024a0d1fa013

do you really mean show always ? I think we should let the OS call the shots.

**Comment by scztt** [comment]
Yeah, haven't pull-req'd that branch yet, I have one more change that
tracks the state of the pref and enables/disables. It (scroll bar
auto-hide) works fine if you use the "Macintosh" theme, but that theme
disrupts sclang's layout in weird ways, so it probably shouldn't be default.

- S

**Comment by crucialfelix** [comment]
operating systems and frameworks are great ...  until they become annoying.

**Comment by edwardenixon** [comment]
I’m not finding that changing that setting makes any difference with the Quarks.gui statement. At least after an SC alpha1 restart; does it take effect after a reboot?

What I just noticed however, is that the scroll bar makes a brief appearance just as the window has opened. Then it disappears.

…edN

**Comment by scztt** [comment]
So - I can make this behave reasonably on mac. However, I'm not aware of calls on Windows / Linux to check whether the overlay (disappearing) scrollbars are appropriate (or to check for the presence of a mouse wheel). So, to fix this bug on those platforms, we'd have to show the scrollbars ALL the time... I don't love that solution, as the overlay scrollbars save screen real estate and the always-on scrollbars in Qt are, frankly, terrible looking. It's tough, because transient scrollbars are probably most appropriate for anyone that has a trackpad / wheel mouse, but are a complete deal-breaker without wheel support.

One things I've done in the past to solve this sort of problem: default to the show-always behavior, and switch to autohide as SOON as you receive the first mouse wheel event. That way, users who don't have  a mouse wheel / don't use it will always see scrollbars, but users who are wheelers will get the probably-more-appropriate auto-hide behavior.

**Comment by nuss** [comment]
At least on my machine (Ubuntu Studio 14.04, Qt 5.21) scrollbars are _always_ visible within the Quarks gui - doesn't bother me. Rather have them always visible instead of not being able to scroll if the mousewheel breaks somehow...

**Comment by scztt** [comment]
Ubuntu 15 has a system-wide setting that enables/disables the overlay scrollbars - we should be honoring that. I think it's new, though....

**Comment by edwardenixon** [comment]
Here! Here!               …edN

**Comment by telephon** [comment]
fixed.
