### ISSUE TITLE
FreqScope doesn't work

### ISSUE THREAD

**Issue by ceremona** [supercollider/supercollider#1527]
Running 10.8 OSX

s=Server.internal;
s.boot;
FreqScope(server:s)

Leads to:

-> internal
booting internal
Found 0 LADSPA plugins
Number of Devices: 13
   0 : "Built-in Microph"
   1 : "Built-in Output"
   2 : "Soundflower (2ch)"
   3 : "Soundflower (64ch)"
   4 : "Premiere Pro 7.0"
   5 : "Instant On Sound Effects"
   6 : "Default IN/OUT"
   7 : "iMic In / System Out"
   8 : "Scarlett In / System Out"
   9 : "RC-505 In/System Out"
   10 : "Scarlet In/Bluetooth Out"
   11 : "System In / Scarlett Out"
   12 : "Steinberg In/Out"

"Built-in Microph" Input Device
   Streams: 1
      0  channels 2

"Built-in Output" Output Device
   Streams: 1
      0  channels 2

SC_AudioDriver: sample rate = 96000.000000, driver's block size = 512
-> internal
Receiving notification messages from server internal
Shared memory server interface initialized
Execution warning: Class 'Scope' not found
ERROR: Message 'new' not understood.
RECEIVER:
   nil
ARGS:
Instance of Window {    (0x115ac38a8, gc=58, fmt=00, flg=00, set=03)
  instance variables [5]
    resizable : false
    drawFunc : nil
    view : instance of TopView (0x11a2bbef8, size=35, set=6)
    acceptsClickThrough : false
    currentSheet : nil
}
Instance of Rect {    (0x11a1b3be8, gc=54, fmt=00, flg=00, set=02)
  instance variables [4]
    left : Integer 30
    top : Integer 14
    width : Integer 522
    height : Integer 300
}
CALL STACK:
	DoesNotUnderstandError:reportError   0x115979d38
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x1159a8ae8
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x11597d958
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x11597cd98
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x11597baf8
		arg this = nil
		arg selector = 'new'
		arg args = [*2]
	FreqScopeView:initFreqScope   0x115268ef8
		arg this = <instance of FreqScopeView>
		arg parent = <instance of Window>
		arg bounds = <instance of Rect>
		arg argServer = <instance of Server>
	Meta_FreqScope:new   0x11a0773d8
		arg this = <instance of Meta_FreqScope>
		arg width = 522
		arg height = 300
		arg busNum = 0
		arg scopeColor = <instance of Color>
		arg bgColor = nil
		arg server = <instance of Server>
		var rect = <instance of Rect>
		var scope = nil
		var window = <instance of Window>
		var pad = [*4]
		var font = <instance of Font>
		var freqLabel = [*12]
		var freqLabelDist = 47.454545454545
		var dbLabel = [*17]
		var dbLabelDist = 18.75
		var setFreqLabelVals = <instance of Function>
		var setDBLabelVals = <instance of Function>
		var nyquistKHz = 48
	Interpreter:interpretPrintCmdLine   0x11552b6b8
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "FreqScope(server:s)"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x115ab16e8
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'new' not understood.
RECEIVER: nil

**Comment by scztt** [comment]
Hmm - so, one problem is, this is referencing Scope instead of SCScope, which is what that class is named currently. The SCScope name is probably wrong, and.... possible needs to be named Scope instead? And, beyond that, it's picking to use Scope versus ScopeView based on shmScopeAvailable, which in turn is checking: `and: { server.inProcess.not }` - ScopeView works fine for both in-process and out-of-process servers afaict.

I believe the proper fix for this is:
1. Remove the `and: { server.inProcess.not }` condition from shmScopeAvailable
2. Rename all uses of `Scope` to `SCScope`
3. Create a new "future" + "enhancement" issue to rename SCScope to something more appropriate (`LegacyScope`? `RemoteScope`?), or remove if it's not needed anymore.

@ceremona - Want to give the above changes (1 & 2) a go, and see if it fixes scope for both local and internal servers - if it does, make a pull request!

**Comment by ceremona** [comment]
Sorry.  My SC foo is not strong enough to understand what you are saying for step 1.

**Comment by adcxyz** [comment]
ok, submitted a PR for this

**Comment by telephon** [comment]
Fixed by fa6c53b6b51d326b83d40a984abe306952f33ad9
