### ISSUE TITLE
now that key down actions can return nil

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1554]
now that key down actions can return nil, this can lead to backward compatibility issues. Also now any message that is sent to the ````char```` has to be checked with ```notNil```.

Is there perhaps a "neutral" char that could be passed in instead?

**Comment by telephon** [comment]
Shouldn't we pass the ````NULL```` character ````0.asAscii````? Then no harm could be done, and you could still test for it:

````
+ isNull {
    ^this.ascii == 0
}
````

**Comment by telephon** [comment]
This was the issue where the new behavior (which is correct for QT) was introduced:  #1081

**Comment by davidgranstrom** [comment]
@telephon: I've found one backward compatibility issue which is fixed in #1562. 

`grep -r '.*.ascii' ./SCClassLibrary` gave me some hints where this new behaviour might be a problem.. but then of course there might be user code that breaks in similar ways.

I found (and confirmed) another issue in `JITLib/GUI/TaskProxyGui.sc` line 36. I can make a new pull request later for that, if we don't find another way of managing the backward compatibility issues.

**Comment by telephon** [comment]
Let's undo the original change that cause the error. Otherwise, fixing will be endless!

**Comment by telephon** [comment]
Here is my suggested change:

https://github.com/supercollider/supercollider/tree/topic/null-characters

**Comment by scztt** [comment]
The nil-for-unprintable-characters behavior has been documented for a while, no? And using nil versus a "special" value for non-printables seems like a better design in the long run? Can we just fix known failure cases in the classlib, and keep the behavior as is - it's a super-easy fix for anyone that has code that doesn't behave correctly, and I don't necessarily like the idea of bending an API to fit incorrect usage...

**Comment by jamshark70** [comment]
One point is that OOP should (often?) prefer polymorphic interfaces over testing an object's class -- i.e., ask the object to do something and have it respond sensibly, rather than first asking what kind of object it is. Forcing users to test "char.isNil" before calling any Char methods runs counter to the spirit of OOP. In that sense, Julian's suggestion *feels* better to me (though I admit that this, by itself, isn't necessarily convincing).

**Comment by scztt** [comment]
@jamshark70 - I suppose my point is... we KNOW that the "ascii character" argument is optional, because not all inputs have an ascii character. We've got to represent the case of "there's no value for this argument" somehow, and the usual way to do that in SC is via a nil - checking optional arguments for nil-ness is a pattern that's used all over the place (the !? operator makes it quite concise). This case seems to me to be no different.

Aside from that - NULL is a character that's not a very ordinary / meaningful ascii character (apart from that it's used to terminate c-strings). The common case for doing char.asAscii would be, e.g. concatenating chars into a string for display / text entry. I worry that by giving the user a NULL instead of throwing an error is going to potentially create harder-to-debug problem states for them later on - at best, a string mysteriously filled with NULL's... at worst, weird behavior from SC primitive that tries to read it as NULL-terminated.

**Comment by muellmusik** [comment]
Well isNil and notNil are examples of polymorphism, although very broad ones. I hesitate to suggest making nil any smarter than it is, but if it is deemed too awkward to deal with in this situation, one could add an asChar method for which nil returned NULL. That would seem reasonable.

IAC, I agree nil makes sense when there's no char associated.

**Comment by telephon** [comment]
>"there's no value for this argument" somehow, and the usual way to do that in SC is via a nil - checking optional arguments for nil-ness is a pattern that's used all over the place (the !? operator makes it quite concise). This case seems to me to be no different.

This change breaks *a lot* of code in a way that is hard to test.

>Aside from that - NULL is a character that's not a very ordinary / meaningful ascii character (apart from that it's used to terminate c-strings)

Maybe we pass just some other replacement character in those cases? Something from here: http://www.asciitable.com/

**Comment by jamshark70** [comment]
Practical experience just now, working with key actions: It is very very easy to forget to check for nil before calling a Char method. So you run something that you think will work, get all kinds of doesNotUnderstand errors when you hit modifier keys, which you then have to fix. I found that this raised my stress level, and there really is no reason for the higher blood pressure other than some devs' obsession with the purity of the "nil" concept.

Sorry, but criminy, you kind people are making key actions harder to use. To hell with correctness in that case. I vote very strongly to revert #1081. I **despise** this change. It will make me think twice to try to avoid key actions wherever possible in my code. It's *that* horrible.

I guess this won't make any difference, but I must register my objection.

**Comment by scztt** [comment]
@jamshark70 @thormagnusson - Let's change it back to a NUL char not nil. Someone want to make a pull request that (a) reverts #1492, and (b) fixes the documentation to reflect the fact that a NUL char is the default for non-printables in both Document and View?

**Comment by jamshark70** [comment]
I'll do it later today.

**Comment by LFSaw** [comment]
do we consider this closed then?

**Comment by telephon** [comment]
yes!
