### ISSUE TITLE
LinLog function?

### ISSUE THREAD

**Issue by ceremona** [supercollider/supercollider#1555]
Sorry if this is the wrong place to ask this but...  I am amazed to find that there is no logarithmic input mapping function such as LinLog.  Am i missing something?  LinExp only allows for exponential mapping.  How would someone do this other than writing there own math function?

**Comment by ceremona** [comment]
Ok, I guess nevermind.  I can do what I want with simple math functions, which I guess begs the question, why there is a separate function for these mappings at all, when you can just run your input values through a one-line function?

<input>.log, etc...

**Comment by danstowell** [comment]
.linexp and similar are used to map a range to a range. For example input 0-1 to be mapped to exponential range 1-10? No problem: x.linexp(0, 1, 1, 10). Don't worry about the constants needed to calculate that. It means you can think like an audio engineer rather than a mathematician. (You might find that .explin answers your original question, perhaps.)

If you want to think like a mathematician, use .log .exp and so on, no problem. SuperCollider likes mathematics *and* audio engineering.
