### ISSUE TITLE
Can't use MIDI with Jack on Linux (Ubuntu 14.04)

### ISSUE THREAD

**Issue by Hibou57** [supercollider/supercollider#1559]
Using SuperCollider 3.6.6 installed from PPA on Ubuntu Trusty (14.04) 32 bits, there seems to be no way to use MIDI (I'm disappointed, as I wanted to look at SuperCollider with the hope to use it with MIDI).

When the server is started from SC IDE, I get this in the post‑window:

    JackDriver: couldn't connect  system:midi_capture_1 to SuperCollider:in_3
    JackDriver: couldn't connect  system:midi_capture_2 to SuperCollider:in_4
    JackDriver: couldn't connect  system:midi_capture_3 to SuperCollider:in_5
    JackDriver: couldn't connect  system:midi_capture_4 to SuperCollider:in_6
    JackDriver: couldn't connect  system:midi_capture_5 to SuperCollider:in_7

I can't see any SuperCollider MIDI ports in QJackCtl neither.

Jack is configured to use `seq` as the MIDI driver. I tried with `raw`, but it solved nothing (it's even worse, as SC seems to not even try to connect any MIDI ports).

— Edit —

The MIDI ports only appears as ALSA MIDI ports, not as Jack MIDI ports. Is this really as expected? I have to connect it manually. There is also an issue with MIDI events not received from a VirMIDI virtual device.

**Comment by jamshark70** [comment]
I believe this is a misunderstanding, rather than a bug. It's better to continue troubleshooting on the mailing list.

In SuperCollider, it's the language -- not the server -- that interacts with MIDI. Read the "Using MIDI" help file and if you have further questions, please use the mailing list:

http://doc.sccode.org/Guides/UsingMIDI.html

Your errors are coming from the server. The server has *no* capacity to use MIDI directly. What they're saying is: you're trying to connect (at least) 7 input channels. The server is looking for jack ports containing "capture" as sources for the inputs. Apparently you have system:capture_1 and system:capture_2, which are being connected to SuperCollider:in_1 and SuperCollider:in_2. Since these are working, they don't appear as errors. Then it's looking for sources for SuperCollider:in_3 etc., and it's finding "MIDI capture" ports. It's not difficult to imagine why Jack would fail to connect a MIDI port to an audio port.

Since your audio device has two channels, you should not try to start the server with so many channels.

```
s.options.numInputBusChannels = 2;
s.options.numOutputBusChannels = 2;
```

> The MIDI ports only appears as ALSA MIDI ports, not as Jack MIDI ports. Is this really as expected?

Yes. You should use "none" as the Jack MIDI driver. "Raw" is definitely a bad idea. I've never tried to use "seq" with SC.

**Comment by Hibou57** [comment]
> In SuperCollider, it's the language -- not the server -- that interacts with MIDI.

Indeed, I just checked that's rebooting the interpreter which close all MIDI connections, not rebooting the server.

Thanks for the notice.

**Comment by sensestage** [comment]
To clarify further:
The SuperCollider language is using the ALSA MIDI interface, not the JACK
MIDI interface.

sincerely,
Marije
