### ISSUE TITLE
synthdef directory error message on first startup

### ISSUE THREAD

**Issue by jweather** [supercollider/supercollider#1564]
Many Sonic Pi users dig through the logfiles when things aren't working right, and their first impression is usually this giant error message: `*** ERROR: open directory failed 'C:\Users\Steffen\AppData\Local\SuperCollider\synthdefs'`  However, this is not actually an error, and is expected on the first run.  Can it be changed to a more sedate `Creating directory 'C:\Users\Steffen\AppData\Local\SuperCollider\synthdefs' for first run`, or even removed altogether?  The Sonic Pi support team thanks you!

**Comment by danstowell** [comment]
I've never seen this message with normal SuperCollider. Would you mind explaining a little, why this occurs? Does it happen always/only on Windows? (I ask because your paths look like Windows paths.) Does it happen in non-Sonic-Pi situations?

**Comment by jweather** [comment]
Here's one from a Mac:
`*** ERROR: open directory failed '/Users/wmoore/Library/Application Support/SuperCollider/synthdefs'` reported here: https://groups.google.com/forum/#!searchin/sonic-pi/%22open$20directory$20failed%22/sonic-pi/FNBIHU8VN-w/EEOf8j2mN-QJ

Doesn't appear to be caused by Sonic Pi, because I can trigger it by deleting my synthdefs directory and then starting with "scsynth -u 4242":

`*** ERROR: open directory failed 'C:\Users\JWeatherford\AppData\Local\SuperColli
der\synthdefs'`

Here are two likely sources: https://github.com/supercollider/supercollider/search?utf8=%E2%9C%93&q=%22open+directory+failed%22

**Comment by jweather** [comment]
Perhaps it is expecting the directory to be created by the installer?  Sonic Pi is not using the SC installer, but simply running the scsynth binary.

**Comment by danstowell** [comment]
No, it's actually created by SuperCollider language in normal circumstances - see here: https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Audio/SynthDef.sc#L32

It **is** an error if `scsynth` is started, and the synthdef dir it expects is not there. I think the error message is correct. It seems to me the fix is for Sonic Pi to create the folder, in exact analogy with the way SuperCollider language makes the folder.

**Comment by jweather** [comment]
I guess this doesn't qualify as normal circumstances.  There are no
synthdefs in that folder on my installation, and scsynth is working fine
using synthdefs that Sonic Pi is loading in at runtime.  Sonic Pi is not
installing a copy of SuperCollider when it is installed, so I am loathe to
create additional directories that we are not responsible for.  (for
instance, should we delete it when we are uninstalled?  What if a full copy
of SC has been installed in the meantime?)  Is there a better way to set up
scsynth for use as a portable executable?

On Thu, Jun 25, 2015 at 5:14 PM, danstowell <notifications@github.com>
wrote:

> No, it's actually created by SuperCollider language in normal
> circumstances - see here:
> https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Audio/SynthDef.sc#L32
>
> It *is* an error if scsynth is started, and the synthdef dir it expects
> is not there. I think the error message is correct. It seems to me the fix
> is for Sonic Pi to create the folder, in exact analogy with the way
> SuperCollider language makes the folder.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/1564#issuecomment-115399967>
> .
>



-- 
Jeremy Weatherford

**Comment by danstowell** [comment]
I know it's not normal circumstances - essentially that's my argument.

I don't know Sonic Pi architecture but it sounds from your description as if this folder is NEVER used in a SPi+scsynth session - is that right? That would mean that when Sonic Pi makes use of scsynth, the synthdefs are always sent, rather than loaded from disk. If so, you simply need to change Sonic Pi so that when it launches scsynth, it specifies the `-D 0` commandline flag which stops scsynth from attempting to read synthdefs from disk. (In scsynth code, this option is `inOptions->mLoadGraphDefs`.) Luckily this is already a commandline flag in scsynth :)

**Comment by jweather** [comment]
Easiest feature request ever!  Thanks for pointing me in the right direction.
