### ISSUE TITLE
Using Pkey with Pbind and PlayBuf to set \dur and \amp based on attributes of \buf selected

### ISSUE THREAD

**Issue by surfent** [supercollider/supercollider#1566]
To anyone who might help --

I am a novice user of Supercollider, and am manipulating hundreds of voice samples using Pdef, Pbind, and PlayBuf.  I am at the point where it would be VERY helpful to be able to key the \dur and \amp for each event to particulars of the \buf that is selected ( either through Prand, Pshuf, or the like ).

Does anyone have any suggestions on how this might work?

Many thanks,

**Comment by jamshark70** [comment]
Please be aware: This is a bug tracker, for developers to monitor progress on problems that require fixes within SC's code base. It is **not** a support forum for general usage questions.

Please start here. Your question is perfect for the SC-users list. If you prefer a web-forum interface, look at the Nabble mirror (though you'll need to subscribe to the SC users ACL list in order to post).

http://www.birmingham.ac.uk/facilities/ea-studios/research/supercollider/mailinglist.aspx
