### ISSUE TITLE
elastic FlowLayout

### ISSUE THREAD

**Issue by vividsnow** [supercollider/supercollider#1611]
Hi

What do you think about replacing boilerplate code like this:

```
(
w = Window(scroll:true).front;
w.addFlowLayout;
w.view.onResize_({ |v| 
    var d = v.decorator;
    d.bounds = v.bounds;
    d.reset;
    v.children.do(d.place(_));
});
)
```

with something like:

```
w = Window(scroll:true).front;
w.addFlowLayout(elastic:true);
```

?

**Comment by jamshark70** [comment]
I think we should discourage the use of FlowLayout. If you want elastic layouts, Qt layouts are many orders of magnitude better.

**Comment by vividsnow** [comment]
I need FlowLayout functionality, but with resize responsiveness. 
It's already there, but implementation isn't obvious.

**Comment by tmwoz** [comment]
The problem with Qt layouts is they don't like EZGui controls...

**Comment by jamshark70** [comment]
@tmwoz That issue is fixable. I actually just played around (locally) with a proof-of-concept of some code changes that -- in its present form -- allows EZSlider to be a member of a QLayout. It isn't ready to present as a pull request, but I tested the following just now, and it does behave as you'd expect:

```
w = Window("test", Rect(800, 200, 400, 300)).front;
w.layout = VLayout(
	EZSlider(w, Rect(2, 2, 396, 40), "test", nil, nil, 0.5)
);
```

It's debatable whether to address this in 3.7 or not. There is some risk of breaking backward compatibility, and there hasn't been any testing. For that reason, I think we should wait until 3.8 to bring EZGuis up to speed with layouts. But -- at the very least -- it is technically possible.

**Comment by tmwoz** [comment]
@jamshark70 Well, they already can be members of QLayouts when added with <code>EZGui.view</code> and <i>most of the time</i>  they behave well...except for EZKnob which gets worse the more complex layouts you use.

Have You tested your fix with dynamically changing (nested) layouts? 

Anyways FlowLayout should be recommended when EZGui is involved, at least for the inner layout.

**Comment by jamshark70** [comment]
Let's not hijack this issue. I'll open a separate issue for EZGui + Layout later, when I'm more confident of the approach.

The approach will be to use a qt layout inside the composite view created by an EZ widget, and replace the (excessively complex) bounds logic. That means EZGuis might draw slightly differently, but they would be fully compatible with qt layouts (and I would not consider the issue fixed otherwise).

It is true that, for now, FlowLayout is better for EZGuis.
