### ISSUE TITLE
alter return value of Platform.name to return platform name

### ISSUE THREAD

**Issue by thormagnusson** [supercollider/supercollider#1630]
Platform.name returns "Platform" - if I understand this method, it would be to help detecting the platform.

So perhaps changing Platform:name from

```
name { ^this.subclassResponsibility }
```

to

```
name { ^thisProcess.platform.name }
```

And then we could do checks like

Platform.name == \osx

**Comment by jamshark70** [comment]
Hm, `name` as a class method means to return the name of the class as a symbol. I'm not sure it would be wise to introduce an exception for one class. We would have to be very sure that, e.g., the introspection that provides class library info to the IDE wouldn't break.

Probably it would have been better to have started off with `thisProcess.platform.id`, but we didn't, and now we're stuck with an interface that doesn't translate easily to the class level.

The above-proposed changes would not help because that's the Platform *instance* method called "name," whereas it's the class method that answers `Platform.name`. Also it might introduce a risk of infinite recursion.

**Comment by brianlheim** [comment]
Closing - but saved [here](https://github.com/supercollider/supercollider/projects/6).
