### ISSUE TITLE
Buffer.sendCollection overwrites data of Buffer with explicitly specified bufnum

### ISSUE THREAD

**Issue by michaeldzjap** [supercollider/supercollider#1651]
Noticed this on the latest build from source. Not sure if this intended behaviour, but it is a little strange anyway:

b = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav", 0, -1, bufnum: 0);
b.plot;    // fine...

c = Buffers.sendCollection(s, ([1, 0]!100).flat, 1);

b.plot;    // seems sendCollection has overwritten the buffer explicitly allocated to bufnum 0

**Comment by jamshark70** [comment]
It is expected behavior.

There are two aspects to allocating a buffer: the buffer number (used when addressing the server, but managed by the client) and the server's memory (managed exclusively by the server).

Your Buffer.read statement allocates server memory (aspect 2) but does nothing to tell the client's bufnum allocator that you are now using bufnum 0. Then, Buffer.sendCollection asks the bufnum allocator for an available buffer number. You haven't told it that 0 is in use, so it returns that one.

Recommended approaches:

- Don't mix styles: Either hardcode all your buffer numbers, or always let the bufnum allocator choose them.

- Or, use s.bufferAllocator.reserve(index, numBufs) for all your hardcoded bufnums (see the help for this method -- I might have gotten the arguments wrong).

**Comment by michaeldzjap** [comment]
Ok, thanks for the clarification. I understand now. Another one of those client/server subtleties.
