### ISSUE TITLE
evaluate region (cmd-enter) in help file calls code selected in code editor

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#1676]
Evaluate region in help file calls code selected in code editor. This happens only when using `cmd-enter`(evaluate region) and not in `shift-enter`. Evaluate region isn't implemented in the help system. Instead, the same key should probably do _nothing_.

Possibly the mistake is here?

```
void HelpBrowser::applySettings( Settings::Manager *settings )
{
    settings->beginGroup("IDE/shortcuts");

    mActions[DocClose]->setShortcut( settings->shortcut("ide-document-close") );

    mActions[ZoomIn]->setShortcut( settings->shortcut("editor-enlarge-font") );

    mActions[ZoomOut]->setShortcut( settings->shortcut("editor-shrink-font") );

    mActions[ResetZoom]->setShortcut( settings->shortcut("editor-reset-font-size") );

    QList<QKeySequence> evalShortcuts;
    evalShortcuts.append( settings->shortcut("editor-eval-smart") );
    evalShortcuts.append( settings->shortcut("editor-eval-line") );
    evalShortcuts.append( QKeySequence(Qt::Key_Enter) );
    mActions[Evaluate]->setShortcuts( evalShortcuts );

    settings->endGroup();

    QString codeFontFamily = settings->codeFont().family();
    mWebView->settings()->setFontFamily( QWebSettings::FixedFont, codeFontFamily );
}
```

**Comment by telephon** [comment]
This was discussed in #1385

**Comment by timblechmann** [comment]
the shortcuts for evaluating code in the code editor are defined in MultiEditor: grep for `EvaluateRegion` and `EvaluateLine`.

**Comment by scztt** [comment]
To reiterate / collapse some of my comments from the previous thread:
- we use `QEvent::ShortcutOverride` to catch eval-related events in the HelpBrowser
- for some reason, our ShortcutOverride is not even being reached in case of Cmd+Enter. My hypothesis was that this is because Qt already has an override or other special shortcut handling behavior elsewhere that is catching the Cmd+Enter further up in the UI. ShortcutOverride overrides the normal keyboard event chain, but there doesn't appear to be a mechanism to override OTHER overrides / other non-standard interceptions of the event.
- A pragmatic fix is to install an application-eval Cmd+Enter handler (which we may already have, if it's not on the editors themselves), detect which widget has focus (editor, help browser, etc) and explicitly invoke an eval method on that.

**Comment by telephon** [comment]
Added a note in Known Issues

**Comment by kisielk** [comment]
I can confirm it's something specific about cmd-enter. If I reassign the shortcut to something else in the preferences then it works fine.

**Comment by telephon** [comment]
Fixed in https://github.com/supercollider/supercollider/commit/7201aa7016f2de87b2827cf6bcc2b0f1f952b7a0
