### ISSUE TITLE
Autocomplete tooltip colors are unreadable on Linux

### ISSUE THREAD

**Issue by smrg-lm** [supercollider/supercollider#1704]
The fonto color of the tooltip is white over yellow which makes it not readable.

![white-yellow](https://cloud.githubusercontent.com/assets/703536/10855069/61091fb0-7f1e-11e5-83d9-0298bf1add47.png)

Ubuntu 14.04 Qt from Digia and Ubuntu.

**Comment by theseanco** [comment]
Also having this issue, any way to resolve it?

**Comment by theseanco** [comment]
As pointed out by @danstowell this appears to be a bug with ubuntu and unity.

**Comment by gusano** [comment]
It would be nice to be able to configure those colours in the theme..

**Comment by timblechmann** [comment]
@gusano, QPalette, not theme: https://doc.qt.io/qt-5/qpalette.html#ColorRole-enum

on some operating systems, it is populated by the desktop environment, on some it isn't.

**Comment by felixetienne** [comment]
Same problem for me on Ubuntu16.04 / Gnome3.

**Comment by vivid-synth** [comment]
(can we add the "QT GUI" label to this?)

**Comment by snappizz** [comment]
Still happening here. Ubuntu 16.04 with xfce

**Comment by miguel-negrao** [comment]
Happens in debian testing +  gnome 3.20.2 too.

**Comment by grirgz** [comment]
Ok, I have taken this like a challenge and searched for hours how to fix
this, and I found it ! (at least, on ubuntu 14.04)

install color chooser and launch it:

sudo apt-get install gnome-color-chooser
gnome-color-chooser

then go to "specific" tab, then check the checkbox in "tooltips"
section and choose good colors

now restart the SCIDE, and voila ! (hope this works for everybody)

Maybe there is also something to do in scide code, but at least it's a workaround

**Comment by felixetienne** [comment]
Wow! Works fine :D 
Thanks!

**Comment by telephon** [comment]
So is this a bad choice in SCIDE or in gnome?

**Comment by snappizz** [comment]
@telephon It's not GNOME- or Unity-specific, I'm also seeing it in xfce. It happens when the default tooltip color in the window manager is white or whiteish, and it looks like scide just forgot to override it.

**Comment by telephon** [comment]
ok, so we keep it as a bug.

**Comment by HardwareHaquer** [comment]
For those Raspberry Pi users out there or anyone else having issues try launching scide with:
`scide -style=gtkrc` 
I haven't figured out which gtkrc file it as actually referencing, (my changes don't register) but it make the foreground black!

**Comment by smrg-lm** [comment]
@grirgz It does indeed!

**Comment by snappizz** [comment]
Can we just hardcode the colors or something?

**Comment by smrg-lm** [comment]
@snappizz It is just not implemented, I think it was pointed out by timblechmann.

**Comment by scztt** [comment]
Note that this issue was already fixed for -- what looks like GTK-based platforms? -- by hardcoding colors:  6467e06df947e32413b01e1b3d81a4875334cb18

That conditional (or the #ifdef) are probably not true for the problem platforms - so we're not hitting the hardcoded values. That said, the hardcoded values are still going to look awful depending on your IDE color scheme. We should probably ditch the weird OS-specific logic and just always make the font color == the IDE's code font color, and the window background color == the IDE's code background color, offset lighter or darker by 10% or something.

Commit 1d7d692de72984cf02f15402eb6d60dbb0a922d1 also sets the font to be the code font, which improves match with the IDE as well - worth considering.

**Comment by zetteeh** [comment]
still an issue in 3.9dev and ubuntu 16.04. 
however the workaround via the 
> gnome-color-chooser 
(suggested by grirgz - thanks!)
 still works as well.

**Comment by snappizz** [comment]
#2762

**Comment by snappizz** [comment]
WE DID IT
