### ISSUE TITLE
Github's source code bundles are unhelpful for SuperCollider because submodules missing

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#1807]
OS X read me says it, but not the Linux one. 
results in build errors

**Comment by danstowell** [comment]
What? A git checkout should NOT be required. That would be very bad. If you can't build from a plain `.git`-less source zip, that's a problem that would need fixing. If you're having "build errors" post the build errors as an issue.

I've just checked myself: for me, a linux build works fine without any git machinery.

Are you perhaps having git submodule problems? Remember that githib's automatic source downloads are not good enough, because they don't include the submodules.

If we required git for building, then debian packaging would be buggered, for a start.

**Comment by crucialfelix** [comment]
This was posted on the list by patrick dupuis. 

Now I see the issue is that there is no nova-simd submodule:

```
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- SuperCollider Version: 3.7.0-beta1
-- Building from branch , commit hash is
-- Build type defaulting to "RelWithDebInfo"
-- Compiling with Qt GUI
-- Found Pthreads: /usr/lib64/libpthread.so
-- building boost libraries manually
CMake Error at external_libraries/CMakeLists.txt:2 (message):
  nova-simd submodule is missing: please run `git submodule init && git
  submodule update' from the toplevel of your git working tree
```

How do you put the debian package together ?

OS X readme doesn't say you have to use git but it instructs you to use git to get the source. I think it was me that "simplified" and removed that sentence.

**Comment by danstowell** [comment]
OK so their problem is submodules. This is a big shame with github's system - it would be great to use it for downloads but they are, quite literally, defective! If it included the submodules it would be a delight.

You ask "How do you put the debian package together?" - actually there are two questions to be answered:

1. "How do you put the **linux source** package together?" Answer: you run ./package/package - it creates two source files. *(One is the "full" source code and one is linux-specific simply because it has some of the win/osx folders stripped out. The stripping is not superfluous here: it's needed because there are licensing reasons that those folders can't go into the package managers.)*
2. "How do you put that linux source package **into debian**?" Answer: you take the source bundle and put it into the debian team's special git repository which has some very interesting structure, but anyway the main consequence is that it adds a "debian" folder into the source tree with the debian build rules. The debian build farm then runs a build.

**Comment by danstowell** [comment]
P.S. the "fatal" is not fatal, in that output. It's an annoying side-effect of always telling cmake to run a git command even when it's not in a git checkout.

**Comment by crucialfelix** [comment]
So the source tar on the release page is not usable. That's the issue. 

Then how do you get the source including the submodules ? tediously ?

**Comment by danstowell** [comment]
No, nothing is tedious. It's:

1. Developer uses git clone --recursive to get supercollider
2. Developer runs ./package/package
3. Developer puts the resulting source bundles on a nice website somewhere
4. User downloads

**Comment by timblechmann** [comment]
https://github.com/supercollider/supercollider/blob/master/package/git-archive-all.sh

**Comment by crucialfelix** [comment]
Thanks, very clear.

So we can upload those source bundles as "binaries" on the releases. I'm not sure that we can remove the github generated zip/tar.gz but we can note in the github release notes.

Each of the READMEs should say it quite clearly in the build section that if you did not do a `git checkout --recursive` then you may be missing the submodules.

**Comment by danstowell** [comment]
The READMEs should not assume that they are contained within a git checkout either ;)

...by which I mean, if a user gets a source ZIP and reads the readme, the writing in the readme shouldn't mislead them into thinking they're supposed to be using git. Just to bear that in mind. (Also, remember that the `nova-simd submodule is missing` error message (as you quoted above) should catch people who use git-but-forgot-the-submodules.)

Sounds OK to upload those source bundles as "binaries" thanks.

**Comment by miczac** [comment]
I checked this morning, the tarballs are only a snapshot and miss the .git directory.
it's not possible to checkout or the like without the repo structure.
So, aren't the zip/tar files useless for the SC project then?

**Comment by danstowell** [comment]
The fact that github's source downloads don't include the submodules is a bug in github. So yes I agree that github's automatic zip/tar files are useless for the SC project. However, the nice source code bundles that we create with our own script (described above) are lovely :)

**Comment by danstowell** [comment]
fwiw I disagree with the assertion of the new title to this PR, "Linux README should note that git submodules source code is required to build" - this is a misleading statement when people have a proper source download. If you have a proper source download you don't need to have a clue what git is.

**Comment by crucialfelix** [comment]
Well I just changed it because the old title was no longer relevant: it does not require git.

This isn't the documentation itself, its just the github issue.  Edit it if you like.

Actually no - its not misleading at all. The github submodules source code is required to build.  Full stop. That's true.

**Comment by danstowell** [comment]
I'm being picky, but it's just because there are two ways of interpreting when you say "the git submodules source code" - it can be read as meaning it has to be obtained via git, which is a reasonable reading of the phrase but it is not correct.

Let's imagine that github's half-finished source code bundling never existed. Then there is only one use case we need to worry about, which is people doing a git checkout without getting the submodules. In that case, they will get the correct warning output by the cmake command, which will tell them exactly what git commands to run to fix the situation.

The linux readme doesn't tell people how to acquire the source code at all. This is reasonable I guess, because most people are reading the readme because they've already acquired it.

**Comment by crucialfelix** [comment]
> Let's imagine that github's half-finished source code bundling never existed. 

But it does, so the situation we find ourselves in:

> The linux readme doesn't tell people how to acquire the source code at all. This is reasonable I guess, because most people are reading the readme because they've already acquired it.

So we had better warn them about the git submodules in case they don't have them.

Look - its just the title of the issue. Change it and/or actually write the README.

**Comment by danstowell** [comment]
thanks for the sarcastic title. I'm just trying to make sure the linux readme doesn't go off down the wrong path of filling up with guff.

the github "release" mechanism, I've not worked with it. Is there no way to remove the source bundles, not even going forward? the documentation is sparse. we really need to stop people from downloading them, because if people download them then they are guaranteed to be in a broken situation.

**Comment by crucialfelix** [comment]
lol, its even worse now. how is that an issue ? we cannot take action on that.  there is not way to resolve the issue now.

the issue I had is to update the README to inform the person to make sure they have the full source code.

anyway, less yammering more hammering.

**Comment by danstowell** [comment]
It's a good description of the problem - i.e. the issue - but not a description of the solution.

**Comment by danstowell** [comment]
Well FWIW I asked Github support, and they gave a friendly but fruitless reply:

> Sorry for the trouble! This is mainly due to the way git-archive works. If you would like to include submodules in your release, we recommend building a source tarball that includes the submodules and manually upload it to the release as a release asset.
> 
> It's not currently possible to stop or hide the source code download but I'll make a note of this for the team to consider as a feature request.

**Comment by gusano** [comment]
> Is there no way to remove the source bundles, not even going forward? the documentation is sparse. we really need to stop people from downloading them

@danstowell Sorry if I miss something but what do you mean by *remove the source bundles*? Do you mean the release archives?

**Comment by danstowell** [comment]
@gusano when one makes a "Release" on Github, it creates a .zip and a .tar.gz of the source code. Those are what we're referring to. Those source bundles are defective. We can upload our own source bundles by "pretending" that they're binaries, but we can't remove the defective auto-made ones.

**Comment by gusano** [comment]
@danstowell Thanks, got it.
Indeed that's a bit annoying..

On a side note, I guess we could give a more meaningful name to our release binaries than
`SC-9899190d8808191e871cbfced848d7791374ed8c.zip`, maybe something like `SC-3.7.0-beta1-OSX.zip`?

**Comment by timblechmann** [comment]
at the time when i managed the releases, i have built the source tarball with this script:
https://github.com/supercollider/supercollider/blob/master/package/git-archive-all.sh

**Comment by danstowell** [comment]
Thanks Tim, it's a useful script (and it's also invoked by the "package" script). I presume you weren't using the github website's "Release" option though? That's the problem here, really, not the question of how we make our own packages.

**Comment by timblechmann** [comment]
at that time binaries and tarballs were still served from sourceforge

**Comment by crucialfelix** [comment]
I think that as long as the release notes on each release on github say that the .zip and .tar.gz do not include the source code that is in git submodules, and that you should get the source using git then we shouldn't worry too much about this. Most everybody does that anyway. 

The README/build instructions should again note there are git submodules and you should use git to get the full source.

If you want you can add something to travis that packages the full source and uploads it just like the release do. But IMO this isn't worth the time or effort. It increases maintenance costs and documentation and yet most people are probably just fine with being told to use git to get the source.

**Comment by danstowell** [comment]
It's important for linux package managers to have an official upstream source bundle to refer to. I can manually add the linux source as a "binary" so let's just do that.

(To put it on record: it's the "-linux-source" thing produced by the "package" script. It is special because it has non-linux things stripped out, and the reason for explicitly doing that is because of debian's strictness about licensing and source code.)

**Comment by crucialfelix** [comment]
Sounds good. "SuperCollider-3-7-0-Linux-Source.tar.gz" or something like that

**Comment by danstowell** [comment]
What I've done, for dress-rehearsal, is taken SuperCollider-3.6.6-Source-linux.tar.bz2 from SourceForge and added it to [Github's 3.6.6 release](https://github.com/supercollider/supercollider/releases/tag/Version-3.6.6). The one for 3.7 will be very similar format. I can use this 3.6.6 file for a dry-run, tweak the debian stuff.

**Comment by danstowell** [comment]
It doesn't look too bad actually, nice and prominent

**Comment by crucialfelix** [comment]
Yeah, looks good.

On Thu, Feb 4, 2016 at 9:11 PM danstowell <notifications@github.com> wrote:

> It doesn't look too bad actually, nice and prominent
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/issues/1807#issuecomment-180027257>
> .
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by danstowell** [comment]
OK great! I'm going to close this issue, on the basis that all we need to do is remember to upload the linux source package and hope that people like to click on it!

For reference, creating the linux source package can be done by anyone, like this:

      git checkout 3.7
      cd package
      ./package -v 3.7.0 -s

(Just now I've double-checked that the linux source package that is produced by this process compiles on my machine: yes, looking fine.)

**Comment by crucialfelix** [comment]
@danstowell looks like other people are annoyed at the source code thing too: https://news.ycombinator.com/item?id=11087857

**Comment by danstowell** [comment]
@crucialfelix I added the linux source to 3.7.0beta2 as described above

**Comment by crucialfelix** [comment]
i noticed that. thanks !
