### ISSUE TITLE
Documentation conflict - Float vs. FloatArray

### ISSUE THREAD

**Issue by carlocapocasa** [supercollider/supercollider#1874]
The FloatArray helpfile says: FloatArray - 32 bit floating point

The Float helpfile says: A 64 bit double precision floating point number.

0.1111111111111111111111.postln
=> 0.11111111111111

This would suggest double.
#1873 may suggest that historically, Float may have been 32 bit, and that some functionality of FloatArray may not have been adapted yet.

**Comment by jamshark70** [comment]
The behavior you describe is exactly what you'll get from 32 bit floats.

Use DoubleArray.

**Comment by jamshark70** [comment]
To be more precise: SC's freestanding FP numbers are 64 bit, always. There is no Float32 class. Math on floats is 64 bit, and printing is based on 64 bit.

FloatArray and its subclass Signal exist because soundfiles are usually 16 or 24 bit precision. Double precision has 54 bits of precision. If you load 24 bits of precision into 64 bit floats, you're wasting space for no gain in actual accuracy. So FloatArray is meant for storage of large amounts of lower-precision data, but it is not meant for super-accurate math.

When SC prints numbers from a FloatArray, it has to get the numbers out as atomic floats: 64 bit. SC's default string conversion for floats is good for true 64 bit, but it's too precise for 32 bit floats. So you magically see the inaccuracy that was always there. Even if SC rounded the 32 bit floats to "appear" to be accurate, they are still exactly as imprecise as before.

So, if you want 0.1 to print out as 0.1, use double-precision. In SC, this is Float for single numbers and regular Arrays or DoubleArray for collections.

**Comment by carlocapocasa** [comment]
Thanks for the detailed explanation.

**Comment by brianlheim** [comment]
Fixed/explained via #2666.
