### ISSUE TITLE
OS X Readme: note that Qt 5.5 is required, not Qt 5.6

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#1931]
Due to recent update, supercollider doesn't work with Qt 5.6

Update build instructions:

`brew install homebrew/versions/qt55` instead of just `brew install qt5`

I don't think this part is needed, but:

- set CMAKE_PREFIX_PATH to /usr/local/opt/qt55 (instead of ..../qt5)

`brew switch` for changing versions

**Comment by bagong** [comment]
> I don't think this part is needed, but:
> - set CMAKE_PREFIX_PATH to /usr/local/opt/qt55 (instead of ..../qt5)

If this part is not needed for you, the only explanation I have is that you have qt5 in the PATH. Which carries the same risk of pointing to the wrong qt version. I am not sure if it is well defined what happens if you have qt5 in the path and point to a different version with `CMAKE_PREFIX_PATH`.
What I've just empirically verified: if you update qt5, you will have both, v5.5.1 and v5.6 on your machine, /usr/local/opt/bin will be linked to qt5.6, and `brew --prefix qt5` will point to that location. So you need to make sure, none of the mechanisms pointing to any "default location" of qt5 are still active, in order to make sure your compile looks at v5.5.1 only. I am pretty sure `CMAKE_PREFIX_PATH` is the safest way to achieve that.

**Comment by crucialfelix** [comment]
this clarifies it for me:

> will be linked to qt5.6, and brew --prefix qt5

so brew switch can change that

> And sorry for nitpicking

No no, thank you for nitpicking ! That's what we are all here for. To pick the nits before everybody else has to.

Now we have all the info to update the README

**Comment by bagong** [comment]
I am glad you're not oversensitive ;). I can update the readme it if you're busy...
