### ISSUE TITLE
Find a community hub to showcase SuperCollider-related sounds and music

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#1934]
https://soundcloud.com/groups/supercollider

```
SuperCollider 
Music made with the SuperCollider Programming Language

Please post stuff that is more or less pure sc1/2/3 only!
If you can provide code also, it-s appreciated.
More info about SuperCollider at supercollider.sourceforge.net
```

should be (example to be adapted)

```
SuperCollider 
Music made with the SuperCollider Programming Language

Please post stuff that is more or less pure sc1/2/3 only!
If you can provide code also, it's appreciated.
SuperCollider code sharing e.g. via http://sccode.org. 
More info about SuperCollider at http://supercollider.github.io
```

**Comment by LFSaw** [comment]
@nuss , I think you're able to do that change...

**Comment by alln4tural** [comment]
the creator of the group, mstep, made a bunch of us moderators at some point, and we've been 'curating' successfully, i think, without ever talking about it.

the way soundcloud works, apparently, is that only the orig creator can change the descriptions usw ..
i will try to get mstep's attention by email -- or does anyone else have contact?

**Comment by patrickdupuis** [comment]
Has there been any progress on this?

**Comment by alln4tural** [comment]
Ok, mstep no longer has access to the edit functionality, either, leaving the group partially in limbo.

I've contacted soundcloud support but am not holding my breath.

**Comment by alln4tural** [comment]
ok, got a response from soundcloud: 

"[..] and since Groups is a legacy feature, we have little to no flexibility with them besides the ability to delete them."

Groups are a legacy feature, who knew.

i guess we can either create a new group (awkward), or think about another place to showcase supercollider-made sounds.

thoughts?

**Comment by LFSaw** [comment]
create a netlabel on archive.org?

https://archive.org/details/netlabels&tab=about
http://www.ektoplazm.com/blog/hosting-netlabel-releases-at-the-internet-archive

**Comment by crucialfelix** [comment]
netlabels should have releases. supercollider is a group of known tracks that may have been released elsewhere.

how about soundcloud/the-real-supercollider ? /jk

**Comment by LFSaw** [comment]
I have a strong opinion to use a _free_ and open source service for something supercollider related. 
With the recent development around soundcloud, I do not see it as a sustainable platform anymore. 
This is why I suggested archive.org. 


:)
	Till

**Comment by crucialfelix** [comment]
Sure sure, I'm not against archive.org in the least. I just thought that maybe this supercollider playlist doesn't qualify as a netlabel. You could start a label though and actually do releases. why not do that ?

**Comment by LFSaw** [comment]
hey chris,

I think we're just talking abou thte same way on different terms:

AFAIK Archive.org does not provide playlists or groups made of tracks of many users.
Archive.org's netlabel feature requires releases and a dedicated person (community?) that organises this.
The current situation with SoundCloud is IMHO not sustainable for an open source-based community as the one surrounding SuperCollider.


>>> so I don't have a clue what to do.

:/
	Till

**Comment by alln4tural** [comment]
Ok, things have come to a head in that soundcloud have announced they're closing down groups. So we need a new showcase scheme (those of us that think this kind of thing useful)

One relatively near-by possibility is to create a dedicated soundcloud account and use the repost function. The internal management will be a bit more cumbersome, I think, especially speaking the work, but the net effect would be the same (a widget we can embed to showcase sound made with supercollider)

@LFSaw i'm happy to help with a internet-archive-based solution, but it sounds like a lot more work for the maintainer(s). I'd be really happy to be proven wrong on that, though. My love affair with soundcloud has been going through some dire straights.


Any ideas?

**Comment by alln4tural** [comment]
ok, i have created a dedicated account on soundcloud:
https://soundcloud.com/supercollider-showcase

its main purpose is to maintain a playlist we can point to:
https://soundcloud.com/supercollider-showcase/sets/supercollider-showcase
or embed as we do with the current, soon-dead soundcloud group
<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/246521077&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;visual=true"></iframe>

The process -- shamelessly stolen from http://disquiet.com/2016/07/26/disquiet-junto-after-the-end-of-soundcloud-groups/ -- is


Step 1: Participant uploads/posts track to SoundCloud.

Step 2: Participant (privately) messages (on soundcloud) @supercollider-showcase the track’s URL.

Step 3: we (the account admins) then add the track to the playlist.
(optionally, also 'repost' the track; this is of interest only to active soundclouders)



i am asking for comments on this "solution", and
i am looking for people to share the burden of maintaining this, i.e. periodically logging into the account and performing step 3. 


cheers,
eddi

**Comment by chilina** [comment]
Hey you guys thanks for working on this.  I've enjoyed listening to the "old group" over the past couple of years and I'm glad you have found a way to continue it, despite the demise of groups.  I agree that the SoundCloud model might not be compatible with SuperCollider users over the long term, and at the very least you've bought some time to explore other options.

SoundCloud wouldn't let me message @supercollider-showcase.  It found SuperCollider.github.io (because I'm following it I think) but told me a few times that it had an error in sending the message, so I'm not sure if it made it or not.  And sorry for multiple messages if that's the case.

I'd be happy to help maintain the new list (log in every once in a while and perform step 3.  So just let me know if you need some help.  Hopefully my message made it thru the message system for 
SoundCloud.

Thanks,

Tim

**Comment by lf0-fl0** [comment]
hi guys,

shame on that soundcloud + so on...but in absence of alternatives im more than happy to help maintaining the profile if this is needed.

best

flo.huth

**Comment by alln4tural** [comment]
hi

if you are willing to co-moderate this experiment, send me an email
alln4tural@gmx.net
and i'll give you the account password.


i want to make announcement on sc-users, something like below -- comments welcome!

cheers,
eddi


______________________________________________________


SC showcase on soundcloud

greetings fellow soundmakers,


as most of you interested in this kind of thing know, soundcloud has killed the 'groups' functionality,
which was host to the SuperCollider group since about 2009.

The group had over a thousand tracks by hundreds of artists, countless hours of sounds more or less pure SuperCollider.
I have tried to archive them here:
https://soundcloud.com/supercollider-showcase/sets/supercollider-showcase-pre
https://soundcloud.com/supercollider-showcase/sets/supercollider-showcase-2013
https://soundcloud.com/supercollider-showcase/sets/supercollider-showcase-2010


Going forward, until someone sets up something that isn't reliant on soundcloud
-- if you have ideas, please join the conversation here: https://github.com/supercollider/supercollider/issues/1934 --
there is 

https://soundcloud.com/supercollider-showcase

If you'd like your track to featured:


Step 1:  Upload your track to SoundCloud. 
Please indcate in the track notes and tags how SuperCollider was involved,
and (always greatly appreciated, but not mandatory) post some code,
maybe on http://sccode.org


Step 2: Privately message (on soundcloud) @supercollider-showcase the track’s URL.

We (the account admins) will then add the track to the playlist:
https://soundcloud.com/supercollider-showcase/sets/supercollider-showcase

**Comment by brianlheim** [comment]
Ping. Can I close this? I think an open issue on GitHub is maybe not the best place for this info. Maybe we could migrate it to github.io site (if it's not there already)?

**Comment by LFSaw** [comment]
how to migrate it there?
is the issue tracker purely for software or also for community-related issues?

**Comment by brianlheim** [comment]
It's perfectly fine to have organizational issues tracked here!

Okay, basically I just want to know what needs to be done so that this issue can be closed, because it's unclear to me from the discussion. Is the problem that it's still hosted on SoundCloud instead of some other service? If that's the case then I propose simply changing the issue title.

**Comment by LFSaw** [comment]
I see your point...
I'd propose closing this issue as unresolved and opening another issue with a description on what needs to be done:
e.g. "Find community hub to showcase SuperCollider-related sounds and music"

which links to this.

thoughts?

**Comment by LFSaw** [comment]
I think, this is a good idea, @chilina . However, for the sake of keeping issues central, I'd propose to open an issue here on the (central and open) github tracker and refer to it within (forum and email) threads.

**Comment by chilina** [comment]
Sounds great!  I think if the github tracker is the best platform for discussion then it should be used to collect feedback.  I don't know if the (prior) thread ever found its way into the SC forum; I found it by digging thur Google search.  I'm kinda wondering too if we might need a couple of platforms.  Lots of people are vested in Soundcloud for various reasons, but something less "proprietary" might be better for others.  And I worry if Soundcloud is going to be around in a few years time.  I tired to email archive.org a while back to see if it might be suitable but never heard back from them, and then got busy with other stuff.  Looking forward to seeing what develops with this.

**Comment by brianlheim** [comment]
In the interest of keeping the discussion in one place, I've simply renamed this issue to what @LFSaw suggested. Even though the discussion started off as something else, there have been a lot of relevant bits of information shared here!

I think archive.org is a very good option. I'm looking over their FAQ right now, and the hurdle seems to be getting together documented permission from all contributors/artists. I'm not sure the fact that they were available for free on SoundCloud automatically means that they can be shared on archive.org... Thoughts?

**Comment by chilina** [comment]
It may be that moving the existing Soundcloud archive to something new 
will require artists to resubmit tracks to the new platform; moving it 
may be a ton of work for just a few people.  The current playlists on 
Soundcloud could stay intact as a static archive. Soundclouds allows 
both the designation of a Creative Commons (CC) license for each upload, 
along with an option to allow downloads. So theoretically any track in 
the playlist that has a suitable CC license and allows downloads could 
be moved to a new platform.

Archive.org has netlables (https://archive.org/details/netlabels). We 
could create a SuperCollider label with monthly releases.  But like 
@LFSaw indicated in an earlier post, I think it would require one entity 
to collect and upload the content.    And then this morning I came 
across Netlables.org, which says its open-source and has a github page, 
abut that's all I know about it at the moment. I'll look at it a bit 
more over the weekend.  Also, I'm wondering if sccode.org could be 
expanded to include audio uploads, if even on a limited basis (revolving 
archive, max size, etc).  It might be a nice pairing to have the code 
and audio on one site.

In this evolving digital age, it may not be a bad idea to have more than 
one platform, to try different things and see how it goes. Soundcloud 
has been great because it lets artists manage their own accounts 
(upload, download, license, tags, etc).  And the idea of using a 
playlist to aggregate SuperCollider content into one place seems like an 
easy and efficient way to manage that.  The obvious risks of SoundCloud 
are its proprietary nature and its unproven business model.  However, 
both of those could change in the future, for better or worse.

I'll message @alln4tral again this weekend about continuing to add to 
the playlists on Soundcloud.  But on balance I think its worth looking 
around for a new platform, as we may find something that is better 
suited as @LFSaw has suggested.

I'm also glad this thread has remained intact, even though its evolving 
a bit.  Should we post a note in the forum and ask the users for ideas 
for a new platform?  and weigh in on continuing the current Soundcloud 
lists?

**Comment by brianlheim** [comment]
I think going to users is a good idea for this. Would you mind making a thread?

**Comment by chilina** [comment]
Yes I'll join the forum and post something in about a week.  I'd like to 
see if I hear back from @alln4tural before posting something in the forum.

**Comment by chilina** [comment]
One more thing to consider before posting to the forum.  We could maybe make this really easy and able to accommodate a wide variety of  platforms by adopting a common tag for uploads.  #SuperCollider is not exclusive enough (Radio Head, other bands, etc).  But #SuperColliderUsers has not been used on either archive.org or Soundcloud.  If we tried to get artists to use a common tag, they could pick any platform they want, or as many as they want, and it would be searchable on any existing or new platform.  Any thoughts on this?

**Comment by telephon** [comment]
#SuperColliderUsers is a bit long. What about `#sclang`?

**Comment by snappizz** [comment]
How about `#scsynth`? It encompasses alternate client users and makes it immediately clear that it's some kind of synthesizer.

**Comment by LFSaw** [comment]
I like both, sop why not both?

**Comment by chilina** [comment]
Hey thanks for these responses about the idea of using common tag(s) that could help uniquely identify SuperCollider work on various platforms.  I think I'll add this to the posting in the forum later this week, and see what people have to say.  

I also like both scsynth and sclang.  A quick check gets some search hits on Soundcloud, with fewer on archive.org.  But scsynth.new and sclang.new both give no hits on a Soundcloud search.  There are lots of hits for sctweets on Soundcloud, but only 1 for sctweets.new.  I'm not necessarily advocating the ".new", just looking at how well different (related) tags can generate search results in the present, and trying to find ones that haven't been used too much (yet!).

I do like this idea of using a common tag to aggregate content from contributors though.  It seems easier and more robust than maintaining a playlist, and it would work on lots of different platforms.  Plus a mini-list of "common tags" could allow some segregation of content ("anything Supercollider" vs tweets vs. livecoding vs. compositions, etc).

**Comment by brianlheim** [comment]
I like both #scsynth and #sclang -- I'm glad this discussion is happening! Looking forward to hearing what the wider community has to say. :)

**Comment by chilina** [comment]
The SoundCloud playlist appears to be actively maintained again, according to this:  http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/SuperCollider-on-SoundCloud-td7630422.html.  The new playlist resides here:  https://soundcloud.com/supercollider-x.

This morning I posted to the mailing list about the idea of using tags.  Find it here:  http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/a-list-of-common-tags-for-supercollider-work-on-various-platforms-td7630529.html.

**Comment by dmorgan-github** [comment]
Why not reddit?

**Comment by brianlheim** [comment]
closing as stale. perhaps the discourse forum now fulfills this in some ways.
