### ISSUE TITLE
Buffer.write sample rate is that of server, not buffer

### ISSUE THREAD

**Issue by capocasa** [supercollider/supercollider#1952]
When allocating a buffer with a specific sample rate (e.g. 15000), a sound file written from it will still have the server's sample rate (e.g. 48000).

s.boot;
(
d=Buffer.new(s, 100, 1);
d.sampleRate=15000;
d.alloc;
d.updateInfo;
d.sampleRate
)
=> 15000

(
d.write("/tmp/a.wav", "wav");
)

$ soxi /tmp/a.wav

[...]
Sample Rate    : 48000

**Comment by jamshark70** [comment]
Actually, in your example, the buffer's sample rate is *not* 15000. You've been bitten by a subtle gotcha: `updateInfo` is asynchronous. The buffer's variables are not updated until the message comes back from the server with the new information.

When you run the first block all at once, it goes like this:

1. d.alloc -- sends the `/b_alloc` message to the server, to reserve buffer memory.
2. d.updateInfo -- sends a `/b_query` message to the server.
3. d.sampleRate -- returns (and prints) the old sample rate.
4. A `/b_info` message comes back from the server, and d's variables are updated. But, you already printed, so this never makes it onto the screen.

If you run the first block one line at a time -- printing the sample rate after `/b_info` comes back -- you'll find that the buffer's rate in the server is the server's sample rate.

The reason is that `/b_alloc` sends the number of frames and number of channels, but not the desired sample rate. That is, currently, there is no way to do what you're asking. (A buffer's sample rate differs from the server's rate only if it has been loaded from disk, never otherwise.)

It's a legitimate enhancement request, but it also means changing the OSC message format (or adding new messages). Not quite simple.

**Comment by jamshark70** [comment]
Well... "no way to do what you're asking"... `SoundFile` in the language can write audio files at any sample rate. So, you can fetch buffer data into the language and write from there:

```
d = Buffer(s, 15000, 1);
d.sampleRate = 15000;
d.alloc;

(
var file = SoundFile("~/temp.wav".standardizePath)
.sampleFormat_("int16")
.headerFormat_("WAV")
.sampleRate_(15000),
bufData, chunkSize = 1500,  // 1500: stay within OSC limit
cond = Condition.new;

if(file.openWrite) {
	fork {
		protect {
			(d.numFrames * d.numChannels / chunkSize).roundUp.do { |i|
				var start = chunkSize * i,
				size = min(chunkSize, d.numFrames - start);
				d.getn(start, size, { |data|
					bufData = data;
					cond.unhang;
				});
				cond.hang;
				file.writeData(bufData.as(Signal));
			};
		} { file.close };
	};
};
)
```

Now ~/temp.wav will be 15000 Hz.

**Comment by carlocapocasa** [comment]
Thank you for your prompt and detailed feedback, James, as always.

I do now feel a certain itch to create some kind of nasty client side "allocRate" hack involving the writing of a temporary sound file. We will see.

**Comment by carlocapocasa** [comment]
... and now I'm getting a spontaneous code snippet, this is really above and beyond and much appreciated.

What I'm using now is this snippet that re-writes a soundfile with a different header. Of course this would lead me to requesting the re-writing of sound file headers (except sampleFormat) without changing the data, but here it is:

+ SoundFile {
  *s_convert {|path,newSampleRate,newHeaderFormat, newSampleFormat, chunkSize = 4194304|
    // TODO: Fine a way to do this without converting the data (ignore newSampleFormat)
    var s, t, d;
    s = SoundFile.openRead(path);
    if (s.isNil) {
      Error("Could not open file %".format(path)).throw;
    };
    t = SoundFile(path ++ ".s_convert");
    t.sampleFormat = newSampleFormat ?? s.sampleFormat;
    t.headerFormat = newHeaderFormat ?? s.headerFormat;
    t.sampleRate = newSampleRate ?? s.sampleRate;
    t.openWrite;
    d = FloatArray.newClear(chunkSize);
    while { d.size > 0 } {
      s.readData(d);
      t.writeData(d);
    };
    s.close;
    t.close;
    "mv % %".format(t.path, s.path).systemCmd;
  }
}

(
// More or less the same as above but trades re-writing the data on disk for not having it go through the network stack
~buffer.write("/tmp/foo.wav", "wav")
SoundFile.s_convert("/tmp/foo.wav", 15000);
)

**Comment by carlocapocasa** [comment]
The performance of the above function lead to unacceptable delays, so I ended up writing a UGen to set a buffer's sample rate:

```
void BufSet_next_k(BufSet *unit, int inNumSamples)
{
  float trig = ZIN0(1);

  if (trig > 0.f && unit->m_prevtrig <= 0.f) {
    SIMPLE_GET_BUF
    float samplerate = ZIN0(2);
    SndBuf* buf2 = unit->mWorld->mSndBufsNonRealTimeMirror + (int)unit->m_fbufnum;
    unit->m_buf->samplerate = samplerate;
    buf2->samplerate = samplerate;
    //printf("SR %f %f\n", unit->m_buf->samplerate, buf2->samplerate);
  }

  unit->m_prevtrig = trig;
}
```

I hope setting an NRT buffer mirror won't blow anything up, but for my current use cases it works (triggered, control rate).

**Comment by telephon** [comment]
It makes sense to have such a UGen.

`BufSet` is not a good name. Better `BufSampleRateSet`, I think.

**Comment by carlocapocasa** [comment]
Yes, that's better.
