### ISSUE TITLE
Server crash when calling play on a not-yet ready Buffer

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#2005]
This was reported on sc-users.
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/beginner-question-on-samples-td7624999.html

Evaluating the following line crashes the server for some users:

`b = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav"); b.play; `

I'm on 3.7.1 linux. It has been reported to crash on OSX as well.

**Comment by patrickdupuis** [comment]
Post window says:
`-> Synth('temp__0' : 1000)`
`RESULT= 0`

**Comment by gusano** [comment]
With 3.8dev (linux) I *only* get an error, no crash:

```
ERROR: a PlayBuf: wrong number of channels (nil)

PROTECTED CALL STACK:
	MultiOutUGen:initOutputs	0x332de80
		arg this = a PlayBuf
		arg numChannels = nil
		arg rate = audio
...
```

Full error [here](https://gist.github.com/gusano/b81949425fe4b9a90d50313a6a7dae0b)

**Comment by jamshark70** [comment]
@patrickdupuis do you have any extensions that might be overriding core Buffer methods?

As far as I can see in the main 3.7 class library, the crash should be impossible -- as gusano noted, Buffer:play should fail even to build the SynthDef. The only ways that Buffer:play could be sending a SynthDef and trying to play anything in this case are:

- the play method is overridden somewhere with a buggy, unsafe alternative;

- or, something else is overridden so that the Buffer object's default numChannels is a number (rather than nil, as in the main library).

**Comment by jamshark70** [comment]
Disregard my last comment. It's a genuine bug in 3.7 that is fixed in 3.8.

We should backport the fix into 3.7. Commit = 727f7b33

**Comment by telephon** [comment]
No need to backport IMO, 3.8 will come out in 12 days.

**Comment by vivid-synth** [comment]
This can be closed, no?
