### ISSUE TITLE
Specify minimum build requirements for each platform, scsynth/supernova

### ISSUE THREAD

**Issue by crucialfelix** [supercollider/supercollider#2143]
Let's make a formal decision about what the current minimum build requirements are, and when we can change those.

I think we should use the normal github wiki: https://github.com/supercollider/supercollider/wiki

Though the information would also be in the build instructions / READMEs.

To discuss:   cmake, c++14, gcc, Qt

**Comment by crucialfelix** [comment]
I don't see a problem with allowing supernova to use any advanced toolchain; it's the high performance server and it should be able to move forward and test newer performance features. Those features will trickle down to sclang/scsynth.  

If travis doesn't build it, then we would have to drop supernova from testing.

That said, supernova needs to document the requirements clearly or we will all be wasting time answering the same questions over and over again.

**Comment by crucialfelix** [comment]
scide/scsynth/sclang need to be pretty easy to compile for people that don't live and breathe c++. They should track whatever tool chains are common on each platform.

Let's not insist on supporting anything really ancient.

These are just my simple thoughts.  Those of you with expert compiler knowledge know better than me.

**Comment by snappizz** [comment]
The non-supernova components should support cmake 2.8 at minimum. As old as it is, it's the version you get from the debian repositories.

**Comment by miguel-negrao** [comment]
> scide/scsynth/sclang need to be pretty easy to compile for people that don't live and breathe c++. They should track whatever tool chains are common on each platform.

It would be good to have an understanding of how difficult it is to update the tool chain in each platform. From a quick googling about ubuntu and debian, it seems it is very easy to [install](http://askubuntu.com/questions/26498/choose-gcc-and-g-version) multiple versions of gcc in the same machine (disclaimer, never tried it myself). There are [many](https://packages.debian.org/search?keywords=gcc) versions of gcc available for debian. Not sure if updating in an old system to a very new gcc would be impossible due to package version collisions.

> The non-supernova components should support cmake 2.8 at minimum. As old as it is, it's the version you get from the debian repositories.

debian stable moves very slowly, it is released only every two years, and essentially it doesn't change once released except for security updates. Therefore, I don't think it should be required that master compiles on the current debian stable, otherwise no requirements could be changed for two years, which is too slow for development purposes. Developers who want to stay on debian stable can update their tool chain. I suppose that binaries compiled with an updated tool chain in debian stable should also run in a stock debian stable, right ?

**Comment by danstowell** [comment]
FWIW (as a distant maintainer) I'm happy with the idea that supernova can push forward.

It's certainly possible to install updated cmake/gcc/etc (as Miguel mentions), but I'd like to request that the standard repository versions continue to be supported (for non-supernova builds), even for "master" as opposed to point releases. I request this so that SC development remains accessible for a larger pool of people, and also so that packaging SC for the repositories is possible. (You don't get to install special gcc versions when you're preparing the official packages.)

**cmake**: on debian, [cmake 3.0.2 is the current debian stable version](https://packages.debian.org/jessie/cmake) while 2.8.9 is the *old* stable. On ubuntu, [2.8.12 is available in the old LTS](http://packages.ubuntu.com/trusty/cmake) and [3.5.1 in the new LTS](http://packages.ubuntu.com/xenial/cmake). (For the [debian supercollider package](http://anonscm.debian.org/cgit/pkg-multimedia/supercollider.git/) we require cmake >= 2.8.12 since although the README_LINUX says 2.8.11 is the minimum, I think 2.8.12 is actually the minimum due to a couple of extra little cmake commands someone added.) I think it would be nice to keep cmake requirement at 2.8.12 because of the widespread older Ubuntu LTS but I'd say it is NOT necessary to do that since there's a new LTS already out. So I'd say it's *possible* to bump the cmake requirement up to 3.0.2 for linuxen, if there's a good reason to prefer only cmake 3+.

**gcc**: current README_LINUX says 4.8+. Ubuntu has 4.8.2 in the old LTS, [5.3.1 in the new LTS](http://packages.ubuntu.com/xenial/gcc). Debian has 4.7.2 in the old LTS, [4.9.2 in the current one](https://packages.debian.org/jessie/gcc). So again, it'd be nice to stick to gcc 4.8.2+, but we could jump to 4.9.2 without causing much trouble on debian/ubuntu.

Qt, c++14: not my area

**Comment by miguel-negrao** [comment]
> and also so that packaging SC for the repositories is possible. (You don't get to install special gcc versions when you're preparing the official packages.)

Ah, yes, hadn't thought of that. :-) Still when the planned date for release of SC is after the planned released date of debian stable or ubuntu LTS, one could update the requirements, since in that case we know the packaging will work at the time that SC is released (unless each sc release has to be able to be packaged for even older debian versions, such as debian old stable). We are still one year away from the next debian stable more or less (no official date), so that is no the case currently, since 3.8 is apparently coming out in the summer.

**Comment by crucialfelix** [comment]
We will/should always know the sc release date a few months before. It was June 1 but maybe July 1 is better. We should decide at the start of work on a release about any toolchain changes.

**Comment by miguel-negrao** [comment]
> and also so that packaging SC for the repositories is possible. (You don't get to install special gcc versions when you're preparing the official packages.)

It just occurred to me, isn't it the case that once a certain debian stable is released we can't release a new version of SC into that debian stable ? Doesn't a new version of SC forcefully have to go into debian unstable, then testing, etc ? For instance SC 3.7 is currently in debian unstable, and not yet in in debian testing. The latest build log says that is was built [with](https://buildd.debian.org/status/fetch.php?pkg=supercollider&arch=amd64&ver=1%3A3.7.0~repack-3&stamp=1464132490):

    Toolchain package versions: binutils_2.26-9 dpkg-dev_1.18.7 g++-5_5.3.1-20 gcc-5_5.3.1-20 libc6-dev_2.22-9 libstdc++-5-dev_5.3.1-20 libstdc++6_6.1.1-4 linux-libc-dev_4.5.4-1
    Setting up cmake (3.5.2-1) 

So actually, isn't it the case that for packaging what matters is what is currently being used in debian unstable ? 

Btw, it is true that it is not that easy to install a gcc version that is not available in debian stable, since for that first the apt sources have to changed to debian testing, and then gcc installed with apt-get, which could result in a broken system.  So indeed if we want to support developing in debian stable we will need to stick to gcc 4.9.2 until around April 2017.

**Comment by crucialfelix** [comment]
btw. Miguel, did you ever do a nix package ? They would take sc I'm sure.

**Comment by danstowell** [comment]
@miguel-negrao yes you're correct for the standard supercollider in the repository. However there's also backports - the ability to support backports is not our highest priority but we did at least used to do it for ubuntu.

**Comment by timblechmann** [comment]
as for qt, you might want to check the qtwebkit/qtwebengine issue

**Comment by miguel-negrao** [comment]
> btw. Miguel, did you ever do a nix package ? They would take sc I'm sure.

yes, but I didn't test it for nixos, just nix on ubuntu, and there it looked ugly, had to do with lack of theme. It might look ok on nixos,  don't know. I think it would be better for someone who runs nixos to propose and maintain it.

> @miguel-negrao yes you're correct for the standard supercollider in the repository. However there's also backports - the ability to support backports is not our highest priority but we did at least used to do it for ubuntu.

Ok, got it.

**Comment by miguel-negrao** [comment]
So, in terms of linux the timetable for constraints seems to depend on the timetable of debian stable and ubuntu LTS. For the moment debian stable is the active constraint, as it has lower versions of gcc and cmake,  and even the next known release of ubuntu is october 2016 a long time before the next release debian stable, so debian stable will have lower bounds for quite some time. So a timetable for the *maximum* allowed constraints (sclang/scsynth/ide) would be something like:

cmake  now -> release of next debian stable (~ April 2017) - 3.0.2
gcc       now -> release of next debian stable (~ April 2017) - 4.9.2

These would be the maximum allowed constraints, the chosen constraints can be below this off course, in which case a criteria should be decided for when to switch to newer versions.

I'm not an experienced c++ developer, but for what it's worth on my recent coding for the IDE I did come across a couple of situations where c++14 features would have been nice to have. For instance, one was the use of [ generalized lambdas](https://solarianprogrammer.com/2014/08/28/cpp-14-lambda-tutorial/) - i.e. `auto func = [](auto input) { return input * input; };`, so not having to enter the type of the function and also being able to re-use that function with different argument types (as along as they are compatible, I suppose). Without this feature lambdas seemed to me quite a bit harder to use, and specially re-use, at least for someone coming from Haskell, where [all of this is taken for granted](https://en.wikipedia.org/wiki/Hindley%E2%80%93Milner_type_system). gcc 4.9.2 does support this, and [generalized lambda captures](https://isocpp.org/wiki/faq/cpp14-language#lambda-captures) too, but compiler flags need to be set to activate c++14 mode, and it seems the easiest way is [ using cmake 3.1](https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html) which unfortunately is not available out of the box in debian jessie. It might be possible to add those flags explicitly, but that will certainly be more work (volunteers ?). Another option is to direct users which use debian jessie to download recent cmake binaries and use those. I think that is easy enough:

1. Download [tar file](https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz) (using iceweasel).
2. Untar file to some directory at choice (do 'extract here' in nautilus, then move somewhere appropriate).
3. invoke the downloaded cmake binary with full path or add that folder to the PATH:

```
miguel@miguel-MacBookPro:~/Development/SuperCollider/supercollider/buildMaster$ ~/bin/cmake-3.4.0-Linux-x86_64/bin/cmake ..
-- The C compiler identification is GNU 5.2.1
-- The CXX compiler identification is GNU 5.2.1
```

I think that this is easy enough that it might be worth considering setting cmake 3.1 and gcc 4.9.2 as minimum, provided this is not a problem for other platforms. When considering this, don't forget to consider not only the extra effort required of debian jessie users (the 3 steps above) but also the savings in effort and time for those developers that would like to use c++14 features. It should also be taken into account that a knowledgeable use of some c++11 (fully supported since gcc 4.8.2, so not an issue) and c++14 features can make the code safer and more maintainable.

**Comment by bagong** [comment]
SC Windows build currently uses 2 build systems, one MinGW (Windows port of GCC) based, and the native MSVC/VS. MinGW is the traditional build system. VS does not support building sclang with command line mode (readline), and supernova yet, but has been the platform on which the most significant contributions for the Windows platform were lately made.

Basically Windows is not bound to distributions, therefore we could require modern toolchains (VS 2015, MinGW 5.3 or even 6), BUT:

- VS 2015 cannot be used with Qt 5.5 (Qt 5.6 only)
- The MinGW build (master) is broken on any version above 4.8

-> therefore the choices on Windows are currently simply and only: MinGW/GCC 4.8.x and/or VS 2013

Cmake is not an issue on Windows, the latest version can be installed and runs on every supported OS version (currently 3.4.x are already required). The question is purely what cmake is used for ;)

A way towards better c++14 support on Windows would be to fix the build for higher gcc-versions. But it is nobody in sight who is able AND willing to do that, and: VS seems by far the more promising platform if the goal is to attract new Windows developers. Both Lucas and Luis are VS based developers. But as said before: VS 2015 can only be used with Qt 5.6 (and even VS 2015 has partial c++14 support only).

Let's ignore that Qt5.6 support in SC only exists as sketch, let's just look at the Linux situation instead: it'll likely take 2 years until Debian stable (and RPi) reach Qt5.6. This means both C++14 and Qt5.6 should be avoided for a substantial period.

I am fine with any community vote on supernova. Just informational: supernova can't be built with VS so far. For supernova only I think (but am not sure) MinGW 4.9 is fine.

I would also like to vote for including RPi among supported environments. Supported in the sense that commits to master should not break the build on RPi.

Finally, the Travis build system should be setup to reproduce exactly the specifications decided upon here. Setting up a Raspbian build machine on Travis is probably possible, though not trivial. Windows is not possible yet, but I have a Jenkins build server close to useable and am willing to dedicate it to SC builds if the community decides to make Windows support compulsory.

Locking out Windows (think students, 3rd world), making the Linux build more complicated than necessary (think musicians) and ignoring ARM/RPi (think the amazing diy community growing on Raspbian), cut out important areas where SC is/could be used, and where prospective new developers could be recruited. That, IMHO, is the most important goal the SC community should set itself: recruit new members.

Un abrazo, compañero ;)

**Comment by crucialfelix** [comment]
I wish we knew how many people compile their own versions and why they do it. Since we have regular updates coming out I am guessing we no longer have people forced to compile their own because they need new fixes/features.

Most people who want to compile supercollider should be able to update their cmake to 2014 (3.1), no ? Good developers (which we always want to attract) like up to date toolchains. eg. c++14

Any other thoughts out there ?

**Comment by brianlheim** [comment]
(Note that #2704, #2473 may relate to this discussion)

**Comment by brianlheim** [comment]
AFAIK, what is documented in the READMEs as of #3762 is very close to what we require. CMake req'ment is at 3.5, and the compiler versions are gcc 4.9 (?)/AppleClang from Xcode 7.3/VS 2015. I am able to build supernova in VS 2017 in a local branch which I can submit sometime soon. No idea if it builds in 2015.

I think a good timeframe within which we ought to _require_ backwards support is about 3 years. That's enough for at least 2 major versions of every compiler. On Windows I would personally be OK with just saying VS 2017; apparently even some of the MS devs have said that 2015 ought to be skipped over.

That would mean that C++14 is also fair game now. There's not a whole lot that we gain there (aside from more constexpr, auto deduction, and make_unique <3), but I don't see why not. It would give us access to some newer Boost libraries, which might come in handy.

In general if we can do longer than 3 years, that's great, but I think 3 years is reasonable and not so far away from what we've been doing now.

**Comment by brianlheim** [comment]
this has been solved by https://github.com/supercollider/rfcs/pull/1 and by documentation
