### ISSUE TITLE
Windows / readline / MSVC

### ISSUE THREAD

**Issue by llloret** [supercollider/supercollider#2171]
As part of the effort of bringing the Windows version on par to Linux and Mac, I have been having a look at the readline stuff for MSVC.

I have seen that there is a library called linenoise-ng, that we could use for this. I have been doing some initial testing and it looks promising. The only potential problem is that it does not have a mode to give it chars as they come (like the `rl_callback_read_char`). It has a similar interface to the vanilla `readline()`.

As I said I have been doing some testing, and it works fine. I have changed the original code:

```
mStdIn.async_wait( [&] (const boost::system::error_code & error) {
        if(error)
            onInputRead(error, 0);
        else {
            DWORD bytes_transferred;

            ::ReadFile(GetStdHandle(STD_INPUT_HANDLE),
                       inputBuffer.data(),
                       inputBuffer.size(),
                       &bytes_transferred,
                       nullptr);
            onInputRead(error, bytes_transferred);
        }
    });
```

to:

```
char* result = linenoise("sc3>");
    if (result){
        strncpy(inputBuffer.data(), result, inputBuffer.size());
        inputBuffer[strlen(result)] = kInterpretPrintCmdLine;
        inputBuffer[strlen(result) + 1] = 0;
        DWORD bytes_transferred = strlen(result) + 1;
        onInputRead(boost::system::error_code(), bytes_transferred);
    }
```

And everything seems to work fine.

Now I have a question: what is the reason to have readline work in async mode? Since it is running in its separate thread, couldn't we just use the direct `readline()` function call? I am probably missing something here...

If this is possible, we could probably take this further and have a common version of readline-like functionality using the linenoise-ng library?

Any thoughts? If people are interested I can publish my branch or do a PR.

@timblechmann, I see you were involved in this part of the code? Any insights?

**Comment by llloret** [comment]
Well, to be more exact: The idea would be to keep the current code as is for non-readline mode, and put the new code for readline mode.

And do something similar with the non-Windows stuff, using the `readline()` call in readline mode, and the async in non-readline mode.

**Comment by llloret** [comment]
Ok, I see that my approach is having some issues when the bind keys are taken into account... I will continue working on this, and see if I get somewhere that is worth sharing.

**Comment by llloret** [comment]
Hi, so we have something that works under Windows (MSVC and mingw), MacOs and Linux.

Now it is a matter of deciding how to proceed: should we use linenoise for Windows only, and continue using readline for the rest of the architectures, or should we ditch readline in favour of linenoise?

From what I can see the features are very similar to readline but it is missing some regarding vim and emacs key bindings.

It has history, and unicode support, in case we need that in the future.

@danstowell, seems like you might want to have a say in this, I would really like to have your input...

It would be great if we could include support for this for the 3.8 release.

**Comment by danstowell** [comment]
Thanks for the initiative and the proposal. I'm not in a position to do any actual testing (sorry) but my opinion, for what it's worth: I think the [linenoise-ng project](https://github.com/arangodb/linenoise-ng) is not very widely used, at least that's what a web search suggests to me. (It isn't yet packaged for ubuntu or debian, for example.) We don't really know how good it is, so I don't see any strong argument to go "all-in" with it yet. I'd say, if the windows crew are happy with it, then go with it, and at some future point once we know the windowsers love it we can consider harmonising on it for other OSes.

**Comment by timblechmann** [comment]
@llloret people complained to me not to care about the community, so i stopped caring about the community and won't give you a full review.

though from an architectural perspective, i'd say: if any linenoise based solution works in a cross-platform manner, go for it and ditch readline, which is too unix-centric. https://github.com/yhirose/cpp-linenoise also looks nice, especially it is header-only, which simplifies the build process.

**Comment by llloret** [comment]
Hi, @danstowell, thanks for the feedback. Line noise-ng is not very well known, but it is a close fork of linenoise, which is in use in some big projects, adding support for Windows.

@timblechmann, thanks for the tip. I will explore that too.

**Comment by llloret** [comment]
@danstowell, perhaps we could create a test version for Linux, and people can take it for a spin and see if they find issues?

**Comment by danstowell** [comment]
Yes, of course you could, but in practice it wouldn't get any proper testing if it wasn't in a release! But I've no objections to you making a test version, to see how it goes...

**Comment by bagong** [comment]
@danstowell , that would have to be a debian package, right? Is there a reasonably simple way to create one?

I'd love to know which features sc-command-line mode should offer to be considered satisfactory. Linenoise doesn't offer everything readline does, but we get history and line-editing stuff like ctrl-a/e/w/f/b... Is the advanced readline stuff, like emulation of emacs-/vim-mode, use of .inputrc and the like ever used for sc? If a reasonably clear line could be drawn between what is necessary and what not, we could try to verify if it works on different platforms. That would save Luis some work...

I doubt that we will ever have any feedback how well command-line works on Windows. I think most people either never notice it, or take it for granted....

**Comment by danstowell** [comment]
@bagong I just mean a standard SC release. a separate .deb would be OTT. I just mean:

The question one would need to answer is, "which readline-ish features are essential to SC folk?" and I don't think we'd really get an answer to that just by a handful of devs compiling a fork and verifying that basic line-editing works.

**Comment by bagong** [comment]
Sorry, I still don't understand. You mean use linenoise in 3.8 and then be ready to return to readline if people find it's missing things? Sounds good to me, but you initially sounded more sceptical?

**Comment by crucialfelix** [comment]
3.8 is currently set for July 1st-ish. So changing this for that release is too late I think.

Using it for the Windows build might be fine - good way to test it out. just my 2c

I don't know how many people try to REPL sc from the terminal. Nearly everybody is using ide, atom, emacs, vim. But maybe more would if there was a usable interface. Multi-line support sounds essential.

**Comment by danstowell** [comment]
@bagong it's what I _meant_ but it's not what I was _suggesting_. I was simply saying "feel free to make a test version, but don't assume that this means it will have been tested"

**Comment by danstowell** [comment]
@crucialfelix I use REPL sc on Bela, and I suspect Raspberry Pi folk might have a similar use case. I agree that it's not very common, and we don't need to freak out too much. This is an interesting proposal, and I'd say piloting on windows-only first seems totally sensible.

I don't believe we have multiline in our readline at the moment. Therefore it isn't essential ;)

**Comment by llloret** [comment]
For the sake of the discussion, so that we can talk about something tangible, I have opened pr #2190.

**Comment by vivid-synth** [comment]
Sorry for joining this conversation late -- I do have some concerns about linenoise-ng, now that I've looked at the code a bit. Does the "-ng" version have better Windows support?

I'm all for switching to a simpler codebase than readline, but:

  - This is only 36 commits on top of https://github.com/antirez/linenoise , which seems to have orders of magnitude larger user and tester base (see @danstowell 's concern)
  - It hasn't stayed up-to-date with its parent - https://github.com/antirez/linenoise/commits/master has months of commits. It seems, in fact, to have not pulled changes from linenoise since forking from it
  - The code quality, though I haven't looked at it in much depth, seems not to be great: e.g. they've already introduced a buffer overflow (which they later fixed: see df1cfb41e3) and a couple commits are to fix missing includes and incorrect module names (e402dc2f, 1c4e58f)
  - Many of the changes are just large whitespace changes (e.g. df1cfb41) and file moves (ceba571df)
  - Smaller issue: they've moved/renamed large files and made huge whitespace/formatting changes at the same time as making small edits to them: so it's very difficult to see what in fact they've changed in the git diff (e.g. ceba571df)

If we're introducing code we depend on but don't maintain/review, I'd much rather have something that's got ample resources and is well-tested.

**Comment by llloret** [comment]
Hi, thanks for your input,

from I saw when I put this in, the original linenoise didn't have Windows
support at all. That's why I went for the linenoise-ng. If that has
changed, I agree that linenoise is a better alternative.

This is a valid matter for discussion, and I can see we have a number of
options:
1. Do not use linenoise-ng at all -> No readline-like support on Windows
2. Use linenoise-ng for Windows and readline on Mac and Linux -> More
difficult to maintain but less risky on non-Windows platforms
3. Use linenoise-ng for all platforms -> More risky, as you correctly
state, but easier to maintain

Ideally, I would like to go for 3, since it simplifies our lives (at least
in theory), but it is clearly the most risky. That's why we were asking for
people to give it a try. We might find that for SC's purpose, it works fine.

What I am aiming for is to have as few platform differences as we can, to
avoid having platforms "breaking" in the future. It has been quite some
work to try to get the Windows port back in shape...
Luis

**Comment by vivid-synth** [comment]
Hi @llloret -- I don't have a machine to test on but I agree, it would be great to find out if linenoise works on Windows.

A 4th alternative to the 3 you mention is a combination of 2 and 3: maybe there's less maintenance overhead if we use linenoise on Linux/Mac and linenoise-ng on Windows? Looking at your pull request I think it's plausible they're interchangeable.

**Comment by llloret** [comment]
I tested it on Windows, and it worked well for me (history, bindings to move around, ...). But I am not a sclang command line power user, so it's not too relevant.

Regarding option 4, I like it, but I had to make an addition into linenoise-ng to support key-bindings, that I think it would also need to be added to vanilla linenoise.  From what I saw, linenoise does not have a facility to capture custom key-bindings (i.e CTRL-T, CTRL-X, etc).

**Comment by vivid-synth** [comment]
Another option is to add windows support to linenoise itself -- the changes "-ng" have made seem not to be huge: maybe we can use their work.

**Comment by llloret** [comment]
Yes, that is worth considering too. It's probably worth asking the linenoise guys if they would be willing to accept a PR with that support.

It's worth noting that they also added UTF-8 support, so perhaps it is not so straightforward as adding the Windows stuff in.

Then "someone" can have a look at creating a PR for that... which from what you describe can be a quite "interesting" task.

I like the idea, but it will take quite some time, that we probably do not have at the moment.

**Comment by vivid-synth** [comment]
I'd personally much rather have a more stable codebase than gain UTF-8 support. We can add UTF-8 later if that ends up being something we want.

**Comment by llloret** [comment]
Agreed, what I mean is that I am not sure how easy it would be to separate the UTF-8 stuff from the Windows stuff. And then how to see the current differences to create a PR.

**Comment by vivid-synth** [comment]
Microsoft seems to have created a port of linenoise for Windows (as part of their Redis port):

https://github.com/MSOpenTech/redis/tree/3.2/deps/linenoise

Depending on the version you use,it's also behind linenoise master but the code seems higher-quality and more thorough.

**Comment by llloret** [comment]
Worth having a look at that ms thing

**Comment by vivid-synth** [comment]
@llloret @bagong any update on your thoughts re: getting readline working for Windows+Visual Studio for 3.9? I see there's still some work on supercollider/linenoise-ng. I did some more looking around tonight and I still have some major concerns about its inclusion, though:

  - First and foremost, how are you able to assess what's changed from the linenoise project? There were many commits that changed files at the same time as moving them: I can't tell at all from a simple diff what's changed
    - Specifically, linenoise is a 20,000-line project: the -ng fork has ~5,500 lines of insertions and deletions https://github.com/antirez/linenoise/compare/master...arangodb:master 
      - This commit alone https://github.com/arangodb/linenoise-ng/commit/06521dee4598a1787bb7e493f6ed7c9f3460bf05 (which features a pretty rough critique at the end) is >5,000 lines of changes
  - It hasn't been updated for almost a year (although its upstream has), which makes me concerned about its support in the future
  - There have been a few bugs introduced already (https://github.com/arangodb/linenoise-ng/commit/de4b562de4ed3c1d7d407282ac3286407e7fcc03 , https://github.com/arangodb/linenoise-ng/commit/df1cfb41e3de9d2e716016d0571338ceed62290f , https://github.com/arangodb/linenoise-ng/commit/e402dc2f , https://github.com/arangodb/linenoise-ng/commit/1c4e58f ). If there are e.g. memory bounds bugs, this could actually glitch or crash other parts of the running system

Let's find a solution that makes us all happy -- I would love to get Windows+Visual Studio to be a fully supported platform. :smiley: 

A few other options:
  - @timblechmann 's suggestion of the headers-only https://github.com/yhirose/cpp-linenoise (which also appears relatively untested, but smaller)
  - Microsoft's fork (https://github.com/MSOpenTech/redis/tree/3.2/deps/linenoise) which also may be a larger change but, ya know, it's MS-supported
  - **My preference:** Find what Visual Studio actually needs to work with linenoise and get it fixed upstream (or fork it ourselves)

**Comment by bagong** [comment]
Yes, many thoughts, @vivid-synth 😃

The PR is ready to be tested now, and of course for review, preferably the actual code (Of which the linenoise-submodule has 4507 lines including licenses and comments. Not sure where you got the 20.000 from, @vivid-synth , maybe you misunderstood a forum contribution referring to readline?). I may mention that this PR has been tested far more already than most others, and not only by me, but by people who actually use the command line. Of course "testing" can mean a lot, and there is never enough of it. 

Linenoise-ng has now been turned into a build option that is used by default on Windows (can be switched off with a build option), and can be enabled at build-time to replace readline with the switch SC_LINENOISE ON/OFF on the other platforms. Please give this a whirl, it means a lot to some, to have command-line functionality on Windows too, and it costs the ones that don't use it close to nothing. As to the - undeniably important - trust factor: it has been prepared by @llloret , who has rightfully earned a reputation for quality work in areas not many SC contributors are competent in, or care about. The fact that SCs Windows version is not far anymore from being an equal citizen among SC versions is largely his merit. And we are using stuff Luis has contributed in core spots of SC every day, without even noticing it.

Your arguments:

- 4.500, not 20.000 lines
- the diff you complain about is how diffs look if you replace one file with another. The comment is a troll's polemic rejection, without an argument other than distaste.
- not being updated might mean neglected or without problems. The argument in itself means nothing. What we need is testing and if we are really good, code review (not so much forum review).
- you know about the bugs because they are fixed. So again not a strong argument
- the alternatives:
    - microsoft linenoise fork: the ms-factor is a plus and a minus at the same time. Plus because likely good quality control, minus because likely less care for cross-platform concerns. In my understanding this linenoise depends on redis code and thus would need rework.
   - "fixing" linenoise upstream: I get the attractivity of this approach as the ideal of open-source collaboration, and this is not the only place where you are suggesting it. In practical terms this is usually somewhere between difficult and impossible. Dozens if not 100s of people have requested Windows support for stock linenoise. Apparently it's not a priority for them.
    - yhirose's header only lib. That one looks attractive from the outside. The choice would have to be substantiated though. And I only see a necessity to do additional work (or repeat all over again) if *real* arguments were made against linenoise-ng. I welcome those and I am sure Luis does so too.

I am a bit emotional about your rejection because you do not seem to see the kind of work done before such a contribution is made. I think Luis deserves better. Creating concern without much substance scares off testers, frustrates developers, and likely makes them regret having spent time over code rather than with their kids.

**Comment by llloret** [comment]
A big coincidence? Today I have been reminded by the linenoise-ng guys to provide a License Agreement to be able to put my contributions into linenoise-ng... :).

Which means that there will be some recent commits in there ;).

Seriously, I still think that the best measure is real testing within SC. If it shows issues, and is not good, I'll be more than happy to look at another alternative, time permitting. If it works for our use case, I think we should accept it.

**Comment by vivid-synth** [comment]
- The 20,000-line number may be wrong. I was taking it from the header "Can a line editing library be 20k lines of code?" near the top of the Readme. My point, though, was that the diff is a huge percentage of the size of the whole file. If it's 5,500 lines of diff, and only 4,500 lines of code, to me that's *more so*.
  - My issue with the large diffs is not an aesthetic one: my concern is that files have moved at the same time as they were changed. I'm not able to provide significant comments, pro or con, about the library's quality, because *I still don't even know how linenoise-ng differs from linenoise*.

To your emotions point: I certainly don't want to sound like I don't appreciate @llloret 's work. I do! It would be great to get this all to work (and I know this isn't high-profile work). @llloret can you share how you got a diff between linenoise and -ng, or otherwise share how you evaluated the project's quality?

**Comment by xinaesthete** [comment]
I wonder to what extent this issue is still on anyone's radar.

From my point of view, I do quite a bit of piping code to sclang from Node, for which I'm not at all concerned about line-editing facilities etc, but the current status means that recent versions of sclang are unusable on Windows (I'm on 3.6.6 currently, maybe I could be slightly more recent than that).

I'm not averse to contributing if it'll help, but not sure I'm best suited in this instance.

**Comment by crucialfelix** [comment]
🥳
