### ISSUE TITLE
Dealing with sc3-plugins

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2185]
Moving the discussion at [sc3-plugins](https://github.com/supercollider/sc3-plugins/issues/89) here. Here are some of the open questions if I understood the discussion correctly:
- Should plugins be a type of quark? If not, how should quarks manage dependencies on plugins?
- Should sc3-plugins be bundled with supercollider?
- What is the process for migrating ugens from sc3-plugins into supercollider?

**Comment by vivid-synth** [comment]
As someone who maintains a non-sclang SC language, I'd much prefer for less-mature plugins to stay in their own repo. As it is, I can create wrappers for UGens in the SC repo and be fairly sure their behavior (and arguments!) will stay relatively stable. Some sc3-plugins, though, are still in flux, and that makes versioning a lot more of a pain.

I'd love to see a process for migrating plugins to the sc repo when they're mature, though! Some of these have been around and stable forever at this point.

**Comment by snappizz** [comment]
As someone who is trying to encourage a greater wealth of user-contributed plugins, I'd like to see some kind of system. Something as simple as a wiki page with links to different plugin repositories would be a good start.

**Comment by snappizz** [comment]
Also, everyone is free to use this thread to nominate some of their most beloved plugins.

**Comment by joslloand** [comment]
Actually, I'd like to see **_all UGens_** as plug-ins, rather than just push in certain "mature" sc3-plugins. IMV this would make SuperCollider feel like a much more modern programming environment, and lead to more concise workflows.

I'm imaging something like using [Modules](https://docs.python.org/3/tutorial/modules.html) and/or [Packages](https://docs.python.org/3/tutorial/modules.html#packages) in [Python](https://www.python.org/). UGens would be collected into small, useful and related sets. To start with, I'd imagine a core of _classic Music V_ UGens, broken down into related groups. E.g.:

- Music V Filters
- Music V Oscillators
- Music V Envelopes
- Music V [Etc.]

The thought is these collections would be easy to navigate, easy to document and easy to maintain. Admittedly, such an approach may actually be something to think about for SC 4.0. (Maybe some of this should be moved there.)

My feeling is that the current set of UGens shipped with SC 3.x is not always consistent and is drifting towards significant UGen bloat (as experienced in [some other platforms](http://csound.github.io/docs/manual/PartReference.html)). It would be useful to think about ways to both facilitate users needs for additional UGens (e.g., [ATK](http://www.ambisonictoolkit.net/)) and have the power and functionality of our current offering.

The risk is that without developing a better management strategy we end up with a _mega-list_ of UGens, but with little sense of curation, or suitable use. I'm feeling the suggestion to migrate selected sc3-plugins leads us in this direction.

Some sort of package management system (with summaries) _could_ facilitate a more convenient and navigable way through the great UGen offerings available.

--
Yeah, and as you'd imagine, we're facing some development and distribution issues with the [ATK](http://www.ambisonictoolkit.net/) that could possibly be resolved or moderated by such a strategy.

@scazan may want to add some more comment here...

**Comment by vivid-synth** [comment]
Actually, since this is a user- (and not dev-)oriented conversation, maybe we should discuss on the sc-users list instead of here?

**Comment by gusano** [comment]
> Should plugins be a type of quark? If not, how should quarks manage dependencies on plugins?

I'd vote for *no* as plugins are kinda (or should be) more stable and "sc official add-ons(TM)" ;) whereas quarks can be submitted by anyone and therefore potentially unmaintained or simply not working

> Should sc3-plugins be bundled with supercollider?

I'd also vote for *no* as I find it nice to have a barebone sc version installable

My 0.02$..

**Comment by snappizz** [comment]
By "should plugins be a type of quark" I mean server plugins in general, not just the stuff in sc3-plugins. For example, Victor's [DWGReverb](https://github.com/sonoro1234/DWGReverb) or [this pink noise ugen](https://github.com/snappizz/StenzelPink).

**Comment by vivid-synth** [comment]
@crucialfelix I think there's a use to having an "experimental" repo (sc3-plugins) where people can submit UGens that are useful to them but not yet fully standardized or stable.

I think the problem we all agree we have is that people try to play some patch and go "Oh crap, that UGen's in sc3-plugins, huh? Apparently I didn't install those... Ok, let me go find them," even for a UGen we all know and love. IMO having a migration strategy for mature UGens into the sc repo is nicer than just providing the sc3-plugins with releases because the sc3-plugins can then be under active development. Once they're in Supercollider with a capital 'S' there's an expectation of stability.

**Comment by joslloand** [comment]
I'd just like to add that the [ATK](http://www.ambisonictoolkit.net/) team is looking at developing a strategy that could be used to separate the various sc3-plugins packages into smaller parcels. Several advantages would result, including facilitating new contributions.

We're just taking baby steps at the moment, so don't actually have anything to show for comment as of yet. (Yeah... _vapour-ware_)

**Comment by vivid-synth** [comment]
@joslloand the big thing I'd be concerned about is getting into territory where we have to start managing version constraints and dependencies -- if we get to a place where we're basically running a small-scale npm it's going to be a big headache.

I agree that making new contributions easier is a good goal. Thinking out loud here, but what if we had a scheme with "tiers" of repos: either split by categories or not. So you'd have e.g.

supercollider (most stable)
sc3-plugins-stable
sc3-plugins-experimental

or, to your earlier suggestion:

supercollider
sc3-plugins-filters-stable
sc3-plugins-filters-experimental
sc3-plugins-ATK-stable
sc3-plugins-ATK-experimental

...and new contributers would be free to mess around extensively within the "-unstable" repo(s).

The most important thing, I think, is that once they're in "-stable", they *do not change if at all possible* -- the last thing any of us want to see, I think, is a dependency header on sc source files saying which packages our code works with (similar to how python, ruby, node, etc. packages work)

```
/*
Dependencies:
sinOsc >= 0.3.7 && < 0.9.4
lfSaw > (0.18.4.1 && <= 0.18.4.5) || (0.19.4.1 && <= 0.19.4.5)
*/
play { SinOsc.ar + LFSaw.ar }
```

**Comment by vivid-synth** [comment]
The other question @joslloand raises is, independent of repo organization, how do we organize ugens and prevent bloat/big-pile-o-ugens?

Something like http://doc.sccode.org/Browse.html#UGens is ok to navigate but we can probably do better.

**Comment by telephon** [comment]
Once the plugins are installed and can be loaded by the server, their class can be managed from the Quark gui, and different projects can depend on them selectively.

Which is not saying that the quarks themselves become increasingly hard to handle. But right now it is still kind of ok. The only thing that is a bit annoying is that when a quark installs its dependencies you don't know which they were and you can't switch off the bunch. But that is a solvable problem.

**Comment by snappizz** [comment]
here's a new idea: every ugen should have a fancy 3D spaceship GUI and cost $200

**Comment by snappizz** [comment]
Closing because this was more of an open discussion than an issue (we're being a little more stingy these days about what qualifies as an issue because 400+ is way too much).
