### ISSUE TITLE
[ide] server marked as unresponsive if it fails to start or dies

### ISSUE THREAD

**Issue by timblechmann** [supercollider/supercollider#2241]
if the server fails to start (e.g. if no jack server is running), the audio status box remains yellow, indicating an "unresponsive" server. the same happens if the server is killed.

**Comment by snappizz** [comment]
Same thing has been happening here.

**Comment by telephon** [comment]
Is there anything that would signal sclang about a failed start or crash? Currently there seems to be no way for it to know what the status of the server really is.

**Comment by jamshark70** [comment]
Tested 3.7, not an issue. So I guess it's the server status refactoring.

I think (somebody correct me if I'm missing something) that the only sure thing is polling a server at a specific address and port with `/status` and receiving a valid `/status.reply` back.

If you send `/status` and receive no reply, this doesn't distinguish between a few cases:

- The server is momentarily busy (e.g. with a large number of async commands) but it will start replying again very soon;
- Or, the server process still exists but it's hanging and will never recover;
- Or, the server process crashed (or, another client told the server to quit).

The first case shouldn't be assumed to mean the server is down, which is why there's `pingsBeforeConsideredDead`.

The second case would be nice to show. Server has a `pid` variable. If we reach the `pingsBeforeConsideredDead` limit, in Unixy systems, it's easy to check whether the pid still exists. I'm not sure about Windows. For this, we have to be sure aServer.pid is trustworthy. Otherwise, you could have multiple server processes and not know which pid is for which port.

Certainly the third case should clear the status bar and GUIs.

**Comment by telephon** [comment]
Yes, this is correct.

Before the server status refactoring, the IDE claimed the server dead when it wasn't responding for a while, so that when you set the computer to sleep for a while, the shared memory interface was gone.

So it has shifted the problem (arguably to a better place), but needs more work.

**Comment by telephon** [comment]
But also note that the refactored code isn't yet merged completely.

**Comment by jamshark70** [comment]
Oh, right. That's a tough one. The language doesn't know if the server wasn't responding for the last hour because it hung or the computer was asleep... but we need to distinguish those cases.

Maybe there's a hook that the OS tries to call in every process when it's going to sleep or waking up?

I don't see how we can handle all the cases if sclang doesn't know if it's naptime or not.

**Comment by telephon** [comment]
Yes, also for cpu-hungry tasks you don't know if it has died or is just not responding. The server stops responding while something is done in the non-realtime thread –  I always wondered how to change this. You probably need another separate thread that does the message handling?

**Comment by timblechmann** [comment]
the correct way to solve this would be to write a sclang primitive, which properly owns the server process instead of launching and detaching it.

**Comment by snappizz** [comment]
@telephon After #2458, how far are we on this?

**Comment by telephon** [comment]
fixed
