### ISSUE TITLE
Quarks.installQuark -- progress indication

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2313]
Some quarks (like Dirt-Samples) are pretty huge and take a long time to download. A progress indicator in the post window would be really helpful, such as printing the % completed every second.

**Comment by crucialfelix** [comment]
How do you get the % ? It's a command line call. You would have to parse the output of that.

```
(AJAXSELECTS)(py2)Downloads ❯ git clone https://github.com/supercollider/supercollider
Cloning into 'supercollider'...
remote: Counting objects: 202110, done.
remote: Compressing objects: 100% (91/91), done.
Receiving objects:  19% (38602/202110), 24.68 MiB | 3.67 MiB/s
```

what, read the terminal buffer ? fly a drone around the laptop and try to take snapshots of the screen, animate those into discrete frames and predict ETA based on velocity of change in the percentage readings ? ;)

Let's keep in mind that Quarks is a very simple package manager. It's not npm, it's not industrial strength, it shouldn't be.

**Comment by snappizz** [comment]
I still think it's a feature worth having. It's not fun to wait 20 minutes for a 350MB quark to download while my interpreter is effectively frozen and telling me nothing about its status.

I'm googling around and it seems that most solutions involve polling the file size of the downloaded object. I was hoping there was some way to get a porcelain progress report, but `git clone` doesn't support that afaict.

**Comment by crucialfelix** [comment]
I thought I did it as an async action. Can you not cancel with command . ?

**Comment by snappizz** [comment]
I remember I wasn't able to execute anything else while it was downloading.

**Comment by gusano** [comment]
> it seems that most solutions involve polling the file size of the downloaded object

@snappizz I don't think this would work properly and it might add a lot of overhead.

I vote for going asynchronous for `git clone` and forget about progress percentage.

**Comment by snappizz** [comment]
> I don't think this would work properly and it might add a lot of overhead.

Only one way to find out.

**Comment by jamshark70** [comment]
> I thought I did it as an async action.

No, just checked, it's `Pipe.callSync`.

**Comment by crucialfelix** [comment]
I think I thought that I should do it async but didn't have the time to finish that. It needs to set the ui to downloading, then can a cancellable action that calls the async pipe. The cancellable action is already implemented and used by quarks guide

**Comment by crucialfelix** [comment]
Right now all calls to Git do block the app thread because it uses Pipe.callSync

For it to use Pipe.call (which is async) then either:

1. All Git methods need to have callbacks (ok, error) supplied to it (ie the Pyramid of Doom)
2. SuperCollider needs a Promise class and then all Git methods would return Promises. Those are chainable, and you can add a single error handler to the end of the chain.

Option 1 would make a disastrous mess out of the gui code and is to be avoided.

I considered Option 2 at the time but my goal was to write a package manager and a gui and to keep it simple.

It makes it simpler than using callbacks:

```supercollider
git = Git(localPath);
git.clone(url)
  .then({ git.fetch() })
  .then({
    changed = nil;
    data=nil;
  });
```

Another option is to do 2. and then also add .await which would make writing code a bit easier. You would have to be in a Routine:

```supercollider
{ 
  git = Git(localPath);
  // thread resumes when the promise resolves
  git.clone(url).await;
  // thread resumes when the promise resolves
  git.fetch().await;
  changed = true;
  data = nil;
  // etc
}.fork;
```

which is a bit cleaner to read.

aPromise.await is supposed to pause the thread until the Promise resolves. if it errors then it throws the error.

object.await just returns the object itself.

http://rossboucher.com/await/#/

**Comment by telephon** [comment]
@crucialfelix Do you have an sclang implementation of promises at hand? There are a lot of other cases where they would help, I suppose.

**Comment by crucialfelix** [comment]
Nope. I would recommend a very simple and [A+ compliant](https://promisesaplus.com/) implementation. Don't reinvent the wheel, no funny business, no new method names.

googling for it:

<img width="638" alt="screen shot 2016-09-01 at 13 45 25" src="https://cloud.githubusercontent.com/assets/218738/18166258/6429129a-704a-11e6-9690-57ea2c9d26c2.png">

So I guess we will need to sacrifice somebody :0

**Comment by snappizz** [comment]
stale issue, no resolution.
