### ISSUE TITLE
server plugins: Some UGens fail to calculate one sample of output at Ctor

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2333]
A ugen's constructor function should do three things:
1. initialize the state variable of the ugen and allocate memory
2. set the ugen's mCalcFunc
3. calculate one sample of output

Some ugens fail to do step 3, so downstream ugens that rely on Ctor-stage inputs end up accessing garbage memory from an uninitialized wirebuf. The resulting bugs can be incredibly nasty and difficult to reproduce: http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Gendy-instability-td7627785.html Many such bugs have been around since the beginning of SC3.

The fix is pretty easy, but there's a lot of ground to cover. We have to review the constructor function of every ugen and check for a line like one of the following:

```
// most common:
FBSineN_next(unit, 1);
ClearUnitOutputs(unit, 1);
OUT0(0) = something;
ZOUT0(0) = something;

// less common:
(unit->mCalcFunc)(unit, 1);
```

If there is no such line, the ugen might not initialize correctly. (Some ugens like `Out` and `LocalOut` don't have any wirebuf outputs, so the absence of the line might be alright.) The least intrusive fix is `ClearUnitOutputs(unit, 1)`, but depending on the ugen there may be better options.

See also #782.

**Comment by snappizz** [comment]
Checklist:

- [ ] BeatTrack2.cpp
- [ ] BeatTrack.cpp
- [ ] BinaryOpUGens.cpp
- [ ] ChaosUGens.cpp
- [ ] Convolution.cpp
- [ ] DelayUGens.cpp
- [ ] DemandUGens.cpp
- [ ] DiskIO_UGens.cpp
- [ ] DynNoiseUGens.cpp
- [ ] FeatureDetection.cpp
- [ ] FFT2InterfaceTable.cpp
- [ ] FFTInterfaceTable.cpp
- [ ] FFT_UGens.cpp
- [ ] FilterUGens.cpp
- [ ] GendynUGens.cpp
- [ ] GrainUGens.cpp
- [ ] IOUGens.cpp
- [ ] KeyTrack.cpp
- [ ] LFUGens.cpp
- [ ] Loudness.cpp
- [ ] MFCC.cpp
- [ ] ML.cpp
- [ ] ML_SpecStats.cpp
- [ ] MulAddUGens.cpp
- [ ] NoiseUGens.cpp
- [ ] Onsets.cpp
- [ ] OscUGens.cpp
- [ ] PanUGens.cpp
- [ ] PartitionedConvolution.cpp
- [ ] PhysicalModelingUGens.cpp
- [ ] PV_ThirdParty.cpp
- [ ] PV_UGens.cpp
- [ ] ReverbUGens.cpp
- [ ] TestUGens.cpp
- [ ] TriggerUGens.cpp
- [ ] UIUGens.cpp
- [ ] UnaryOpUGens.cpp
- [ ] UnpackFFTUGens.cpp

**Comment by miguel-negrao** [comment]
Would it be possible, and make sense, to make a separate executable for testing, which calls every ctor function with an appropriately initialized struct Unit and then checks if mOutBuf[0][0] has the right value and doesn't segfault ?

**Comment by vivid-synth** [comment]
@miguel-negrao that would be an awesome tool to have

**Comment by muellmusik** [comment]
You guys are awesome for stepping up.

Regarding the 'specification', make sure this goes into the doc to help others avoid the mistake.

Am I correct in saying that in many cases ```ClearUnitOutputs(unit, 1)``` would be the most appropriate? (i.e. we don't want to advance state by one sample so just clear).

**Comment by joshpar** [comment]
I was thinking the same thing when I started to look at some of these. The function calculating the first sample - when is that sample written out? Ctors calculate that one sample for the end of a sample block? Or is the Ctor called, then next for the rest of the control block? I'll dig a little deeper into that - it's something I don't think I know. Anyone else?

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by snappizz** [comment]
@muellmusik It depends on the UGen. For time-invariant filters, you want `Foo_next(unit, 1)`. For synthesis, you either want to duplicate the first proper sample of output, or use `ClearUnitOutputs`. I'm not sure which is a better choice.

**Comment by snappizz** [comment]
@joshpar The meaning of the Ctor sample is confusing and it took me a while to figure it out. The basic idea is that it's a sample that comes before everything else. Normally a digital signal `x[t]` is defined for all `t >= 0`, but this Ctor sample functions as all negative-time samples: `x[-1] = x[-2] = x[-3] = ...`. It is discarded when the signal reaches the Out stage, but you can see it using the Delay1 ugen.

The question is, what is the point of this sample? From a DSP perspective, I think it's some way to characterize what the ugen looks like coming from negative infinite time, so you can avoid the step response of a filter. For example, consider the signal `x[t] = t < 0 ? 0 : 1`, which is equivalent to a signal that outputs constant 1 but has a Ctor sample of 0. If you run this signal through a first difference filter (HPZ) you'll get a transient immediately after time 0. If the Ctor sample was 1 instead, a first difference filter would constantly output 0.

I hope these scatterbrained thoughts make some sense. Please take it with a grain of salt since I still haven't gotten a definite answer from an experienced SC dev.

**Comment by joshpar** [comment]
Right - I know it has a ‘prime the pump” type of functionality - but I am not sure if that output sample is actually ever sent to an output. I’ll dig in more after work today.

**Comment by telephon** [comment]
We should also check whether for thos UGens that have a trigger or gate input, the prev-value should be initialized to zero. Otherwise we don't get a trigger (arguably, as expected) when starting with a constant value `> 0`.

**Comment by jamshark70** [comment]
> We should also check whether for those UGens that have a trigger or gate input, the prev-value should be initialized to zero. Otherwise we don't get a trigger (arguably, as expected) when starting with a constant value > 0.

Coming a bit late to this party, but, #2343 is a case that demonstrates why it should be the *downstream* unit (one that expects to receive a trigger) that should initialize a trigger *input* to 0, and it should not be the *upstream* unit that initializes its output to 0 (to prepare for a trigger in the first calculation cycle).

From that perspective, I'm going to have to disagree with @snappizz 's comment "The basic idea is that it's a sample that comes before everything else" (which he might have reconsidered after chiming in on #2343).

We have filter-style UGens that need to initialize their state to the actual first input sample, and most emphatically *not* a sample that comes before time 0. For this to work, we have to rely on upstream units initializing to their value at -- *at*, not before -- time 0. We cannot have some units deciding -- as `Impulse` currently does -- to initialize to y(-1) because they expect most of the time to go in a trigger.

If you do have that situation, then there are four cases. (Such an explosion of cases is a good predictor of trouble.)

A. Upstream inits y(0), downstream expects y(0). No problem.

B. Upstream inits y(0), downstream expects y(-1). In this case, the downstream trigger input would not fire in the first calculation cycle.

C. Upstream inits y(-1), downstream expects y(0). Filters, like Lag, don't behave as expected.

D. Upstream inits y(-1), downstream expects y(-1). No problem.

Case B is easy to handle, as Julian pointed out: UGens that expects an input to be used as a trigger may simply ignore ZIN(i) and initialize the trigger state to 0.

Case C is not at all easy to handle. So, I propose getting rid of it and making it illegal for UGens to initialize to any time index earlier than 0.

If we don't cut out the extra cases, then we remain in the present situation where there are certain magical combinations of UGens that simply cannot be made to work, and there's no obvious reason why. At present, I don't see any good reason to keep it this way. That "pre-sample" idea has got to go.

**Comment by snappizz** [comment]
So the proposal is to make the Ctor sample equal to the first sample. Sounds good to me.

**Comment by joshpar** [comment]
OK - so, that means my requests will need another pass on my end.

**Comment by jamshark70** [comment]
There may be some case that I'm overlooking... I'm not sure this is ready for fast and widespread action. I'm certainly open to hearing about cases that contradict my analysis.

What I'm proposing would complicate UGens whose calc functions advance time in some way -- because the Ctor init calculation would have to avoid advancing time. I'm not sure of a good way to do that. I am sure that allowing this init sample to mean different things in different UGens is likely to cause trouble.

**Comment by snappizz** [comment]
My only objections are practical -- it's a very large scale API change, and it can be slightly annoying to implement for some ugens. You've already mentioned the details of the latter issue in #2343:

> We have tended to resist delayed-initialization because you would need either an "if" in the calculation function (performance hit), or switch the calculation function on-the-fly.

**Comment by snappizz** [comment]
But I should point out -- the problem of inconsistent Ctor initialization (the issue we're discussing now) is separate from the problem of *absent* Ctor initialization (the issue described in the OP of this thread). The latter is serious and requires pretty much immediate action. FWIW, I've just been reminded of its urgency because I just got ANOTHER shotgun sound in a piece I'm working on.

**Comment by joshpar** [comment]
Do you know what UGen caused it?

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by snappizz** [comment]
EnvFollow from sc3-plugins, just filed a PR.

**Comment by telephon** [comment]
Just to understand the issue better: there is the external input to a UGen (`IN(0)`) and the internal member variable where values are kept during calculation (and specifically across block boundaries) – `m_prev`, e.g.

I limit myself to the trigger example. A UGen expecting a trigger initializes the member variable `m_prevtrig` in `Ctor` before going into the calculation loop. So in the first cycle the previous input is not some external `IN(-1)` value, but whatever the `Ctor` function has defined as default previous value in `m_prevtrig`. 

The calculation loop will get:
```
prevtrig = m_prevtrig;
curtig = IN(0);
if(curtrig > 0.f && prevtrig <= 0.f) { do it; }
m_prevtrig = curtrig
```

There shouldn't be anything to do for Impulse or the like, no? I may have overlooked something important!

**Comment by jamshark70** [comment]
@snappizz

> My only objections are practical -- it's a very large scale API change, and it can be slightly annoying to implement for some ugens. You've already mentioned the details of the latter issue in #2343:

> > We have tended to resist delayed-initialization because you would need either an "if" in the calculation function (performance hit), or switch the calculation function on-the-fly.

Not exactly... that was an objection to an alternate suggestion (to eliminate pump-priming altogether). What I am proposing would not require any delayed init, so that comment of mine is moot.

The technical objection to my current proposal is: currently, units like Impulse or SinOsc must advance a phase variable during the calc function. But, this proposal is: 1. During Ctor, call `_next_1` to get time 0, and don't advance phase. 2. During subsequent `next` calls, *do* advance phase. That's a bit tricky, and probably why it became allowed to have an inconsistent definition of that init sample. ("Premature optimization is the root of all evil.")

**Comment by jamshark70** [comment]
@telephon that's right. If the trigger *receiver* initializes its `prevtrig` member variable to 0, then there is no longer any need for Impulse to initialize to 0.

**Comment by telephon** [comment]
So then we would need a list of UGens that suffer from bad behavior when they encounter an uninitialized value of some input in `Ctor`? Then we could check if receiver UGens need not rely on such input at all.

**Comment by telephon** [comment]
if that is really the case, then (e.g.) the Ctor of `Delay1` is the thing to be changed. Instead of

```
void Delay1_Ctor(Delay1* unit)
{
	//printf("Delay1_Reset\n");
	SETCALC(Delay1_next);
	unit->m_x1 = ZIN0(0);
	Delay1_next(unit, 1);
}
```

it should be

```
void Delay1_Ctor(Delay1* unit)
{
	//printf("Delay1_Reset\n");
	SETCALC(Delay1_next);
	unit->m_x1 = 0.0;
	Delay1_next(unit, 1);
}
```

So the problem would be reversed and blame on the receiver.

There might be cases, however, where we one can argue that one does need a valid output. If `Gendy1`, e.g. uses `IN0(8)` to check how much memory to allocate, it should get some reasonable value. But perhaps it should check anyhow.

**Comment by telephon** [comment]
As a reply to myself to (1), it doesn't seem so. See:

```
{ Out.ar(64, TDuty.ar(SampleDur.ir, 0, Dseq([1, 0], inf))) }.play(addAction:\addBefore);
p = { a = In.ar(64); [a, Delay1.ar(a)] }.plot(0.0004).plotMode_(\points); // not good
p = { a = In.ar(64); [a, Delay2.ar(a)] }.plot(0.0004).plotMode_(\points); // even worse
```

**Comment by jamshark70** [comment]
> So then we would need a list of UGens that suffer from bad behavior when they encounter an uninitialized value of some input in Ctor? Then we could check if receiver UGens need not rely on such input at all.

I'm not following this. The determining factor is: how does it make sense for the downstream unit to init?

- If it's a trigger input, we want a positive incoming value in the first calculation cycle to fire a trigger. So `prevtrig` should initialize to 0, *no matter what the upstream Ctor did*.

- If it's a filter input (my Lag case), I'm struggling to think of a case where we want the initial state to be different from the state at the beginning of the first calculation cycle. So, the upstream unit should provide the actual first sample, not a pre-sample.

- Delay1 is a special case... I've never heard of any delay unit anywhere that repeats the input (in sync) until reaching the delay time. I'm frankly baffled that Delay1 outputs `x(0), x(0), x(1), x(2)...` instead of `0.0, x(0), x(1), x(2)...`. I agree about `unit->m_x1 = 0.0;` but this specific case doesn't have any bearing on UGens outside of the delay category.

>    when a new synth reads from an audio bus that has some other synth that is already running, it may not pick up the correct previous value. The question is if it currently does this.

Hm, you're right, if the sequence of events for a calculation cycle is: 1. Process any s_new messages scheduled for this control block (including Ctors). 2. Iterate over synths and their UGens. In that case, the "eventual" value for that calculation cycle would not be available to the Ctor.

I don't have a solution for that, except to push initialization into the calculation functions (which involves extra branching and would cost a bit of performance).

>    There might be cases, where we one can argue that one does need a valid output. If Gendy1, e.g. uses IN0(8) to check how much memory to allocate, it should get some reasonable value. But perhaps it should check anyhow.

My suggestion is that units should always "prime the pump" with a valid number, which would seem to satisfy this requirement, or...?

**Comment by jamshark70** [comment]
Hm, a couple of other thoughts for now:

- Completely agree with @snappizz that the *uninitialized* cases should be fixed ASAP. Probably according to the current standard practice (whether it changes later or not).

- I guess my argument is something of a polemic, responding to questions about the meaning of that init sample (and showing a way in which the current practice seems not ideal). However, the Lag case does have a workaround (an ugly one, but a workaround nonetheless) so... despite my stern words, I would not advocate changing the API across the board if it's done in a hurry without considering a reasonable spectrum of cases. I don't think Josh should redo the work he already did and I don't think we should go with my viewpoint "just because" -- I do think my proposal should be evaluated, and I think my argument is generally sound (though I would like someone to poke holes in it before major code revisions take place!).

**Comment by Sciss** [comment]
On 23/09/16 07:34, jamshark70 wrote:
> I would not advocate changing the API across the board if it's done in a
> hurry without considering a reasonable spectrum of cases

I agree. The first step, apart from fixing missing init, is probably to
document the init behaviour as it is know, so the user can find that
information and possible work-arounds for some common cases (e.g. how to
ensure trigger is fired at initialisation time).

**Comment by muellmusik** [comment]
I'm pretty convinced by @jamshark70's argument that each UGen should be responsible for its own initialisation strategy. A few points:

- Deciding on the basis of what the upstream UGen is would make things crazy complicated.
- It seems to me that for similar reasons that where it matters we should assume that any input from before a UGen existed is 0.0, but UGens *don't have to use 'previous' input* when initing. (So the HPZ case can act sensibly.)
- Switching the calc_func is an established practice and should not be resisted. Therefore it's totally acceptable to have Some_UGen_firstBlock as a calcFunc and then switch. Please don't make maintenance complaints about this approach. Maintenance issues arising will be small and from a performance perspective it's a good route.

My thoughts anyway. Catching up on this in a hurry, so apologies if I missed something!

**Comment by snappizz** [comment]
We're almost done! Nine open PRs in need of review.

**Comment by vivid-synth** [comment]
Closing, as the initialization work is done. Let the what-to-init-to conversation continue on https://github.com/supercollider/supercollider/issues/2343
