### ISSUE TITLE
Many UGens silently default to buffer 0 for an invalid input buffer number

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2368]
An example is in the commonly used `GET_BUF` macro:

https://github.com/supercollider/supercollider/blob/master/include/plugin_interface/SC_Unit.h#L263

Not sure what the best alternative would be. My idea is that it could emit a warning the first time it happens in the Synth, and the ugen could output zeros until a valid buffer number is supplied.

This is a minor problem because most users use Buffer objects (or the equivalent in alt clients) rather than deal directly with buffer numbers. You have to be doing some pretty tricky things before encountering this bug. We have bigger fish to fry with our plugins anyway.

**Comment by Sciss** [comment]
Well, it can be a bug in the client abstractions, so printing a warning is very good in any case.

**Comment by telephon** [comment]
In some case, you may want to modulate the buffer number, then you can accidentally hit the limit. But I agree that this is a smaller fish.

**Comment by danstowell** [comment]
Changed the title because it affects many UGens not few, and there's not an actual "fail" occurring; although undocumented it seems clear from the code that the behaviour was designed in.

I would be happy for the change to be made so that the behaviour is exactly as now (i.e. it falls back to using buffer number 0), except that a warning is posted the first time the UGen receives an invalid buffer number. I disagree with @snappizz's more drastic suggestion that "the UGen could output zeros"
