### ISSUE TITLE
Windows: help pages don't open with non-ASCII character in username/helpdir-path

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2441]
If a username contains a non-ASCII character help pages do not display. The help pain still displays  "Sending help request", and the indexing is processed:

```
*** Welcome to SuperCollider 3.8.0-beta1. *** For help press Ctrl-D.
SCDoc: Indexing help-files...
SCDoc: Indexed 1381 documents in 6.03 seconds
```

But the pane remains empty.

SDoc does contain spaces in usernames (as opposed to Quarks), but not non ASCII characters.

**Comment by snappizz** [comment]
This is top priority for 3.9. Many people are affected.

**Comment by snappizz** [comment]
In [this thread](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/problem-running-SC-3-8-on-Windows-10-td7629711.html), a user reports experiencing the same effect as this bug, but his username contains only letters and numbers.

**Comment by jamshark70** [comment]
SCDoc depends heavily on file primitives. If some of them are erratic based on specific features of file paths, that would explain the observed behavior. I might suggest unit testing them, especially by generating paths with non-ASCII characters. (SC doesn't handle "diäcrítîcals" in string literals, but we've seen cases where they were sort of ok being read from disk or supplied by primitives.)

That calls to mind another question: What are the reported SCDoc paths?

```
[SCDoc.helpSourceDir, SCDoc.helpTargetDir]
```

Alternately, make a "debug mode" for SCDoc (to be enabled in startup.scd) and find out where it's breaking.

Also, does it temporarily avoid the problem if you close the help docklet? The next time you launch the IDE, it should not auto-index the help files (should do it on demand, when opening help). It's very likely that indexing the help later would still fail, but it may be useful to confirm anyway.

**Comment by brianlheim** [comment]
Okay, after spending a few hours today poking around about this, I'm just going to dump all the information I've collected so far.

## Diagnostic info:
- Using Win10 Home Edition, amd64 processor
- Two users: "brianheim" (**control**) and "tést üser" (**test**)
- Instead of installing to `Program Files\SuperCollider 3.8` as default, **I installed to `C:\Program Files\TÔst Usér\SuperColliderJan8`** (I couldn't be bothered to find proper altcodes to name that folder).

## Tests

1. on **test**: ran SC 3.8 installer from main release on test account, no issues
2. ran scide.exe. Same as @bagong, got "Indexed #### documents in ### seconds", but help browser does not load anything.
3. on **control**: ran scide.exe. Seems to be working fine; help browser works.
4. on **control**: executing `[SCDoc.helpSourceDir, SCDoc.helpTargetDir]` returns:

```
[ C:\Program Files\T?st Us?r\SuperColliderJan8\HelpSource,
  C:\Users\brianheim\AppData\Local\SuperCollider\Help ]
```

Where `?` represents the "no-show" glyph in SC.

5. on **test**: the same line returns:
```
[ C:\Program Files\T?st Us?r\SuperColliderJan8\HelpSource,
  C:\Users\t?st ?ser\AppData\Local\SuperCollider\Help ]
```

## Possible directions of inquiry

Everything I've come up with so far seems to suggest this is an issue with C++ [std::fopen](http://en.cppreference.com/w/cpp/io/c/fopen), which is used pretty extensively in the codebase without properly handling Unicode encodings. [This page seems to be helpful](https://msdn.microsoft.com/en-us/library/yeby3zcb.aspx), and in particular [this section](https://msdn.microsoft.com/en-us/library/yeby3zcb.aspx#Anchor_3). Some other useful (or maybe not) resources:

https://msdn.microsoft.com/en-us/library/c426s321.aspx
https://blogs.msdn.microsoft.com/andrewarnottms/2008/02/22/why-you-should-never-use-tchar-in-c-header-files/
http://linuxgazette.net/147/pfeiffer.html

I have no idea if this is an outlandish suggestion, but it seems like on the path to fixing this it might not be that much more difficult to update all of SC for Unicode support.

Anyway, I do have this Windows machine here, so if you want me to run some diagnostics just send me some code/ideas and I'll see what happens. I'm definitely out of my depth here, and I'm just wasting time trying to tackle it at this point.

**Comment by jamshark70** [comment]
So, the control environment is reading help source files from `C:\Program Files\T?st Us?r\SuperColliderJan8\HelpSource` with no problem -- thus, the remaining difference between the environments is the location to which rendered help files are written. In **control**, this path has no non-ascii characters and everything is fine. In **test**, the target location does have non-ascii characters and it breaks.

So it seems to be something about fopen() for writing.

**Comment by brianlheim** [comment]
Could also be SCDoc.sc passing bad strings to the C++ primitives. If someone can give me some suggestions on where to add debugging lines I'd be happy to try that out.

**Comment by snappizz** [comment]
I might be wrong, but it looks like `SCDoc.indexAllDocuments` is succeeding and the problem is in the help viewer.

**Comment by brianlheim** [comment]
@snappizz I don't know where your comment went (it's in my newsfeed but not on this page), but you're totally right. I'm going to search for the issue in the URI and HelpBrowser SC classes; URI has a lot of platform-dependent code so that looks promising.

**Comment by snappizz** [comment]
Oops, sorry, I deleted it (I mistakenly thought that I was repeating what was already known). It said something like "it looks like SCDoc.indexAllDocuments is succeeding and the problem is in the help browser."

Immediately after the "Indexed # documents in # seconds" print, `SCDoc.indexAllDocuments` calls this:

    NotificationCenter.notify(SCDoc, \didIndexAllDocs);

This notification is watched for in `HelpBrowser.initClass`, which calls `WebView.clearCache`, which invokes the primitive `_QWebView_ClearMemoryCaches`.

So here's my suggestion: in `HelpBrowser.initClass`, add a postln before and after the call to `WebView.clearCache` and see if that primitive is where failure happens.

**Comment by brianlheim** [comment]
Well it cleared up some confusion for me, so I'm glad I caught it. I'm away from my Windows machine right now, but I will check that tonight if I can.

**Comment by snappizz** [comment]
(Actually, it's probably not `WebView.clearCache`. That method seems pretty innocuous to me)

**Comment by brianlheim** [comment]
Yeah, `WebView.clearCache` is fine. Current best guess is that it's a problem in [this method](https://github.com/supercollider/supercollider/blob/master/editors/sc-ide/primitives/sc_ipc_client.cpp#L310-L338).

I don't have time to test it now, but I think the call `QString::fromUtf8` is going to cause an issue since the string being passed from the SC language is in fact not encoded in UTF-8, but ASCII. I'm pretty sure that's what's being passed: I put a postln in `ScIDE.prSend` and it prints the `data` argument with ? characters. A string that was encoded in UTF-8 would have printed é & ü.

http://stackoverflow.com/questions/23888263/russian-or-non-latin-filename-load-qt-windows

As a further test, I added the line
```c++
postfl("Serializer data: %s\n", serializer.data());
```
to the method linked above, after the line
```c++
YAMLSerializer serializer(argSlot);
```
And tried various calls of 
```
ScIDE.prSend("openHelpUrl", url);
```
Can confirm that sending a garbage or non-existent URL silently fails.

**Comment by snappizz** [comment]
How are we doing here?

**Comment by brianlheim** [comment]
I'm hoping to start stabbing at this after I'm done with #2751. Although I haven't looked in a while, at the moment I plan to approach a solution by rewriting SC_DirUtils.cpp and related functionality using boost::filesystem::path, which has already been introduced piecemeal.

**Comment by tiagmoraismorgado** [comment]
i think encoding it as utf-8 makes sense for this purpose
