### ISSUE TITLE
Windows: move on to VS 2015 build

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2460]
VS 2013 is getting hard to download and restricts us to Qt 5.5. It would be nice to move on to VS 2015, which in turn requires us to move on to Qt 5.6 or higher. The main blocker for that is SC's dependence on Webkit, which is not supplied with Qt 5.6 any more. OSX, though for other reasons, has similar pressures to move on to Qt > 5.5. Some Linux distributions oth might not reach Qt 5.6 for a while (debian stable seems still to be at 5.3.2). But older Qt versions already come with Webengine, so we might be lucky.

This move would also mean though that Qt-dependent parts of SC cannot be built with MinGW any more, because Qt's MinGW build does not come with Webengine, the replacement of Webkit.

This in turn means we will either have to port supernova to VS 2015 or drop it from the release. :(

**Comment by scztt** [comment]
Do we have a sense of whether any of the supernova threading functionality is even performant on Windows right now? If it's not, then dropping it isn't really a critical loss of functionality...

That said, I think porting to VS would be good - especially since it would mean SuperCollider has someone with some domain expertise in supernova threading stuff other than Tim, as he's only really committed to maintaining it for a pretty narrow deployment case. Using portaudio as the audio backend in a VS2015 context probably requires some build hacking, and the instructions I've seen mention it being build on top of ASIO, which is non-ideal - it might be better (and more performant + more maintainable?) to just build a new WASAPI backend - it only requires implementing 8 or so calls, and it involves actually writing code and not fiddling with build settings. :)

The rest of the move to webengine is easy for SC - I think there are branches by me and tim that fix all the easy problems. A bunch of methods have become asynchronous - this stuff is a bit harder to fix, as it probably should be incorporated into SC's existing async / non-async way of getting and setting properties. Or, we could simply remove that functionality from WebView to get things moving forward, and add it back as people complain.... The WebKit -> Webengine switch is a pretty huge architectural change, so it's not at all crazy for it to have an impact on the existing functionality.

**Comment by vivid-synth** [comment]
I'm not a Windows user, but would like to second the enthusiasm about porting supernova to VS. It would be great for Windows to be a first-class citizen for supernova, and to have more developers who understand it!

**Comment by telephon** [comment]
sounds good. What functionality of WebView would be affected?

**Comment by scztt** [comment]
All of the functions listed on these:
https://doc.qt.io/qt-5/qwebenginepage.html
https://doc.qt.io/qt-5/qwebengineview.html
that take a `resultCallback` as a parameter have become asynchronous. Those will either have to be removed, or re-written to be async. Basically, this amounts to any function that returns internal information about the page - text, what's under your cursor, etc etc. The web pages are now out-of-process, so any content-related things are async. 

Note that there's also MORE work to be done beyond that - after moving to qt5, we never fully got web views working - lots of their rendering (for e.g. PNG's) came from plugins, and there was some additional build/packaging work required to get ALL the plugins required to things like --- a YouTube page. It's not hard, but I never found a canonical list, so it was a piecemeal process of randomly picking some plugins, adding them in Cmake, trying some pages, figuring out what wasn't working, etc.... It might have been improved with WebEngine though?

**Comment by telephon** [comment]
In the main distro, we are using WebEngine mainly for showing the help files, don't we? And I suppose that, while there may be a few, not so many people are using the web view for their own systems. So this suggested change wouldn't have much of an impact.

**Comment by scztt** [comment]
Yup! I think it would basically be a deprecation of stuff no one is using. Though: the WebView is a very useful and extremely untapped widget in SC, so it WOULD be nice to maintain / expand functionality and not decrease it in the long run. That said, I don't think this temporary functionality loss would be enough to warrant an otherwise critical QT upgrade

**Comment by telephon** [comment]
Then I'd say move as soon as possible, aka now ...

**Comment by brianlheim** [comment]
Fixed in #3165.
