### ISSUE TITLE
Fix suggestion for dangerous scvim bug

### ISSUE THREAD

**Issue by carlocapocasa** [supercollider/supercollider#2472]
I fixed a [very nasty bug](https://github.com/sbl/scvim/pull/36) in sbl/scvim, a more mature fork of supercollider/scvim. I dubbed it the "two headed monster bug" because it lead to two concurrent sclang instances running at the same time, looking like one but randomly taking turns receiving commands. Each one is in a slightly different state than expected, leading to all sorts of unpredictable errors. I was writing a lot of complex SC classes at the time and debugging was *not* fun.

My fix in sbl/scvim replaced the finicky ruby multi-process code with a very simple single-process approach that has proven very robust for my own work and other users.

I looked into supercollider/scvim and it shares the same inner workings of the bad sbl version, so it is likely to suffer from the same problem.

I believe one of the following should urgently be done:

(1) Replace supercollider/scvim with sbl/scvim in the submodule (preferred)

(2) Apply the fix to supercollider/scvim

To do (1), some existing supercollider/scvim users ought to weigh in. Personally I love sbl/scvim, but switching shouldn't break any workflows. I can do (2) if necessary but I would much rather move forward; sbl/scvim is much improved in terms of code quality and polish.

Option (3) "do nothing" should be avoided; the bug is amazingly destructive, because you don't notice it and it slowly sabotages your workflow over time.

**Comment by snappizz** [comment]
cc @blacksound

**Comment by blacksound** [comment]
I agree with option 1 - also mentioned in https://github.com/supercollider/scvim/issues/7
I haven't gotten anyone to weight in on this proposal yet.
This bugfix raises this issue to a new level in my opinion, but we should get more people to weigh in on it in my opinion.

**Comment by carlocapocasa** [comment]
@blacksound, I can notify the supercollider/scvim watchers and starrers, and post to the SC mailing list linking to this issue if you don't have any objections, or would you prefer to handle it yourself, or differently?

**Comment by vivid-synth** [comment]
Maybe let's phrase it the opposite way: if anyone objects to option 1 (replace the submodule with sbl/scvim), please speak soon! Else let's just swap it out

**Comment by blacksound** [comment]
@vivid-synth, nobody has stepped up and objected to this proposal, so I would say that we just go ahead and redirect the scvim submodule from supercollider/scvim to sbl/scvim.

I will add a note about this in the README for supercollider/scvim when we have redirected it.

Now, this becomes a git issue with the main repo, so I'm closing this issue here now. I will make a new issue here on Github about redriecting the submodule to sbl/scvim and ask on the dev list for the best way to do it.

There were some people that had problems with their own supercollider git repos when the scvim folder was moved into a submodule, so we should discuss the best way to do this before making the change.
