### ISSUE TITLE
Windows build should link to class files in source tree

### ISSUE THREAD

**Issue by bagong** [supercollider/supercollider#2479]
Currently the class files are copied to the target build folders during a build. That allows to run each target in its target folder (debugging), but it prevents that changes to class files in the source tree are directly reflected in the build (running in the target folder). It would be nicer (and faster) to have sclang use the classes in the source tree, either by creating a link in the target folder or by setting the folder in which sclang searches specifically for the build only (rather than the install).

**Comment by telephon** [comment]
That would be in LanuguageConfig, maybe?

**Comment by bagong** [comment]
I think a dynamic link would be far less hassle, but I am not sure how to make cmake create one that works in Windows.
Trying it via LanguageConfig, I guess, would require to use a local config file, which would require to provide a startup parameter to sclang. And that should somehow be passed to an IDE to be used when running targets... pretty involved I think, I wonder if it's possible at all...

**Comment by crucialfelix** [comment]
It's not just windows. this used to be an option during build but it was
removed for some reason.

I use a shell script to symlink classes and help

On Sat, Nov 5, 2016, 14:11 Rainer Schütz <notifications@github.com> wrote:

Currently the class files are copied to the target build folders during a
build. That allows to run each target in its target folder (debugging), but
it prevents that changes to class files in the source tree are directly
reflected in the build (running in the target folder). It would be nicer
(and faster) to have sclang use the classes in the source tree, either by
creating a link in the target folder or by setting the folder in which
sclang searches specifically for the build only (rather than the install).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/supercollider/supercollider/issues/2479>, or mute the
thread

**Comment by telephon** [comment]
>It's not just windows. this used to be an option during build but it was removed for some reason.

The argument was that it never worked properly and that you can do the same thing using LanguageConfig.

**Comment by bagong** [comment]
I am just speaking about the case SC development system here, which in practice usually means running SC within a target build folder in an IDE for debugging purposes. I am not referring to the general use case. For the development environment cmake should be creating as much of the configuration as possible. After all, the build might be recreated very frequently.

**Comment by telephon** [comment]
Ok, I understand.

**Comment by bagong** [comment]
I've suggested a solution in PR #2708

@telephon , this uses a shell script that knows locations because cmake passes them in as arguments. In principle this should work on MacOS too, but: the MacOS build system creates a more or less full application bundle in the IDE-target-build-folder (and "developers" are supposed to work there rather than in an install). For the full install, that bundle is basically copied to the install location. MacOS symlinks only survive move, not a copy, and of course the resulting installed bundle wouldn't be portable any more. So installing classfiles, helpsource (examples and sounds) would have to be reimplemented the way it used to be in the older build system - I think. It's possible, and not too difficult, I think, but I'd only try that after some time, if there is noticeable interest. Or maybe somebody else? ;)

**Comment by bagong** [comment]
Done #2708
