### ISSUE TITLE
Redirect supercollider/scvim submodule to sbl/scvim

### ISSUE THREAD

**Issue by blacksound** [supercollider/supercollider#2550]
Following the discussion in #2472 and supercollider/scvim#7 , and the fact that nobody has stepped up and objected to it, we want to redirect the scvim submodule to the sbl/scvim repo.

The recent bugfix of @carlocapocasa and the fact that the sbl/scvim repo has been more maintained are the main reasons to do this.

There were some people that had quite a few issues with their git repos when the scvim folder was moved into a submodule, so we should discuss the best way to do this before making this change.

**Comment by danstowell** [comment]
as an old-time scvimmer I say "go ahead"... (I don't use it at the moment I'm afraid)

**Comment by gusano** [comment]
:+1: for me too, but changing the submodule URL might be *super painful* for already existing scvim users.. I still didn't find a nice-and-easy way to do that.. It might be much easier to replace `supercollider/scvim` with the code from `sbl/scvim`, or merging it, not sure.. cc @carlocapocasa

**Comment by carlocapocasa** [comment]
> replace supercollider/scvim

I recommend to change the url, and place the following in the release notes:

Please run `git submodule sync` after checking out the master branch.

Once it's there, I'll gladly expand those instructions a little.

Rationale: It's not *that* painful since scvim users are assumed to be a bit more on the technical side of the SC user skill spectrum. It will save labor in the long run to directly submodule sbl/scvim because he has done a stellar quality job.

**Comment by gusano** [comment]
> scvim users are assumed to be a bit more on the technical side

@carlocapocasa Agreed but it's definitely more than just `git submodule sync` :)

**Comment by snappizz** [comment]
Great! Would someone mind summarizing the major improvements of `sbl/scvim` for the changelog?
