### ISSUE TITLE
[travis] Avoid building sc when only changing class library

### ISSUE THREAD

**Issue by gusano** [supercollider/supercollider#2635]
I found a way to detect if a PR only contains changes to the class library, help, doc, etc..
I would love to avoid building sc for those PRs but rather get the latest build and only try to compile the library against it (although I'm not sure how much faster that would be than building..).

Right now, it seems that [we only deploy osx builds](https://github.com/supercollider/supercollider/blob/master/.travis.yml#L66).

 - why is that?
- would it be possible to also deploy linux ones?

cc @scztt

**Comment by scztt** [comment]
We can skip building for classlib-only changes, but it requires [caching build files between travis jobs](https://docs.travis-ci.com/user/caching/). I never implemented this because it increases complexity and introduces the potential for various kinds failures - the latency of getting build results seems less important than a high bar for accuracy / stability of automated build results (which we have now). I think things are stable enough now that I'd be more comfortable adding caching, if someone wanted to take ownership of that functionality. I think if we cached for classlib-only and helpfile-only changes, and cleared the cache for all else, we'd still have a pretty high bar for build stability too, and it would make those builds VERY fast.

As far as linux builds: I believe I had actually done that originally, but in general folks simply build from scratch on linux - afaik you can't do much with a linux binary unless your environment exactly matches the env in which it was built. It would be AWESOME to spin actual binaries that could be dropped-in on one or two common linux distros, and *especially* on raspberry pi / etc. environments. It would take someone with more linux knowledge than myself to get this done - but I'd be glad to facilitate posting those builds (it's very easy).

**Comment by gusano** [comment]
@scztt I played with travis cache some time ago and ran into some issues:

- you're not supposed to cache built binaries but rather dependencies
- travis doc is a bit confusing about caching for several languages/os projects (this is not so common)
- I don't see any way to clear cache programmically in the middle of travis build

> afaik you can't do much with a linux binary unless your environment exactly matches the env in which it was built

Yeah that was the idea, only use the linux build from travis inside travis :)
As you said, it doesn't make sense for anything else..

Not sure all this is worth the research/effort...

**Comment by scztt** [comment]
My intuition is - build caching is a ways down the stack in terms of priority of travis things. I would much rather see someone, for example, figure out how to run the Server-based unit tests on a system without a sound card. :)

**Comment by gusano** [comment]
@scztt Yeah it's just that I find it annoying to have builds lasting up to 45/50 min... It seems it's travis/osx related though but that's kinda OT.
Re-tests I don't even see how feasible it is to boot a server without soundcard :)
Thanks for your inputs!

**Comment by scztt** [comment]
The builds themselves are only taking between 10 and 15 minutes in general - I'm not exactly sure what the "total time" / "elapsed time" measurements are indicating... maybe it's just taking longer to pick up a free machine?
https://travis-ci.org/supercollider/supercollider/builds/191480788

**Comment by brianlheim** [comment]
I think "total time" is the sum of all the individual build durations, and "elapsed time" is the difference in time between the initial request and the last build exiting.

**Comment by jamshark70** [comment]
> I don't even see how feasible it is to boot a server without soundcard

I think most UGen tests could be done in NRT mode, right? That wouldn't work for tests of outgoing messages from the server, but otherwise...? You could even package multiple tests in one OSC input file.

**Comment by gusano** [comment]
> I think "total time" is the sum of all the individual build durations, and "elapsed time" is the difference in time between the initial request and the last build exiting

Yep

> maybe it's just taking longer to pick up a free machine?

Yep, for osx only: https://github.com/travis-ci/travis-ci/issues/6841#issuecomment-259402341

**Comment by gusano** [comment]
@jamshark70 That sounds great but I never worked with NRT.. Will investigate.

**Comment by jamshark70** [comment]
@gusano here's a hint for retrieving nrt server data to validate test results: http://doc.sccode.org/Guides/Non-Realtime-Synthesis.html#Analysis%20using%20a%20Non-Realtime%20server

**Comment by brianlheim** [comment]
IMO, it's better to let SC build each time. There was a PR a few weeks ago where @snappizz changed the name of `README_OSX.md` to `README_MACOS.md`. The build failed because CMake couldn't find the file to copy. Maybe that's me being myopic, but I think being sure a change will build OK is harder than it seems.

**Comment by brianlheim** [comment]
@gusano @scztt - would you consider #3136 a resolution for this? (I would)

**Comment by brianlheim** [comment]
closing for now, if there's something else we can do let me know. i think #3136 solves this problem better than caching binaries - Travis explicitly recommends not doing that because pulling them from the cloud takes a long time.
