### ISSUE TITLE
Possible to compile supercollider-server for the web via emscripten

### ISSUE THREAD

**Issue by abhi18av** [supercollider/supercollider#2685]
Hi @supercollider team!

Being an avid user of `overtone`, `sonic-pi` and `alda` for music programming - I was wondering whether the core-server could be ported to the web via `emscripten`?

I've skimmed around the emscripten tutorials and reached the conclusion that the people familiar with the codebase could give a quick overview about how - if possible - can this be done.

**Comment by brianlheim** [comment]
Hey @abhi18av, thanks for the question! While I don't have a definite answer to your question, I'd like to suggest asking this on the sc-dev mailing list—where it will be probably be read more frequently and by more people—rather than creating an issue here. If you run into any specific problems while trying to use emscripten, and they do relate to an issue with the code base, you're more than welcome to submit a new issue for that.

**Comment by abhi18av** [comment]
No issues @brianlheim :+1:
