### ISSUE TITLE
Array:pyramid and Array:pyramidg <-- towards a better helpfile

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#2691]
At the [Array helpfile](http://doc.sccode.org/Classes/Array.html#-pyramid), I read: 

```
pyramid (patternType: 1)
Return a new Array whose elements have been reordered via one of 10 "counting" algorithms. Run the examples to see the algorithms.
10.do({ arg i;
    [1, 2, 3, 4].pyramid(i + 1).postcs;
});
Arguments:
patternType	
Choose counting algorithm. The algorithms are numbered 1 through 10.

-pyramidg (patternType: 1)
Like pyramid, but keep the resulting values grouped in subarrays.
// compare:
[1, 2, 3, 4].pyramid(1).postln;
[1, 2, 3, 4].pyramidg(1).postln;
```

Although I understand the general idea of pyramid/pyramidg, we should get a better description in the helpfile.

**Comment by brianlheim** [comment]
Thanks for bringing attention to this, but I don't think we should get in the habit of having an open issue for every under-documented helpfile method. The lack of clear documentation is a well-known and long-standing issue for SuperCollider. #2687 is worth keeping because the C++ itself is under discussion, and cases where the documentation directly conflicts like #2678, #2686 are good, but "better description for a single method" is not worth its own issue at this point, and is just going to create clutter in the long run. I'm going to open a new issue so we can keep track of these in a more organized way.

**Comment by LFSaw** [comment]
Thanks for your reaction.
I understand that we don't want to have too much clutter, however, I am also trying to keep up with what little I can add to the SuperCollider community, and discussing helpfile issues wherever I stumble over them during my sc-related time, I'd like to gather that information.

I google around to find a source (or any kind of reason to have) the pyramid methods. 
I am willing to spend time on this (as you see in #2687 and #2678) and am genuinely interested in clearing these up.
However, where should I discuss this with others if not here?

**Comment by brianlheim** [comment]
> I'd like to gather that information.

Absolutely, and that's why I created #2692 — so we can have an organized list of these methods so that, among other things, people are more encouraged to tackle multiple fixes at once.

> I am willing to spend time on this

I don't doubt that at all; I hope my response didn't come across as "stop opening issues just to bug us." I know you've been submitting PRs to fix these and other issues, and I really appreciate your collaboration! I'm just trying to find a workflow for what I'm seeing as an emergent pattern that I think will be more productive, ultimately. 

What are your thoughts? Would it motivate you more if you can open a single issue and then close it with a targeted PR?

**Comment by LFSaw** [comment]
> What are your thoughts? Would it motivate you more if you can open a single issue and then close it with a targeted PR?

Thanks for your patience :) Honestly, I am struggling to find my way. Yesterday I spend 2 hours to understand the PR mechanism so that I can add 2 sentences to the PinkNoise helpfile ( #2678 ), which I considered as "learn how to do things". What I do know by now is, that things is lists outside of this very issue tracker will get lost eventually, whereas I get messages from issues over a year old that got "stale" at first but were picked up later-on.

I don;t see this a question fir myself but rather on how to get more people interested in contributing and fixing, also little things, within sc3 (and its helpfiles). 

So, either way is fine with me as long as there is a possibility to discuss with people and also the  history of that discussion is kept until the issue is settled one way or the other.

**Comment by brianlheim** [comment]
> Yesterday I spend 2 hours to understand the PR mechanism so that I can add 2 sentences to the PinkNoise helpfile ( #2678 )

Which is _awesome_, and I'm currently looking over your changes. It was just as painful for me when I first started working with git.

> What I do know by now is, that things is lists outside of this very issue tracker will get lost eventually, whereas I get messages from issues over a year old that got "stale" at first but were picked up later-on.

Yes, no argument there!

I guess with adding documentation I think of it a little differently, because there are plenty of cases where someone just submits a PR to uncontroversially improve documentation, even though there's not a related issue. It's not as if we have to go through the whole rigamarole of tracking down a bug and its reproducer, or even discuss it much at all aside from wording—except when, of course, there's confusion, ambiguity, or conflict.

> I don;t see this a question fir myself but rather on how to get more people interested in contributing and fixing, also little things, within sc3 (and its helpfiles).

Understood! An idea I've floated before (and still intend to go through with) is enacting a "documentation drive" where we encourage SC users who may have never used git or GitHub to do exactly this. Would you be interested in discussing/brainstorming that?

> So, either way is fine with me as long as there is a possibility to discuss with people and also the history of that discussion is kept until the issue is settled one way or the other.

Yes, definitely. Well, could we try using #2692 for now, and it's not working out, we can go back to this method?

**Comment by LFSaw** [comment]
> An idea I've floated before (and still intend to go through with) is enacting a "documentation drive" where we encourage SC users who may have never used git or GitHub to do exactly this. Would you be interested in discussing/brainstorming that?

I already once initiated a helpfile overhaul, I think about 6 months ago... so I'm definitely in for this. Just contact me off-issues ;) 

> I guess with adding documentation I think of it a little differently, because there are plenty of cases where someone just submits a PR to uncontroversially improve documentation, even though there's not a related issue. It's not as if we have to go through the whole rigamarole of tracking down a bug and its reproducer, or even discuss it much at all aside from wording—except when, of course, there's confusion, ambiguity, or conflict.

OK, so you suggest to "file" a PR, without an issue. maybe this is a good point for many of the helpfile issues.
