### ISSUE TITLE
suggestions on doneAction: 2 tag

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2730]
doneAction: 2 tag on Supercollider, leads to an abrupt cut of the sound, right after the statement which leads to it is actually finished.

my suggestion goes in the line of:

- adding a small fade out curve to the instantiated synth or synthdef, so that right before cut is set there is a small fade out

**Comment by brianlheim** [comment]
This is well-documented, longstanding behavior, and there are easy ways of adding a fadeout. Changing this would be unnecessarily disruptive for many users.

**Comment by vivid-synth** [comment]
I think @tiagmoraismorgado raises a fair use-case: maybe it would be feasible to add a ```Done.release``` method, which "sends a gate=0 to itself"?

**Comment by brianlheim** [comment]
I'm all for some easier way to do that. I'm not sure adding a new doneAction is the best way, though, because of the particular behavior of that feature (i.e., only acting on nodes, instantaneous effect, only pausing/freeing, no messaging). To me, those are valuable guarantees to maintain. I think the standard way of doing this is to use `Linen`'s gate argument with `Done` wrapping a done-flag-compatible UGen?

**Comment by jamshark70** [comment]
I'm not sure that it's wise to automate this too much. Convenience methods are one thing (though we've created some maintenance headaches by hastily adding convenience methods that weren't thought through very carefully), but this request is verging on trying to compensate for the user's lack of knowledge of signal processing design.

I think this issue comes from a number of help file updates [1], reflecting incorrect synth design. If you design the synth incorrectly, you will get unwanted behavior. That isn't a bug in SuperCollider.

If you're generating an audio signal that is going to hit the speakers, you have to apply an amplitude envelope to the output signal, and `doneAction: 2` should belong to the amplitude envelope, *not to any other component in the SynthDef*. The help file updates in question add `doneAction: 2` to *control-signal UGens* (e.g. `XLine`) -- that's incorrect. So the point should not be "how to make a bad idea function better." The point should be how to educate users that this is a bad idea.

For convenience, what would be the proposal? `Out.ar(0, mySignal * Done.release(controlSignal))` where the hypothetical `Done.release` would wrap a `Linen`? I don't see how to simplify further.

[1] https://github.com/supercollider/supercollider/pull/2736/files among others
