### ISSUE TITLE
Allow ' in identifiers

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2773]
Once the parser tests are in place it would be really nice to allow to append a `'` to a variable name. This is very common in Haskell, and it is such a nice way to denote a variant.

`x' = x + 1`
`x'' = 7`
`freq' = freq * rato`

instead of 
`x1 = x0 + 1`
`x2 = 7`
`newFreq = freq * rato`

etc.

It seems, naively, that this could be legalized. Obviously, the tick is used also to close a symbol – so this would have to be checked if it is nevertheless ok.

**Comment by brianlheim** [comment]
This would be a major change to the language definition. It's possible (I can already think of a few changes that might work on the lexer side), but I have no opinion right now whether it's worth the cost. It would lead to major backwards compatibility issues. Looking forward to others' thoughts.

**Comment by snappizz** [comment]
I'd like Unicode variable names more than this.

**Comment by telephon** [comment]
`others' thoughts` - there you got it! yes, it was just an idea to try out - and sure, unicode would be great.

**Comment by smoge** [comment]
This is probably much simpler than Unicode support. Both would be really great improvements.

**Comment by brianlheim** [comment]
I'm a firm no on this now. Even though AFAICT there are no overlapping cases where a legal string in SC would be interpreted differently under this change, it would cause visual dissonance in cases where single-quote symbols and identifiers are used in combination, which would be more common than in Haskell (where single quotes, as in C, denote a single character literal).

It would require rewrites of the highlighting rules for any client that performs SC syntax highlighting including the help browser, the IDE, and the syntax highlighting on GitHub.

It would require that the IDE (and perhaps other clients) know not to auto-expand `'` when within an identifier name.

It would create major backwards compatibility issues and an entirely new language definition. Identifiers with `'` couldn't appear in helpfiles, quarks, or class library files for at least a few years without major complaints.

It would be more difficult to read SuperCollider code in general if `'` is used in three very common places (anywhere in idents, at the start of a symbol literal, at the end of a symbol literal). In my experience, char literals in Haskell (and any language) are quite rare. Symbol literals in either notation, however, are very common in SC, especially when working with SynthDefs.

There are already alternatives to the notation `newFreq`: `freq2`, `freq_`, `freqB`, or just reassign to `freq` since SC has no notion of `readonly var`.

Unicode support in the lexer would actually be less difficult because it only requires expanding the set of legal characters, not altering the logic of existing lexing behavior.

**Comment by brianlheim** [comment]
By the way, this change would affect not only variable names, but method names as well, unless you wanted to add some currently non-existing logic to separate method name identifiers from variable identifiers in the parser.

**Comment by snappizz** [comment]
> It would create major backwards compatibility issues and an entirely new language definition. Identifiers with ' couldn't appear in helpfiles, quarks, or class library files for at least a few years without major complaints.

This is also true for other proposed lexer changes, like allowing class extensions to come before classes, or allowing symbols like `\1a`.

**Comment by brianlheim** [comment]
That's true, but those aren't major backward compatibility issues in my estimation. Identifiers comprise the vast majority of tokens in the vast majority of code, so any expansion of the legal character set for identifiers is likely to be picked up and used immediately. In addition, renaming an identifier is potentially a much more complex refactor than renotating a symbol literal or swapping around class definitions.

The other changes you mention have been recognized as solutions to inconsistencies between the language's informal definition and implementation, rather than feature expansion. The argument for compatibility also applies there, but I think it's obvious that the potential issues they would create are both rare and easily solved.

**Comment by smoge** [comment]
> Unicode support in the lexer would actually be less difficult because it only requires expanding the set of legal characters, not altering the logic of existing lexing behavior.

Perhaps `'` has a lot of practical concerns as you explained. But I'm curious, how about Unicode specific obstacles regarding sclang implementation? How hard or smooth would be to establish the sclang in terms of Unicode, not just characters and strings?

**Comment by brianlheim** [comment]
> How hard or smooth would be to establish sclang syntax with Unicode, not just characters and strings?

Very smooth to introduce since none of these symbols is currently used, although there would have to be discussion about which codepoints are legal for what kinds of tokens (i.e. variable names, method names, class names, primitive names). Implementing it (for most legality rulings) is not too hard either, although it would probably mean bringing in at least one other API (I haven't looked at it closely but I think the [ICU](http://site.icu-project.org/) library which is already packaged with SC would do). The lexer just needs to know when to flag a token as an identifier. You would need to change the checks [here](https://github.com/supercollider/supercollider/blob/master/lang/LangSource/PyrLexer.cpp#L417), and [here](https://github.com/supercollider/supercollider/blob/master/lang/LangSource/PyrLexer.cpp#L550-L551) to also allow the desired set of Unicode codepoints through.

Also...

> not just characters and strings?

Characters are only 1 byte in SC for now and don't support the full range of Unicode codepoints. Strings and `'`-enclosed symbols do (thanks to [this block](https://github.com/supercollider/supercollider/blob/master/lang/LangSource/PyrLexer.cpp#L751-L787)), purely by virtue of having been implemented a little loosely, but `\`-prepended symbols don't. Hope that makes sense :)

**Comment by telephon** [comment]
brian, your description is definite! Beautiful to see how a single charcter added can make hell break loose ...
