### ISSUE TITLE
Update yaml-cpp to 0.5.3

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#2788]
This would get rid of a large number of emitted deprecation warnings with boost now at 1.63. May be related to #1154.

@timblechmann has a [branch](https://github.com/supercollider/supercollider/tree/topic/yamlcpp-0.5) for this. Tim, I'm wondering how close that is to a ready-to-go solution.

Also, wondering if it would be better to fork yaml-cpp and keep it as a submodule ourselves.

**Comment by timblechmann** [comment]
someone may have to fix the merge conflicts. iirc i had been using it for quite a while. most deprecation warnings are not related to boost, but to `auto_ptr`, which is used in yaml-cpp-v0.3.0 and is deprecated since c++11.
as for the ide/sclang communication, it may be worth considering msgpack instead, as it will reduce the IPC load.

**Comment by brianlheim** [comment]
> someone may have to fix the merge conflicts.

Yeah, there are some and I'm happy to do that myself.

> most deprecation warnings are not related to boost, but to auto_ptr, which is used in yaml-cpp-v0.3.0 and is deprecated since c++11.

Ah, I missed that the first time around, thank you for clarifying.

> as for the ide/sclang communication, it may be worth considering msgpack instead, as it will reduce the IPC load.

Thanks for the tip!

**Comment by brianlheim** [comment]
(#2792)
