### ISSUE TITLE
Jitlib common error messages with BinaryOpUgen

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2822]
I saw someone complaining about the following error, regarding Jitlib usage, on the Beast sc:users mailing list. As I get similar errors with binary openuges once in a while, specially when things start to become complex, I decided to post it here so that you guys can inspect it. Looking forward. cheers. T.

```
WARNING: Synth output should be a flat array.
[ [ a BinaryOpUGen ], [ a BinaryOpUGen ] ]
Flattened to: [ a BinaryOpUGen, a BinaryOpUGen ]
See NodeProxy helpfile:routing
```

**Comment by snappizz** [comment]
Can you post some short code to reproduce?

**Comment by telephon** [comment]
This is a "good" error - check your code (see mailing list discussion).

**Comment by jamshark70** [comment]
It arises easily by accident if you have a single-channel proxy which you access by `proxy.ar` instead of the (more correct, but fussy) alternative `proxy.ar(1)`.

I understand the reasoning behind it and I won't ask for it to change, but I'd like to register that the good intentions behind it do not reduce the annoyance factor. ;)
