### ISSUE TITLE
should this simple build script be included?

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2827]
https://github.com/lvm/build-supercollider

**Comment by bagong** [comment]
I've been thinking about where build info and ideally also build automation could be stored while making sure that it remains up to date. A good solution would be transparent enough to be readable, and at the same time serve some purpose of general interest that makes it worthwhile keeping it up to date.

The travis script isn't really readable, but it's pretty ideal from a maintenance point of view. On OSX a homebrew script would be nice. Windows isn't there yet, I think...

**Comment by brianlheim** [comment]
IMO, this is duplication/fragmentation of knowledge that we'd do better to avoid; the readmes should be the sole authority on how to build SuperCollider. I also think it's bad form to distribute scripts that use sudo. If someone finds scripts like this valuable, they're better off keeping them somewhere outside the main repo.

> I've been thinking about where build info and ideally also build automation could be stored while making sure that it remains up to date. A good solution would be transparent enough to be readable, and at the same time serve some purpose of general interest that makes it worthwhile keeping it up to date.

This is an exact description of the readme, isn't it? Modulo the fact that anyone who is interested in regularly building this software can and should write their own script to do it in the way that they want.

**Comment by snappizz** [comment]
It would be nice if we threw in a Dockerfile.

**Comment by bagong** [comment]
Sure @brianlheim , I wasn't making that statement to support including the script, I was politely opposing it :smile:. 
But as you and I know the readme isn't ideal either. I am all for keeping it the sole authority for the time being. Midterm I think it's better to move the build-related part of it to the web. Ultimately, I think a "text" or a script that is guaranteed work because it is in continuous use, and contains the recipe for the current "reference build" is highly useful and desirable. But we're not there yet anyways, so it's a discussion for the future, I feel. Btw, for defining a reference build per platform Linux is really the biggest headache...

**Comment by telephon** [comment]
ok, just a suggestion

**Comment by brianlheim** [comment]
Ah, sorry for the misunderstanding. Thanks for the suggestion @telephon !
