### ISSUE TITLE
Add support for pulseaudio

### ISSUE THREAD

**Issue by windo** [supercollider/supercollider#2848]
Pulseaudio is default in many/most linux distros now. For use cases that don't require jack, it would be nice to be able to just start supercollider without having to deal with jackd setup (possibly challenging for some users).

**Comment by snappizz** [comment]
See also #1944.

**Comment by brianlheim** [comment]
Does anyone plan to work on this? I think we should probably close this since we are generally not working on new features right now. Maybe I'm overestimating how much effort it would take.

**Comment by brianlheim** [comment]
I'm going to close this one as a won't-do, since nobody else has chimed in. The simple answer is that SuperCollider is a project aimed at low-latency/real-time use, and because of that jack is a much better choice than pulseaudio for the general use case. I agree with the OP that it would be also good to make things easy for the casual user, but as I see it we don't have the time or dev power available to make it happen. I would not be opposed to making it available if the necessary changes were submitted as a PR.

Research I used to reach this decision:

http://jackaudio.org/faq/pulseaudio_and_jack.html

https://bbs.archlinux.org/viewtopic.php?id=48385

https://freedompenguin.com/articles/how-to/pulseaudio-toilet-full-roses/

https://unix.stackexchange.com/questions/68772/jack-vs-pulseaudio-how-is-it-faster

**Comment by bagong** [comment]
There is a line worth researching: there is a portaudio fork with a tight link to the portaudio scene that adds a pulseaudio backend. It should be quite easy to use with SC. I haven't experimented with it yet because the author is still working on recent problem reports. The announcement was quite recently.

https://app.assembla.com/spaces/portaudio-pulseaudio/git/source/PulseAudioHostAPI
