### ISSUE TITLE
Language menu is too big

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#2852]
Low priority, not for 3.9, but... here's the Language menu with XFCE's default system font on a 768-pixel-high screen (typical for laptops):

![language-menu](https://cloud.githubusercontent.com/assets/318301/25364025/eaea50f4-2991-11e7-904c-147d843dba1c.png)

It's not pretty.

Concrete suggestion: Many of these options are about the Server, not the Language, so we could have a separate Server menu.

**Comment by scztt** [comment]
That would give us room to add a list of running servers, which would help with problems of ghost scsynth processes after a crash.

**Comment by telephon** [comment]
It would be good to be able to switch servers indeed. 

Note that the problem of ghost servers has been solved, but hasn't been merged – @adcxyz I can't find a pull request right now.

**Comment by tiagmoraismorgado** [comment]
i vote on that please make the gui responsive

**Comment by adcxyz** [comment]
@telephon 
The ghost server problem is in the ServerRecover part of this branch:
https://github.com/supercollider/supercollider/compare/topic-server-refactor-fix-multiclient
There was no pull request yet, because that branch contains other related proposals as well (multi-client support on a single server, changes to the allocators and nodeID ranges), and I did not have time yet to unpack it into smaller chunks that are easier to review and agree on.

**Comment by telephon** [comment]
ah yes! if you could separate that, it would be excellent

**Comment by kisielk** [comment]
Thanks for the review @brianlheim
