### ISSUE TITLE
binding tensorflow to supercollider

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2856]
<h1>greetings everyone</h1>

<h3>it would be interesting if, within sense:</h3>
<I><b>- there would be bindings of tensorflow to supercollider</b></I><br/><br/>

<p><i>perharps someone already did it, and I am not aware, but this would definitely be a great thing to incorporate into supercollider, peharps as a quark. memo akten has an implementation of tens-reflow in open frameworks, so that could be a start to perhaps make a port using c++. I know that you guys will probably close this issue, but I consider it relevant and that my main motivation to post it</I></p>

**Comment by LFSaw** [comment]
uhm... do you have a link on what you're talking about? *dumbquestion*

**Comment by snappizz** [comment]
I'm going to have to ask you to discontinue opening requests for major new features like this. You're free to develop your own quark, or fork SC to develop new sclang primitives, but please understand that this is not the right place to propose ideas for new features that are only tangentially relevant to core development and are only useful to a small group of users.

**Comment by jamshark70** [comment]
@tiagmoraismorgado I get the feeling that you have a desire to be useful to the SC community, where you're measuring "usefulness" by influencing SC's future direction. But that's not the only way to measure usefulness.

Consider the results of trying to *change* SC into something you want... that hasn't been very successful.

Another way to be useful is to *ask what the SC community needs* and then do that. For example, you had suggested QML bindings. I think that's a good idea, and I'm not the only one. If you made a good start at making this work, it would be more valuable than a hundred feature requests like this.

To help somebody, listen first to what they need.

**Comment by tiagmoraismorgado** [comment]
@jamshark70  that's pretty difficult to choose the right words for what I feel towards the overall supercollider community. first of all thanks for all the insights on my contributions, and for welcoming me here. my standing point is that I've been trying to contribute to supercollider and learn from it. I opened up a bunch of pull requests and issues over the course of last year. and most of them were actually rejected. I don't want to impose anyone my vision of what a product should be, disregardless the fact it is open source or not. I believe I have awesome ideas, and I just want to share them, and make an impact on overall tech development, and learning a bit within this process. sometimes making those ideas turning to reality takes years for me, as I don't have the immediate know how to implement them. but that's why share them, because even if I cannot implement them someone will, ultimately do so. and that's a great way to contributing to the development of the overall thing. that's my only status quo. and that's my only motivation for contributing to supercollider. what I feel is that most of my feedback gets rejected, with an accepting ratio of about 7.5-15%. while other users feedback gets accepted almost immediately right after being committed. that's perhaps because their ideas are more inlined with the overall dominating position in supercollider development. and that's perhaps because they can make these ideas turn to reality quicker. anyway I just want to share ideas I have which I believe to be good, and have an impact on open source, and helping the the overall development of computer music and digital media arts scene. perhaps it's time for me to try to adapt or look for a more suitable open source community. looking forward. kind regards. T.

**Comment by vivid-synth** [comment]
@tiagmoraismorgado I agree with you that bindings like this could be interesting, but even if someone did have the time to implement this (it's a **very** large feature), they would do it as a quark, and we don't make issues for quarks we want on the main repo. A good place to put "big picture" SC ideas might be a blog. I'd be interested to read a blog post which proposed Tensorflow bindings, especially if the post was about what we could **do** with those bindings once we had them.

> I believe I have awesome ideas, and I just want to share them, and make an impact on overall tech development, and learning a bit within this process. sometimes making those ideas turning to reality takes years for me, as I don't have the immediate know how to implement them. but that's why share them, because even if I cannot implement them someone will, ultimately do so. and that's a great way to contributing to the development of the overall thing.

If you want to share "big picture" ideas, I think a blog is the best place. If you want to learn development or help us out with work that needs doing, I'd suggest taking a **very small** need and working on it thoroughly, making sure it's high quality. In the past there have been some pull requests that were closed because they felt like "quantity over quality."

I'd suggest submitting a pull request which is 10 lines or fewer next time. A small change, when a lot of work has been put into it, can be very valuable. You might be able to find something in the "low-hanging fruit" category https://github.com/supercollider/supercollider/issues?q=is%3Aopen+is%3Aissue+label%3A%22low+hanging+fruit%22

In addition, I'd recommend picking one pull request and getting that polished. Once you've submitted it, wait for feedback and when feedback comes, just work on that one PR until it's accepted or rejected. I'm much happier to provide suggestions for one pull request that needs work than for many.

**Comment by jamshark70** [comment]
> even if someone did have the time to implement this (it's a very large feature), they would do it as a quark

It depends... if tensorflow is a separate executable invoked by SC, it could be a quark. If it has to be linked and exposed by primitives, a quark would be impossible. The former might be feasible, but would depend on a developer or team willing to put in hundreds of hours of work. The latter, I think, won't happen.

I agree with all of vivid-synth's recommendations for contributing. PRs are more likely to be accepted when they are complete, high-quality, and tested. For example, when I was working on the new Rest stuff:

- I *did* finish the new primitives and test then

**Comment by jamshark70** [comment]
Sorry, I'm doing this on my phone and the bus lurched so I brushed the wrong button.

Anyway.

I did finish the new primitives and test them first. Where I wasn't sure about something, I asked for help in a discussion before committing anything.

I did NOT commit half-finished, buggy work and expect others to clean it up after me.

I think those are reasonable expectations.
