### ISSUE TITLE
Interpreter options blank in IDE

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#2878]
in preferences>interpeter, the interpreter include/exclude paths are blank regardless of the contents of the config files.

probably has to do with yaml-cpp?

**Comment by brianlheim** [comment]
yeah, probably. if someone wants to dig into this one, go ahead. i'll try to look into it when I get a chance.

**Comment by miguel-negrao** [comment]
I think  I found the issue.  Looking at the code in SclangPage::readLanguageConfig() I wonder if it wouldn't be better from maintenance point of view to have a single function to read the yaml file for ide and lang (and possibly later scsynth). In order to avoid temporary data structures one could pass lambdas to the function for processing each includePath, excludePath, inlineWarnings, etc.

**Comment by miguel-negrao** [comment]
Also, it seems that  YAML::Load( configFile.toStdString() ) doesn't work  (that uses internally stringstream instead of ifstream). There are a couple of other places where that is used. I can try to look at this later.

**Comment by miguel-negrao** [comment]
I looked at all the other uses of YAML::Load and they seem to be correct.

**Comment by brianlheim** [comment]
thanks @miguel-negrao

**Comment by snappizz** [comment]
thanks :)
