### ISSUE TITLE
Move Halo into standard Distro

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#2884]
As it came up in the discussion of #2883, @adcxyz proposes:

> Lots of objects benefit from having local numerical specs that are uniformly accessible and changeable. Rather than implementing var <specs, addSpec etc etc methods in all of them,
Halo provides a simple, compact and uniform solution for every object to store stuff around it, including the convenience methods for specs.
> 
> I have yet to encounter any of the initially suspected trouble with memory leaks.
If worried, one can always get rid of the halo explicitly with object.clearHalo.
So in my opinion, Halo has passed the long-term usage test, and I would much prefer
to move Halo to standard distro than having various (possibly diverging) bypasses for it in various objects.

`Halo` is currently part of [JITLibExtensions](https://github.com/supercollider-quarks/JITLibExtensions). It's help file can be viewed [here](https://github.com/supercollider-quarks/JITLibExtensions/blob/master/HelpSource/Classes/Halo.schelp).

**Comment by telephon** [comment]
Just for discussion, here is a second variant, as part of a library that I am preparing (which might be a good candidate for common in the future):

https://github.com/telephon/Neutral/blob/master/Delegators/Extendable.sc

**Comment by telephon** [comment]
… in any case, a good idea to move the `Halo` from JITLibExtensions. Maybe we could generalise a few methods, as indicated in the source code.

One question: how do we make sure to avoid incompatibilities? (Duplicate class errors)?

**Comment by LFSaw** [comment]
@telephon , could you describe briefly what `Extendable` does, and how it relates to `Halo`, please?

**Comment by adcxyz** [comment]
@telephon 
> One question: how do we make sure to avoid incompatibilities? (Duplicate class errors)?

Simple but ugly - rename one of them (e.g. make a final JITLibExtensions tag that uses HaloOld)
Or Move Halo to a separate quark for use with pre 3.9 SC, and require it in JITLibExtensions when using pre 3.9 SC ... not sure how exactly, should be well tested first.

**Comment by bagong** [comment]
In theory Quarks should support versioning. Maybe @crucialfelix can explain.

**Comment by miguel-negrao** [comment]
They do. Example:
```
(
  name: "ImmLib",
  summary: "A Library for immersive spatialization",
  version: "0.1.6",
  schelp: "ImmLib tutorial",
  dependencies: [
    "FPLib@v0.2.1",
    "https://github.com/miguel-negrao/UEvNetMod.git@v0.1.0",
    "https://github.com/miguel-negrao/Unit-Lib.git@immlib-v0.1.1",
    "https://github.com/miguel-negrao/WFSCollider-Class-Library.git@immlib-v0.1.0"
  ],
  license: "GPL3",
  copyright: "Miguel Negrão 2013-2015"
)
```

**Comment by adcxyz** [comment]
Thanks Miguel, 
will try to get a working example together ASAP.

**Comment by telephon** [comment]
See also #3467.

**Comment by scztt** [comment]
We don't currently have a solution for moving classes from a Quark into the main lib (hence the somewhat bad breakage with quarks related to UnitTesting). We should definitely fix that before bringing this into the main library.

**Comment by telephon** [comment]
Yes, this needs to be fixed.

But I would also suggest *not* to just move `Halo` as it is to the class library, but implement it in terms of an `AbstractObject` wrapper. The same could be done for dependencies.

The current implementation suffers a bit from the same problem as other parts of the dependency  system: you need to explicitly release the object. This is a shame, because it creates a global pool where none would be needed.

In principle, I see two ways to proceed:
1. implement an intermediate level of object that has a slot for a halo (this can then also model dependencies). Such a class could serve as a superclass for any object that can change its state.
2. implement a transparent wrapper for object, using the `ExtendibleObject`, which carries a halo. This is only reasonable if we don't get much of an overhead for message passing. I can imagine that message forwarding is really fast, so perhaps this is a good way to go.

**Comment by miguel-negrao** [comment]
> We don't currently have a solution for moving classes from a Quark into the main lib (hence the somewhat bad breakage with quarks related to UnitTesting). We should definitely fix that before bringing this into the main library.

Added an issue for that #3588.

**Comment by scztt** [comment]
I've got another concern about pushing Halo as a defacto spec management API: we ALREADY have a system in place for tracking specs for synth arguments, in SynthDesc / SynthDescLib. This could be another case where we end up with two completely separate and incompatible ways of doing the same thing, which is only going to create user confusion. I'm really not sure what the solution should be if we  moved Halo into the main classlib...?
- **Separate `addSpec` functionality into it's own separate quark?** (JITLibExtensions or something else)
- **Merge Halo specs and SynthDesc specs so that they point to the same thing for all cases where they can?** (this is a large-ish engineering task)
- **Extend existing SynthDesc-based spec system to provide the same functionality as Halo, and then deprecate the Halo versions?** (I have a PR extending spec behavior, though it doesn't address the Halo `addSpec` etc APIs - it could if we decided we should keep those).
- **Move all spec tracking to Halo?** (this seems like a bad idea, since the breakage for existing code would be bad, and the current design is still solid - but I wanted to put it on the table)

**Comment by adcxyz** [comment]
As the author of Halo etc, I'd like to offer some biased opinions:

1. Generality - There are other objects that use the obj.set(<name>, <value>) interface pattern 
to access named numerical parameters, e.g. Tdef and Pdef; 
The Halo/addSpec approach is designed to _just work_ for all of them, 
including any newly written objects that have the basic set/get methods. 

2. Reliability - I have been using JITLib Halo/addSpec/getUni/setUni every day for years, 
in all of my projects and teaching, and have not had issues with it in a long time. 

3. Flexibility - You can tweak specs with say x.addSpec([0, 11]), 
or x.getSpec(\y).maxval = 111, and it is just there immediately. 

4. Sharing of specs - A familiy of objects to have the same dict of specs, 
as e.g. obj.class.addSpec adds to a class-shared dict;
you could use the same spec dict for multiple objects:
x.addSpec(\y, [0,11]); y.addHalo(\spec, x.getSpec); 
or you could share other parent specs between objects 
with 3 lines of custom code...

5. Semantic contexts - Halo generally allows adding a context of named sets 
of named objects to any object, which I find semantically really useful: 
one can keep flexible local variables close to the objects they belong to, 
instead of creating global dictionaries for each object that needs it by hand.


Personally, I find the Halo pattern general enough to be worth adding to Object; 
by comparison, adding support addSpec, getSpec/getUni/setUni methods 
to every new object that has a set of named numerical parameters seems 
a lot of code duplication, with all its downsides. 

Of course, transparent syncing of the SynthDesc specs handling and similar
to a single general spec handling mechanism (could be Halo or something better) 
would be really nice and useful. 

2c, adc

**Comment by telephon** [comment]
I'd just like to add: `Halo` is essentially a part of the introspection system of the object system. It is extra mutable data that *any* object can carry with it. In such a way it is a generalization of dependency schemes.

>Personally, I find the Halo pattern general enough to be worth adding to Object

We can't add an instance variable to every object, this would make too much overhead. What do you think about my two suggestions?

**Comment by LFSaw** [comment]
I am not the author of `Halo` but I use it, primarily for my livecoding. I have the following thoughts:


+ `Halo` makes it easy to associate `Specs` to any `Object`, which provides a much more transparent (and useful) interface for livecoding and dynamic prototyping, in which changing Specs on the go is a necessity.
+ `Halo` also adds the possibility to associate `Object`s to any `Object`. Especially in livecoding situations, it is useful to not have to deal with external data structures but have a space to work only with and around the central object (be it a `Synth`, a `NodeProxy`, a GUI or whatever).

IMHO such piggybacking, as introduced by many different systems (AFAIK, e.g., hjh developed a similarly capable structure for rapid `Class` development in his dewdrop lib) is a reaction of developers to one of the limitations of the OOP capabilities of the SuperCollider language: that of not being able to derive subclasses at runtime which could provide the necessary functionality in an individual case. Now we could start the discussion on which programming style is best but I'd rather have a proper analysis of what kind of functionality is actually _needed_/_asked_for_ by users. Let me offer a starting point (incorporating ideas and suggestions I heard around this theme):


+ The current `Spec` association system (`Spec.add`) is too limited (only global key/value pairs) and complicated to be used in an everyday livecoding environment. A common use case is therefore to provide functionality like this:

```
Ndef(\a).addSpec(\freq, [100, 3874, \exp]);
Ndef(\a, { LFPulse.ar(\freq.kr(100)) })

// change spec on the fly
Ndef(\a).addSpec(\freq, [100, 374, \exp]);


// have an independent spec for freq for a different Ndef
Ndef(\b).addSpec(\freq, [200, 38074, \exp])
Ndef(\b, { LFPulse.ar(\freq.kr(100)) })
```

You may interchange `Ndef` with `NodeProxy`, `SynthDef`, essentially with any Class implementing the `Synth:play` pattern.

+ When controlling Synths on the fly with a hardware controller (e.g. a MIDI controller), chances are high that the controller has input that sends relative information, i.e. for each delta turn of a knob, we get a value that corresponds to the distance turned, opposite to an absolute value. A popular though discontinued product example for this is the [BCR2000](http://modalityteam.github.io/controllers/behringer-bcr2000.html). To use a knob of such a controller, a state-saving mechanism needs to be in place, something where it sometimes makes sense to either associate it with the controller, or with the synth to be controlled. Here a set/get mechanism for any object to store an additional state comes in handy.

+ (via AdC) Sharing of specs - A familiy of objects to have the same dict of specs, as e.g. `obj.class.addSpec` adds to a class-shared dict; you could use the same spec dict for multiple objects:
```
x.addSpec(\y, [0,11]); 
y.addHalo(\spec, x.getSpec); 
```

**Comment by adcxyz** [comment]
> I'd just like to add: Halo is essentially a part of the introspection system of the object system. It is extra mutable data that any object can carry with it. In such a way it is a generalization of dependency schemes.  
> 
> > Personally, I find the Halo pattern general enough to be worth adding to Object  
> 
> We can't add an instance variable to every object, this would make  too much overhead. 

I did not mean to add an instance variable to Object; I just meant adding the set of Halo-related methods, addHalo/getHalo etc Object.

> What do you think about my two suggestions?

Not sure I fully get them - let me try: 

> 1. implement an intermediate level of object that has a slot for a halo (this can then also model dependencies). Such a class could serve as a superclass for any object that can change its state.

// Would that be something like this?
```ObjectPlus : Object { 
   var <halo; 
   addHalo { ... }
   etc ...
}
```
// And then decide which objects should be halo-able, and make them ObjectPluses? such as:
```
PatternProxy : ObjectPlus { ... }
```
That would hardcode which objects can be haloed, which may turn out an unnecessary constraint. 
E.g. Numbers may seem like things that will never ever need haloes, 
but maybe there is a context where it makes perfect sense to say:
```42.addHalo(\meaning, "The meaning of life, the universe etc"); ```


> 2. implement a transparent wrapper for object, using the `ExtendibleObject`, which carries a halo. This is only reasonable if we don't get much of an overhead for message passing. I can imagine that message forwarding is really fast, so perhaps this is a good way to go.

- message passing speed can be tested simply, no?
 
// would that be like this: 
```
ExtendibleObject { 
   var <object; 
   var <halo; 
    addHalo { ... }
    etc ... 
    getExt { this.}
   // and then the long list of redirects for every message implemented in Object to object?
}
+ Object { 
     wrapInExtObj { ^ExtendibleObject(this) }
    isExt { ^this.class == ExtendibleObject }
}
```
// and what would usage code look like? 
```
x = TaskProxy(); 
x = x.wrapInExtObj;
x.addSpec(\y, [0, 11]); 
// and how to do named lookup pattern? 
// With e.g. Tdefs, put the ExtObject in Tdef.all?
// always make Tdefs extensible by default?
Tdef(\x).wrapInExtObj; 
```

**Comment by telephon** [comment]
>That would hardcode which objects can be haloed, which may turn out an unnecessary constraint.

yes, I also find this not ideal.

>and what would usage code look like?

yes, just as you write, maybe we find a nice vocabulary for it.

>always make Tdefs extensible by default?

Good question. Yes, we could just add a method for all of those (unless we rewrite them all as ExtendibleObjects anyways :)

**Comment by LFSaw** [comment]
So is `ExtendibleObject` meant to collect all the stuff we're not willing to put into `Object`? If so, this seems to be more a shifting of the problem rather than a solution...


cheers
	Till

**Comment by telephon** [comment]
`ExtendibleObject` etc. introduce a new alternative to subclassing and to composition. Together with environments, they allow you to add any interface to every object addressed in the environment.

**Comment by adcxyz** [comment]
That is a very interesting idea!
Actually, if everything is redirected to the ExtendibleObject wrapper, they become indistiguishable:
```
a = Whatever().makeExtensible;
a.isExtensible; // true
// and doesNotUnderstand redirects to its internal halo-ish library:
a.singAndDance = { ... };
a.spec.freq = [0, 11].asSpec;
a.addHalo(\gui, XYZGui(a)); 
a.addHalo(\controls, \faderbox, MKtl(\uc4)); 
a.addHalo(\songs, \children, Pdef(\Mary_had));
```
This is really brilliant.

**Comment by telephon** [comment]
`a.spec` could even return an extendible object, so that `a.spec.freq` is redirectable ...

**Comment by adcxyz** [comment]
Happy to help working on a branch with this :-)

**Comment by telephon** [comment]
if you want to play around with the draft system: `Quarks.install("Neutral")`. The "low level" implementation is still a hack, but the rest works as it should.

**Comment by adcxyz** [comment]
Any help files and commented examples?  ;-)

**Comment by telephon** [comment]
No. But you can read the very clear source code and play with highly abstract examples that really work!

**Comment by telephon** [comment]
I didn't want to document something that is on the move. When we are getting closer to actually doing all this, I'm very happy to supply documentation.

**Comment by adcxyz** [comment]
ok, fphaire einugh.

**Comment by adcxyz** [comment]
Some tests of redirection speed with the List object (which is a wrapper that forwards): 
```
l = List.fill(100, { 100.rand });
a = l.array;

// redirection, no args
bench({ 10000000.do { l.size } }); // 0.676
bench({ 10000000.do { a.size } }); // 0.570

// redirection, one arg
bench({ 10000000.do { l.at(37) } }); // 0.91
bench({ 10000000.do { a.at(37) } }); // 0.67

// redirection, two args
bench({ 10000000.do { l.put(37, 42) } }); // 1.4 - 2.5 sec!
bench({ 10000000.do { a.put(37, 42) } }); // 0.66
```

**Comment by telephon** [comment]
Yes, this confirms that argument passing is our bottleneck.

 [I actually would like to know why exactly this is so]

This is why I supposed that method forwarding would be desirable - although I do not know how fast to would be.

 @scztt mentioned here https://github.com/supercollider/supercollider/issues/3467#issuecomment-360257395 that it would be possible.

The point would be that the other method would be called with exactly the same argument stack. In normal message passing the arguments are copied over.

**Comment by eleses** [comment]
For what's worth it, I liked Halo for the ability to "add fields" even if it's just really "on the side" to "dangerous to change" classes like Thread. See e.g. my mini-proposal to add a [`hasYield` check](https://github.com/supercollider/supercollider/issues/4642#issuecomment-599037452). I was a bit concerned that there's no obvious replacement for Halo already in the library. (Adding to Specs instead for hasYielded is of course possible, it just seemed a more awkward, if just maybe because of the naming..)

**Comment by telephon** [comment]
It will also allow to better decouple functionality and keep the base classes simple.

**Comment by telephon** [comment]
The main problem of the current version is that you have to have to release the halo explicitly when you want to forget the object. Like the current dependency model, this "breaks" garbage collection.

**Comment by eleses** [comment]
I think that's impossible to solve in general without hinting the garbage collector, like Java's `SoftReference` does.  There's some more interesting research in this area https://arxiv.org/abs/1610.04790

**Comment by telephon** [comment]
It would be useful to have weak references (I remember that I've had discussions about it for a long time).

But also without, it is solvable with abstract objects. If you have a delegator object (an object that forwards all messages received to its "inner" object), both objects can be garbage collected once they become unreachable. And you can add the halo to this delegator.

**Comment by eleses** [comment]
I see nobody mentioned this here (and for me it's an obscure feature I've just discovered), but there's an `ObjectTable` in the classlib already. And it turn out you can use almost anything as a _key_ in it, i.e. any object...

```
e = (foo: 2).addHalo(\toto, 47)
e.getHalo

// vs

ObjectTable.put(e, (fofo: 88))
ObjectTable.at(e)
```

ObjectTable just lacks some methods in Object to exploit this.

**Comment by telephon** [comment]
There is a Halo implementation that is garbage collected in the https://github.com/telephon/Neutral Quark (called `Halo2` for now). It'll be a bit of a longer rfc-process to  bring AbstractObject into the standard distro, but then we have a lot of improvements at once.

**Comment by adcxyz** [comment]
Halo is fine staying in JITLibExtensions.
