### ISSUE TITLE
sclang: implement sending Boolean types via OSC

### ISSUE THREAD

**Issue by dvzrv** [supercollider/supercollider#2887]
It would be very beneficial to implement sending Boolean types via OSC (currently they are implemented as integers), and if not to at least document it properly in the help files, so users will know what to expect.
Libraries such as liblo [implement Boolean types](http://liblo.sourceforge.net/docs/group__liblo.html) according to [OSC 1.0 specification](http://opensoundcontrol.org/spec-1_0) (sorry, v1.1 is currently 404).
To be able to communicate more fully, it would be very good to have Boolean types. As I'm a little unsure about to what extend SuperCollider actually implements OSC (and what specification), it would be very awesome to get some background on this as well.

**Comment by patrickdupuis** [comment]
The "OSC Communication" guide was updated 4 months ago. If you are using 3.8, you do not have these changes. 

Have a look at it here:
https://github.com/supercollider/supercollider/blob/master/HelpSource/Guides/OSC_communication.schelp

The section at the bottom called "OSC type tags and sclang" will be of interest to you.

**Comment by snappizz** [comment]
@dvzrv just for the record, i asked the osc people what happened to 1.1 and they said it was abandoned.

**Comment by snappizz** [comment]
this is already supported and documented by sending the character objects `$T` and `$F`.

**Comment by brianlheim** [comment]
Since that link may change (points to master-head), the gist of it is that sclang supports T/F/N/I tags inbound and converts T/F/N to 1/0/0 outbound. Not clear on what it does with I tags outbound, maybe you can't send them because `inf` is converted to a floating-point representation.

I am in support of this, but see the discussion about this on #1029. Since the only tag types needed for full compliance are `bfsi`, I think it's reasonable to add switches such that the extended tag types are only used when opting-in.

>this is already supported and documented by sending the character objects $T and $F.

That is incredibly unintuitive; why not support both? And I haven't seen it documented anywhere; could you please post a link?

**Comment by brianlheim** [comment]
Never mind, I just saw it while rereading.

**Comment by brianlheim** [comment]
I think there ought to be an open ticket for supporting optional automatic conversion to extended OSC types. The current system is problematic, because the tag type `c` is also used for sending individual characters, and that's what I'd expect `sendMsg($T)` to do.

**Comment by dvzrv** [comment]
@snappizz that is too bad! They should probably clarify it then.

> this is already supported and documented by sending the character objects $T and $F.

However, this doesn't seem to work at all (or do I have to use supercollider > 3.8?).
When I'm using something like

`
(
a = NetAddr("localhost", 50001);
a.sendMsg("/subscribe", $T);
)
`

to send to a liblo-based application, that is expecting "/subscribe" with a boolean parameter, the application receives the message, but there is no parameter.
Maybe I'm missing something crucial about how to use it?
Looking at the documentation, I read

> Chars are added as a raw type tag, appending no data to the OSC packet. This is needed to send code::$N:: (nil), code::$T:: (true), code::$F:: (false), code::$I:: (infinity/impulse). Be careful with this -- if the destination entity doesn't agree that the tag consumes zero bytes, the remaining part of the OSC message may be corrupted!
 
Does this make a lot of sense? How are other implementations handling this case? liblo is used in so many different software projects and it doesn't seem to accept zero byte tags apparently.
With which implementations was the above tested?

> That is incredibly unintuitive;

@brianlheim I agree.

**Comment by dvzrv** [comment]
For the record (thanks to Glen on the sc-users mailing list), my above example can be send, but (imho) it's unneccesarily complicated:

`
( 
a = NetAddr("localhost", 50001);
m = Int8Array("/subscribe".acii.extend(12,0) ++ ",T".ascii.extend(2,0)); 
a.sendRaw(m); 
)
`
This will also work properly, when sending to applications using liblo implementations.
I'll rename this issue to reflect the problem better.
I'd like this to be reopened and left open, until Booleans can actually be send like any other data type in NetAddr.sendMsg().

**Comment by jamshark70** [comment]
> However, this doesn't seem to work at all (or do I have to use supercollider > 3.8?).

I'm pretty sure I recall the mailing list discussion saying this is new in 3.9, and won't work in 3.8.

**Comment by totalgee** [comment]
@dvzrv: FYI there are a few errors in your example above: you missed the "newFrom"; typed "ascii" wrong; and also the ",T" should be extended to 4 bytes, not just 2 (each OSC "item" must have a length that is a multiple of 4, and for strings that must always include at least one 0 byte).

But the following does work fine in SC 3.8.0, which is what I'm using:

```
// The following two give the same result:
["/subscribe", $T].asRawOSC;
m = Int8Array.newFrom("/subscribe".ascii.extend(12,0) ++ ",T".ascii.extend(4,0));

// Try actually sending/receiving them (both work):
OSCdef(\sub, { arg msg, time, addr, recvPort; msg.postln; }, "/subscribe");
NetAddr.localAddr.sendMsg("/subscribe", $T);
NetAddr.localAddr.sendRaw(m);
```

Thanks to @snappizz for documenting the current behaviour (4 months ago), I wasn't aware of those Char shortcuts; much simpler than my raw message mangling! (-;

However, I agree it would be more intuitive if `true`, `false` and `nil` worked on their own, not being converted to Integer...but I suspect this was done because the integer type **must** be supported by all OSC implementations, whereas these extra type tags are optional (though I think most implementations people are likely to use will support them these days).  I think it would be reasonable (if well documented) to expect SC users to have to send `true.asInteger` or `false.asInteger` in the rare cases that the other end of their OSC connection didn't support these extra True/False tags.

**Comment by dvzrv** [comment]
@totalgee thanks, fixed!

This doesn't work on my end though. Not with SuperCollider internally, nor with my liblo-based application. Not with SuperCollider 3.8.0 or the latest development version.

While the Int8Array version from your above example works (receives `[/subscribe, true]`), the char based does not (receives `[/subscribe]`).

**Comment by dvzrv** [comment]
@totalgee oh, nevermind... I guess the char issue is actually a scvim issue (https://github.com/supercollider/scvim/pull/25)....
Sorry for the noise.

Nonetheless, I 2nd what you wrote about using `true`/`false`/`nil` directly in sendMsg() would be more intuitive and should be used instead of the character literals (it's cleaner and more readable, than the current indirect conversion from bool -> int).
