### ISSUE TITLE
Support for 14 bits MIDI in MIDIDef Class (Modality toolkit feature merge)

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2910]
# **Hi**

On my standing point, **we should take advantage of the fact that @sensestage  and the overall Modality toolkit team took the effort of implementing 14 bit MIDI in Modality Toolkit and implement it in Supercollider MidiDef Class**. @sensestage  @miguel-negrao @woutersnoei  @scztt  @snappizz  @brianlheim what do you think? i think **this can be a main advantage for supercollider**. please follow issue https://github.com/ModalityTeam/Modality-toolkit/pull/295 and **please do draw your comments**

**Comment by sensestage** [comment]
Initially I looked at how to implement it in MIDIFunc et all, but I couldn't quite wrap my head around how to go about it in that framework.

**Comment by tiagmoraismorgado** [comment]
well, hopefully we will all together sort that out

**Comment by LFSaw** [comment]
The feature was implemented in modality about 4 days ago and neither sufficiently nor extensively tested. Though I (as part of the Modality Team) appreciate your enthusiasm, I also think that we should take time with such steps. 
That aside, the implementation requires a specific setup within `MIDIresponder`s (or equivalent) to work and hence cannot "just" be merged into vanilla SC.

Whoever is eager to try is of course invited to install the Modality Quark or, to actually test this feature (that is currently not in master), clone the respective tree mentioned in https://github.com/ModalityTeam/Modality-toolkit/pull/295.

I therefore close this issue.

------

@tiagmoraismorgado , IMHO your excessive use of **boldface** does not necessarily make your contributions to github more readable. In fact, they look quite bloated to my eyes and I find it  quite exhausting to read. This might be personal taste, however, it seems that others agree with me (since they do not write in boldface all the time :) )

**Comment by snappizz** [comment]
@tiagmoraismorgado more importantly than boldface, *please never, ever, ever tag large numbers of people in comments*. this sends out annoying email notifications to people who may not be interested.
