### ISSUE TITLE
style: Semicolon after last statement of block

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#2914]
# Issue

SuperCollider gives the option of leaving off the semicolon for the last statement of a block. In the class library, which should we prefer?

### With semicolon
```supercollider
func {
    var value;
    value = this.multiplier * 3;
    ^value;
}
```

### Without semicolon
```supercollider
func {
    var value;
    value = this.multiplier * 3;
    ^value
}
```

**Comment by snappizz** [comment]
with. that way statements are reorderable.

**Comment by brianlheim** [comment]
I also prefer with-semicolon for that reason. I guess I always thought of it as a convenience to be able to omit a semicolon while prototyping or in one-line statements like `collection.do { |x| x.postln }`. But when it comes to more intentional development, I've been bitten several times by forgetting to add a semicolon to the former final statement.

I'd also like to add while we're having these discussions that another dimension to consider is strictness/stringency. For example, if we had categories of guidelines like recommend vs require, I'd say this one is a recommendation—it's worth knowing the preference is there, but it isn't a big deal if it's not consistently applied. #2913 is more of a requirement IMO because the syntax possibilities look so very different.

**Comment by telephon** [comment]
Unlike in other languages, in sclang, the semicolon is not part of a statement, but it is a delimiter *between* statements. In such a way, it is very similar to white spaces in a sentence. One would not write `I am so happy .` but `I am so happy.`  This is because `happy` is the word and not `happy `.

Expressions that are followed by a semicolon suggest that another expression follows. A function return value isn't followed by any other statement.

I'd recommend the following convention (in continuity with a tacit practice):

1. for functions that are not methods never add a trailing semicolon: this communicates that the last expression is intended as the function's return value
2. for methods, follow the same principle wherever the last expression is intended not to be followed by another one (e.g. if there is only one `return` statement). If there are several `return`s *and* the last one is not a fallback (but could just as much be amended by further ones), then and only then add a trailing semicolon.

But I agree that this is just a recommendation of clarity.

**Comment by brianlheim** [comment]
This reminds me somewhat of the discussion about trailing commas in C/C++:

https://stackoverflow.com/questions/7043372/int-a-1-2-weird-comma-allowed-any-particular-reason
https://stackoverflow.com/questions/29099517/why-is-an-extra-comma-not-allowed-in-a-parameter-list-when-it-is-allowed-in-a-br
https://stackoverflow.com/questions/6372650/trailing-commas-and-c

The arguments for and against are quite similar I think: in English, we normally don't write `the colors are red, green, blue,.` but `the colors are red, green, blue.` where you can imagine the `.` as the closing brace. On the other hand, when we are working with multiline statements, the difference between
```
red,
green,
blue,
```
and
```
red,
green,
blue
```
is that the first is easier to move around, plays nicer with git, and it's easier to add elements to the list.

I agree though that the meaning @telephon mentions above is lost by flatly adding semicolons to the final statement. In the conflict between what's easier to write and what's easier to read, I tend to lean toward what's easier to read.

**Comment by jamshark70** [comment]
I tend to agree with Nathan -- the ability to reorder statements is very nice.

BUT it's not really meaningful to reorder a `^return`, because, by definition, any statements you put after it are not evaluated. So it would seem silly to insist on `^return;` (and it seems there is not much pressure in that direction, good).

**Comment by telephon** [comment]
yes my point was that statements that semantically differ in such a way that they shouldn't be reordered also shouldn't have a trailing semicolon. This adds readability and discourages, well, reordering …

**Comment by brianlheim** [comment]
That makes sense, I'm leaning toward omitting `;`s using exactly the rules Julian mentioned [above](https://github.com/supercollider/supercollider/issues/2914#issuecomment-305886554)

**Comment by jamshark70** [comment]
I'll make every effort to comply in my contributions to the class library (just as I edited the indentation by hand in the C++ primitives I recently wrote, after emacs insisted on two-space indentation), but in my own code, I'll continue using semicolons throughout.

I don't see that the absence of a semicolon at the end of a function is a strong visual marker of a return value. One could be trained to read it that way, but it isn't self-evident in the way that, to me, the pipes are clearly, visually, delimiters in `|item|` but not so clearly in `| item |`.

**Comment by gusano** [comment]
> I don't see that the absence of a semicolon at the end of a function is a strong visual marker of a return value

:+1: I sometimes wish we could use `^` outside from Classes

**Comment by brianlheim** [comment]
> I don't see that the absence of a semicolon at the end of a function is a strong visual marker of a return value. One could be trained to read it that way, but it isn't self-evident in the way that, to me, the pipes are clearly, visually, delimiters in |item| but not so clearly in | item |.

I think this is a fair point, and since opinions on this seem to be mixed, I've migrated Julian's recommendation to the WIP style guidelines, but only as a recommendation: https://github.com/supercollider/supercollider/wiki/%5BWIP%5D-Code-style-guidelines#return-statements

I tried to capture the nuances of this discussion. I hope nobody feels like their toes have been stepped on!

If anyone has an idea for how to word the explanation of "recommendation" at the top of the document, feel free to edit.
