### ISSUE TITLE
Clean up traceback output

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2921]
if you happen to say supercollider: s.recorder, which happens to be a deprecated method, you will get a log saying something similar to:
```
ERROR: Message 'recorder' not understood.
RECEIVER:
Instance of Server {    (0x1153d9118, gc=E4, fmt=00, flg=00, set=05)
  instance variables [32]
    name : Symbol 'localhost'
    addr : instance of NetAddr (0x1153d6498, size=4, set=2)
    clientID : Integer 0
    userSpecifiedClientID : false
    isLocal : true
    inProcess : false
    sendQuit : true
    remoteControlled : true
    options : instance of ServerOptions (0x1153d9348, size=31, set=5)
    latency : Float 0.200000   9999999A 3FC99999
    dumpMode : Integer 0
    nodeAllocator : instance of NodeIDAllocator (0x12183b0e8, size=6, set=3)
    controlBusAllocator : instance of ContiguousBlockAllocator (0x120f247a8, size=5, set=3)
    audioBusAllocator : instance of ContiguousBlockAllocator (0x120b60fe8, size=5, set=3)
    bufferAllocator : instance of ContiguousBlockAllocator (0x121525b48, size=5, set=3)
    scopeBufferAllocator : instance of StackNumberAllocator (0x125b7e068, size=4, set=2)
    syncThread : nil
    syncTasks : nil
    tree : nil
    window : nil
    scopeWindow : nil
    emacsbuf : nil
    recordBuf : nil
    recordNode : nil
    recHeaderFormat : "aiff"
    recSampleFormat : "float"
    recChannels : Integer 2
    recBufSize : nil
    volume : instance of Volume (0x1153dab28, size=18, set=5)
    statusWatcher : instance of ServerStatusWatcher (0x1153d9578, size=20, set=5)
    pid : Integer 1629
    serverInterface : instance of ServerShmInterface (0x1242bc1f8, size=2, set=2)
}
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError   0x125cbe588
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError   0x125cbe428
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError   0x125cbcd08
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw   0x125cbcc58
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand   0x125cb9ee8
		arg this = <instance of Server>
		arg selector = 'recorder'
		arg args = [*0]
	Interpreter:interpretPrintCmdLine   0x1210c0098
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "s.recorder"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x125cba218
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'recorder' not understood.
RECEIVER: localhost
```

although extensive debugging information is relevant in a case like this, and many other cases, getting a message saying: `ERROR: Message 'recorder' not understood`, would be more then enough

it would be imporant to create two debugging menus: one for extensive debugging information, in this case, all the rest, once that's important for developers, but keeping a separate log for debugging where you just get a message saying `ERROR: Message 'recorder' not understood` which is what most users actually need to know

**Comment by brianlheim** [comment]
So is the complaint just that here is too much information, or that it is unclear in some way? I disagree with the idea of making this configurable; I can't imagine going very long without a call stack before having to use it in some way. Also, a call stack is not just useful for backend developers, it gives very important debugging information.

**Comment by snappizz** [comment]
there are a lot of incremental improvements we can make to these things. they are so long and noisy that i've actually been conditioned not to read them, and i do most of my debugging with `.postln`. here are some simple suggestions, in roughly increasing order of size.

the receiver section uses 2 spaces indentation and the call stack section uses tabs. i don't care too much about the decision, but it should be consistent.

the receiver section should use `=` instead of `:`. the call stack section doesn't need angle brackets around `<instance of Foo>`.

again in the receiver section, the notations for integers (`Integer 1629`) and floats (`Float 0.200000   9999999A 3FC99999`) are unnecessarily verbose. i think it is sufficient to simply write out the decimal representations, where floats have decimal points and integers do not.

all the `0x125cbe428` hex memory addresses (that's what they are, right?) should be off by default. also whatever the hell `gc=E4, fmt=00, flg=00, set=05` means, i think we can safely say it is useful to almost nobody.

does the call stack seem backwards to anyone else? i prefer chronological order since i grew up on python, but it might be subjective.

most of the stuff above `Object:throw` seems gratuitous, and i wonder if we could simply cut it out since it shows up in like 99% of tracebacks. should be configurable though.

**Comment by telephon** [comment]
I think it's OK to give some "expert information" also to beginners, they will learn more quickly that way.

But we could store the thrower object (or some error representation) in a global variable and make it easier to inspect it after the fact. Then we wouldn't need to dump the receiver (which is most of the call stack).

**Comment by brianlheim** [comment]
@snappizz Perhaps we should make individual tickets for a few of those? Configurability and cleanup seem like they deserve separate conversations.

**Comment by snappizz** [comment]
alright, here comes a lot of issues :smile:

**Comment by vivid-synth** [comment]
@tiagmoraismorgado this is a great example of something I've gotten so accustomed to I haven't thought to try and improve it!

**Comment by brianlheim** [comment]
I agree with vivid-synth, this was a good discussion to start! Since we have detailed issues now, I am going to close this more general one, but please open new separate issues if you think of any more specific changes you'd like to see.
