### ISSUE TITLE
help doc has outdated look

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#2943]
old school is nice, but design wise, the help docs are neither old school nor up to date. It would be good to update the css.

e.g.
http://doc.sccode.org/Tutorials/Getting-Started/02-First-Steps.html

**Comment by tiagmoraismorgado** [comment]
i had already pointed to this idea several times. and i honestly think it's something important to do.

**Comment by tiagmoraismorgado** [comment]
another thing that could honestly work out would be considering to bind a framework such as bootstrap or angular, to the supercollider documentation, to improve its overall look and feel.  there are plenty of good free templates on those frameworks in a site called css author https://cssauthor.com/ most are free and opensource. i think we could take advantage of some of the css present in the templates. to update the overall css of the supercollider documentation, by binding the css of several templates together. and using it to replace the current one

**Comment by tiagmoraismorgado** [comment]
or, at least to update the current one

**Comment by snappizz** [comment]
i kinda dislike the `position: fixed` top bar, seems sorta unnecessary. i'd prefer if it was just the default `position: static`. any thoughts?

**Comment by telephon** [comment]
the table of contents is practical to have when you have scrolled down a large document. The other things are not necessary maybe.

As it is now, it seems as if the navigation were part of the toolbar on top of it. The combination of the two doesn't look very well though out, more like a collision.

**Comment by snappizz** [comment]
agreed. i think it's not terrible to ask the user to scroll to the top to figure out what document they're on. ruby, python, and go docs do this.

**Comment by telephon** [comment]
right now I have the problem that I can't scroll anymore in the table of contents (try `Collection` for a long one).

**Comment by snappizz** [comment]
ah shit. i'll look into it.

**Comment by telephon** [comment]
#2968

**Comment by snappizz** [comment]
i think it's looking pretty great now. what do you think?

**Comment by telephon** [comment]
There are some tweaks that would be nice to have - but certainly the help looks very good now (and not outdated anymore!).

My personal wish-list:
- one extra step of carefully adjusting the font sizes (also headers relative to each other, and zoom)
- hide the sections Inherited methods and Undocumented methods.


And one minor thing: for infix operators like `+`, a space between it and its argument. If there is only one argument, possibly omit the brackets.

**Comment by telephon** [comment]
(and thanks!)

**Comment by snappizz** [comment]
> And one minor thing: for infix operators like +, a space between it and its argument. If there is only one argument, possibly omit the brackets.

i thought about th is when i was working on method rendering and decided to leave the brackets in for two reasons. first, if you omit them, imo it sacrifices too much clarity for brevity. a bare `+ x` on a line looks too obtuse to me. second, a good number of infix op methods take adverb arguments, and the decision to write `+(foo, adverb)` vs `+ foo` seems a little arbitrary/confusing to me.

there are two things we can do to repair this: first, add a left operand, like `number + foo`. second, we can recognize when there's an adverb, and display something like

> `number + foo` (`number +.<adverb> foo`)

this is fairly clear, but it seems too tricky to me. i prefer it the way it is now.

> one extra step of carefully adjusting the font sizes (also headers relative to each other, and zoom)

the headers look okay to me, but if you have some concrete suggestions i'd be happy to discuss.

**Comment by LFSaw** [comment]
thanks for looking into this!
small thing: 
+ padding for hover and visited is set to 1px whereas the "normal" measurement for padding in `.submenu a` is expressed as 0.2em (see attached screenshot). This results on my machine (in the sc helpviewer as well as in FF) in a weird "animation" when hovering over entries in the menu.
+  special pages "browse" and "search" still have the label `SuperCollider` in the upper left, whereas everything else says `SuperCollider 3.9dev`

otherwise awesome!

![screen shot 2017-07-30 at 13 22 59](https://user-images.githubusercontent.com/75468/28752889-3d25ce82-752a-11e7-8133-f3f5be79cfc4.jpg)

**Comment by snappizz** [comment]
@LFSaw 

> padding for hover and visited is set to 1px whereas the "normal" measurement for padding in `.submenu a` is expressed as 0.2em (see attached screenshot). This results on my machine (in the sc helpviewer as well as in FF) in a weird "animation" when hovering over entries in the menu.

good eye, i'll take care of it.

> special pages "browse" and "search" still have the label `SuperCollider` in the upper left, whereas everything else says `SuperCollider 3.9dev`

i'll see what i can do. that's not a simple omission -- the reason is that most help file pages are dynamically generated whereas those pages are static. but i'm pretty sure it can be hacked together with some javascripting.

**Comment by snappizz** [comment]
ok, unfortunately i just don't have the patience to deal the "SuperCollider 3.9dev" issue. it is just too annoying to fix.

**Comment by crucialfelix** [comment]
The pro way to set padding is to use something like `.25rem` — this means that the padding will be the same anywhere it used on the page. `.2em` would be relative to font size of the immediately enclosing block.

I like to always use paddings and margins of: 0.125rem 0.25rem 0.5rem 1rem 2rem 4rem  and then use that *everywhere*.  No fiddling or eyeballing. Just stick to the geometric series based on the document's base font size. If you think you want 1px because it is small then use .125rem instead

Also: [there is no such thing as a pixel anymore](https://medium.com/@julienetienne_/pixels-are-dead-faa87cd8c8b9).

**Comment by brianlheim** [comment]
Can we close this issue?

**Comment by snappizz** [comment]
yeah we're good :)
