### ISSUE TITLE
adding tutorials to the supercollider package on how to generate graphics with supercollider

### ISSUE THREAD

**Issue by ghost** [supercollider/supercollider#2949]
topIc - adding tutorials to the supercollider package on how to generate graphics with supercollider

Hey everyone

It's probably known by many of us here, that supercollider is capable of generating graphics (for example, using native opengl support; there were also bindings to quartz composer, but those are, at the moment, deprecated, otherwise using osc - opensoundcontrol). I would like to suggest that:

- We consider to include in the default supercollider package some examples on how to deal with opengl graphics inside supercollider

There are some books available on this topic, so if someone has access to those, or if the authors can provide the code, it would possibly be easy to include those in the default supercollider budle.

looking forward to hear your feedback
kind regards
T. (Tiago)

**Comment by snappizz** [comment]
do you mean tutorials for UserView/Pen? we already have some introductory materials on those.

**Comment by tiagmoraismorgado** [comment]
no, i mean more advanced stuff with opengl, which is perfectly possible. 
a greek guy released a book on the topic a while ago. 
i think one of the guys who reviewed the book was joão martinho moura,
portuguese digital media artist, working with processing/openframeworks + ableton/supercollide
you should be able to find the book that way, and, who knows, asking the guy to include some of the code examples in the main supercollider repository

**Comment by tiagmoraismorgado** [comment]
i just opened a PR on the Pen class documentation

**Comment by LFSaw** [comment]
please do link the related PR to this issue by means of GH's link support. (add this issue's #<number> to the PR description)

**Comment by SaccoSVD** [comment]
I'm right now working on animations for one of my projects and just 10 UserViews with one object each in a 1080p is running slow. Even if it barely uses any CPU. (yes I want it 1080 fullscreen)

I'm looking for a way to accelerate 2D imaginery...was hoping for some kind of OpenGL capability to use my GPU instead.

Does anyone knows?

Here is a pastebin of what I'm at now. (bottom of the code)

https://pastebin.com/iFCbjwCe

**Comment by joshpar** [comment]
First - this isn’t really SC’s strong suit. Using something like a Processing would make more sense.
However, if you do want to do this in SC, there is a lot of optimization you can be doing. I see a lot of math being done twice, rather than being stored to a variable and reused. I see:

    Pen.strokeRect(Rect.aboutPoint(Point(
        sin(40*(sin(~u1.frame*0.1908 )*0.1+0.1))*4+950,
        sin(20*(sin(~u1.frame*0.1908 )*0.1+0.1))*4+480),
    sin(100*(cos(~u1.frame*0.1908 )*0.1+0.1))*4+50,
    cos(80*(cos(~u1.frame*0.1908 )*0.1+0.1))*4+120));

~u1.frame*0.1908

Could be stored to an var, then the sin of that could be as well, and reused (as well as the cos). Those values * 4 could be, etc

When you run into performance issues, steps like these are needed to try and reduce the number of operations happening in a code block. This is a first pass - optimize your code. It’s much easier to do, and then if you still have problems, the idea of porting it to another language or trying to figure out how to make the SC GUI system run on the GPU is what you look for when that doesn’t work. That is a much larger task, and one that (as I mentioned in my first point) I think would be better suited to a language / domain that is built to be optimized for visuals.

I hope that helps - good luck!


/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by SaccoSVD** [comment]
I optimized it a lot. I figured out I was using too many Userviews.

Thanks for the suggestions as well, very useful :)

**Comment by SaccoSVD** [comment]
Sorry I deleted my original comment before refreshing and finding your answer.

**Comment by brianlheim** [comment]
there doesn't seem to be much interest in this, and the original reporter is no longer around, so i'm going to close it.
