### ISSUE TITLE
including scott wilson's book tutorials as part of supercollider package

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#2961]
hey guys
i think a really nice thing, would be to grab the examples of supercollider book by scott wilson and nick collins (i think those are opensource and available online), and making some tutorials based on that, for supercollider, so giving the full code examples, and commenting out those a little bit (of course with the permission of scott himself). i think those are one of the most comprehensive resources available for people willing to learn supercollider, and it's a pitty if we don't include those

**Comment by brianlheim** [comment]
If i'm understanding correctly, you want an extra 17 MB of examples/code in the repo? and then also have this repo's maintainers responsible for making sure that code is up to date and usable? makes no sense to me. it's a separate project, and this repo is _not_ the compendium of all SuperCollider-related ideas and resources.

i think that needs to be made clear: _we are not collecting all SuperCollider resources here just to make things easier for users_.

OTOH, I would welcome a one-line PR to add a link in the documentation to that site so that people can download the code themselves and decide whether they need an extra 17 MB of examples on their hard drive.

**Comment by tiagmoraismorgado** [comment]
hey @brianlheim  i just created a PR on the schelp file. please help me to review it. looking forward. T. (I think i will do the same with the opengl examples, by pointing the book on the documentation)

**Comment by LFSaw** [comment]
please do link the related PR to this issue by means of GH's link support. (add this issue's #<number> to the PR description)

**Comment by LFSaw** [comment]
AFAICS, you are referring to this PR  #2962 which is closed since 7 days without follow-up reaction.
Since this minor issue seems to be dead since 18 days, I'll close.
