### ISSUE TITLE
Default install directory is /usr/local

### ISSUE THREAD

**Issue by kisielk** [supercollider/supercollider#3037]
I followed the compile instructions in `README_MACOS.md` where it states 

```
If successful this will build the application into `build/Install/SuperCollider/`
```

However the build instructions given in the readme file attempt to install to `/usr/local`, which fails due to permissions. I had to set `-DCMAKE_INSTALL_PREFIX=./Install` to have it work as the instructions state. 

I'm not sure which of the instructions or the build file are wrong.

**Comment by brianlheim** [comment]
@kisielk thanks for the report!

 Can you please try again from a clean build folder, and make sure all submodules in the repo have been initialized first? In the previous case I'm thinking of, the issue was that the user had performed the config phase before initializing submodules; after they had been correctly initialized, the CMake cache still considered `/usr/local/` to be the install target.

**Comment by kisielk** [comment]
Removing the build directory and starting over seems to have worked.
