### ISSUE TITLE
SCIDE: Tab menu appears in the wrong position on MacOS

### ISSUE THREAD

**Issue by kisielk** [supercollider/supercollider#3042]
When I right-click on an editor tab in the IDE on MacOS the menu appears in a totally different location.

![screen shot 2017-07-16 at 15 33 23](https://user-images.githubusercontent.com/58618/28251917-450b2aaa-6a3c-11e7-84ba-e557a665082f.png)

The example here is after I right-clicked on the "template.scd" tab. Actually it doesn't matter which position on screen the IDE is, the menu always appears in that same spot.

**Comment by telephon** [comment]
Seems fine here (Macos 10.11.6), fresh build on master.

**Comment by jamshark70** [comment]
@kisielk Did you build yourself or use a package?

Which Qt version?

I'm asking because I've seen menus pop up in the wrong screen location in Linux, but that was probably a weird interaction between a Qt version and a window manager version that was not right for the Qt version. (I ended up in a weird place in my previous Linux environment from trying to work around some problems incrementally.) I don't know if it's relevant to your case or not, but it's a possible cause, if something is "off" about the Qt on your system.

**Comment by brianlheim** [comment]
I also experience this. The context menu appears offset from the _screen bounds_ at the same x and y offset that it should be offset from the _window bounds_.

This is built from recent master on macOS 10.12, with Qt version 5.5.1

**Comment by kisielk** [comment]
I have the same setup as @brianlheim

**Comment by telephon** [comment]
ah now I can reproduce this. I need to move the window around to see it.
