### ISSUE TITLE
please consider to take quartz composer integration out of deprecation, by maintaining it

### ISSUE THREAD

**Issue by tiagmoraismorgado** [supercollider/supercollider#3111]
please consider to take quartz composer integration out of deprecation, by maintaining it. this would be a great add-on for supercollider audiovisual capabilities

**Comment by jamshark70** [comment]
Who is going to do the work?

**Comment by joshpar** [comment]
@tiagmoraismorgado - do you know if QT has hooks available for this?

**Comment by muellmusik** [comment]
Huh? First, there is already a Qt QuartzComposerView, and has been for years. (I did it with a lot of generous help from @jleben.) 

Second, AFAICS it's not deprecated, so? 

There has been some question if Apple will continue to support it, but it still seems to work in 10.12.

If it's broken, file an issue.

**Comment by jamshark70** [comment]
@muellmusik Thanks for the clarification -- I never used QC so I hadn't even thought to look for it.

@tiagmoraismorgado  There is no reference to "quartz" anything in the deprecated/ folder.

Closing.

**Comment by tiagmoraismorgado** [comment]
https://vimeo.com/229303294 as you can see in this video i took the effort of recording, quartz composer is not supported anymore on supercollider. i think the problem appeared with the implementation of the new IDE, but I am not entire sure about this.

**Comment by redFrik** [comment]
you must be doing something wrong.  quartz composer works perfect here (osx 10.12.6, sc3.9dev).  see this for example http://fredrikolofsson.com/f0blog/?q=node/609

**Comment by tiagmoraismorgado** [comment]
thanks for the insights on the problem. i already figured out where the problem is. 

the problem is on the way as the Platform.helpDir method is set which returns -> /Volumes/DATA/data/Nova pasta com elementos/SuperCollider/SuperCollider.app/Contents/Resources/Help/QC/Cells.qtz, where what should be returned is "/Volumes/DATA/data/Nova pasta com elementos/SuperCollider/SuperCollider.app/Contents/Resources/HelpSource/QC/Cells.qtz" 

so i guess i know what is wrong with the whole thing. the help folder name has been updated from help to help source, and the same didn't happen with the Platform.helpDir which is still returning help. 

as a matter of fact, the way as all the examples are written returns something wrong. it should return  HelpSource/QC/Cells.qtz and it is returning Help/QC/Cells.qtz and as a matter of fact the quartz composer patches don't load

**Comment by tiagmoraismorgado** [comment]
my 50 cents for sorting the problem out

**Comment by tiagmoraismorgado** [comment]
dear professor @muellmusik scott wilson, the whole supercollider owes you, and owes people like josher and timblechman and fredrik and jakob a lot. also to brian from yale university, who in less then 1 year has given more to supercollider then probably i will give in ten years. hopefully when it comes to open source projects, or anything in life, listening to each other, accepting each other feedback, being assertive, and giving meaningful insight for the development of a project is crucial. i am sorry if i was below spectations of community at any point

**Comment by jamshark70** [comment]
> hopefully when it comes to open source projects, or anything in life, listening to each other, accepting each other feedback, being assertive, and giving meaningful insight for the development of a project is crucial. i am sorry if i was below spectations of community at any point

I didn't want to let this pass without comment, because it's an ongoing concern for the better part of a year now, at least.

"listening to each other, accepting each other feedback" -- the other part of it is *acting on* feedback. Tiago, I'm sure it must be frustrating for you to offer suggestions and proposals, and encounter a lot of resistance. However, much of the resistance is because the suggestions and proposals keep repeating the same kinds of mistakes. It's not enough to listen to feedback. You need to *do* the feedback.

For example, you've been asked at least five times in the last few months not to boldface your comments... but, two days ago: https://github.com/supercollider/supercollider/issues/3111#issuecomment-321875865 -- it's all in bold. Feedback, ignored or forgotten. That's not the only thing, just one example. Try to put yourself in Brian's position -- giving advice, and then seeing the same problem again. That's frustrating too.

For making pull requests, it helps a lot to be detail-oriented. You seem not to be very detail-oriented. That's not a bad thing in itself -- maybe you're more of a "big ideas" person. But it does mean, if you want to submit a PR, you should take more time than you think to check and doublecheck for mistakes. Even here on this screen, I see a reference to an issue "fixing bug with helpir method (updating path)" -- `helpir`, should be `helpDir`. Sure, everybody makes mistakes sometimes, and it's a nice thing in git that there is often a way to fix them. At the same time... a 7-word description... it's not too much to check it before hitting "go."

I'm going to take a guess -- it seems, Tiago, like you might be looking for some validation, like contributing something (*anything*) to this project would prove that you're a valuable person. It's a good intention, but this community isn't here to make people feel better about themselves. It's here to make the software better. That's a gift to the user community, no need to repay it. Please enjoy the software, and if you have ideas, comments or changes, I hope you can feel comfortable enough to slow down. There's no rush, no urgency for you to give anything back. You don't have to fire off an issue or PR *right now*. Take a little more time. *One* high-quality, nicely researched issue report will do more to contribute than 20 fast and sloppy issues/PRs. Really. Slow down. Nobody expects you to prove anything. Take it easy. Slow and careful. That works better.

I guess I'm taking a little risk by writing this, but I also see the same kinds of PR feedback coming into my inbox over and over again, and I'm hoping to find a supportive way to get to the heart of it. Apologies if I missed the mark in some way.
