### ISSUE TITLE
Rewrite UnitTests to avoid using audio hardware

### ISSUE THREAD

**Issue by nhthn** [supercollider/supercollider#3133]
travis doesn't let us use audio hardware.

the tests that make noise are cute but, aside from being un-runnable on travis, they don't control for sample rate and blocksize either. also they would be much faster if NRT.

server tests could be rewritten by mocking the scsynth process.

**Comment by josiah-wolf-oberholtzer** [comment]
Very curious about the (im)possibility of audio tests on Travis. Has anyone ever heard of a project running on that platform that has been able to use Jack in some kind of "dummy" mode?

This project appears to use Jack on Travis, but I haven't been able to verify that it really works, or works to the extent that SC could benefit from their technique: https://github.com/RustAudio/rust-jack/blob/master/.travis.yml

**Comment by vivid-synth** [comment]
I'm also very interested in the "mocking the scsynth process" concept. I wonder if we can just use a subset of the server code, keeping things as similar as possible?

**Comment by snappizz** [comment]
@josiah-wolf-oberholtzer if it is possible, then i'd be very interested to know how. the main point here is that most of the tests (in particular the ugen ones) invoke a real-time server when they don't need to do so at all. using NRT reduces moving parts in the test suite.

@vivid-synth i don't have a really specific plan in mind for that, we probably need to do make some more concrete progress first

**Comment by josiah-wolf-oberholtzer** [comment]
@snappizz Sounds like a good plan overall, and probably easier to analyze the resulting soundfile to prove that audio was processed as expected.

If `scsynth` had a built-in dummy mode, with no hardware interaction, verifying the status of the server tree in realtime might be easy, but no idea how hard that would be to set up in the first place.

**Comment by Sciss** [comment]
If someone implements "New NRT" with interface compatible with real-time, you have the test server for free. Just saying... :)

**Comment by LFSaw** [comment]
related to  #3132

**Comment by josiah-wolf-oberholtzer** [comment]
I now have realtime`scsynth` (the 3.6.3 that comes with Ubuntu) booting successfully under Travis-CI and responding to OSC messages for the test suite of my project https://github.com/josiah-wolf-oberholtzer/supriya.

See https://travis-ci.org/josiah-wolf-oberholtzer/supriya/builds/338803410 lines 455 through 847 for the general process.

Note that my test suite doesn't pass, although many tests that involve realtime scsynth do. A lot of that's work I need to address. However, scsynth does appear to crash a few times. It's not clear to me if that's because of the ancient scsynth provided by Ubuntu, the Travis-CI environment, or some combination.

I'm not sure I'm capable of fully explaining _why_ this works, but the basic process is this:

- `sudo usermod -a -G audio travis`
- `sudo apt-get update -qq`
- `sudo apt-get install -y alsa-oss alsa-utils graphviz jackd libasound2-dev libjack-dev libjack0 portaudio19-dev supercollider`
- `sudo bash tests/prep-dummy-soundcard.sh` (see [this file](https://github.com/josiah-wolf-oberholtzer/supriya/blob/20419eab2aa546dceef4320dd1151b3703c652ce/tests/prep-dummy-soundcard.sh))
- `export DISPLAY=:99.0`
- `sh -e /etc/init.d/xvfb start`
- `sleep 5` (give xvfb time to start)
- `sudo -E su $USER -c "jackd -r -ddummy -r44100 -p1024" &`
- `sleep 5` (give jackd time to start)
- `sudo -E su $USER -c "scsynth -D 0 -H dummy -R 0 -u 57110" &`
- `sleep 5`
- `killall scsynth`

**Comment by brianlheim** [comment]
Thanks again to @josiah-wolf-oberholtzer for figuring that out and documenting it (Josiah, do you have any updates/caveats to add now?). Since there appears to be a solution for this, could we update this to "Allow travis to boot scsynth" or merge this with the related issue #3132 ?

**Comment by brianlheim** [comment]
no longer an issue now that we are using GHA
