### ISSUE TITLE
SimpleNumber has a roundUp, but no roundDown

### ISSUE THREAD

**Issue by cianoc** [supercollider/supercollider#3169]
Which seems a little odd.

There's a simple solution for this. Just create a new roundDown that essentially looks like this:
```
roundDown { arg aNumber=1.0, adverb;
  ^roundUp ( -1, adverb);
}
```
My question is is this a good idea? Would it be better to create a primitive (which from looking through the code is no small thing in this instance), or is the extra function call essentially to insignificant to matter here?

**Comment by jamshark70** [comment]
SimpleNumber has both `trunc` and `floor`.

```
1.8.trunc
-> 1
-1.2.trunc
-> -2
```

There is no need for roundDown because the functionality already exists.

(Well, for that matter, there's no need for roundUp because of `ceil`. So, maybe a better fix would be to deprecate roundUp -- clean up the interface, rather than make it messier.)

I vote to close.

**Comment by jamshark70** [comment]
Deleted previous comment, sorry for noise. I had mentioned `floor` and `ceil` but those do not allow you to specify the resolution, so they aren't relevant for rounding.

BUT `trunc` is still the companion to roundUp:

```
1.8.trunc(0.7)
-> 1.4
```

(That is, 1.8 has been "rounded down" to the next lower multiple of 0.7.)

I'd say it's a documentation issue -- roundUp should point the user to `trunc`.

I would argue strongly against introducing new method selectors for functionality that already exist -- we already have enough of a problem of "too many ways to do things."

Also, I think the above implementation of `roundDown` is incorrect because it loses the resolution specifier `aNumber`.

**Comment by cianoc** [comment]
Yes you're right about the implementation of roundDown - always test your code.

But the point about trunc is valid. I'll update the documentation instead.
