### ISSUE TITLE
TextView:enterInterpretsSelection only interpets last line of selection 

### ISSUE THREAD

**Issue by LFSaw** [supercollider/supercollider#3279]
```
(
t = TextView(bounds: Rect(300, 400));
t.string = "1.postln;\n2.postln";
t.enterInterpretsSelection = true;
t.front;
)
```
select all and evaluate e.g. with ctrl-return.
This should result in 

```
1
2
-> 2
```

does result in

```
2
-> 2
```

**Comment by LFSaw** [comment]
@jamshark70 maybe you have an idea? I found #1637 and the related PR...

**Comment by jamshark70** [comment]
Not really... that was more than two years ago, and I don't really have time today to dig into the source code.

I can confirm that it's using textual linebreaks, rather than semicolons or some other criterion. Changing the reproducer as follows gets a syntax error, because the only string being submitted to the interpreter is `.postln`.

```
(
t = TextView(bounds: Rect(300, 400));
t.string = "1.postln;\n2\n.postln";
t.enterInterpretsSelection = true;
t.front;
)
```

Anyway, yeah, this is definitely wrong behavior. "Selection" should mean the selection, not the last line of the selection.

**Comment by jamshark70** [comment]
Related:

```
TextView(nil, Rect(800, 500, 300, 200))
.string_("1 + (2*3)  // select in parens and ctrl-enter")
.enterInterpretsSelection_(true)
.front;
```

Prints 7.

If you have selected only `2*3`, it should print 6.
