### ISSUE TITLE
string.compare producing non-documented results

### ISSUE THREAD

**Issue by Beechside** [supercollider/supercollider#3309]
I understood `"abc".compare("ABC")` should produce -1, 0 or 1.  However, it returns 32.  Checking further:

`"abc".compare("abd")` gives -1
`"abc".compare("abe")` gives -2
`"abc".compare("abf")` gives -3

I'm assuming this is a bug, rather than a documentation error.

SC 3.9dev, Mac OS X 10.13.1

**Comment by jamshark70** [comment]
https://github.com/supercollider/supercollider/blob/develop/lang/LangPrimSource/PyrStringPrim.cpp#L523

The string comparison primitive delegates to the operating system's implementation of memcmp. Possibly it should sanitize the output (return the sign only), or possibly the documentation is wrong.

I would have assumed that the only relevant characteristic of the `compare` result is `< 0`, `== 0`, or `> 0`. I would not have assumed it would be exactly magnitude 0 or 1. I'm surprised the documentation claims otherwise.

**Comment by brianlheim** [comment]
I think this is a documentation problem. If you need exactly -1 and 1 just add .sign. In many languages string comparison works the exact same way, and IMO there is really no problem with that because as James said you should be fine just checking the sign of the output most of the time.

**Comment by Beechside** [comment]
I'm all for consistency between languages.  Quite happy to use `.sign` so perhaps this should be flagged for a future documentation change...
