### ISSUE TITLE
jackd problems starting server on Ubuntu 16.04

### ISSUE THREAD

**Issue by ionakathryn** [supercollider/supercollider#3321]
I posted earlier about not being able to install the latest v of supercollider. I've now managed to install version 3.9.0-beta1. 

I'm trying to make some sound and when running:
`Server.local.boot;`

getting what seems to be a jackd error message, see below - can anyone help solve this?

```
booting server 'localhost' on address: 127.0.0.1:57110
jackd 0.124.1
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details

JACK compiled with System V SHM support.
loading driver ..
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
could not initialize audio.
RESULT = 0

```
Thanks

**Comment by ionakathryn** [comment]
the attached image shows the setup of jackd
![screenshot from 2017-12-03 16-28-43](https://user-images.githubusercontent.com/16601596/33527358-1bbf2204-d847-11e7-8030-70794e66da26.png)

**Comment by patrickdupuis** [comment]
This is likely a JACK or a system configuration issue. I see from the photo that QJackCtrl is installed. That's great. Can you try and start JACK using this application? If JACK is unable to start, press the "Messages" button and post what it says here so that we can see what might be causing JACK to fail.

Also, can you check to see that your user is a member of the `audio` group? You can check this by opening a terminal and typing `groups`. If not, you will need to add yourself to that group in order for JACK to use realtime scheduling. There's some info about on the JACK website: http://www.jackaudio.org/faq/linux_rt_config.html
```

**Comment by snappizz** [comment]
tangential -- is there a way to configure scsynth so that it doesn't automatically boot JACK when JACK isn't around?

**Comment by patrickdupuis** [comment]
Not that I'm aware of... Would that be useful? I suppose it could be good to tell users that they need to start JACK before SC can boot. I don't know what others think (@jamshark70). Is it considered a best practice on Linux to start JACK outside of SC?

**Comment by miguel-negrao** [comment]
Idealy I think that if the system uses jackd with dbus support, scsynth should start the server via dbus. It's very annoying for users who use jackd with dbus to have scsynth start the jackd instead of jackdbus.

Personally I start jack from sclang with:

```
namespace.start_jack = {
			"testing if jack is running".postln;
			if( "jack_control status".unixCmdGetStdOut == "--- status\nstopped\n" ) {
				var f;
				"starting jack".postln;
				"jack_control start".unixCmdGetStdOut;
				f = { |i|
					if( i > 0 ) {
						if( "jack_control status".unixCmdGetStdOut != "--- status\nstarted\n" ) {
							0.5.wait;
							f.((i-1).postln);
						} {
							"jack started".postln;
							true
						}
					} {
						"jack didn't start".postln;
						false
					}
				};
				f.(10)
			} {
				true
			}
		}
```

Regarding the issue here, the user should first be able to play sound through jack using VLC or something of the kind, in order to first sort the issues with jack, etc. A very complete guide for audio config in linux is available [here](https://wiki.linuxaudio.org/wiki/system_configuration).

**Comment by ionakathryn** [comment]
Jack was telling me to add the user to the audio group so i did this. Will check also by typing groups though. What is the command for running JACK @patrickdupuis ? I will try this then let you know the results. 

Thanks for your advice and help.

**Comment by miguel-negrao** [comment]
If you want to use jack with dbus (my preference):

    jack_control start

if you don't want to use dbus check [here](https://wiki.linuxaudio.org/wiki/recommended_jackd_parameters).

I recommend using Cadence as the gui manager. See [here](http://libremusicproduction.com/articles/demystifying-jack-%E2%80%93-beginners-guide-getting-started-jack).

**Comment by jamshark70** [comment]
I'm going to stay (mostly) out of this because my JACK setup works for me, but it isn't "correct" (doesn't use dbus).

I tend to think it's better to start JACK before booting the server. If scsynth starts JACK, then JACK uses whatever configuration and you might not have control over it.

**Comment by miguel-negrao** [comment]
> I'm going to stay (mostly) out of this because my JACK setup works for me, but it isn't "correct" (doesn't use dbus).
> 
I didn't say either option was more correct... I just stated my personal preference. :-)

> I tend to think it's better to start JACK before booting the server. If scsynth starts JACK, then JACK uses whatever configuration and you might not have control over it.

jackd It will use the config from ~/.jackdrc or /etc/jackdrc if that doesn't exist.

**Comment by patrickdupuis** [comment]
If you want to try and see if using JACK2 will help, all you need to do is install the package `libjack-jackd2-dev` and that should replace your JACK1 install with JACK2.

```sudo apt-get install libjack-jackd2-dev```

**Comment by patrickdupuis** [comment]
Closing since this is likely a system configuration issue related to JACK and not SuperCollider specifically.

**Comment by doconnell199** [comment]
This might well be a system configuration issue but I have spent almost a week and failed getting jackd to run with supercollider with out of the box ubuntu 16.04 and Elementary (also based of 16.04)

If supercollider doesn't just work out of the box with the mainstream user focused distro long term supported distro  (even if it is Ubuntu fault) then it reduces the potential supercollider userbase who just give up ... or move to windows where it does work out of the box.

I want low latency as much as the next guy ... but I also value my time and endless futzing with jackd is not a value add for me.  I don't think I am the only one

Pulse audio regardless of peoples opinion on it is  now the defacto default and I think supercollider would be better for supporting it.  Preferably as a run time switch user option, and not a compile option. Then if a "professional audio user" really wants lowest possible latency they can futz around with jackd to their hearts content letting the rest of us enjoy supercollider with zero configuration worries.

I think your are limiting your userbase.

**Comment by miguel-negrao** [comment]
Besides latency and output channel managment I suspect there are further problems with pulseaudio... I don't think that the fact that no professional audio app uses it is out of stuburness...

**Comment by doconnell199** [comment]
Yes I do agree with that, and indeed pulse audio was pretty rough around the edges several years back but as it has now the defacto distribution standard and it is robust and seems to be in the "just works " category of software, which jackd is definitely not, even after 15 plus years.

Not saying supercollider shouldn't use jack of course but that that it should offer pulse audio as the  "just works" out of the box  option. The really "enthusiastic" can futz with jack to optimize if so inclined. 

I actually came close to giving up on supercollider because of jackd. However I got jack working in the end but for my uses I didn't consider jack worth the effort and would have rathered used supercollider regardless of optimum latencies offer by jack.

Originally I was using Supercollider on Windows but  Windows version doesn't offer serial port support, (want to talk to an Arduino board) which forced me to Linux

For what it's worth to other people, to get it working on Ubuntu 16.04 and derivatives. Run jackd  manually by first suspending  pulse audio via pasuspender. Also jack seems to have problems with the capture interface for some devices,  so the jackd option -dhw:0 is replaced with -Phw:0 so it works just as a playback device only.

>killall -9 jackdbus
> pasuspender -- jackd -v  -dalsa  -Phw:0  -n2

**Comment by jamshark70** [comment]
JACK is fine. I've only ever seen JACK *just work*. (For instance, I was recently trying a modular synth package, VCVRack. Out of the box, audio was a disaster. But when I compiled it myself with "experimental, not-officially-supported" JACK support, everything was clean.)

What does *not* work seamlessly is the way that dbus is "supposed" to suspend PulseAudio automatically so that JACK can get the soundcard, but it doesn't always do that.

I recommend Ubuntu Studio over vanilla Ubuntu, for audio work. They've done a lot of the audio configuration for you. But I can't speak to the behavior of dbus there, because I don't use dbus. I run PA through JACK instead -- my system has no audio capability at all until I start JACK, but after that, every app works. (I can have audio in Firefox and scsynth at the same time, which I think you don't get even with a working OOTB jackdbus setup.)

**Comment by miguel-negrao** [comment]
> Yes I do agree with that, and indeed pulse audio was pretty rough around the edges several years back but as it has now the defacto distribution standard and it is robust and seems to be in the "just works " category of software, which jackd is definitely not, even after 15 plus years.

In audio, "just works" means audio just comes out perfect, no drop-outs, no play rate fluctuations. If that is indeed the case with pulseaudio, and if latency was acceptable for live playback, then I would also be all for using pulseaudio  with supercollider. 99% of the time I don't need to use jack audio routing system I just need supercollider outputs direct to my soundcard.  The question is if pulseaudio is glitch free for a heavy audio software like supercollider. Is it ?

> I was recently trying a modular synth package, VCVRack. Out of the box, audio was a disaster.

Was this with pulseaudio ? If that is the case then it is confirmation that pulseaudio is not reliable. 

After properly configuring jack and your linux system jackd is completely reliable. I have pretty-much almost zero drop-outs. In my case I did need to use a realtime kernel and configure irqs, turn off some of the CPU frequency scalling, turn off hyperthreading, etc.

**Comment by jamshark70** [comment]
> > I was recently trying a modular synth package, VCVRack. Out of the box, audio was a disaster.

> Was this with pulseaudio ? If that is the case then it is confirmation that pulseaudio is not reliable.

No. IIRC it was the PortAudio library connecting directly to ALSA, bypassing PulseAudio.

Ironically, with that dev, I made the same argument as here -- "You're limiting your user base" :lol: -- but based on the fact that it doesn't follow the standard of other Linux real-time audio software, and its actual performance is worse than the standard.

**Comment by doconnell199** [comment]
Can't supercollider users of all audio religions have their cake and eat it?

Ubuntu 16.04 does not work out of the box due to the aforementioned jackdbus issues.  (plus I also hit the jackd capture bug). It is probably the most mainstream distribution and supercollider should just work with no configuration faff. It took me almost a week, to get it to work. Maybe just me (but forums suggest otherwise) but how many people really care about understanding the multitude of underlying Linux audio apis and how they interact and step on each other toes before they can get supercollider up and running. 


Even if pulse audio is not perfect, which I won't deny at least let supercollider work first out of the box on Ubuntu and then let people if they become deeply involved start to get concerned with latencies and then move to jack if they care. I suspect many won't and supercollider has lost people due to this. It is of course impossible to measure how many people gave up as it is measuring a negative. Anyway for what its worth I came close to giving up, got it working in the end, but I just don't think it should be this way. It was way too hard.

**Comment by jamshark70** [comment]
> Can't supercollider users of all audio religions have their cake and eat it?

If labor were free and time were infinite, yes.

I do, in fact, see the point that it might be beneficial to have SC working easily in Linux with minimal configuration, even if the latency is unacceptable for live applications. We would have to be sure the audio wouldn't glitch, though. *Probably* ok, but if you can boot the server with PulseAudio and the audio is glitchy, this is exactly zero improvement over the current situation. The trouble is, to find out would take hours of developer time, researching the PulseAudio API, adding command-line arguments, and testing (dozens of hours, at least). It is known that the cost would be non-trivial, but the benefit is only probable, not certain. But, in the way the argument is posed here, the benefit is guaranteed and there's no mention of any costs at all.

If you wanted to help concretely to get a feature request going, you could research what it would take to add PA support. Find some APIs, stackexchange threads about potential problems. SC benefits most from participation.

FWIW, everything you said applies to, say, Ardour as well. ("Shouldn't Linux have a DAW that 'just works' without messing about with JACK?") Now, I don't know if you've seen how Paul Davis argues online, but if you have, you probably wouldn't try arguing this with him. He can be... let's say, stern. That conversation wouldn't go like this one.

**Comment by miguel-negrao** [comment]
> Probably ok, but if you can boot the server with PulseAudio and the audio is glitchy, this is exactly zero improvement over the current situation.

This is exactly what I was trying to say also. If the first experience people have with supercollider on linux is glitchy audio that is also going to be bad and possibly deter more people from using SuperCollider because they just give up given how bad it sounds.  In a perfect world we would have glitch free and easy to use audio system on Linux. It appears we are not living in that world so we have to make compromises... unless off course PA is glitch free, in which case I'm all for using it, but indeed the fact that audio gurus like Paul Davis stay away from it doesn't give me much confidence in PA. But I would love to be proven wrong. Most of the time PA is fine for my music and movies playback but I never used it with anything other than that... @doconnell199 you could start by looking for a professional/heavy audio application with pulseaudio support so we could see how PA sounds with that kind of workload.

**Comment by miguel-negrao** [comment]
Actually just found dj style program that works with pulseaudio:
https://terminatorx.org/
https://launchpad.net/~alex-lisas/+archive/ubuntu/terminatorx/+build/10512078

When I start with pulseaudio immediately I get glitches, sounds horrible. When I start it with jack no glitches... Might be programmer's error, but this doesn't give much hope for pulseaudio...

**Comment by snappizz** [comment]
hi everyone -- i don't want to be a jerk, but i would prefer if this discussion took place on the existing issue about pulseaudio support (#2848), or better the sc-dev mailing list. thanks
