### ISSUE TITLE
Installing SuperCollider 3.8.0+ on Ubuntu (by default 3.7.0 is installed)

### ISSUE THREAD

**Issue by OscarSouth** [supercollider/supercollider#3364]
When I install SuperCollider on Ubuntu 17.10, version 3.7.0 is installed.

I'm installing it in the process of setting up FoxDot, which lists 3.8+ as a requirement (http://foxdot.org/installation/)

I've followed this method:
https://launchpad.net/~supercollider/+archive/ubuntu/ppa
as well as this similar one:
https://github.com/supercollider/supercollider/wiki/Installing-SuperCollider-on-Ubuntu-systems

Everything is successful apart from the version.  Can anyone provide me with any insight?

Thanks,
Oscar

**Comment by snappizz** [comment]
hi oscar, i'm sorry but debian packaging for versions 3.8+ has been delayed. information on how to package was (partially) lost due to members leaving the project and not leaving behind sufficient documentation. unfortunately the only way to get newer versions on Ubuntu currently is to build it yourself.

please watch issues #2513 and #2917 for updates. this will be addressed soon.

**Comment by OscarSouth** [comment]
No worries, I'll give that a go.  Thanks for the info!
