### ISSUE TITLE
[3.9.0] Document any known-issues in Release notes

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#3381]
This is space to list and discuss any known-issues that should perhaps be mentioned in the 3.9.0 Release notes.

**Comment by patrickdupuis** [comment]
- The SCIDE server status display turns yellow after a few secons when opening `s.makeGui`. This does not cause any usability issues. This issue will be addressed as part of `3.10`'s  server refactoring.

**Comment by brianlheim** [comment]
Good idea!

I've already begun documenting all the known issues for building on Windows while reworking that readme.

Thinking.. should probably advertise the ABI update for plugins. I'm sure people will miss it in the changelog.

**Comment by snappizz** [comment]
#3266 is a pretty bad one for alternate client developers.

**Comment by brianlheim** [comment]
honestly I'm not sure what the issue is in #3266, or who it will affect or how often it will come up.

**Comment by jamshark70** [comment]
> honestly I'm not sure what the issue is in #3266,

The SynthDef binary format changed. `scsyndef` files compiled into the old format, by an older client or an alternate client that hasn't updated its SynthDef writer, crash the server.

> or who it will affect or how often it will come up.

There is no issue, provided that everybody uses sclang to build SynthDefs. But we *want* to allow other clients. It doesn't matter that non-sclang users of scsynth are in a minority.

I don't know if it's realistic to keep support for an older binary SynthDef format indefinitely. At some point, maintainers of other clients need to update their SynthDef code. But, crashing instead of warning the user is somewhat less than ideal.

**Comment by brianlheim** [comment]
> The SynthDef binary format changed. scsyndef files compiled into the old format, by an older client or an alternate client that hasn't updated its SynthDef writer, crash the server.

Ok, this confuses me, because the file was "version 2" format, which AFAICT is still the current version for the synthdef format and has been for quite awhile. So is it really the case that the old format is now problematic, or is it just that the file itself didn't meet the spec?

**Comment by jamshark70** [comment]
> Ok, this confuses me, because the file was "version 2" format

https://github.com/supercollider/supercollider/issues/3266#issuecomment-340756965

Quote:

samaaron commented 2 months ago • edited 2 months ago
I just taught Overtone about SynthDef version 2 and recompiled the beep synth and it does indeed work with v3.9 of scsynth.

I'm now fairly confident that the issue is that v1 of the SynthDef File Format no longer works with scsynth

**Comment by brianlheim** [comment]
@jamshark70 as I observed farther down the thread the file being used as a reproducer described itself as v2.

**Comment by jamshark70** [comment]
Fair enough, sorry for the noise, you're right, I should have read further down... then, I don't know what it is either.

Now I see: "I ran this through a debugger, and it's crashing in the same place that #3196 is. I suspect both issues are being caused by the same problem (memory allocation bug), and therefore that fixing one will fix the other. In other words, I am about 60% sure this is not related to the version number"... did anyone test that?

**Comment by brianlheim** [comment]
@jamshark70 - I should have added in that comment (in fact I'll go and edit it) that the crashes I observed were in Supernova, which I was in the process of debugging on a related issue. So, that's been fixed. I don't know if anyone had problems in scsynth but I wasn't able to find anything.

**Comment by patrickdupuis** [comment]
- #3395 
- #3396

**Comment by patrickdupuis** [comment]
- Mention supernova expecting plugins to be found in `/plugins` folder #3391

**Comment by patrickdupuis** [comment]
- LevelIndicator GUI widget partly broken ('Meta_QLevelIndicatorStyle')

**Comment by brianlheim** [comment]
Is anyone working on this? I can create PR if nobody else has work in progress.
