### ISSUE TITLE
[SUGGESTION] - supercollider/supercollider - improving CmdPeriod.run instructions

### ISSUE THREAD

**Issue by tiagomoraismorgado88** [supercollider/supercollider#3386]
## **Hi Again**

**IMHO**, we should consider to **add a few tweaks** to _`CmdPeriod.run`_ **Supercollider** _command_, in order to make it capable of

- *excluding actual tasks from being stopped whenever you run the command*

That would be, **IMHO**, of relevant importantance, whenever using **JITLib**, rather then **common syntax**

**That would also imply to**
- _create a command for listing currently running processes, if it doesn exist already. something in the context of supercollider, equiparable to ps or top, in the context of **GNU/UNIX** based systems_

**Looking forward,**
*Kind regards*

**Comment by snappizz** [comment]
sorry, but it's not clear to me what you're asking for here regarding `CmdPeriod`.

also, i don't understand why we would want to clone ps/top in sclang when ps and top already exist, and can be invoked from sclang via `unixCmd`.

**Comment by brianlheim** [comment]
I also don't understand what the end result is supposed to be, or why it would be desirable. What kind of tasks do we want to stop from running? I'm not sure it's a good idea to mess with semantics of CmdPeriod.

**Comment by jamshark70** [comment]
> create a command for listing currently running processes

Since you mentioned JITLib, have you tried TdefAllGui and PdefAllGui?

SC doesn't have a concept of a "process" in the same way that an operating system has one and only one type of process. So I think this proposal needs more detail. Which processes do you mean?

> I'm not sure it's a good idea to mess with semantics of CmdPeriod.

I agree with Brian here: CmdPeriod needs to be, and remain, a panic button -- stop everything.

**Comment by jamshark70** [comment]
Thinking about this a little more: Part of the point of allowing users to add `CmdPeriod` is exactly to restart processes that were stopped.

That is, if the point is to exclude some entities from being stopped, the currently available workflow is: the user keeps track of entities to be restarted, and uses `CmdPeriod.add` to set up hooks to restart them. If it's done correctly, it will be practically seamless.

There's a real risk with, e.g., excluding specific NodeProxies from being cleared. For instance, I've had occasional cases where a synth glitched and sent hundreds of dB into a reverb synth, so that the resulting distortion takes minutes to decay. In that case, when I hit ctrl-., I *need* everything to stop, right now. If I had said "my reverb synth should be persistent and I want to exclude it from ctrl-.," then I would hit ctrl-. and the reverb would still be decaying. That's dangerous.

So I suggest to close this. Ctrl/Cmd-. needs to reset everything, and `CmdPeriod` gives you the option of re-creating/restarting objects that you want to be working afterward. (Or, if you want the concept of a "partial reset," then it's up to the user to define that behavior in her/his own code.)

**Comment by tiagomoraismorgado88** [comment]
fair enough
