### ISSUE TITLE
CFBundleShortVersionString of macOS application contains incorrect value

### ISSUE THREAD

**Issue by orbsmiv** [supercollider/supercollider#3397]
Version: 3.8.1
System: macOS

The `CFBundleShortVersionString` key (in _Info.plist_) still contains value `3.8`. Further to this the `CFBundleVersion` key contains value `.1`. I've noticed that version 3.7.2 did something similar but this is non-standard use of the version keys (as described in [Apple's Core Foundation Keys docs](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-111349)).
From my perspective this creates issues with managed deployments (e.g. using Munki) which often use the `CFBundleShortVersionString` keys to ascertain software update requirements etc. but expect the key to contain the full version string of the release.

**Comment by brianlheim** [comment]
Hey @orbsmiv - thanks for the report. We've fixed this for releases for 3.9+: #2471. I forgot that this wasn't changed until after 3.8, so the issue is still present in that branch. I've edited the plist for the 3.8.1 release asset to fix this and uploaded the new version. We don't intend to release any further patch releases for 3.8, since we're moving on to the 3.9 series this week.

**Comment by orbsmiv** [comment]
Many thanks @brianlheim ! Sorry, I'd missed #2471 and subsequent PR although am not surprised that Tim spotted this already!
Looking forward to 3.9!
