### ISSUE TITLE
Pen.addRect and Pen.addOval very slow

### ISSUE THREAD

**Issue by redFrik** [supercollider/supercollider#3449]
since sc3.7 the .addRect is acting weird and very slow.  under sc3.6.5 (non scide) it was fine - both for cocoa and qt.
same issue with addOval but addRoundedRect, addWedge and addArc doesn't seem to be affected (the ones that don't have a corresponding .fill method?).
this might be an macos specific issue.

```supercollider
( 
var width= 1024, height= 768;
var win= Window("test", Rect(10, 10, width, height), false);
var usr= UserView(win, Rect(0, 0, width, height));
usr.background= Color.black;
usr.drawFunc= {
	Pen.fillColor= Color.red;
	5000.do{|i|
		var r= Rect(i%999/999*width, i%99/99*height, 1, 1);
		Pen.fillRect(r);  //try with Pen.addRect(r) here - superslow!
	};
	Pen.fillColor= Color.white;
	Pen.stringAtPoint("fps:"+usr.frameRate, Point(10, 10));
};
win.front;
usr.animate= true;
CmdPeriod.doOnce({win.close}); 
)
```

**Comment by brianlheim** [comment]
> acting weird and very slow

What do you mean exactly by "acting weird"?

**Comment by redFrik** [comment]
i only meant that when using these add methods the framerate drops significantly. it didn't use to do that way back (pre sc3.7).

**Comment by nuss** [comment]
I find this super-weird: I checked @redFrik 's example with `Pen.addRect(r)`, once leaving `Pen.fillRect(r)` in place (following immediately after the `addRect` call) and once _omitting_ the `fillRect` call. It turned out that when leaving the `fillRect` call in place, though it's an additional call did have **no** negative impact on the framerate. Only when commenting out the `fillRect` call, only leaving the `addRect` call the framerate dropped dramatically... what??? How can that be?

**Comment by brianlheim** [comment]
OK. Here's my sketch of an explanation. When you call `addRect`, you're adding objects to the "path", the buffer of things to be painted on the next call to a drawing function such as `stroke` or `fill`. `fillRect` does this for you, so it flushes the path buffer. `addRect` doesn't, by design. By making a huge number of calls to `addRect` my guess is you're causing the buffer to grow beyond what your processor's cache can hold, resulting in a lot of costly swaps when that buffer is grown and destroyed. In other words the method by itself is not slow; using a lot of memory in a critical loop is. You can see this by doing what @nuss did or by following each call to `addRect` with a call to `Pen.stroke` or `Pen.fill`.

As for why the other methods aren't as bad when you draw 5000 of them, I'm not particularly certain. Probably has to do with Qt's internal representation of those objects. For instance, the documentation says `addRect` stores the rectangle as a set of lines. The others may be stored as more complex (and compact) representations that are unpacked at draw-time. There is really not much going on underneath these calls, so that's my best guess. And as a matter of fact, try using these lines in your critical loop:

```supercollider
( 
var width= 1024, height= 768;
var win= Window("test", Rect(10, 10, width, height), false);
var usr= UserView(win, Rect(0, 0, width, height));
usr.background= Color.black;
usr.drawFunc= {
	Pen.fillColor= Color.red;
	5000.do{|i|
		var r= Rect(i%999/999*width, i%99/99*height, 1, 1);
		Pen.addRoundedRect(r, 0.001, 0.001); // fast
		// Pen.addRoundedRect(r, 0.001, 0); // slow
		// Pen.addRoundedRect(r, 0, 0); // slow
	};
	Pen.fillColor= Color.white;
	Pen.stringAtPoint("fps:"+usr.frameRate, Point(10, 10));
};
win.front;
usr.animate= true;
CmdPeriod.doOnce({win.close}); 
)
```

As you can see in the C++ implementation of `addRoundedRect`, this is just making a call directly to `QPainterPath.addRoundedRect`.
https://github.com/supercollider/supercollider/blob/cca12ff02a774a9ea212e8883551d3565bb24a6f/QtCollider/primitives/prim_QPen.cpp#L434-L445

AFAICT, these observations imply that Qt is doing some internal calculation to optimize draw time, and it looks like that involves breaking up the rounded rectangle into more pieces when either or both of the radii are 0 on a call to `addRoundedRect`.

Actually, I looked at their source and that's exactly what's happening:

http://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/painting/qpainterpath.cpp?h=5.5#n3091

It would take a lot more digging to find out why exactly the internal representations are leading to the effect we're seeing, but hopefully this explanation is convincing enough.

**Comment by brianlheim** [comment]
This should go into documentation, otherwise it is resolved.

**Comment by telephon** [comment]
This is still very slow:

```
( 
var width= 1024, height= 768;
var win= Window("test", Rect(10, 10, width, height), false);
var usr= UserView(win, Rect(0, 0, width, height));
usr.background= Color.black;
usr.drawFunc= {
	Pen.fillColor= Color.red;
	5000.do{|i|
		var r= Rect(i%999/999*width, i%99/99*height, 1, 1);
		Pen.addRect(r);  //try with Pen.addRect(r) here - superslow!
	};
	Pen.fillColor= Color.white;
	Pen.strokeColor= Color.white;
	Pen.stroke;
	Pen.stringAtPoint("fps:"+usr.frameRate, Point(10, 10));
};
win.front;
usr.animate= true;
CmdPeriod.doOnce({win.close}); 
)
```
