### ISSUE TITLE
[enhancement] - Buffer - allowing allocating compressed audio files

### ISSUE THREAD

**Issue by tmm2018** [supercollider/supercollider#3460]
Some remarks:

- one of the things i really enjoy doing, is to play with really large files, with tgrains, and warp1
- currently supercollider version, accepts, at least last time i checked 2 gb of server memory
- that allows for maybe 4-8 wav audio files of one hour at 44.1khz 16
- it would be cool if with that amount of memory i would be able to load perharps a bunch of 128kbs 44.1khz mp3 files
- that would mean i would be able to load, with two gigs of virtual memory, something like 40 files of one hour
- that would mean i would be able to have a lot of kaleidoscopy with granular, and i could even map that to sensors or to wiimotes, or to a kinect (for an installation for instance), and having some cool visuals in openframeworks playing on the background, with supercollider loaded with supercollider extension for ofx and miguel negrao standalone template for linux

what are your thoughts about implementing something like this? i know there's already an UGen which supports mp3, but it's not the same thing, and it's fairly unstable

looking forward, cheers
T.

**Comment by scztt** [comment]
Compressed audio files already work in SuperCollider. libsndfile, which SC uses for file import, supports several compressed formats - at least OGG and FLAC - and several other formats that support sizes larger than 2gb (the wav file format is limited to 2gb - so it's partly a file format limit).

As far as I know the synthesis server should support loading any number of buffers at any size, as long as you have enough memory, so there should be no 2gb issues there. If you're hitting memory limits of your hardware, you can minimize memory usage by streaming audio from disk instead of loading it ahead of time - however, this only works with the DiskIn ugen - you wouldn't be able to use Warp1 or TGrains like this (at least, not if you wanted random access across the entire audio file). Unfortunately, building a Warp1 / TGrains UGen that could stream from disk (or even from an in-memory compressed audio file) is bordering-on-impossible for performance reasons. :(

**Comment by muellmusik** [comment]
I think he wants them stored compressed in memory. Currently compressed files are converted to uncompressed floats.

This would require special UGens for playback.

**Comment by tmm2018** [comment]
- ogg files load effectively, as well as flac; this takes space in uncompressed audio; and takes time to load; i tried loading wagner tristan und isolde opera in ogg. took a lot of time to load and caused the server unstability. i also tried a piece of rock music by Tomahawk, i had in my music folder (a project of mike patton from faith no more)
- if you want to take advantage of compressed memory addresses, i think it would make sense at least to rewrite the source code of Buffer UGen, in C++;
- if you do so, this can be an advantage not only for applications such as the ones i mentioned, but also for playing live large multi-channel pieces, from a single multichannel file, rather then using synthesis routines scores, created with some form of frontend, which could have its applications
- by doing so, you can make sure you can load the files, the loading time is relatively fast, and you get minimal memory usage, and you can quickly, specially if you use ssd drives, to load files dynamically really quick

**Comment by joshpar** [comment]
what you are talking about involves storing compressed and decompressing on the fly. The real-time thread really won’t handle this well, especially under load.
Decompressing to a buffer first, then using the full uncompressed buffer is how all buffer playing UGens expect data. We can’t expect all Buffer reading UGens (Warp1, PlayBuf, grain buffers) to branch to handle compressed / uncompressed data. It would seriously degrade the system.

**Comment by snappizz** [comment]
this is not a bad idea -- for sizeable audio files, sometimes improved memory usage can outweigh the CPU costs of decompressing on the fly.

this could be implemented in a 3rd party server plugin by writing your own buffer player ugen capable of handling the compressed format. if such buffers requires special preparation before playback, the `DefinePlugInCmd` API lets you create your own variant of `/b_read`.

either way, this seems pretty complicated and not high priority for the project.

**Comment by jamshark70** [comment]
But you will still be able to access specific frames within the buffer using only single-precision floats, which have about the same precision as 24-bit integers. `2 ** 24 / 44100` comes to about 380 seconds = 6m20s. Beyond that point, you will not have sample-accuracy for grain positions, and the further up you go, the less accuracy you have.

I don't see a point in doing a lot of work to support lossy-compressed data in buffers without also supporting double-precision sample indexing. That's been discussed and, so far, rejected because it's essentially impossible without making the entire signal chain double-precision, and I'm fairly sure this would be bad for performance. ("Suddenly I can only run half the UGens I could before, what happened?" "Somebody needed hour-long buffers, so we broke performance for everybody." Nope, not gonna happen.)

If you need kaleidoscopy, I'd suggest loading sections of files into separate, shorter buffers, with a mapping scheme. Then you get lots of data *and* precision.

Also worth noting that every professional audio package I've ever used converts compressed formats to straight PCM when importing.

**Comment by dyfer** [comment]
I'd like to share an observation on file formats - I have been recording >2GB wav files in SC using DiskOut, so whatever version of the wav format SC implements (wave64 or BWF or ?) it does not seem to be limited to 2GB on the file format level.
Indeed, I'm not able to load that file into the buffer afterwards (or it loads but doesn't play properly) but it works fine in DAWs and other programs.

**Comment by jamshark70** [comment]
Also, for the stated use case (granular synthesis) -- I was just looking for information about the performance of random access into compressed audio formats. (Difficult to find: I get a lot of information about random access into non-audio zip-style archives, or a lot of MP3 download links for "Random Access Memories" by Daft Punk.)

Many compression schemes (FLAC, I'm pretty sure) encode the current frame based on its relationship to the previous frame. That's okay in normal use because these formats are optimized for start-to-end playback.

Random-access then needs to embed sync frames periodically. So, playing a grain starting at sample index 'i' means rolling backward to the preceding sync frame, and then decoding all the audio rolling forward to the point that you need. In a granulator, you'll be doing this dozens/hundreds of times per second. Performance impact will be worse than you expect. You're used to playing MP3s under optimal conditions, and CPU use is low. Granular synthesis is basically a worst case for compressed audio formats.

> currently supercollider version, accepts, at least last time i checked 2 gb of server memory

I don't think this is correct. Where did you hear that?

A 32-bit OS uses 32-bit memory addresses, covering 4 GB. usually some of this potential address space is reserved for system use -- e.g. 32-bit Windows limits normal user processes to 2 GB of user space (keeping 2 GB for the system). That's possibly one source for the idea that "the server can use only 2 GB."

But almost everybody is running 64-bit OSes now. Potential memory address spaces are far larger than any amount of RAM you can afford to buy. Scsynth *buffers* can use as much memory as is available.

Proof:

```
// 256 MB / 4 bytes per sample = 64 meg-samples = 64 * 1024 * 1024
// 8 of these = 2 GB, so, as a test, grab 9 of them
(
var size = 64 * 1024 * 1024;

b = List.new;

fork {
	9.do { |i|
		b.add(Buffer.alloc(s, size, 1));
		s.sync;
		"done %\n".postf(i + 1);
		1.0.wait;
	};
};
)
```

After the routine completes, I check the xfce4 Task Manager and I see scsynth has a Resident Set Size (= memory use) of 2.4 GB. Easy. There's no 2 GB limit on RAM usage.

Or, possibly the 2GB myth comes from the file format issue that @dyfer mentioned. But, any file format limitation is separate from RAM / `malloc()` limits -- no relationship at all.

@dyfer - did you try CAF files for recording? (Btw that's a separate issue from this enhancement request.)

**Comment by tmm2018** [comment]
would be interesting to test such a possibility on already existing technology and comparing the audio quality with audio processing, no matter if it's granular, sampling, or some form of concatenative synthesis or whatever it is. just grab a software toool, no matter if it's commercial or opensource, and try this yourself, to see if you can get the whole thing up nice and running, and if it sounds well. if it sounds well, we may then consider to implement this. but as far as i can tell, i have at least processed samples with paul stretch, in audacity, that were audio compressed and they seem to perform as great as wav files, at least in time stretching. so, IHMO, i don't personally think this would be an issue. whether, in a serious DSP analysis, you could state that there is information loss, and it may compromise the overall result, by reducing the amount of data that becomes heard, it doesn't make a difference. i also play a lot sometimes, with sampling in ableton (well, most lately not as much, as i am attempting to switch to linux), and use mp3 files, and cannot tell a difference between using mp3 and wav files, in such a procedure. and, of course things can be enhanced with dsp algorithms, so you could create some form of dsp algorithm, to enhance audio playback of supercollider, even after loading stuff, and so on, and even for overall supercollider, synthesis and making it compelling to this kinds of transformations. that would be the same as doing some form of audio mastering, or so, or post processing, already embedded in the system (in fact i think that there is an urgent need in improving the overall supercollider dsp, and something as simple as injecting convolution by using IRs, and FIRs, and work pretty well for that)

in relaton to the server memory, i think i mostly used 32 bits supercollider versions. i don't say if you upgrade for 3.8 or 3.9, and use a 64 bit version of supercollider, you won't get more server memory allocation possibilities. in fact, it makes sense

**Comment by vivid-synth** [comment]
Closing this as if-someone-wants-to-build-it-they-can (and because of @jamshark70 's great points above). Feel free to reopen if it looks like someone's going to work on this.

Aren't there also realtime issues with decompressing on the fly?

**Comment by scztt** [comment]
Decompressing on the fly would never really be realtime safe. You could make it realtime-safe-enough if you were doing read-ahead, but I think what @tmm2018 really wanted was random access (for granular stuff) - that means random access, which is NOT possible either with compressed files OR on-disk files.

Actually, the best solution to this problem is engineering heavy, but probably do-able without new UGens:
1. Assuming you're only granulating over a small area of your whole long file at any given time.....
2. Divide your long file into e.g. 60 second chunks.
3. Reserve a chunk of buffer numbers corresponding to each chunk (without allocating them yet...)
4. Load JUST the chunk you're reading from, plus a couple of adjacent chunks.
5. If the area you're granulating over changes, load more adjacent chunks. Unload chunks that are no longer needed.
You'd have to control the area you're granulating / warping from the sclang side, and you wouldn't be able to change it too fast (because you'd need some lead time to load the new area), but otherwise this would be do-able, and would work over arbitrarily large audio files.
