### ISSUE TITLE
Main:run - legacy method?

### ISSUE THREAD

**Issue by snappizz** [supercollider/supercollider#3470]
`Main:run` is a blank instance method with the following comment in its source code:

    // used to be called by command-R, customisation now via CocoaMenuItem
    //interpreter.interpretPrintCmdLine;

the help file says you can override this:

    + Main {
        run { "myPatch.rtf".load }
    }

this is a pretty bad suggestion because multiple overrides will conflict with each other. i'm pretty sure this is what we have `startup.scd` and `Class.initClass` for.

the only place `Main:run` seems to be called in the class lib is [a single line in scel](https://github.com/supercollider/supercollider/blob/2e4b72a16ed8389a06cc51265eeba9d7abf86c0d/editors/scel/el/sclang-interp.el#L696).

i'm pretty sure this is a legacy method, and thus should be documented as such -- does anyone more knowledgeable on its history have an explanation?

**Comment by telephon** [comment]
Its origin is in SC2, which was closed source and there was SCPlay that allowed you to run "images" or "applications" with sclang code. These could use the `run` method for set up. Since sc3 has come out as open source, the method has been used in the same way, for stand alone applications.

I don't think it is legacey really, it's just used in very specific cases (the name suggesting the opposite!). The `initClass` metods have a slightly different meaning/intent, but could be used for the same purpose of course.  But probably the main question is whether the startup file is a valid replacement.

**Comment by snappizz** [comment]
no resolution to this discussion.
