### ISSUE TITLE
Qt5OpenGL, Qt5Sensors and Qt5Positioning not actually used?

### ISSUE THREAD

**Issue by simonvanderveldt** [supercollider/supercollider#3471]
Hi supercollider team,

Whilst working on updating the supercollider package for gentoo I noticed there was a [patch that removes Qt5OpenGL from the list of dependencies](https://github.com/gentoo/gentoo/blob/master/media-sound/supercollider/files/supercollider-3.8.0-no-opengl.patch). A quick scan through the supercollider codebase seems to indicate non of the headers provided by Qt5OpenGL are being used. So it seems Qt5OpenGL isn't actually being used.
If that's the case, can it be removed?

The same goes for [Qt5Sensors](https://github.com/gentoo/gentoo/blob/master/media-sound/supercollider/files/supercollider-3.8.0-no-qtsensors.patch) and [Qt5Positioning](https://github.com/gentoo/gentoo/blob/master/media-sound/supercollider/files/supercollider-3.8.0-no-qtpositioning.patch).

**Comment by scztt** [comment]
It's worth experimenting with removing these from cmake and seeing how things work. However, at some point in updating to QT5.9 I believe I stripped the dependencies back to nothing, and then added them back in as I ran into link errors - so it may be that those packages are included because other QT packages depend on them also. If someone wants to make a pull request with these packages stripped from the various CMakeLists.txt's, travis should tell us pretty quickly whether they're required.

**Comment by simonvanderveldt** [comment]
@scztt I can create a PR with the gentoo patches applied so we can try it out. Is that OK with you?

**Comment by telephon** [comment]
aren't the `Pen` primitives open GL?

**Comment by scztt** [comment]
They're not explicitly OpenGL... QT may or may not use OpenGL though. Removing the library is the easiest way to determine if there's some linkage buried in a plugin or framework somewhere.

**Comment by telephon** [comment]
ah yes

**Comment by yurkobb** [comment]
I was trying to update to 3.10.2 in [nix](https://nixos.org) (running on fedora) and noticed that sclang and scide started requiring OpenGL to run. Since in nix on non-nixos OpenGL is not configured by default, they simply crash. I wonder if OpenGL is actually required by supercollider - I don't see any new OpenGL-related features in the 3.10 release.

**Comment by yurkobb** [comment]
I see these dependencies have been [removed](https://github.com/supercollider/supercollider/commit/19c7f4c290693954f80df43644a3779c81cb1528#diff-4aeb57b39efdea8a7cecc1748e8a500e) and [added back again](https://github.com/supercollider/supercollider/commit/298b285d33bcd30228c3d8f5cd58d95deb0d8751#diff-4aeb57b39efdea8a7cecc1748e8a500e) - I'm curious why.

**Comment by brianlheim** [comment]
@yurkobb sorry for the long reply -- it looks like they were added back in https://github.com/supercollider/supercollider/pull/3165. qtwebengine requires opengl and probably svg as well since it is a web browser (https://doc.qt.io/qt-5/qtwebengine-overview.html). feel free to make a PR to remove this dependency via CMake when SC_USE_QTWEBENGINE is OFF, but we don't currently make an effort to support Nix so for now i'm closing this issue as solved.
