### ISSUE TITLE
Pbind keeps playing

### ISSUE THREAD

**Issue by ofefo** [supercollider/supercollider#3484]
Hi,
newbie here.

I was following a tutorial ("Gentle introduction to SC"), and it suddenly crashed.
This is what I did.
```
c = Pbind(\note, Pwhite(0, 10), \dur, 0.1);
c.play;
```

I think i changed the values on Pwhite parenthesis before it crashed.
To my surprise, when restarted and booted, the server keep playing that line. I did Ctrl+., rebooted the server, killed all servers, tried `s.freeAll;`, but all these failed, the synth stops for a second and suddenly starts again.

The error message i get is: 

> FAILURE IN SERVER /n_set Node 29080 not found

What can i do? Is it a bug?

**Comment by beatboxchad** [comment]
Without going into too much technical detail I can't remember off the top
of my head anyway: some of those artifacts live on the language side. If
you recompile the class library it should clear out all those variables
and, perhaps, patterns you lost access to (maybe by evaluating the variable
assignment line more than once?) which are still running and trying to tell
the server to do things with nodes it forgot.

Nowadays I'm using Ndef and friends heavily and things like that happen
more rarely. You should still grok things the way you're doing, but I
thought I'd leave that breadcrumb. Play with it when you've got this stuff
internalized. Happy noisemaking!


On Jan 29, 2018 9:59 PM, "ofefo" <notifications@github.com> wrote:

Hi,
newbie here.

I was following a tutorial ("Gentle introduction to SC"), and it suddenly
crashed.
This is what I did.

c = Pbind(\note, Pwhite(0, 10), \dur, 0.1);
c.play;

I think i changed the values on Pwhite parenthesis before it crashed.
To my surprise, when restarted and booted, the server keep playing that
line. I did Ctrl+., rebooted the server, killed all servers, tried
s.freeAll;, but all these failed, the synth stops for a second and suddenly
starts again.

The error message i get is:

FAILURE IN SERVER /n_set Node 29080 not found

What can i do?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/supercollider/supercollider/issues/3484>, or mute the
thread

**Comment by jamshark70** [comment]
> I was following a tutorial ("Gentle introduction to SC"), and it suddenly crashed.

Can I ask, which component crashed? In SC, there are three apps:

- scide: The editor. A crash means the whole window goes away and you get some pop up saying the application quit unexpectedly.

- sclang: The language. Crash = `Interpreter has crashed or stopped forcefully. [Exit code: xx]` in the post window.

- scsynth: The audio engine. Crash = audio stops and you see `RESULT = xx` in the post window, and the IDE status bar changes state.

If it isn't one of those, then it isn't a crash. Just an error.

So... can you be more specific about what happened? You typed in the code, changed something (what did you change?), and then... executed the modified code? And then it "crashed"... what did you see on the screen? Editor window disappeared, or something else?

The only possible explanation I can think of is, maybe scide crashed (editor disappeared), but sclang kept running in the background. If that happened, the old sclang would keep playing, and restarting the IDE would create a new sclang. Ctrl-. would then talk to the new one, but not the old one.

But that's only a guess.

"Is it a bug?" If one of the three components crashed, by definition, that is a bug. But it's basically impossible to fix if we can't reproduce it, and based on the available information, we don't know how to reproduce it. So there might not be anything we can do.

**Comment by ofefo** [comment]
So, the role SC window stopped responding and i got to close it.

As said, i modified the values on the Pwhite parenthesis. Many times. And executed it. Tried 0, 20; 100,10; 15, 12; etc.

I think it crashed when i executed c.play;

**Comment by snappizz** [comment]
i've never heard of this bug before -- it would be much appreciated if you could experiment and try to get it to happen again so we can be informed of the exact conditions that cause this to happen.

**Comment by snappizz** [comment]
@ofefo hi, any updates on attempting to reproduce?

**Comment by brianlheim** [comment]
Closing as stale, not enough info; please reopen if a reproducer is found.
