### ISSUE TITLE
[enhancement/long term/question] is it worthy for the community to spend time translating supercollider to portuguese (IDE and Docs)?

### ISSUE THREAD

**Issue by tmm2018** [supercollider/supercollider#3509]
[enhancement/long term/question] is it worthy for the community to spend time translating supercollider to portuguese (IDE and Docs)?
i can do on a separate repository

**Comment by brianlheim** [comment]
IDE: yes, absolutely, I think you should start there. You should use [Qt Linguist](http://doc.qt.io/qt-5/qtlinguist-index.html) to do this efficiently, don't do it by editing the translation file directly. You'll want to edit [this file](https://github.com/supercollider/supercollider/blob/develop/editors/sc-ide/translations/scide_pt.ts). If you start on this right away you should work off the file from https://github.com/supercollider/supercollider/pull/3510, since it's more up-to-date.

Docs: we don't currently have a process set up for this, so you can start translating if you want, but there's no guarantee we'll find a way to integrate that soon. You would want to focus on very core docs, since most of the documentation is spotty in English as it is. That's why I strongly recommend starting with the IDE translations.
