### ISSUE TITLE
[WIP/ENHANCEMENT] supercollider documentation and IDE translation to portuguese

### ISSUE THREAD

**Issue by tmm2018** [supercollider/supercollider#3517]
[WIP/ENHANCEMENT] supercollider documentation and IDE translation to portuguese
hope you enjoy it!!!

when it wll be completed would be nice to integrate this into supercollider 
help appreciated

https://github.com/tmm2018/traducao_supercollider_portugues

**Comment by brianlheim** [comment]
Hi, sorry, we currently have no way to integrate this into the project. You should ask on the mailing list. Also, what has been translated? At a quick survey not all files in this repo you linked are in Portuguese. Also, the IDE text has not been translated.

I don't understand, when you asked originally I said you should focus on translating the IDE text. You've done the opposite of that for no apparent reason. Kind of a bad use of everyone's time if you put effort into something a project member has explicitly said not to.

**Comment by tmm2018** [comment]
hey brian. a few things:
- i have to respect your position (you are one of the greatest developers in the supercollider community and i deeply admire your work)
- supercollider translation is one of the long term projects of supercollider (so, if i do this, there shall be a way of including this later on)
- this is work in progress, and does not represent a final stage of development
- currently i am only translating the docs, later on i will be working in the IDE as well
- i only started this a couple of days ago.

bearing this in mind, i would like to hear other people's opinion on the topic, including:
- @miguel-negrao (who can actually be a collaborator in the entire process, as he is one of the greatest supercollider developers and he speaks portuguese)
- @jleben (whose contributions for supercollider in the past i deeply admire)
- @sensestage and @vanhuman and @spluta

let's give a chance to everyone to contribute to supercollider
this will make supercollider better and better, which in the end is our main goal

**Comment by snappizz** [comment]
i don't think translating the class help files is a good idea at this stage. that's much more work and, more importantly, SCDoc currently doesn't have the infrastructure to support multiple languages in class files. there has been talk of retiring SCDoc in favor of an existing documentation system, so imo it is best if we wait until that happens. until then, PRs that translate class help files are likely to be rejected.

translating the IDE interface and/or the various tutorials out there would be much less laborious and have much more immediate impact.

it's very rude to use your comments to ping half a dozen people who aren't involved or responsible in this discussion. please don't do that again. thank you.

**Comment by brianlheim** [comment]
@tmm2018 

> this is work in progress, and does not represent a final stage of development

Then the next thing you do should be to start documenting exactly what you've translated, or keep a clean separation between English and Portuguese text so there is no confusion.

Also:

- you should be working off the main repository so that your commit history is easily preserved. do that now, rather than later. I would advise creating a new directory containing all your translations. this also makes it possible to submit your changes as a pull request.
- announcements like this are better on the mailing list. this is not an issue tracker item.

> bearing this in mind, i would like to hear other people's opinion on the topic, including:

It is totally not your right to demand time and attention from people like this. People that want to comment on your contributions will do so and have done so. Like Nathan said above, I really think you should stop doing this, as you've been asked to multiple times in the past and it doesn't fit with our community guidelines - "Exercise consideration and respect in your speech and actions."

**Comment by brianlheim** [comment]
Also, for the record, I think as a community we ought to avoid injecting things like this into unrelated discussions:

> you are one of the greatest and most active developers in the supercollider community these days and i deeply admire your work

> who can actually be a collaborator in the entire process, as he is one of the greatest supercollider developers and he speaks portuguese

> whose contributions for supercollider in the past i deeply admire

This is an open source community with lots of contributors with many backgrounds. All contributors are valid and valued. There is certainly a time and place to praise people for their work, but I think if done too often it can lead to an environment where people are valued more for their past work than their present ideas, more or less a gerontocracy. So, while it's perfectly fine to think this about other contributors on the project, I'd really appreciate it if we all made fewer statements like this.

**Comment by tmm2018** [comment]
- brian, thanks for your feedback, i am truly grateful for it, we are here to learn with each other
- the overall impression i get from what you say: you point out to very important values and attitudes in opensource
- what i feel about this specific thread and the overall attitude towards supercollider community in relation to my contributions in comparison to other communities where i have successfully contributed: more then 90% of the PRs and issues i open are ignored (in comparison to other communities, where 40-70% of my contributions are accpeted)
- that means two things: that maybe i am not following some of the notions that the supercollider community has towards the future of what supercollider shall be in the future, or just not writing code that meets the supercollider community standards, and in this case, it is my fault; i am beiing put a litte bit away; i feel that both things are equally present in the way as i am treated in this community

**Comment by miguel-negrao** [comment]
My opinion:

-  It seems to me that work on translating sc docs into other languages cannot be integrated into the main repo before the infrastructure for that is created first, that is code to select which language should be shown for docs, etc.
- Although I'm more than happy to see either the IDE or the documentation in Portuguese (and the Portugal variant) since it is my language, most if not all portuguese coders know english. Given how small a community we are of supercolliders in Portugal , and given the ammount of documentation we have, and given that it is constanty changing, I don't think it is a priority to translate the help docs. I don't think I will have time to check the translations of help pages, or help maintaining those translations.
- I agree that it is a much smaller job, and without the same need for updates, to translate the IDE interface, so I think it is time better spent translating that.

**Comment by brianlheim** [comment]
> more then 90% of the PRs and issues i open are ignored (in comparison to other communities, where 40-70% of my contributions are accpeted)

They are not ignored, they are closed because they are either:
- incorrect (https://github.com/supercollider/supercollider/pull/2992, https://github.com/supercollider/supercollider/pull/2991, https://github.com/supercollider/supercollider/pull/2990)
- abandoned by you (https://github.com/supercollider/supercollider/pull/3124)

> that maybe i am not following some of the notions that the supercollider community has towards the future of what supercollider shall be in the future, or just not writing code that meets the supercollider community standards

It's somewhat the first (you literally just ignored advice a collaborate gave you after you asked what you should work on), and definitely the second (see above links).

**Comment by sensestage** [comment]
@tmm2018:
just jumping into this discussion: but - great job for translating!

The most feedback you get here is about where to best put your
contribution, given the limitations for multilingual support in the
documentation system in SC.

So let's look at possible solutions:

- make a fork of just the HelpSource directory and maintain it as a
separate repository for now and point it out to Portugese users to look
at, use it and contribute to.

- take an example for how the Spanish version of the documentation is
published? (Is it somewhere? I'm actually not sure - but I had the
impression people had been working on this. In any case, I think the
Spanish community is a bit larger than the Portugese).

The main repository may not be the right place for hosting the
translation right now as currently active developers have pointed out,
but I can definately see that people may find reading documentation in
their native tongue useful (not just in Portugal, but also in Brazil).
I see on https://supercollider.github.io/ that there is a Brazilian SC
FB group - they would probably be interested to know about this effort.

just my 2 cents.

**Comment by brianlheim** [comment]
Closing, announcements are not issues.
