### ISSUE TITLE
No connection between sclang and IDE on Windows 8

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#3528]
Apparently, the IDE starts, and it can start an sclang process, but no communication between the two.

This is on Windows 8.1 (Enterprise, 64 bits).

**Comment by passivist** [comment]
Maybe the communication is blocked by the Windows firewall? Does SuperCollider give any error messages?

**Comment by jamshark70** [comment]
IMO the handshaking at startup needs a thorough review. There are too many open issues about broken startup behavior.

**Comment by scztt** [comment]
When you say "no communication" - do you mean you can't execute code / post window is empty? Or do you mean the `ScIDE` interconnection stuff, like Document.keyDownAction, document syncing, etc?

**Comment by telephon** [comment]
(I'm only indirectly reporting this, so I can't try out stuff).

The interpreter seems to run, but you can't execute any code, as it seems.

**Comment by scztt** [comment]
Communication between sclang <> IDE happens via stdin/stdout - the Document syncing / autocomplete stuff happens via IPC but is pretty non-essential. Neither of those things should require any kind of network access. If the user is seeing output from sclang, but can't run code or quit, that seems like there's a problem with the IDE -> sclang path, but not the reverse. The IDE->sclang path is using QT based process/IO stuff, so there's much more likelihood for failure there.

Maybe point them to the latest build w/ QT5.9? I know some of that process IO stuff changed because there were some bugs introduced, but maybe it also fixed whatever issue the user is seeing?https://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/win64/topicwebengine-latest.html

**Comment by telephon** [comment]
@scztt 

reply:
>This one does not even start at all

**Comment by brianlheim** [comment]
Closing, if there is more information that can help to debug this, please reopen.
