### ISSUE TITLE
Feature Request: an Optional Argument for Out.ar, Pan2.ar etc.

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3592]
Hi,

The followings
```
Out.ar
Out.kr
OffsetOut.ar
OffsetOut.kr
ReplaceOut.ar
ReplaceOut.kr
```
have same arguments:
the first argument is the bus argument,
the second argument is the channelsArray argument.

The followings
```
XOut.ar
XOut.kr
```
have the xfade argument between the bus argument and the channelsArray argument.

It would be very convenient if these of all have a new additional argument after their last argument: ChannelsMappingArray.

For example;
`{Out.ar(0, SinOsc.ar([440, 550, 660]))}.play`
sends
SinOsc.ar(440) to Outputchannel 0,
SinOsc.ar(550) to Outputchannel 1 and
SinOsc.ar(660) to Outputchannel 2.

By Using the ChannelsMappingArray, 

`{Out.ar(0, SinOsc.ar([440, 550, 660]), [0, 2, 4])}.play`

we can send
SinOsc.ar(440) to Outputchannel 0,
SinOsc.ar(550) to Outputchannel 2 and
SinOsc.ar(660) to Outputchannel 4.

How do you think about the idea?

The ChannelsMappingArray could be applicable to the followings as well:
```
Pan2
Pan4
PanAz
LinPan2
Balance2
```

**Comment by joshpar** [comment]
This looks a little strange to me (because of how Array and Multi-Channel expansion work). 

I almost think something like this would make more sense:

Out.ar([0, 2, 4], SinOsc(440 * [1, 2, 3]));

To me, the above would expand in the same way that this would:

SinOsc.ar <http://sinosc.ar/>(440 * [1, 2, 3], 0, [0.5, 0.2, 0.1]);

Where the mapping happens in the bus input. And what would happen if there is a size mismatch? Warning? Failure? Not sure if there is really a clean logic for it in my mind: 

Out.ar([0, 2], SinOsc(440 * [1, 2, 3])); // where does the third SinOsc get routed to?

Best,

Josh

**Comment by prko** [comment]
Oh, I did not think about the case you have mentioned.

Currently, the following code

> `Out.ar([0, 2, 4], SinOsc(440 * [1, 2, 3]));`

works according to the sclang. So it sends
SinOsc(440 * 1) to outputChannel 0, 2, 4,
SinOsc(440 * 2) to outputChannel 1, 3, 5 and
SinOsc(440 * 3) to outputChannel 2, 4, 6.

I think it would be better to preserve it.

For the code in your question:

>` Out.ar([0, 2], SinOsc(440 * [1, 2, 3])); // where does the third SinOsc get routed to?`

I think the following is a possible way to resolve it:
```
(
  {
    Out.ar(
      [0, 2], // [first channel, second channel]
      SinOsc.ar(440 * [1, 2, 3]),
      [ 
        [0, 1, 2], // for the first channel
        [4, 5, 6] // for the second channel
      ]
    )
  }.play
)
```
If this is still unlogical, I would like to withdraw the idea for Out classes, but I believe the idea could be still usable for Pan classes.

**Comment by snappizz** [comment]
it sucks that Out's interpretation of its second argument is inconsistent with the usual multichannel expansion behavior, but i'm not really digging this idea -- feels like it's complicating the API. Out is structured around contiguous regions of channels after Bus. if you need to output to nonconsecutive channels, you can do real multichannel expansion by wrapping the second argument in a 1-element array. i'm pretty sure you can just do this to map x to bus 0 and y to bus 6:

    Out.ar([0, 6], [[x, y]])

i had to figure this trick out for myself since it's not at all well explained in the help file, so this is a documentation issue.

i'm not sure what you mean with Pan2... it takes one input and produces two channels. you can just route & reorder those two channels afterward.

**Comment by prko** [comment]
If we need that Pan2 sounds out to channel 0 and 3, we should do as follows: 
```supercollider
(
{
	~bus = Bus.audio(s, 2);
	Out.ar(~bus, Pan2.ar(WhiteNoise.ar*0.1, LFNoise2.kr(10)));
	Out.ar(0, In.ar(~bus, 1)) + Out.ar(3, In.ar(~bus.subBus(1, 1)))
}.play
)
```
If my idea is implemented in sclang, we can just do:
```supercollider
(
{
	Pan2.ar(WhiteNoise.ar*0.1, LFNoise2.kr(10), 1, [0, 3])
}.play
)
```
[0, 3] is the ChannelsMappingArray

**Comment by jamshark70** [comment]
You don't need to add the Out units.

Nathan already suggested the solution:

```
Out.ar([0, 3], [Pan2.ar(...)])
```

We could reopen this to document the solution but I don't think we need any API changes here. Actually, please let's not make any API changes here. It causes no end of trouble for non-sclang clients.

**Comment by prko** [comment]
Ah, [Pan2.ar(...)]
Now I understand Nathan's suggestion! SC has had the feature what I want to have... Just I had not known the feature... Sorry for my ignorance. Thank you for the explanation!

**Comment by prko** [comment]
```supercollider
{Out.ar([1, 7, 5, 3], [PanX.ar(4, SinOsc.ar, LFSaw.kr(1/10).range(0.1))])}.play
```
This works also well!
The solution is really perfect! Thank you!
