### ISSUE TITLE
a white space as a separator

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3593]
Hi,
Is it discussable to allow the future version of sclang to use a white space as a separator together with a comma?
In the examples below, I think the examples without commas are the simplest way to express the same thing.

e.g. 1:
```
Out.ar(0, SinOsc.ar(440, mul:3, phase:0))
Out.ar(0,SinOsc.ar(440,mul:3,phase:0))
Out.ar(0 SinOsc.ar(440 mul:3 phase:0))
```
e.g. 2:
```
[1, 2, 3, 4, 5]
[1,2,3,4,5]
[1 2 3 4 5]
```
e.g. 3:
```
fork{ [30, 40].do{ arg i, j; [j, i.squared].postln; 0.5.wait } } 
fork{ [30,40].do{ arg i,j; [j,i.squared].postln; 0.5.wait } } 
fork{ [30 40].do{ arg i j; [j i.squared].postln; 0.5.wait } } 
```
e.g. 4:
```
x = {arg a=0, b=3; a + b}
x.(3, 4)

x = {arg a=0,b=3; a+b}
x.(3,4)

x = {arg a=0 b=3; a+b}
x.(3 4)
```

**Comment by miguel-negrao** [comment]
I'm against this. This would be yet one more syntax that can confuse people.

**Comment by brianlheim** [comment]
You can do this with the pipe notation for args.

I would strongly say No to this. Increases opportunities for programmer errors and increases the number of "dialects" for no practical gain.

**Comment by brianlheim** [comment]
Also, it introduces some ambiguous (i.e. impossible to resolve) parsing situations, e.g. `SinOsc.ar(440 mul: 3)`. `mul` could be parsed either as a keyword argument to SinOsc.ar or as a keyword selector on 440.

**Comment by jamshark70** [comment]
IMO Brian's last comment is the decider -- because that issue isn't a matter of taste or complexity, but rather one of technical impossibility. Computer languages can't tolerate strings of input with several equally valid interpretations.

"A comma walks into a bar, where it spends the evening watching the television getting drunk and smoking cigars." ... wait, the TV is getting drunk?

^^ Same problem.

You could resolve the ambiguity by forcing parentheses for any terms with spaces -- `SinOsc.ar(440 (mul: 3))` -- but this requires more characters than the original version with a comma. If the point was to reduce typing, it won't work. If the point was to look different, there's not much gained from it.

It's worth brainstorming ideas -- thanks for the suggestion -- but I think we can close it.

**Comment by prko** [comment]
The point of suggestion was simply to reduce typing.
Thank all of you for the kind answers.
I close this issue. ^^
