### ISSUE TITLE
Variable declaration/assignment behaves differently interactively than in scripts

### ISSUE THREAD

**Issue by wasamasa** [supercollider/supercollider#3606]
Take the following code snippet:

```supercollider
var x = 42;
"x = %\n".postf(x);
exit(0);
```

If I evaluate it with `sclang test.sc`, it prints "x = 42" as expected. However if I run `sclang` and paste each line on its own, "x = nil" is printed. If you modify the code to separate declaration from assignment, it behaves correctly both when run in a script and interactively.  I couldn't find any documentation clarifying this behavior, only about assignment syntax and scoping. What is going on here?

OS: Arch Linux.
Reproducible with "sclang 3.9.2" and "sclang 3.9.2 (Built from branch 'develop' [3f0d27bf5])".
Plugins: No plugins whatsoever.

**Comment by brianlheim** [comment]
Your first statement shadows the global variable `x` with a local variable. Variables declared with `var` do not persist across invocations of the interpreter (each new statement given to the command-line interpreter counts as a separate invocation). When you run the interpreter by passing a filename, the entire contents of the file are executed as a single statement, which is why you're seeing a difference. Consider what would happen if you replaced `x` with an identifier that isn't a single letter:

```supercollider
var val = 42;
"val = %\n".postf(val);
exit(0);
```

You would get an error if you tried to run it one line at a time, because `val` isn't available to the second statement.

This is why it's more common in SC to use environment variables or the single-letter global variables instead of `var`s. You could get the behavior you're looking for with one of:

```supercollider
x = 42; // assigns to Interpreter.x
"x = %\n".postf(x);
```
or
```supercollider
~x = 42; // assigns to a new environment variable named x
"x = %\n".postf(~x);
```

**Comment by wasamasa** [comment]
Wow, that's kind of surprising, but makes sense. All other REPL-driven environments I've used so far support creating new values incrementally, I didn't even consider that the identifier length would change the behavior.

**Comment by jamshark70** [comment]
> I didn't even consider that the identifier length would change the behavior.

Technically, identifier length isn't exactly the right explanation.

`var x` and `var foo` are both local to the scope in which they're defined. Every block of code submitted to the interpreter (single line or multiple) compiles to a Function object, which is then evaluated. `var` declarations are local to that function. The next block of code compiles to a new function object, which has its own local variables and can't access previous functions' variables. Identifier length makes no difference to these variables' scope.

It happens that SC defines 26 single-letter variables, which persist. When your first test printed nil, you were accessing the *interpreter* variable `x`, which is totally separate from the `var`.
