### ISSUE TITLE
undocumented: Dictionary.getPairs returns `nil` on empty dictionary

### ISSUE THREAD

**Issue by wasamasa** [supercollider/supercollider#3617]
To quote the manual:

> method::getPairs
> Return an link::Classes/Array:: with all keys and values pairwise.

`Dictionary.new.getPairs` evals to `nil`. This contradicts the documentation. `Dictionary.new.asPairs` and `Dictionary.new.asKeyValuePairs` do the right thing.  Is this considered a bug?  Why are there three methods doing seemingly the same thing?

**Comment by wasamasa** [comment]
If they're intended to do the same, it would be better to not have three different implementations and instead have an alias to one implementation. That would avoid inconsistencies such as one of them behaving differently for an empty dictionary.

**Comment by telephon** [comment]
Sorry, I wasn't very clear: they are not intended to do the same.

It is intentional that `getPairs` returns `nil` for an empty dictionary. The symmetric method `putPairs` also accepts `nil` as argument.

By contrast, the methods `asPairs`  return an instance of `Array`, which is mirrored by `asDict`, the complementary method which can be sent to an array.

While some of the differences are historical, and it might be nice to bring them together one day, it isn't inconsistent at all. If you always want an Array back, then just call `asPairs`.

**Comment by wasamasa** [comment]
Then the documentation should mention this. And yes, I've changed my code to use `asPairs`. Still not sure why I'd pick that over `asKeyValuePairs`.

**Comment by telephon** [comment]
if you don't want to supply the class of the pairs, both work the same.
