### ISSUE TITLE
documentation: the behavours of **2 and .pow(2)

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3621]
Hi, according to the help document:

> **
> Exponentiation. When used with UGens which produce a negative signal this function extends the usual definition of exponentiation and returns neg(neg(a) ** b). This allows exponentiation of negative signal values by noninteger exponents. For the normal behaviour use pow (see below).
> 
> pow
> Exponentiation.

However, evaluating the following code
```supercollider
{[SinOsc.ar**2, SinOsc.ar.pow(2)]}.plot
```
returns the same result of both operators.
I am confused because it seems that `SinOsc.ar.pow(2)` does not work according to the help document.
The following expression:

> For the normal behaviour use pow

means that .pow(2) does not produce negative values. Doesn't it?

best,
prko

**Comment by jamshark70** [comment]
I wonder if this ever worked. According to https://github.com/supercollider/supercollider/blame/develop/SCClassLibrary/Common/Core/Object.sc#L608, `**` has translated into `pow` for the last 16 years (one of James McCartney's own early commits). There is no `UGen:**` implementation to override this and pass a different operator name into the SynthDef.

So the documentation is currently flatly wrong. Good intention, but sclang eliminates the distinction, and AFAICS, BinaryOpUGens.cpp implements `pow` in the JMc signal-processing way rather than the strict math way.

**Comment by telephon** [comment]
If you want to get past it, you can use complex power:

```
a = Complex(-2, 0);
b = a ** 2;
b.real == 4
```

But I see that one doesn't always want that, it's much less efficient …

**Comment by geoffroymontel** [comment]
So what would be the best way to fix that ? Keep it as it is and change the documentation only ?

**Comment by ajbt** [comment]
The fix to the documentation removed all reference to the fact that both pow and ** behave in an unusual manner -- as far as I can tell, there's now no mention anywhere in the docs that pow / ** behave this way (which confused me for quite a long time, and also upset my ears!).
Could the documentation be updated to include a description of this behaviour, please?

**Comment by elgiano** [comment]
Good point! Thanks!
I agree it would be better if we put back the following, this time under pow:
> When used with UGens which produce a negative signal this function extends the usual definition of exponentiation and returns code::neg(neg(a) ** b)::. This allows exponentiation of negative signal values by noninteger exponents.
