### ISSUE TITLE
classlib: File.mkdir should fail on failure

### ISSUE THREAD

**Issue by brianlheim** [supercollider/supercollider#3635]
As pointed out in #3633, `File:*mkdir` just prints a warning if it fails to complete. This makes checking for failure impossible. It should instead fail in some helpful way, like internally throwing an exception or returning a nonzero error code.

**Comment by jamshark70** [comment]
Yeah, I just ran into this myself.

Probably all of the file primitives should be checked. It looks like they assume everything is just going to work (a quite remarkable assumption for software engineers to make).

I think I'll add sclang as a component, since the primitive will have to return the error code.

**Comment by brianlheim** [comment]
> It looks like they assume everything is just going to work (a quite remarkable assumption for software engineers to make).

Remember that many of the boost.filesystem calls in that code are the throwing versions. The wrapping primitive doesn't need to return an error code in this case.

**Comment by jamshark70** [comment]
FWIW, yesterday I lost 6 of 25-30 student recordings (about 20% failure rate) because, despite adding `File.mkdir(Platform.recordingsDir)` into my code, there's no reliable way to detect failure and warn the user.

If someone can point me to the error-throwing version of boost mkdir, I'll be happy to submit a PR.

IMO this shouldn't be "future" -- it should be 3.10. Lost data from a live performance is not acceptable.

**Comment by brianlheim** [comment]
@jamshark70 it's easy to find the reference documentation for boost.filesystem with a quick google search. Throwing behavior is clearly defined there

**Comment by joshpar** [comment]
https://www.boost.org/doc/libs/1_49_0/libs/filesystem/v3/doc/reference.html#create_directory

bool create_directory <>(const path& p, system::error_code& ec);

Should be what you’d want to use.

Best,

Josh

**Comment by jamshark70** [comment]
Thanks @joshpar, I'll try to make a PR today.

@brianlheim It was a really busy week last week, like, come home and collapse on the sofa busy. I'm doing the best I can here.

**Comment by brianlheim** [comment]
Closed in #3813. Thanks for the PR @jamshark70 !
