### ISSUE TITLE
SC-IDE with Qt5.11 does not respect a dark screen theme

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#3792]
Screenshot attached. The colors are wrong in the:

- Menu bar
- Document tabs
- Documents panel
- Separator between the code window and post window
- Status bar

Other window elements with wrong styling that I noticed later:

- Scrollbars
- Auto-completion pop-ups
- File dialogs

At this point I have to assume that everything not under control of the editor theme is incorrectly styled ... which is, kind of a lot.

**Use case** (i.e. why is this important, beyond just "looks bad"?) -- I use SC for live coding performances, projecting my screen as part of the performance. That means the IDE is *audience-facing*, not only user-facing. Performance spaces (livehouses, bars etc.) are typically dimly lit. Uncontrolled bright screen elements are disruptive.

I'll try to figure out how to hack it for my purposes, but a/ I don't know where to look and b/ experience tells me that it eventually will be unsustainable to track multiple local patches for issues that I can't live with and which don't have a proper solution yet. We really should have the window follow the system theme.

(But, ooh, just noticed, the font anti-aliasing is much improved.)

SCDevelop:

![sc-ide-bad-colors](https://user-images.githubusercontent.com/318301/41517387-253975e6-72ed-11e8-8aea-77dc52d97863.png)

SC3.9:

![sc-ide-3dot9-colors](https://user-images.githubusercontent.com/318301/41522909-a7fdbe2a-730a-11e8-8293-5ce17ff11cc0.png)

**Comment by jamshark70** [comment]
Oh, one other element -- scrollbar colors are light too.

**Comment by jamshark70** [comment]
Couple of other observations:

- http://doc.qt.io/qt-5/qtquick-usecase-styling.html says "The SystemPalette type provides information about the system's palette information" but grep says the IDE codebase contains no reference to SystemPalette. But, I retested the IDE in 3.9 (against the older Qt version) and it *does* use system colors for window borders, scrollbars, autocompletion menus etc. So, in the past, Qt's default behavior might have been to pick up the system theme, but now we have to do it explicitly.

  - "When using the [Qt Quick] controls, the system colors are already used." -- I guess we aren't using Qt Quick, then?

- Our `style.cpp` file includes a lot of functions that pass in `const QStyleOption * option` where we then do `option->palette.blahblah()`. But I don't see yet where the style options are populated. Possibly, if it's done there, then it might affect the entire environment.

For comparison, here's 3.9:

![sc-ide-3dot9-colors](https://user-images.githubusercontent.com/318301/41522909-a7fdbe2a-730a-11e8-8293-5ce17ff11cc0.png)

**Comment by brianlheim** [comment]
> Oh, one other element -- scrollbar colors are light too.

> EDIT: And auto-completion pop-ups.

James, you sometimes have a habit of reporting across multiple comments... would you mind please just updating the top ticket comment? It makes it a lot easier to follow.

**Comment by jamshark70** [comment]
OK, done.

**Comment by snappizz** [comment]
weird. qt claims that it tries to match native styles by default. but even if i remove this line in the scide main function so that we strip away any possible interference due to custom styling...

https://github.com/supercollider/supercollider/blob/60919df45b75aff9b3966f418a9b725fee0bcdc4/editors/sc-ide/core/main.cpp#L84

...i still get a GUI look that doesn't match native. qt's own development apps also have the same look. could someone try setting up a small Qt project with default styling and see if they also have this style? if so, that would verify my suspicion that this change is the fault of Qt.

whether or not that's the case, i wonder if we can just take this opportunity to unify the appearance of the IDE across *all* platforms, and offer dark and light GUI theme options to the user.

**Comment by snappizz** [comment]
it seems that the best way for us to edit the IDE colors is to use stylesheets (.qss files). a cool thing is that these are already supported by scide thanks to some default qt magic. just add the command line option to scide when you run it: `scide -stylesheet=$HOME/stylesheet.qss`

here's an example of a very silly stylesheet so you can make sure it's working:

    QMenu, QMenuBar { background-color: black; color: white; }

**Comment by jamshark70** [comment]
Thanks for the research! I can't play with these today, but I'll try when I can.

**Comment by scztt** [comment]
Stylesheets are not necessarily a great way to style the IDE. I tried this a while ago (there should still be a branch floating around with these changes), and I saw several issues:
1. QT Stylesheets aren't really parameterizable - you're basically stuck with fixed colors, so doing things like e.g. making a "shadow" variant of a color that's slightly darker than a base color is impossible.
2. Stylesheets tend to conflict with QPalette-based colors and any code that directly sets a color. My general impression was that you have to either do 100% stylesheets, or none - it wasn't straightforward to patch in StyleSheet specifications while keeping other color logic the same.
3. I seem to remember some OS-specific color things (like theme-related font colors etc) flowing through the QPalette pathway - this would come into conflict with styling in stylesheets. Basically: when I styled the IDE a bunch with stylesheets, it looked great on Mac where the theme is fixed, but looked like garbage on linux because it didn't respect basic theme things.

I'd encourage anyone that wants to test this to try to revive the [ui-refresh](https://github.com/supercollider/supercollider/tree/topic/ui-refresh) branch and see if there are pathways to making the stylesheet system more flexible.

**Comment by snappizz** [comment]
thanks scott, this is very useful info.

as for parameterizing stylesheets, i just checked and it doesnt seem like they support the new-fangled [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables), which is a shame. i'm not wild about bringing in sass/less as a dependency either -- it's not hard to build your own miniature preprocessor, but it does add a layer of complexity in maintaining the system.

**Comment by jamshark70** [comment]
I might not be understanding fully, but -- does the IDE *need* QPalette?

sclang GUIs depend heavily on QPalette, and I'm not suggesting to make sclang use stylesheets. My startup file does `'QtGUI'.asClass.palette = 'QPalette'.asClass.dark;` and I'm generally happy with that.

But in the IDE, I don't see that we will need to manipulate colors programmatically. I can see that it's useful to refer to a color and darken it 50%, and stylesheets don't support that presently, but if QPalette can no longer read GTK2 themes without extra help (which seems to be the gist of the threads Nathan found), maybe the better solution is to style the IDE by ourselves and not rely on the system.

**Comment by scztt** [comment]
Style sheets generally

**Comment by prko** [comment]
Is it possible to affect the help browser as well?
For me, it seems to be unbalanced that the background colour of the help browser is not affected by dark mode. I think it would be great that SC-IDE theme modifies scdoc.css automatically.

**Comment by brianlheim** [comment]
@prko That's kind of off topic for this ticket, but feel free to open a new one if there isn't one for it already.

**Comment by lnihlen** [comment]
![screenshot from 2018-08-01 22-20-13](https://user-images.githubusercontent.com/1123536/43563962-4edaa672-95d9-11e8-9ed0-bf2527e15fe2.png)

Update: here is the window elements rendered in a hard-coded white-on-black theme. My window manager is not currently set up to render dark so the border elements are still light. Also the IDE widget has its own settings options to set colors, here they are at the default black-on-white theme. Also note the log window and help window provide their own palettes.

So there doesn't seem to be a mechanism on Linux to query the current system colors of the operating system. I could see a couple of options here:

a) On Linux we query the IDE color settings and force the window elements (+ possibly the help and log widgets) to follow the same color scheme as the IDE, for consistency.

b) We add settings to allow the user to specify colors for these other elements.

c) Somebody has a better idea?

**Comment by prko** [comment]
@brianlheim  
#1919 is very similar. I think a new issue may not be necessary.

**Comment by jamshark70** [comment]
@lnihlen gets a beer from me. Now I can look at the IDE again without facepalming. Thanks!

**Comment by atlllas** [comment]
Hey guys, what's the simplest way to change the theme to darkmode?

Couldn't find any settings for this in the IDE

I'm new to programming, and just discovered supercollider today.

**Comment by nhthn** [comment]
@atlllas Hi, go to Edit -> Preferences (or SuperCollider -> Preferences on macOS) and go to Editor -> Font and Colors. The dropdown lets you pick a few different themes.
