### ISSUE TITLE
Unable to call .degrad on UGen

### ISSUE THREAD

**Issue by patrickdupuis** [supercollider/supercollider#3817]
It is currently not possible to call `.degrad` on a UGen. The error message:
```
The preceding error dump is for ERROR: Operator 'degrad' applied to a UGen is not supported in scsynth
```
Currently, we are obliged to do a multiplication by `(pi/180)` to convert a UGen's output to radians. The `degrad` operator should be implemented for UGens, just as it is for numbers, functions, and collections.

**Comment by jamshark70** [comment]
The quickest way to do it is as a pseudo-operator:

```
+ UGen {
	degrad { ^this * (pi/180) }
	raddeg { ^this * (180/pi) }
}
```

... which, in a SynthDef, will compile to a single BinaryOpUGen.

I don't see a particular problem with that. There's precedent in UGen.sc to override specific operators with pseudo-UGen implementations (`explin`, `expexp`, `lincurve`, `curvelin`, etc.) when native server support hasn't been added.

The error occurs now because `degrad` uses the implementation from AbstractFunction, `degrad { ^this.composeUnaryOp('degrad') }`, where a `UGen:composeUnaryOp` produces a UnaryOpUGen, which checks the operator's specialIndex to verify server support. Providing `UGen:degrad` would bypass this.

**Comment by brianlheim** [comment]
That seems like a reasonable solution to me!

**Comment by telephon** [comment]
Most of the specific UGen workarounds are there because we still lack n-ary op primitives and ugens.

But this is a unary operator. Normally, it the existing method should already have been added to the primitives in the right place (happened here out of convenience: https://github.com/supercollider/supercollider/commit/242068e11b3a2b945b1035212ff3122b86840e09)

I am fine with the suggested addition, but I'd prefer if it were instead properly implemented, using for example the implementation of `bilinrand`.

It is not that hard.

**Comment by patrickdupuis** [comment]
I agree that this should be implemented properly for the sake of consistency and speed. I'm not sure that I can dive into the world of primitives at the moment. If someone want to take this over, be my guest.

**Comment by brianlheim** [comment]
Why let the perfect be the enemy of the good here? I am happy to work with #3821 as is.

**Comment by patrickdupuis** [comment]
The good, the bad, and the never finished because it isn't perfect enough...

**Comment by patrickdupuis** [comment]
I think that I would be nice if it were as fast as possible, thinking ahead to Rpi improvements down the road.

**Comment by jamshark70** [comment]
> I'm not sure that I can dive into the world of primitives at the moment.

For the sake of precision: This is about an operator implementation in the server. Primitives are part of the language. No primitives need to be added to address this.

The "proper" implementation would be to add the operators into UnaryOpUGens, and give them both their own specialIndex.

But I don't see the point, really. It will not be faster than the BinaryOpUGen produced in the initial proposal.

**Comment by telephon** [comment]
As I said, I'm fine with the current PR as it is.
