### ISSUE TITLE
[feature request] - binding the several existing language bindings into a single distributed IDE

### ISSUE THREAD

**Issue by tmm2018** [supercollider/supercollider#3838]
#### [feature request] - binding the several existing language bindings into a single distributed IDE

Supercollider currently provides support for different languages, thanks to mappings via opensoundcontrol (OSC) from the interpreter to the scsynth.

One really cool feature that strikes me in processing is:
- the ability to use the same IDE to use different language bindings

It would be cool if we:
- could bind the Supercollider IDE to several languages simultaneously

This would allow us to:
- develop for different languages using the same IDE

IMHO:
- that could benefit the community, and making SC3 an even more awesome language

these things are already available and the community is using them, so:
- why not gluing them together?

please drop your comments, and let me know what do you think about this idea;

looking forward
kind regards/best regards
Tiago

**Comment by Sciss** [comment]
I can only speak for ScalaCollider, but I estimate this goes for all other languages as well: There is not just "bindings", but the entire client library is different, and consequently the API as well, even if in many cases it is closely modelled after ScLang. So the benefit of using the same IDE is quire marginal IMHO. You would have to literally adapt the menu structure, the help system, etc. so that in the end you basically rewrite the entire IDE, only to look slightly familiar... Each language also comes with their "tooling culture", so I guess Clojure people have their preferred editors, Scala people have theirs, Haskell people have theirs, etc.

So while it's a nice idea, I don't think it is any feasable (without even talking about the mere resources required to implement this)

**Comment by tmm2018** [comment]
@Sciss i understand your insight, and i honestly see it as valid and respect. maybe we should also listen to others. and see what other people have to say about this. i think it's ok if people don't want to proceed with this idea, although IMHO I see it as an interesting feature for enhancing supercollider

**Comment by brianlheim** [comment]
@Sciss's comment explains the problems with this idea pretty well I think. There is marginal benefit for us in sinking time into it.

**Comment by jamshark70** [comment]
The IDE is an acceptable environment for coding SC, but if you look at the features of Eclipse for Java, or any number of dedicated editors for C++, our IDE is,  frankly, feature-poor, and we don't have the development resources to compete with Atom or Sublime Text or even Emacs(!) on their own turf.

Better, IMO, would be to reduce coupling between sclang and the IDE (eg HelpBrowser methods that now currently talk only to the IDE's help panel) and improve sclang support for other editors.

**Comment by tmm2018** [comment]
it's ok for me. although I share the opinion, that we could integrate some stack from the atom into supercollider, I see your point about, not being the current direction in terms of development for the community, and wanting to stay aside from merging it. for me, it's ok to close this thread, although I don't share the same opinion as you guys. however, I see that it would require a lot of effort in terms of development, and there may be more priority things ATM.
