### ISSUE TITLE
cell spanning in SCHELP

### ISSUE THREAD

**Issue by prko** [supercollider/supercollider#3846]
What do you think about to have cells span across rows and columns in schelp?
```HTML
<table style = "border:1px solid black">
  <tr>
    <td colspan="2", style = "border:1px solid black">hello</td>
  </tr>
  <tr>
    <td style = "border:1px solid black">hello</td>
    <td style = "border:1px solid black">hello</td>
  </tr>
  <tr>
    <td rowspan="2", style = "border:1px solid black">hello</td>
    <td style = "border:1px solid black">hello</td>
  </tr>
    <tr>
    <td style = "border:1px solid black">hello</td>
  </tr>
</table>
```
You can paste the code above in https://html-online.com/editor/ and see the table.

**Comment by brianlheim** [comment]
Can we please have bikeshedding-type discussions somewhere else than the issue tracker? The mailing list and Slack are better venues for spitballing these kinds of ideas.

**Comment by prko** [comment]
Hi, it is a request written in a question style.
I did not think that it could be interpreted as in opening a discussion.
I am sorry for it.

**Comment by brianlheim** [comment]
@prko No need to apologize. @telephon is right, we have a lot of open issues and I am trying to limit new issues to more serious concerns at this point. Issues like this can be hard to act on, because some of the things we normally look for in a ticket are missing - why is this change better? who is going to implement it? The issue stays open not because it's necessarily a good idea or something we plan to do, but because nobody is interested enough in it to add their response. That leads to frustration over time for people that maintain the project.
