### ISSUE TITLE
Quarks.install fails silently

### ISSUE THREAD

**Issue by johnsdba** [supercollider/supercollider#3967]
Bug description:
I have install SuperCollider 3.93 64 bit on windows, and it seems I can't get anything to work on this laptop...

* Quarks.install("FoxDot") does nothing. It highlights the line but no output. Same when I try to run
Quarks.install("https://github.com/supercollider-quarks/UnitTesting.git"). I have git installed. Also, I noticed when I typed Quarks, the autocomplete didn't kick in.

 * on the Help browser, it shows "Sending request..." that never goes away

* When I pick 'recompile class library' I get no output, but also no error.

Is there a log file somewhere that will help me figure out what's going on? I've installed SuperCollider/FoxDot on other computers successfully following the same steps.

Sorry, this is more of a request for help than a bug fix.

I've tried uninstalling, reinstalling, different versions, but still no luck.

Thanks

**Comment by jamshark70** [comment]
I'm unclear of the exact steps you took - important because I can't tell from the issue description if the Quarks problem is causing the other two, or if they are separate problems.

Side note: Is git installed on your Windows machine? This is required for Quarks to download packages automatically.

Back to the problem:

One possibility is that you ran the Quarks line, which caused the interpreter to hang waiting for the command to complete. If the interpreter is hanging, then both help and library compilation might fail. "No output" sounds like this sort of hang.

Or, the interpreter's installation is broken somehow and this causes help and Quarks to fail.

In general, when testing, start with the simplest things. Quarks.install is complex -- a hundred things to check. `1+1` is simple. If even that is broken, then we have to step back from Quarks and fix that first.

Suggest these steps to get more detailed info:

1. Launch sc-ide. What happens in the post window?

2. Close the help browser.

3. Quit and relaunch the IDE. (Having the help browser closed makes the startup process simpler. We want to start with the simplest possible sequence.)

4. Run `1+1`. What happens in the post window?

**Comment by JordanHendersonMusic** [comment]
Closing because its stale. @johnsdba, feel free to reopen if you want to provide more information!
