### ISSUE TITLE
[Feature/Enhancement] Docstring-like functionality in SuperCollider?

### ISSUE THREAD

**Issue by jreus** [supercollider/supercollider#4044]
Hey ya'll, 
I was curious if it has been discussed at any point to develop a kind of docstring like functionality in SuperCollider? Most quarks and extensions come without documentation files, and I can imagine having a docstring convention would allow basic documentation files to easily be generated straight from the source code. Generally I can imagine programmers to be more motivated to include in-line comments (that are useful for other, non-altruistic, reasons) vs. fleshing out documentation pages. 

I'm thinking of the docstring conventions of Java, or one of the many Python docstring conventions, as a starting point...

Python "Google" docstring format:
```
def func(arg1, arg2):
    """Summary line.

    Extended description of function.

    Args:
        arg1 (int): Description of arg1
        arg2 (str): Description of arg2

    Returns:
        bool: Description of return value

    Raises:
        AttributeError: The ``Raises`` section is a list of all exceptions
            that are relevant to the interface.
        ValueError: If `arg2` is equal to `arg1`.

    Examples:
        Examples should be written in doctest format, and should illustrate how
        to use the function.

        >>> a=[1,2,3]
        >>> print [x + 3 for x in a]
        [4, 5, 6]

    """
    if arg1 == arg2:
        raise ValueError('arg1 may not be equal to arg2')
    return True
```

Java documentation format:
```
/**
 * Returns an Image object that can then be painted on the screen. 
 * The url argument must specify an absolute {@link URL}. The name
 * argument is a specifier that is relative to the url argument. 
 * <p>
 * This method always returns immediately, whether or not the 
 * image exists. When this applet attempts to draw the image on
 * the screen, the data will be loaded. The graphics primitives 
 * that draw the image will incrementally paint on the screen. 
 *
 * @param  url  an absolute URL giving the base location of the image
 * @param  name the location of the image, relative to the url argument
 * @return      the image at the specified URL
 * @see         Image
 */
 public Image getImage(URL url, String name) {
        try {
            return getImage(new URL(url, name));
        } catch (MalformedURLException e) {
            return null;
        }
 }
```

thoughts?

best
Jon

**Comment by snappizz** [comment]
hi jon, thanks for your input -- this is a useful idea and i think it would help a lot. unfortunately, i don't think any of SC's current regular contributors will be able to work on this soon, so i'm going to have to close.

the sclang lexer/parser/compiler code base is a huge mess that needs a lot of refactoring before something like this can be implemented properly. also, i think it would be more productive to focus efforts on fixing its numerous bugs like #52 rather than adding new (and fairly complicated) features.

if you'd like to help out and dig into contributing to the language, feel free to take a look at the bison grammar in `lang/LangSource/Bison/lang11d`.
