### ISSUE TITLE
IDE Document tab too large for space when many documents open

### ISSUE THREAD

**Issue by txmod** [supercollider/supercollider#4167]
Environment
-----------

* Your SuperCollider version: 3.10.0-rc1
* Your operating system and version: MacOS 10.11.1

Current Behavior
----------------
If I have many documents open in the IDE (20+), when I select one, the document name in the tab on the top row becomes bold and then is a bit too wide for the tab space it's in.

**Comment by brianlheim** [comment]
thanks @txmod 

please open a single ticket per issue, this makes it easier to discuss and triage

last issue is related to #3882, please add your note there and remove it from this post.

**Comment by txmod** [comment]
Yes, sorry about that. 
The last issue is the same issue as  #3882, so no need to add a new note there, but for some reason I am unable to edit my post to remove it (maybe because I am using an older computer online).

Best,
Paul

**Comment by brianlheim** [comment]
Can repro on macOS 10.13

<img width="406" alt="image" src="https://user-images.githubusercontent.com/15369640/49053343-5effd800-f1b5-11e8-8d52-7d024b96b981.png">

Since this has to do with the scaling of the text we could try to add padding based on how wide the text will be when bold (I think this is not too hard to compute in Qt).

**Comment by brianlheim** [comment]
After a quick look at http://doc.qt.io/qt-5/qtabbar.html and http://doc.qt.io/qt-5/qwidget.html I don't see an easy way to fix this. In fact a bug has been reported in https://bugreports.qt.io/browse/QTBUG-6905

I'm closing this here because the fix can (and should) only come from upstream.
