### ISSUE TITLE
[develop] String:findRegexp handles empty results incorrectly

### ISSUE THREAD

**Issue by jamshark70** [supercollider/supercollider#4239]
Environment
-----------

* Your SuperCollider version: develop branch (0685eb153)
* Your operating system and version: Ubuntu Studio 16.04

Steps to reproduce (for bugs)
-----------------------------

```supercollider
// 3.10:
"abc".findRegexp("def");
-> [  ]

// current develop branch:
"abc".findRegexp("def");
-> def
```

Expected Behavior
-----------------

If `String:findRegexp` doesn't find any matches, it should return an empty array.

Current Behavior
----------------

Between 3.10 and develop, the behavior changed so that an empty result returns the regular expression as a string.

https://github.com/supercollider/supercollider/blame/develop/lang/LangPrimSource/PyrStringPrim.cpp#L416

^^ I'm guessing this is the issue. Right above this line, there is something new to advance the stack (comment says "to avoid overwriting receiver"). But if the match result is empty, now we simply return without un-advancing the stack -- so the returned result is wrong.

I suppose the fix is trivial, but I am not good with GC details.

User impact: I use `findRegexp` extensively in ddwChucklib-livecode. It's impossible to evaluate any cll statements in the current develop branch.

**Comment by brianlheim** [comment]
thanks for reporting this @jamshark70 . it looks like the solution is just to remove that line altogether since the loop will be skipped anyway if `match_count == 0`. (then add a basic unit test.)

btw, i gave #4192 another look to make sure no similar errors were introduced; the other changes are fine as they don't involve early exits. i should have caught that in review, my apologies.

[cc @muellmusik ]

**Comment by jamshark70** [comment]
Tried it and it works. #4241 :sunglasses:
