### ISSUE TITLE
LV2 support

### ISSUE THREAD

**Issue by fpesari** [supercollider/supercollider#4540]
## Motivation

LV2 is the most widely supported plugin format on GNU/Linux and the successor to LADSPA and DSSI. 

It's an open standard which has a solid implementation, and it can be hosted in DAWs such as Ardour, QTractor and MusE, audio editors such as Audacity and standalone via hosts.

## Description of Proposed Feature

SuperCollider has many capabilities which could help authors of plugins such as synthesizers and effects.

Right now, LV2 plugin development usually involves writing C or C++ code, which is efficient if properly written but not really readable and has to rely on third party libraries for DSP and MIDI.

Things have been changing lately: [FAUST](https://faust.grame.fr/doc/manual/index.html#faust2lv2) officially supports compiling to LV2 plugins, while an external [plugin for Pure Data](https://github.com/x37v/pdlv2) allows running Pure Data patches.

## Plan for Implementation

For now, it would be enough to run a SuperCollider client as a LV2 plugin, so that SuperCollider scripts can be easily be run from any DAW that supports LV2. Even doing something as simple as hot reloading a SuperCollider script could be useful.

Later, things could be made easier for plugin writers by automatically generating LV2 plugins from SuperCollider code. Of course, most of the work could be moved to the server so that people could write LV2 plugins easily from external clients like Overtone.

**Comment by jamshark70** [comment]
In principle, a nice idea. I have no idea who is prepared to do the work though.

> For now, it would be enough to run a SuperCollider client as a LV2 plugin...

I think you mean the server? Only the server outputs audio. The language client does not output audio, so very likely any LV2 hosts would not know what to do with it. (I suppose in theory one could run an sclang and boot an internal server.)

There's precedent for running SC audio as a plug-in in the SC Audio Unit module, but I'm not sure of the current status. At one point it was abandoned because it didn't attract a lot of users.

I have a feeling, though, that in Linux it would be easier to boot the server with a large number of IO channels and use e.g. Ardour external bus effects to pipe audio in and out via Jack. You can do that today, while LV2 is very likely to be a long-term project, and probably not as high priority as fixing outstanding bugs.

**Comment by snappizz** [comment]
hi fabio, thanks for bringing up this interesting question!

james is right -- SC is (at least) two processes, not one, and this makes SC especially tricky as a plugin in another environment. plus, integration with tempo/automation/MIDI/etc isn't straightforward at all.

i'm sorry but i'd like to vote to close this question since it's unfortunately too far off from current project priorities.

**Comment by fpesari** [comment]
Hello, I understand. If possible, please leave this issue open, so that if someone implements a way to use SuperCollider from LV2 they can share it here, where most people coming from search engines will probably land.

**Comment by snappizz** [comment]
i understand your concern, but our (informal) protocol is to close large scale feature proposals unless work is under way to implement them. we're saddled with 500+ open issues, which is already seriously overwhelming for maintainers, so we have to be pretty aggressive about closing things to keep that number from climbing even further.

**Comment by brianlheim** [comment]
> if someone implements a way to use SuperCollider from LV2 they can share it here, where most people coming from search engines will probably land.

Closed issues are also indexed by google. Sorry, but I have to agree with @snappizz, there is not much point keeping this open right now.
