### ISSUE TITLE
Document.initAction not called from the editor

### ISSUE THREAD

**Issue by KoltesDigital** [supercollider/supercollider#4549]
## Environment

* SuperCollider version: 3.10.0
* Operating system: Win 10 64b

## Steps to reproduce

```supercollider
Document.initAction = { "initAction called".postln; }
```

Then `Ctrl+N`.

## Expected vs. actual behavior

Message is shown when using `Document.new` and `Document.open`, but not when using the File menu or keyboard shortcuts. However the latter cases do create documents, because `Document.allDocuments` changes. Therefore I expect that `initAction` is called in all these cases.

**Comment by jamshark70** [comment]
Aha... Windows. There are several open issues about losing the Document sync IPC. Probably, if we can get to the bottom of that, then all of those issues disappear at once.

**Comment by KoltesDigital** [comment]
IPC? Isn't it only a problem within ScIDE?

**Comment by jamshark70** [comment]
No. `initAction` is a sclang function. The IDE cannot evaluate functions. It can only tell the language to evaluate them. They are separate processes, so some form of IPC must be involved.

But actually, I just looked again -- it's a general bug.

- Document.new and Document.open go through a method `prAdd` to add the new document to the collection. This method *does* evaluate the initAction.

- IDE document actions go through `Document.syncFromIDE` -- this method overlooked the initAction.

So it turns out that it isn't Windows-specific, and it doesn't have to do with IPC. It's just that something was made more complex at some point, and initAction ended up not being implemented across the board.

**Comment by KoltesDigital** [comment]
Ah indeed I confused sclang and the IDE, it makes sense.

**Comment by jamshark70** [comment]
**Question for developers:**

The cause of the issue seems to be that https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/scide_scqt/ScIDE.sc#L499 adds directly to the `allDocuments` collection, instead of going through `Document:prAdd` as `*new` and `initFromPath` do.

- `*syncFromIDE` -- called by "New" or "Open" document actions in the IDE; *no* `initAction` or autorun. Also called after library recompilation (to rebuild `allDocuments`).
- `Document.new` -- calls `prAdd`; `initAction` and autorun take effect.
- `Document.open` -- calls `prAdd`; `initAction` and autorun take effect.

It's easy to replace line 499 with `doc.prAdd;`.

But, because the document autorun feature (begin a document with `/*RUN*/` and its code will execute automatically) is implemented in `prAdd` -- if we use `prAdd` in `syncFromIDE`, then:

- `initAction` is executed for every document after library recompilation. I think that's good.
- `/*RUN*/` documents will execute *every time* after library recompilation. I'm not sure about that.

This autorun feature seems poorly defined (no spec). Of course you would want it to fire when opening a document that starts with `/*RUN*/` -- but the library-recompile is not opening the document.

If you're still with me... to fix this issue, we need to decide what to do with autorun.

- Dump it.
- Or, define it as occurring when opening a document or during library init. (Easy to do now.)
- Or, define it as occurring only when opening a document. (Requires distinguishing between different uses of `syncFromIDE`.)

Asking here because... I could submit a PR implementing the second option, but then we would be woodshedding in the PR discussion, which is generally discouraged. So... any thoughts?

**Comment by dyfer** [comment]
Thanks @jamshark70 for investigating!

> * Or, define it as occurring when opening a document or during library init. (Easy to do now.)

It seems that this is how this worked back in the Cocoa days.

> * Or, define it as occurring only when opening a document. (Requires distinguishing between different uses of `syncFromIDE`.)

I would think that this would be closer to the desired behavior, but since the original behavior was to have autorun both on document open and on library init, we should probably keep that.

I'd also be against dumping this functionality.

**Comment by jamshark70** [comment]
> > Or, define it as occurring when opening a document or during library init. (Easy to do now.)
> It seems that this is how this worked back in the Cocoa days.

Ok, thanks for the feedback! That's an easy PR then. Probably a couple of days later.
