### ISSUE TITLE
I cannot open any video in usual player when SC is active

### ISSUE THREAD

**Issue by vsmelov** [supercollider/supercollider#4600]
## Environment

* SuperCollider version: 3.10.3
* Operating system: Ubuntu 18.04.1 LTS

## Steps to reproduce

When I open SC and FoxDot and start play and I want to open some YouTube tutorial to follow, when I open browser tab it does not play any video :-) and in VLC player I also cannot play anything

It looks like SC acquire some audio device and all other applications cannot use it
```
-> FoxDot
Booting server 'localhost' on address 127.0.0.1:57110.
Faust: supercollider.cpp: sc_api_version = 3
Faust: FaustJPverbRaw numControls=11
Faust: supercollider.cpp: sc_api_version = 3
Faust: FaustGreyholeRaw numControls=7
Found 0 LADSPA plugins
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 1024
JackDriver: connected  system:capture_1 to SuperCollider:in_1
JackDriver: connected  system:capture_2 to SuperCollider:in_2
JackDriver: connected  SuperCollider:out_1 to system:playback_1
JackDriver: connected  SuperCollider:out_2 to system:playback_2
SuperCollider 3 server ready.
JackDriver: max output latency 42.7 ms
Requested notification messages from server 'localhost'
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
```

## Expected vs. actual behavior

Expected: I can watch video in the same time.
Actual: I cannot.

How can I play with FoxDot and watch YouTube at the same time? :-)
Or at least how to release media device in SC and then acquire it later? :-)

**Comment by jamshark70** [comment]
1. Recommended to start the JACK server before starting SC, using a tool like cadence or qjackctl.

2. Recommended to configure JACK and PulseAudio so that Pulse (which handles audio from your web browser) plays *through* JACK. Then, instead of the two fighting over the soundcard, they cooperate. I've been doing this for years and it works seamlessly. There are a lot of tutorials online about setting this up.
  - https://askubuntu.com/a/777136
  - https://askubuntu.com/a/681079 (points to a YouTube tutorial)

Unfortunately, if you want to use professional audio applications in Linux, then it does require learning more about audio configuration in Linux. I realize it looks like a SuperCollider bug because you never ran into any conflicts before SC, but this one really isn't SC's fault (so I have to remove the "bug" label -- it isn't a bug). It's rather that there are multiple, conflicting audio systems in Linux and it does take a little extra effort to get them to play nicely together. But it is definitely possible.

**Comment by snappizz** [comment]
hi @vsmelov, thanks for the report. setting up JACK and PulseAudio is kind of a pain in the ass, so i wish you the best in setting this up.

closing as this isn't a bug in SC.
