### ISSUE TITLE
exprand() gives float numbers in spite of integer arguments

### ISSUE THREAD

**Issue by wolfgangschaltung** [supercollider/supercollider#4608]
## Environment
* SuperCollider version: 3.10.3.
* Operating system: 10.14.6 (18G95)
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce
`exprand(1, 10)`

## Expected behavior
* repeated execution should give random integer numbers

## Actual behavior
* repeated execution gives random float numbers
 
## Notes
* My behavior expectations are based on page 7 of "The SuperCollider Book" (The MIT Press, 2011), on which both `rand` and `exprand` are introduced and explained, and the text says about the argument usage:  "As a general rule, if you use a float … as an argument, a float is returned. Integers will return integers."
* While this rule "float in, float out" works for `rand`, it does not for `exprand`.

**Comment by jamshark70** [comment]
The desired probability distribution of exprand is proportional to 1/x (in `exprand(1.0, 2.0)`, a result of 1 is twice as likely as 2), where the desired distribution of rrand is a flat constant: a rectangle.

Getting integers from rrand means chopping up the rectangle into equally sized chunks (one for each possible return value), so the resulting integer distribution has the same characteristic as the original continuous distribution: an equal chance of each possible outcome.

Converting exprand to integers means sampling the 1/x curve at some intervals, and this is not guaranteed to preserve the essential characteristics of the distribution. I believe this is why SC makes no attempt to discretize the results: because it would distort the distribution in a way that does not happen for a flat rectangular distribution.

We leave it up to the user to decide how to turn the results into integers.

I think the book over-generalizes here, and this is not a bug.

**Comment by wolfgangschaltung** [comment]
Thanks for the explanation, closing!
