### ISSUE TITLE
bug with MIDIdef chan argument

### ISSUE THREAD

**Issue by elifieldsteel** [supercollider/supercollider#4613]
## Environment

* SuperCollider version: 3.10.3
* Operating system: macOS 10.14.6
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
/*
I think I have stumbled across a bug in which the chan argument for MIDIdef
does not properly respond when set equal to nil. Regarding the chan argument,
the MIDIdef help file reads:

“An Integer indicating the MIDI channel number for this MIDIdef. This can be
an array. If nil, the MIDIdef will respond to messages received on all channels.”

However, this code produces some unexpected results. To test this code
properly, a MIDI controller capable of sending note-on messages on different
channels is required.

Is this a bug, or is this intended behavior?
*/

//init/cleanup
MIDIIn.connectAll;
MIDIdef.freeAll;

(
//basic note-on def
//successfully responds to all channels
MIDIdef.noteOn(\x, {
	arg vel, num, chan, src;
	[vel, num, chan, src].postln;
});
)

MIDIdef(\x).chan; //returns nil, as expected

(
//overwrite def at key \x
//now only responds to messages on channel 4
MIDIdef.noteOn(\x, {
	arg vel, num, chan, src;
	[vel, num, chan, src].postln;
}, chan:4);
)

MIDIdef(\x).chan; //returns 4, as expected

(
//overwrite to respond to all channels again
//***but STILL only responds to channel 4***
MIDIdef.noteOn(\x, {
	arg vel, num, chan, src;
	[vel, num, chan, src].postln;
}, chan:nil);
)

MIDIdef(\x).chan; //returns 4, unexpected behavior (or is it?)
```

**Comment by jamshark70** [comment]
Probably @muellmusik should weigh in. Here's my thought.

I've thought about this some more since this came up on the forum, and I think the best solution is documentation.

If you do `MIDIdef(\x, ..., chan: 0)` and then, later, `MIDIdef(\x, ..., chan: 1)`, it *happens* to change the channel filtering -- leading to the inference that this is the best or correct way to change a MIDIdef's properties -- especially since there's no `chan_`. (So, on the forum, I thought "we have `nil` meaning "no filtering" and also `nil` meaning "don't change the property" = ambiguous interface = small flaw in the design).

After looking over the implementation, I'm starting to think that the best/safest way to change these properties is to `.free` the MIDIdef first and recreate it -- start from a clean slate.

I can imagine objections -- if you've set several properties and want to override only one of them to be `nil`, it's a bother to have to remember all those properties somewhere. Maybe it's worth implementing `chan_`. But I think we can't afford to change the meaning of `nil` in MIDIdef `*new`.

**Comment by elifieldsteel** [comment]
I'm indifferent on how/if this is addressed. I'm perfectly happy getting into the habit of specifying chan: (0..15) as an alternative to nil in order to bypass channel filtering. I was mostly looking for an explanation for the unexpected behavior.

**Comment by muellmusik** [comment]
Hi both, 

This strikes me as a classic example of the explicit vs. implicit nil design problem, which can arise when nil is used in some meaningful way. It's not a big deal either way, but given where we are with things, I think there's a balance of considerations of convenience – i.e. swapping a proxy's source and leaving its state otherwise changed is a common operation, redefining a proxy in a way that seems kind of like making a new and different one is rather less common (probably why this hasn't come up until now) – and consistency – i.e. for better or for worse other classes behave in a similar way.

So I'd say this is by design, rather than a bug. Certainly documentation can always be refined, but I note it does say in the help "args for which nil is passed will use the old values". James is right that freeing first is one way around this.

Hope that all makes sense.

**Comment by dyfer** [comment]
I think including an example of this "gotcha" when redefining `MIDIdef` with `nil` as a parameter would be a worthwhile addition to the MIDIdef help file - `args for which nil is passed will use the old values` is easy to miss by itself.

While I haven't experienced this myself, I would've been surprised by this if I used a code similar to @elifieldsteel's example. The explanation makes sense though.

**Comment by jamshark70** [comment]
I think these properties need setters. It looks like setting filtering properties might have to move the responder from one dispatcher to another, so perhaps a little tricky, but it's worth it for the case I mentioned above (changing one property to nil without affecting others).

**Comment by jamshark70** [comment]
Here's a proof-of-concept setter. Am I doing anything wrong here?

```
	chan_ { |argchan|
		chan = argchan;
		// that looks funny but this is what wraps the func in a matcher
		// and assigns a dispatcher
		if(this.enabled) { this.disable; this.enable };
	}
```

Test:

```
MIDIIn.connectAll;

MIDIdef.cc(\x, { |val, num| [num, val].postln }, chan: 0);

MIDIIn.doControlAction(0, 0, 1, 50);
[ 1, 50 ]

MIDIIn.doControlAction(0, 1, 1, 50);  // no print, ok

MIDIdef(\x).chan = nil;

MIDIIn.doControlAction(0, 1, 1, 50);  // now printing, ok
[ 1, 50 ]
```

**Comment by muellmusik** [comment]
> I think these properties need setters.

I'm a little sceptical. It seems a very rare case, and possibly against the intended usage pattern. I'm not sure adding complexity to allow that is better than just a little documentation.

**Comment by jamshark70** [comment]
> possibly against the intended usage pattern

But it doesn't forbid updating the match properties in general, only for this specific value.

I do hear your point. In general, I'm also skeptical of syntax sugar or needless redundancies in an interface. I'm also not thrilled about unnecessary roadblocks in the user experience.

```
MIDIdef.cc(\x, { 0 }, ccNum: 5, chan: 1);
```

Now I wish to make this omni-channel. So, according to the discussion above, I should free the responder and then re-create it -- but keeping the right CC number.

```
MIDIdef(\x).free;
MIDIdef(\x).msgNum;
```

Oh. It's gone. So the actual procedure must be, then, to a/ store all of the properties somewhere; b/ free the responder; and c/ create a new one using the stored-but-modified properties.

```
~changeMIDIdefProperties = { |key ... pairs|
	var def = MIDIdef(key),
	properties = (
		func: def.func,
		srcID: def.srcID,
		chan: def.chan,
		msgNum: def.msgNum,
		msgType: def.msgType,
		argTemplate: def.argTemplate
	);
	pairs.pairsDo { |name, value|
		properties.put(name, value);  // nil will override here
	};
	def.free;
	MIDIdef(key, properties[\func], properties[\msgNum], properties[\chan],
		properties[\msgType], properties[\srcID], properties[\argTemplate]);
};

MIDIdef.cc(\x, { 0 }, ccNum: 5, chan: 1);

~changeMIDIdefProperties.(\x, \chan, nil);

MIDIdef(\x).msgNum;  // still 5, OK
MIDIdef(\x).chan;    // now nil, OK
```

At present, the argument is that users of any skill level should be expected to figure this out by themselves. This may not be exactly ideal in terms of user experience, and it's not difficult to alleviate by setters.

**Comment by muellmusik** [comment]
Hey James. So generally the model with proxy objects as I understand it is that they are stateful in the sense that if you replace one they hold state for changes you don’t specify.

At the moment with MIDIdef and similar you can replace params when redefining, the problem was actually implicit vs explicit nil. So one solution is to document (0..15) or support \all or something.

That doesn’t seem a particularly big deal to me, so I just wanted to weigh complexity costs against adding setters.

That said I guess it’s different for MIDIFunc. Again I don’t think making a new one is a big deal given these are pretty rare cases but I can see both sides of that.

So if you want to add setters, I’d just suggest do it for all parameters and do it for OSCdef/Func as well (for consistency and completeness), and make sure to add unit tests before just to make sure there are no regressions.

**Comment by smrg-lm** [comment]
`Create a new, enabled MIDIdef. If a MIDIdef already exists at this key, its parameters will be replaced with the ones provided (args for which nil is passed will use the old values). `

What is the practical benefit of this feature? Keys are replaced by calling the same method that also have default parameters, calling twice the same method with the same parameters (default or not) yield different results, it becomes unpredictable when depend on a previous state.

**Comment by muellmusik** [comment]
> calling twice the same method with the same parameters (default or not) yield different results

I don't think that's true. Do you have an example where that's the case?

The interface uses the proxy approach found elsewhere in SC, and the 'def' style of a global dictionary. Alberto or Julian may want to comment more, but I think the general idea of a proxy is placeholder involving a 'source' and some state to define the 'place'. You can swap the source without removing the object or changing that state.

**Comment by smrg-lm** [comment]
The bug report does:

```MIDIdef.noteOn(\x, {}) // chan is nil```

and later

```MIDIdef.noteOn(\x, {}, chan:nil) // chan is nil```

The problem that contributes to unpredictability is the global scope, we may not know its previous state and then need to specify (0..15) and then nil as default it's not worth it.

If the key is the source it does change the state of MIDIdef, the problem is the in the definition of the state of the key. I think the key is a particular building block that should set and hold its own state as a whole and not to depend on the state of a previous configuration of that key.

**Comment by telephon** [comment]
As it has been mentioned above, the main issue is the indistinguishability between a `nil` value that was explicitly passed in, and an implicit `nil` value which is there because nothing was passed in.

This is a specification problem that comes up every once in a while, and it is particularly clear in the proxy approach using "defs".

```
var val;
f = { |x|
   if(x.isNil) { val = 1 } { val = 0 }
};
f.value
f.value(nil)
```

This is an interesting problem worth solving for the larger scope of problems. My guess is that _we need some new convention_ to solve it. 

Possibly an object that is passed in order to remove what is there, like `Tidy`, where receivers test for `shouldTidyUp`. I don't like this yet, but just as an idea.

**Comment by muellmusik** [comment]
> The bug report does:

That's not 'same parameters different results'. The problem here is implicit vs explicit nil (see above). It might have made sense to have defaults of something like \all for this and similar params to avoid that. That might be a possible change but we'd want to be careful to ensure that won't break anything.

> The problem that contributes to unpredictability is the global scope, we may not know its previous state and then need to specify (0..15) and then nil as default it's not worth it.

Sorry, why won't we know this? There are IAC getters for all params so you can check them if you need to.

> I think the key is a particular building block that should set and hold its own state as a whole and not to depend on the state of a previous configuration of that key.

I understand your opinion here, but that would go against a lot of precedent and be inconsistent with similar classes. The idea when swapping a source is you only specify the changes you need. As I said above, in most cases with proxy objects you're just swapping the source.

**Comment by jamshark70** [comment]
Well, I had hoped that this might be a workaround:

```
MIDIdef(\x, MIDIdef(\x).func, chan: { true });
```

... if MIDIFunc/MIDIdef were consistent(!) with other parts of the library in using the `matchItem` interface... but the MIDI matcher objects force the channel to be either an integer or an array. I don't see a particularly strong reason to enforce this (and I bet using `matchItem` would eliminate the need for the thicket of matcher objects we have now -- seven(!) of them -- could probably be reduced to two or three).

The thing that I don't like about using `(0..15)` for omni is that the worst case (incoming message is on channel 15) requires iterating over the entire array. "Match anything" doesn't require O(1) :wink:

I would be OK with a symbol `\all` or `\omni`, or to use `matchItem` and document the above workaround.

I dunno... I won't belabor the point anymore, but it bothers me that it's easy to change an omnichannel MIDI responder into a single-channel responder, but it requires an ugly workaround to change it in the opposite direction. But I'll leave it to others at this point.

**Comment by muellmusik** [comment]
> if MIDIFunc/MIDIdef were consistent(!) with other parts of the library in using the `matchItem` interface

That's an interesting point. MIDIdef and similar classes do support matchItem in argTemplates, and it's used internally where it makes sense. It was years ago all this was discussed, and a rather extensive conversation, and I confess I don't recall exactly why it was done this way. Usually matchItem is useful where one might want dynamic behaviour (i.e. pass a function or similar), and maybe it just didn't seem very likely for channel, etc. I'm sometimes a little suspicious of supporting super-rare cases.

Generally the responsedef classes were optimised to maximise speed, which might be another reason, as you also touch upon above. Interchangeable optimised matcher wrappers were part of that design, and I still think the numbers aren't really a problem because they're relatively simple, and not generally used directly by users.

That said, given MIDI is mostly low throughput, and event based rather than streaming in most cases, you could possibly extend matchItem to other properties. Note however that as nil.matchItem returns true, this would not actually prevent the issue raised here.

**Comment by muellmusik** [comment]
I think we've determined that this is not a bug, and I think we're getting into esoterica a bit now, so I'm going to close this in the name of tidiness. If somebody thinks this should be reopened go ahead, or (maybe better) submit a RFC with a proposed changed. Thanks for the interesting discussion!

**Comment by smrg-lm** [comment]
I don't want to reopen it, but why not to use a symbol as default argument like James says? That looks like a good idea to me, so symbol is a different valid type as seen in other places of the library like with ugens (e.g. nil, number or symbol to specify a parameter).

**Comment by sensestage** [comment]
> That said, given MIDI is mostly low throughput, and event based rather than streaming in most cases, you could possibly extend matchItem to other properties.

Except for when you use a sensor to midi interface. There usually you do have streaming MIDI and the throughput will be quite high.
Classically this was an issue most 1980's synthesizers couldn't cope with, but I think that a good 30 years later we should be able to do it.

**Comment by sensestage** [comment]
I do second that providing an additional example to make the behaviour more clear is the way to go.
