### ISSUE TITLE
scsynth crashes when starting with default device

### ISSUE THREAD

**Issue by gumbo2k** [supercollider/supercollider#4616]
## Environment

* SuperCollider version: 3.10.3 (64bit) and also the latest build SC-Windows-x64-069818b80335a862ae0f46e2f95149c8ef0bc54b
* Operating system: Windows 10 pro, (standalone, no AD)
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce
When starting the server I see the following in the post window:

```
*** Welcome to SuperCollider 3.10.3. *** For help press Ctrl-D.
SCDoc: Indexing help-files...
SCDoc: Indexed 1344 documents in 1.8 seconds
Booting server 'localhost' on address 127.0.0.1:57110.

Device options:
  - MME : Microsoft Soundmapper - Input   (device #0 with 2 ins 0 outs)
  - MME : Mikrofon (High Definition Audio   (device #1 with 2 ins 0 outs)
  - MME : Microsoft Soundmapper - Output   (device #2 with 0 ins 2 outs)
  - MME : Lautsprecher (High Definition A   (device #3 with 0 ins 2 outs)
  - Windows DirectSound : Primärer Soundaufnahmetreiber   (device #4 with 2 ins 0 outs)
  - Windows DirectSound : Mikrofon (High Definition Audio Device)   (device #5 with 2 ins 0 outs)
  - Windows DirectSound : Primärer Soundtreiber   (device #6 with 0 ins 2 outs)
  - Windows DirectSound : Lautsprecher (High Definition Audio Device)   (device #7 with 0 ins 2 outs)
  - Windows WASAPI : Lautsprecher (High Definition Audio Device)   (device #8 with 0 ins 2 outs)
  - Windows WASAPI : Mikrofon (High Definition Audio Device)   (device #9 with 2 ins 0 outs)
  - Windows WDM-KS : Mikrofon (HD Audio Microphone 2)   (device #10 with 2 ins 0 outs)
  - Windows WDM-KS : Speakers (HD Audio Speaker)   (device #11 with 0 ins 2 outs)

Requested devices:
  In (matching device NOT found):
  - (null)
  Out (matching device NOT found):
  - (null)

Selecting default system input/output devices

Booting with:
  In: MME : Mikrofon (High Definition Audio
  Out: MME : Lautsprecher (High Definition A
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Unanticipated host error'
could not initialize audio.
Server 'localhost' exited with exit code -1073740791.
```

As you can see it seems to fail opening the audio device.
So I tried several of the devices from the cmd line and only the `WDM-KS` device seems to work:

```
C:\Users\hlangos\Downloads\SC-Windows-x64-069818b80335a862ae0f46e2f95149c8ef0bc54b\SuperCollider>scsynth -B 127.0.0.1 -t 57110 -u 57110 -H "MME :"

Device options:
  - MME : Microsoft Soundmapper - Input   (device #0 with 2 ins 0 outs)
  - MME : Mikrofon (High Definition Audio   (device #1 with 2 ins 0 outs)
  - MME : Microsoft Soundmapper - Output   (device #2 with 0 ins 2 outs)
  - MME : Lautsprecher (High Definition A   (device #3 with 0 ins 2 outs)
  - Windows DirectSound : Prim├ñrer Soundaufnahmetreiber   (device #4 with 2 ins 0 outs)
  - Windows DirectSound : Mikrofon (High Definition Audio Device)   (device #5 with 2 ins 0 outs)
  - Windows DirectSound : Prim├ñrer Soundtreiber   (device #6 with 0 ins 2 outs)
  - Windows DirectSound : Lautsprecher (High Definition Audio Device)   (device #7 with 0 ins 2 outs)
  - Windows WASAPI : Lautsprecher (High Definition Audio Device)   (device #8 with 0 ins 2 outs)
  - Windows WASAPI : Mikrofon (High Definition Audio Device)   (device #9 with 2 ins 0 outs)
  - Windows WDM-KS : Mikrofon (HD Audio Microphone 2)   (device #10 with 2 ins 0 outs)
  - Windows WDM-KS : Speakers (HD Audio Speaker)   (device #11 with 0 ins 2 outs)

Requested devices:
  In (matching device found):
  - MME :
  Out (matching device found):
  - MME :


Booting with:
  In: MME : Microsoft Soundmapper - Input
  Out: MME : Microsoft Soundmapper - Output
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Unanticipated host error'
could not initialize audio.

C:\Users\hlangos\Downloads\SC-Windows-x64-069818b80335a862ae0f46e2f95149c8ef0bc54b\SuperCollider>scsynth -B 127.0.0.1 -t 57110 -u 57110 -H "Windows DirectSound :"

...

Booting with:
  In: Windows DirectSound : Prim├ñrer Soundaufnahmetreiber
  Out: Windows DirectSound : Prim├ñrer Soundtreiber
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Unanticipated host error'
could not initialize audio.

C:\Users\hlangos\Downloads\SC-Windows-x64-069818b80335a862ae0f46e2f95149c8ef0bc54b\SuperCollider>scsynth -B 127.0.0.1 -t 57110 -u 57110 -H "Windows WASAPI :"

...

Booting with:
  In: Windows WASAPI : Mikrofon (High Definition Audio Device)
  Out: Windows WASAPI : Lautsprecher (High Definition Audio Device)
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Invalid device'
could not initialize audio.
```
And finally:

```
C:\Users\hlangos\Downloads\SC-Windows-x64-069818b80335a862ae0f46e2f95149c8ef0bc54b\SuperCollider>scsynth -B 127.0.0.1 -t 57110 -u 57110 -H "Windows WDM-KS :"

Device options:
  - MME : Microsoft Soundmapper - Input   (device #0 with 2 ins 0 outs)
  - MME : Mikrofon (High Definition Audio   (device #1 with 2 ins 0 outs)
  - MME : Microsoft Soundmapper - Output   (device #2 with 0 ins 2 outs)
  - MME : Lautsprecher (High Definition A   (device #3 with 0 ins 2 outs)
  - Windows DirectSound : Prim├ñrer Soundaufnahmetreiber   (device #4 with 2 ins 0 outs)
  - Windows DirectSound : Mikrofon (High Definition Audio Device)   (device #5 with 2 ins 0 outs)
  - Windows DirectSound : Prim├ñrer Soundtreiber   (device #6 with 0 ins 2 outs)
  - Windows DirectSound : Lautsprecher (High Definition Audio Device)   (device #7 with 0 ins 2 outs)
  - Windows WASAPI : Lautsprecher (High Definition Audio Device)   (device #8 with 0 ins 2 outs)
  - Windows WASAPI : Mikrofon (High Definition Audio Device)   (device #9 with 2 ins 0 outs)
  - Windows WDM-KS : Mikrofon (HD Audio Microphone 2)   (device #10 with 2 ins 0 outs)
  - Windows WDM-KS : Speakers (HD Audio Speaker)   (device #11 with 0 ins 2 outs)

Requested devices:
  In (matching device found):
  - Windows WDM-KS :
  Out (matching device found):
  - Windows WDM-KS :


Booting with:
  In: Windows WDM-KS : Mikrofon (HD Audio Microphone 2)
  Out: Windows WDM-KS : Speakers (HD Audio Speaker)
  Sample rate: 44100.000
  Latency (in/out): 0.011 / 0.011 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
```

Now I also managed to select the device from the IDE using
```
o = Server.default.options;
o.inDevice_("Windows WDM-KS : Mikrofon");
o.outDevice_("Windows WDM-KS : Speakers");
Server.default.reboot;
```

So I have a workaround for SCIDE.
But this does not solve my original issue (getting sonic pi to work on windows).

Is there was a way to make `scsynth` pick the "correct" device from an .init or .conf file? 
That could be a work around for my problem.

I usually work with Linux so my Windows skills and tools are rather limited, but please let me know what I can do to help you fix the problem.

**Comment by snappizz** [comment]
hi, thanks for the report.

> Is there was a way to make scsynth pick the "correct" device from an .init or .conf file?

yes, the `inDevice`/`outDevice` settings become the arguments to the `-H` command-line flag.

> But this does not solve my original issue (getting sonic pi to work on windows).

since you've gotten a configuration working, this issue is a matter of finding the equivalent of `inDevice`/`outDevice` in the Sonic Pi client (which runs on Overtone, not sclang). since SuperCollider is working as expected here, i'm closing this since it is really a Sonic Pi support question.

**Comment by gumbo2k** [comment]
Well. I have found a *workaround*. 
Do you consider it expected behavior of SC to now work with any of the other sound devices?
Especially with the default devices?

**Comment by jamshark70** [comment]
> Do you consider it expected behavior of SC to not work with any of the other sound devices?
> Especially with the default devices?

In a perfect world, SC would work seamlessly with all audio devices.

Unfortunately, you're using Windows, so you don't live in that world.

Completely agreed that it isn't good that so many of the audio protocols and devices fail on your machine. I can assure you that it isn't the case on most Windows systems, however. MME usually works just fine (though with high i/o latency). I've successfully booted the server with the other protocols as well.

I would have to suspect that some system component may be suffering a broken installation. We just don't see your symptoms universally on all Windows machines.

FWIW professional-grade low-latency audio in Windows is a ghastly mess. The things my students have to do, to make the built-in audio devices work with Ableton or Cubase, boggle the imagination -- and those programs don't even try to support MME or WDM-KS (it's ASIO or they won't even talk to you).

I also tend to agree with Nathan about device selection. We provide the bootup option. If Sonic Pi doesn't use it, then it's a Sonic Pi issue.

**Comment by gumbo2k** [comment]
Thank you Nathan and James, 
I didn't want to sound like I was complaining. I guess I'll have to try SC and Sonic Pi on some more machines and see if the same problem pops up there as well.
I've also installed ASIO4ALL now and SC works fine with it, if I tell it to use it, instead of the default,

Now, if there was a way to set a default sound device from e.g. an `scsynth.ini` file, that would allow to set the server options without altering any sc program. That way the music specific stuff could stay separate from the system specific stuff. 

But I understand completely if you want to avoid a new layer of configuration that obviously would have to be implemented differently on mac / windows / linux.

**Comment by gumbo2k** [comment]
Next attempt to improve first-time-user experience;

If no device is selected via `-H` let `scsynth` loop through the available devices on startup, until it encounters a working device, or exhausts the list.

**Comment by jamshark70** [comment]
I think the point is that Sonic Pi should use the -H option to set the desired device. If Sonic Pi is not doing that, a better approach is to file a feature request with Sonic Pi, rather than to ask SuperCollider to make up for it.

Cycling through devices: We'd had a similar discussion before, I think with Sam Aaron. It boils down to -- there are (now) two main categories of SC users: Sonic Pi or TidalCycles (particularly new users who might feel like "I don't care which device from the list it is as long as it boots up with a minimum of fuss"), and those who really require a specific configuration and who want to be warned if there's a problem ("my performance will break if I don't have 8 channels at 96kHz"). It's not easy to satisfy both groups. Suppose we add an "expert mode" commandline switch. If "easy mode" is the default, it annoys users who had always been notified about boot problems. If "expert mode" is the default, then you're in the same boat vis-à-vis Sonic Pi (requiring a non-default setting). There was never a clear resolution to that.

**Comment by gumbo2k** [comment]
Ok. just to be clear. I do *not* propose go through the list, if a particular device was requested by the user. Only if no device was chosen, I'd try the next one on the list (and report the tried and failed devices on stderr or stdout, the way scsynth already reports the opened device).

Is it really that likely, that a special "8 channel 96kHz" device is picked up by scsynth as the default device, without scsynth being instructed to use it explicitly? Do we have data on this? (like user surveys, etc.)? 

I understand the argument, the choice is 
- "not change anything for established users", even though it would 
  -  only change behavior in error conditions AND 
  -  the default order of devices happens to put the intended one up from

vs.

- "make it work for more newbies" (though they might not get the best performance)

My suspicion is that the expert users
* already have their device selection set in code, and/or
* are far better equipped to deal with errors that stem from having a wrong device chosen. 

I hope the long term future of the project should played its part in that decision. Today's newbies may become tomorrows contributors. :-) Speaking of newbies ... It took me a while to figure out the exact nature of the problem and I do not consider myself a newbie. Though, my first x86 was a 8088 so I might be going senile instead ;-)

One last idea:  Would you consider a (non-default) "--easy-mode" option so that Sonic Pi and TidalCycles could always call scsynth with that option and wouldn't need to implement a device selection in their gui?

Anyway, I guess I've taken up enough of your time. 
Cheers -henrik

**Comment by brianlheim** [comment]
In my experience software that tries so hard to be "helpful" often does the opposite. Errors, especially those related to system configuration, tend to be more useful. You usually want to know ASAP if your system configuration has changed without your knowledge, and you rarely want to be in a situation where your configuration is sliding around without your knowledge.

Two ideas that I would prefer to what you're suggesting --

1. a 'probe' mode where the server simply tells you which devices or combinations of devices are capable of being used with the settings you've requested, and then exits. This prevents users from abusing 'easy mode', while also avoiding the frustrating guess-and-check cycle.

2. documented error/exit codes from scsynth and supernova so that these configuration errors can be easily consumed programatically by interfacing software

**Comment by gumbo2k** [comment]
Hello Brian,

In this case the 'easy mode' would come with no guarantee. It would deliberately trade simplicity for accuracy (and save a lot of work). My C++ is rather rusty but I guess I could implement 'easy mode' in less than an hour. Implementing device selection in the consuming software would be much more work and that would have to be repeated in every downstream project.

1. The idea of a 'probe mode' sounds interesting, but
* that would require a way to ask scsynth for the devices it sees (which has its own challenges regarding UTF16 UTF8 conversion as you can see in the output above) 
* it should include opening the device and not just checking if in theory the device is capable of supporting the configuration. I think each of the devices in my machine should in theory be capable of 2channel, 16bit, 44.1kHz. In practice however all but one failed.

2. Something other than
```
SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Invalid device'
could not initialize audio.
``` 
and an exit code of  `-1073740791` would certainly be helpful.

**Comment by brianlheim** [comment]
unicode support -- yes we should fix that, in fact there is already a PR open i believe 
seeing all available devices -- already supported, as you can see above
opening the device -- yes, that is what i was suggesting

sounds like that would be a good way to go. if you want to implement it, go ahead, i would gladly give it a review. however, i think your estimate of 1 hour for the implementation is optimistically low.

i would strongly oppose your original "easy mode" idea, it is simply not good design in my opinion.

**Comment by jamshark70** [comment]
> Implementing device selection in the consuming software would be much more work and that would have to be repeated in every downstream project.

So, it should be optional for scsynth front-ends to provide device selection features (just because it's a lot of work), leaving scsynth to just "do something" in order to be nice to the user?

There's no audio software anywhere that actually works this way. Cubase, for example, doesn't convert audio files' sample rate on the fly, during playback. The audio files' sample rates are tied to the project sample rate, which determines the device sample rate. If there were an "easy mode," then you might open your project with a different audio device and wind up with a different sample rate, and then you are in a mess. So there is no easy mode. Cubase tells you there's a problem and allows you to fix it.

In that case, Cubase owns both the front and back ends, so it appears to be seamless. Here, the back end is SC and the front end is Sonic Pi. Sonic Pi appears to be assuming that something else will take care of device selection (but device selection *is* a front-end function!). We are assuming that Sonic Pi will ask for a device that works.

So I guess step 1 is really to reach an agreement with Sam Aaron about the right expectations.

Despite the technical argument, I wouldn't necessarily oppose an "easy mode" because then it would take the problem of device selection back into the front ends' court, where it belongs. Currently they can say "it's a SuperCollider problem" -- but if SC boots with a device that the user didn't want, and the front end doesn't have any way to deal with it, then it's their problem.

Brian:
> unicode support -- yes we should fix that, in fact there is already a PR open i believe

https://github.com/supercollider/supercollider/pull/4479 -- this needs to be finished and put in. It's a very serious problem for non-USA Windows environments.

> seeing all available devices -- already supported, as you can see above

AFAIK the only way to get a device list in the Windows is to boot the server, capture stdout, and parse it. That's inelegant to say the least.

**Comment by brianlheim** [comment]
i'm talking about using the audio APIs directly in C++..  i thought it was clear that what i suggested is an extension to the server code, and not some other application that wraps the server by parsing its output.

**Comment by jamshark70** [comment]
> i'm talking about using the audio APIs directly in C++.. i thought it was clear that what i suggested is an extension to the server code, and not some other application that wraps the server by parsing its output.

Sure, and admittedly, I was talking about the present situation (which is not ideal).

Still, though, there is always a front-end to the server, and that front-end needs to have access to the available device information. With a new "probe mode" (which IMO is the best idea), the results need to be communicated back to the front-end in some format. That could be human-readable stdout, or OSC, or...?

**Comment by dyfer** [comment]
@snappizz I'm not sure this should be closed. IMO it's not unreasonable for scsynth to be able to use default system devices without explicitly defining them. @brianlheim @jamshark70 since you've discussed this here, do you have opinion whether this issue should stay open to improve default audio selection on Windows?

(As I was working on improving that exact thing it does sadden me that it still does not work for some; but between PortAudio and Windows's API complexity it's a mess)

**Comment by brianlheim** [comment]
i think it should remain closed.

**Comment by jamshark70** [comment]
One of the reasons why this issue was raised here is because of https://github.com/samaaron/sonic-pi/issues/2153#issuecomment-546733448 -- "Is there any chance you could raise the error with them directly? If this can be fixed in SuperCollider, it will in turn be fixed in Sonic Pi..."

I've commented back on that issue:

> IMO the best solution is:
> 
> 1. SC fixes the issue with handling non-ASCII device names.
> 2. Sonic Pi uses device info from scsynth stdout to let the user choose.

The first is pending (PR is awaiting some review if I recall).

The second would remove the need for an "easy mode." (As I also put it in the Sonic Pi issue, there's basically no audio-creation software that leaves audio device selection up to system default -- there's always a front end interface for it. We may or may not be doing enough to provide device info to the client, but it isn't really our job to compensate for the lack of a device selector in this or that client.)

So, yes, closed.

**Comment by dyfer** [comment]
Thank you for clarifying!
