### ISSUE TITLE
aNumber.asTimeString number of decimal places

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4661]
## Motivation

`aNumber.asTimeString` has a `precision` parameter, however the output format always uses 3 decimal places for fractions:
```supercollider
pi.asTimeString(0.001); //default
// -> 00:00:03.142 //OK
but
pi.asTimeString(0.1); 
// -> 00:00:03.100 
```
do we need these zeroes to always be there?
## Description of Proposed Feature

I'd think that the `precision` parameter could control the number of decimal places, like this:
```supercollider
pi.asTimeString(0.001); 
// -> 00:00:03.142 //no change

pi.asTimeString(0.1); 
// -> 00:00:03.1

pi.asTimeString(0.00001); 
// -> 00:00:03.14159
```

Do you think this is a worthwhile change? And since it would be possibly a breaking change (?), should this become a new method? Or should the new method also allow to specify whether hours/minutes are displayed as well?
## Plan for Implementation
If we come to a consensus about what behavior is best, I'd be happy to implement this.

**Comment by muellmusik** [comment]
This seems to be intentional. See https://github.com/supercollider/supercollider/blob/6a8762e4774c325f2c0f57cca8baccc46ad9c69d/SCClassLibrary/Common/Math/SimpleNumber.sc#L710 and https://github.com/supercollider/supercollider/blob/486f6f552371b4a3c1f93f766116c736a7885c92/HelpSource/Classes/SimpleNumber.schelp#L375

I'm assuming the intention is to always have seconds.milliseconds as this is common in audio usage. @brianlheim may wish to comment as he was last to touch this. Whether it should be changed is another issue.

**Comment by brianlheim** [comment]
this is correct behavior according to the documentation, definitely should not change. perhaps though if you feel it is really necessary we could add a new parameter for the number of floating point digits which defaults to 3? precision would still control the rounding and numDigits (or something similar) would control the fp digits in the final string.

**Comment by dyfer** [comment]
With #4709 in I think we can close this.
