### ISSUE TITLE
Server fails to boot (Windows 10)

### ISSUE THREAD

**Issue by abhirajdg** [supercollider/supercollider#4718]
## Environment

* SuperCollider version: 3.10.3
* Operating system: Windows 10.0.18363
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

I have been trying to install SuperCollider and TidalCycles on my machine. When I do a

>    SuperDirt.start

I get the following error:

>     *** Welcome to SuperCollider 3.10.3. *** For help press Ctrl-D.
>     Booting server 'localhost' on address 127.0.0.1:57110.
>     SCDoc: Indexing help-files...
> 
>     Device options:
> 
>         MME : Microsoft Sound Mapper - Input (device #0 with 2 ins 0 outs)
>         MME : Microphone Array (2- Realtek(R) (device #1 with 2 ins 0 outs)
>         MME : Stereo Mix (2- Realtek(R) Audio (device #2 with 2 ins 0 outs)
>         MME : Microsoft Sound Mapper - Output (device #3 with 0 ins 2 outs)
>         MME : Speaker / Headphone (2- Realtek (device #4 with 0 ins 2 outs)
>         Windows DirectSound : Primary Sound Capture Driver (device #5 with 2 ins 0 outs)
>         Windows DirectSound : Microphone Array (2- Realtek(R) Audio) (device #6 with 2 ins 0 outs)
>         Windows DirectSound : Stereo Mix (2- Realtek(R) Audio) (device #7 with 2 ins 0 outs)
>         Windows DirectSound : Primary Sound Driver (device #8 with 0 ins 2 outs)
>         Windows DirectSound : Speaker / Headphone (2- Realtek(R) Audio) (device #9 with 0 ins 2 outs)
>         ASIO : ASIO4ALL v2 (device #10 with 2 ins 2 outs)
>         Windows WASAPI : Speaker / Headphone (2- Realtek(R) Audio) (device #11 with 0 ins 2 outs)
>         Windows WASAPI : Stereo Mix (2- Realtek(R) Audio) (device #12 with 2 ins 0 outs)
>         Windows WASAPI : Microphone Array (2- Realtek(R) Audio) (device #13 with 2 ins 0 outs)
>         Windows WDM-KS : Stereo Mix (Realtek HD Audio Stereo input) (device #14 with 2 ins 0 outs)
>         Windows WDM-KS : Microphone Array (Realtek HD Audio Mic input) (device #15 with 2 ins 0 outs)
>         Windows WDM-KS : Speakers (Realtek HD Audio output) (device #16 with 0 ins 2 outs)
> 
>     Requested devices:
>     In (matching device NOT found):
> 
>         (null)
>         Out (matching device NOT found):
>         (null)
> 
>     Selecting default system input/output devices
> 
>     Booting with:
>     In: MME : Microphone Array (2- Realtek(R)
>     Out: MME : Speaker / Headphone (2- Realtek
>     SC_PortAudioDriver: PortAudio failed at Pa_OpenStream with error: 'Unanticipated host error'
>     could not initialize audio.
>     SCDoc: Indexed 1363 documents in 1.59 seconds
>     Server 'localhost' exited with exit code -1073740791.

Can anyone help me out with a solution here?

**Comment by telephon** [comment]
https://github.com/musikinformatik/SuperDirt/issues/172

Sorry for the change of title, as you found out, it has nothing to do with SuperDirt. 

Reproducer: `s.boot`.

**Comment by jamshark70** [comment]
Supposedly this had been addressed: https://github.com/supercollider/supercollider/pull/4475 (lots of review history here but the gist is that 3.10.3 is supposed to boot to multiple devices where one is "n-in" and the other is "n-out").

@dyfer -- sorry to "at" you by name, but any ideas why SC 3.10.3 running on Win10 would not be able to use the default "MME : Microphone Array (2- Realtek(R)" and "MME : Speaker / Headphone (2- Realtek" devices? It's the old 'Unanticipated host error'.

**Comment by dyfer** [comment]
@jamshark70 unfortunately I don't know. Occasionally such error would occur, although the #4475 tries to take care of at least some common issues.
It _might_ indicate that the devices in question are running at different samplings rates (?).

The possible solution here is to try booting to dedicated devices using `s.options.inDevice`/`.outDevice` (partial name matching works, API should be included in the name), try booting specifying (and leaving as `nil`) `s.options.sampleRate` and as I mentioned previously making sure that the devices in question are set to the same sample rate (somewhere in the Control Panel)

**Comment by jamshark70** [comment]
Thanks @dyfer :handshake:

@abhirajdg -- per Marcin's suggestions, then:

1. Check the system sound control panel for the input and output devices' sample rates. If they don't match, that could cause this problem.

2. Try forcing a sample rate when SC server boots: `s.options.sampleRate = 44100; s.boot;`. (The default here is `nil`, meaning, use the device's settings. It might help to try to override that.)

3. Try specifying devices in SC, rather than leaving it to default. Also try devices, and APIs, other than the default (only, the API must be the same for input and output -- no MME vs WDM-KS).
   ```
   s.options.inDevice_("MME : Microsoft Sound Mapper - Input").outDevice_("MME : Microsoft Sound Mapper - Output");
   s.boot;
   ```
   You might have to try several combinations here.

4. Or try `s.options.device = "ASIO : ASIO4ALL v2"; s.boot` -- this has been the standard workaround. Provided that ASIO4ALL is working on your system (not guaranteed), this is likely to be OK.

Unfortunately, Windows audio is fiddly and it seems like, no matter what we do, there is always some machine somewhere that doesn't boot the server with default settings. So it takes some patience and experimentation.

**Comment by nlebellier** [comment]
hi. I met the same issue. to try your solutions where do we indicates this 
```
s.options.inDevice_("MME : Microsoft Sound Mapper - Input").outDevice_("MME : Microsoft Sound Mapper - Output");
s.boot;
```

**Comment by dyfer** [comment]
> hi. I met the same issue. to try your solutions where do we have to enter these commands ?
> 
It depends how/when you actually boot the server. 

If you boot the server in your code, then specify `s.options...` before the boot command. If you boot the server using a keyboard shortcut, then run `s.options...` before you use that shortcut. If you boot the server automatically on SC start, then `s.options...` needs to go into `startup.scd` before the boot command. I personally never boot the server automatically when the SC starts, since I want it to be set up for a given project first (number of channels, samplerate, etc).

Also please note that the device name needs to match one of the devices found on your system (posted when the server is booting). If SC 3.11 (now in beta) you can also obtain a list of devices with 
```supercollider
ServerOptions.inDevices;
ServerOptions.outDevices;
```
(In case others read this - `ServerOptions` part is new in 3.11 on Windows; this was always available on macOS; this also does not apply on Linux, where sound goes through JACK, which decides the sound device to use)

**Comment by nlebellier** [comment]
Jackrouter 64 bits was the cause of the problem.
https://forum.openmpt.org/index.php?topic=6110.0

**Comment by jamshark70** [comment]
> Jackrouter 64 bits was the cause of the problem.

Ohh... That's good to hear. Hm, seems like we forget about this when the issue comes up. Making a mental note that an otherwise unexplained "unanticipated host" error may be related to Jack.

**Comment by martinhurych** [comment]
Hi, the problem is in setting of privacy in Windows. I found my microphone there as disabled. If you switch it to enabled to choosen apllications it will work. I hope the problem it will figured out...

**Comment by jamshark70** [comment]
> Hi, the problem is in setting of privacy in Windows. I found my microphone there as disabled. If you switch it to enabled to choosen apllications it will work.

Oh that's interesting. I wouldn't have guessed that.

It might help if the PortAudio backend printed more informative errors. "Unanticipated host" is largely useless for troubleshooting and can refer to an unknown situation in the OP's case, or JackRouter or device permission conflicts, or any number of cases we haven't even identified yet. But I have no idea how to get better information from PortAudio.

Otherwise it's a matter of documentation.

**Comment by znmeb** [comment]
It is *not* a matter of documentation! Windows users expect that when you install a package that requires configuration to work, you are sent to a configuration utility that guides you to a working install. That is not the case here. I haven't the faintest idea how to tweak my audio settings to get this to work,


```

*** Welcome to SuperCollider 3.11.2. *** For help press Ctrl-D.
SCDoc: Indexing help-files...
Booting server 'localhost' on address 127.0.0.1:57110.
SCDoc: Indexed 1366 documents in 0.91 seconds
Exception in World_New: boost::interprocess::intermodule_singleton initialization failed
Server 'localhost' exited with exit code -1073741819.
```

By the way, I tried this on Arch Linux - everything installs with the "pro-audio" meta-package and all I had to do to make it work was configure the real-time priorities, which *are* documented, and start `QJackCtl`. 

Please re-open this and put some effort into a more-or-less foolproof install-time configurator.

**Comment by jamshark70** [comment]
@znmeb A configuration dialog box would not fix the "boost interprocess" error.

A configuration dialog is not a bad idea in general. However, SC is a code environment and currently in both Mac and Windows, we use code to handle audio device selection, and this is documented at length in SC's internal help system (help --> browse --> Server --> Audio device selection, replicated online at http://doc.sccode.org/Reference/AudioDeviceSelection.html). Admittedly, in any software, it takes time to make a mental map of the help system, but this help file is also linked in from the Getting Started tutorial chapter on booting the server so it isn't exactly hidden.

A feature request for a configuration dialog would be entirely fair to open as a separate issue, using the feature request template.

As for the interprocess error, see #2409 -- it's a bizarre interaction with the Windows event log that nobody could have anticipated.

**Comment by amias-channer** [comment]
it looks like this is because the interprocess library in boost provides has a specific variant for windows , the normal call only works in linux and osx but it wont use the windows variant unless BOOST_INTERPROCESS_WINDOWS is set in the build. Im guessing it isn't at point when this is processed. 
https://www.boost.org/doc/libs/1_52_0/boost/interprocess/detail/intermodule_singleton.hpp
