### ISSUE TITLE
sclang: "emergency" boot with basic class library if conflicts are detected

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4719]
## Motivation

Sometimes the user ends up with duplicated class definitions. In that case sclang fails to boot.

## Description of Proposed Feature

I'd like to propose that when conflicts are detected, sclang still boots, but without any extensions beside the basic class library. This can aid in users resolving the conflict (e.g. with `Quarks.gui`). 

Additionally, sclang could provide a more concise information about duplicate classes (e.g. inferring files or folders that contain conflicting classes, instead of - or in addition to - listing all the classes).

## Plan for Implementation

If this seems like a worthwhile feature, I would check whether this is feasible for me to implement or not...

**Comment by brianlheim** [comment]
@dyfer can we take a step back here? what is the problem you are trying to solve here? i.e., what about this specifically is frustrating or disruptive to a user's workflow? if we do that, i think it'll be easier to design a solution.

**Comment by jamshark70** [comment]
See also #1423. This has been discussed before.

Some reasonable user expectations:

- If something is wrong with the system, I should be able to find help.[1] But... library failed to compile = help system is down.

- If a SC UI panel (e.g. Quarks.gui) helped me to install something and there's a problem with it, then you go to the same UI panel to fix it. But Quarks.gui is down too.

- The system should provide some information about where the problem is.[2] It does, sort of, but interpreting the output requires some knowledge of class library structure... which is unavailable. Imagine a new user seeing the "duplicate class" feedback -- how do they know which one to keep?

[1] Library and extension structure is not really obvious, and it's transparent/invisible when everything is working. New users don't need to care about it until something goes wrong... but it's exactly at the point of something going wrong, when help is needed, that the system is unable to provide any help. "Frustrating or disruptive" would be excellent words to describe that.

Possibly tricky thing -- currently we can assume LanguageConfig reflects the current state of what is loaded. But in a safe mode, we are loading classes from a restricted set of directories, but if experienced users might want to query the system for details about the problem, then there's the actual (reduced) config while we need to query the *saved* (but not loaded) config. We don't have an API for this now, but it would be really helpful to support interfaces that could guide new users through troubleshooting library problems.

~~

I've just been watching a couple of Tantacrul's UI design rants on YouTube (his evisceration of Sibelius is genius). I find myself imagining what he would say about this... I'll include this just for fun. I don't expect this issue to deal with all of the workflow problems, but it doesn't hurt to be honest with ourselves about one area where SC's workflow is, frankly, pretty awful.

> So we go to `Quarks.gui` and choose some extension package and... oh, this big green button that was disabled before but now it's active, that looks promising... and... "There is a discrepancy"? Hum.
> 
> So, try to go back to the GUI... erm... "Library has not been compiled successfully." What now? Let's ask for help... Oh-kay, there's a big white window that isn't updating and the post window just says again, "Library has not been compiled successfully." Reaching for blood pressure medication...
>
> So I can't go back to where the problem happened, and I can't ask for help. Google, then? A-ha... so if I go to Preferences (a totally different dialog box from the place where the problem began) and Interpreter (so somehow I'm just expected to know that "Library compilation" or "Quarks" have to do with the interpreter) and then look for the thing I just installed (which I had installed using a short name, but now I have to look through a list of full paths on disk) and hit a [-] button (which at least matches the +/- paradigm from the installation panel, +1 point there), and then... what's this pop-up? Oh, who cares... last time, I recompiled, so let's try that again and... "There is a discrepancy"??!!
> 
> So I shouldn't "recompile" again, but now I have to do a different operation (but they're both "resetting" and the distinction isn't clear).

**Comment by dyfer** [comment]
@brianlheim I think @jamshark70 fleshed it out pretty accurately.

Another idea, possibly more dangerous, is to drop classes that are duplicated at runtime, but continue to boot the interpreter. Although if the system will continue to "kind of" work even if the user has multiple versions of extensions, we might end up with even more mess. But still, maybe that's an idea worth considering.

**Comment by brianlheim** [comment]
thanks for the explanation. could we perhaps close this and reopen the issue with more history instead?

**Comment by dyfer** [comment]
closed as it's a duplicate of #1423
