### ISSUE TITLE
default value for useSystemClock

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#4729]
## Environment

* SuperCollider version: dev
* Operating system: macOS 13.13
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
s.options.useSystemClock; //get default value
// -> false
```

## Expected vs. actual behavior

Scsynth always uses system clock for [scheduling](http://doc.sccode.org/Classes/ServerOptions.html#-useSystemClock). Supernova uses sample clock by default. As supernova did not originally allow for using system clock, the default value to use sample clock reflects its original behavior.

I think it would be better if the default settings matched scsynth and supernova as close as possible, what do you think?

I'm happy to make a PR if there's a consensus this is worth changing.

**Comment by jamshark70** [comment]
> The default value might be due to past discussion about that feature claiming that syncing to sample clock is better.

The reason is that supernova initially had no option to sync to the system clock. When the option was added, a default of "true" would have given compatible behavior between scsynth and supernova by default, but changed the default behavior of supernova. So the decision was to leave the default behavior of both servers unchanged.

It may be time to revisit that. It would affect users who are currently used to the sample clock option in supernova (they would need to change their server options).

**Comment by dyfer** [comment]
> The reason is that supernova initially had no option to sync to the system clock. 

Oh yes, thanks for clarifying. It rings a bell now.

**Comment by brianlheim** [comment]
totally fine to change this in supernova IMO, it is not as stable as scsynth

**Comment by dyfer** [comment]
all right, do you think this should be changed in classlib only or also in default args in `supernova` executable?

**Comment by brianlheim** [comment]
in the executable :)

**Comment by dyfer** [comment]
fixed in #4909
