### ISSUE TITLE
[SC-IDE] Custom menu actions

### ISSUE THREAD

**Issue by lijon** [supercollider/supercollider#475]
I was going to ask for menu items calling Server.default.meter, Quarks.gui, (someWord).inspect, (someWord).browse, etc.. Then I realized that it would be better if each user can configure their own favourite menu items (with keyboard shortcuts). See how gedit does it, for example.

I propose we add a dialog in settings for managing custom menu items, where one can add/edit/delete them. Editing them would look like this:
- menu item label (string)
- keyboard shortcut
- use selection as input string if available (bool)
- input string (choice)
  - current word
  - current line
  - whole document
  - current document path
- action (string), an sclang expression where % is replaced with the input string.

This way, all kinds of useful tricks can be added by each user. You could start with just having a config file for this, and add the GUI part later.

**Comment by rd--** [comment]
Hello all,

Not sure if comments on closed issues show up, but this seemed to be where this issue is tracked.

Just adding a note to say that for adding keybindings to documents in the `scide` editor the below seems to work.

````
Document.globalKeyDownAction = {
    arg document, char, modifiers, unicode, keycode;
    (modifiers.isCtrl && keycode == $h.ascii).if({
        var text = (document.selectionSize == 0).if({document.currentLine}, {document.selectedString});
        "(%).play".format(text).interpret}
    );
}
````

For people coming from Emacs this can be very important!

(Emacs people might have lots code fragments that need some text transformation to be useful.)

Is this the standard way to do this?

Is there a better way?
 
Best,
Rohan
