### ISSUE TITLE
Wii remote support for Linux

### ISSUE THREAD

**Issue by grammoboy2** [supercollider/supercollider#4843]
Feature request:

Seems that Wii stuff is replaced in Linux by:

http://dvdhrm.github.io/xwiimote/

So previous attempts to implement wii remote (WiiMote) support for supercollider doesn't work anymore I guess.

Would be nice to be able to work with Wii Remote and supercollider on Linux.

FYI, for pure data there is:

https://github.com/agraef/xwiimote-lua

**Comment by brianlheim** [comment]
the wii is quite old at this point, i think we already decided to deprecate and remove our existing wii support. also, if there is a platform-independent support library that would make it a lot more appealing. would you like to work on this?

**Comment by grammoboy2** [comment]
So I'm too late? I bought a wii remote years ago, waiting to learn 
supercollider and do something cool with it... ;)

I'm a newbie, can't offer much help here, sorry.

**Comment by snappizz** [comment]
Yeah, SC used to have built-in Wii support, but it had completely different code paths for Linux and Apple, no Windows support at all, and a dependency on the unmaintained libcwiid library that caused packaging headaches. I advocated for its removal because it's too much stress on developers to maintain a codebase in bad technical debt for a discontinued product. I'm really sorry about that.

**Comment by grammoboy2** [comment]
Fair enough.

**Comment by grammoboy2** [comment]
For future reference, this is a option too:

https://github.com/SCLOrkHub/SCLOrkTools/blob/master/classes/SCLOrkWiimote.sc

**Comment by snappizz** [comment]
Oh sweet! Props to @lnihlen
