### ISSUE TITLE
Unexpected results setting Synth args to large numbers

### ISSUE THREAD

**Issue by markwheeler** [supercollider/supercollider#4853]
## Environment

* SuperCollider version: 3.11.0
* Operating system: MacOS 10.14.6
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
(
SynthDef("aSynth", {
	arg myArg;
	((myArg + 10) - 40000000).poll(2, "Difference"); // Expecting 10, seeing 8
}).add;
)
Synth("aSynth", [\myArg, 40000000]);
```

## Expected vs. actual behavior

I'm seeing unexpected results passing large-ish numbers to Synth args – it seems like they aren't correctly set within the Synth.

The code example should be fairly self explanatory. Varying the numbers gives different incorrect results. I feel like I may be missing some kind of restriction or...?

For context, I discovered this while trying to pass frame numbers in to a sample player.

**Comment by brianlheim** [comment]
the server uses 32-bit floats for signals; you are seeing rounding error because you are performing operations on numbers of very different magnitudes. if you swap your order of operations you would get the answer you expect. see also [this stackexchange answer](https://softwareengineering.stackexchange.com/questions/101163/what-causes-floating-point-rounding-errors) or the classic ['what every computer scientist should know about floating point arithmetic'](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html)

**Comment by markwheeler** [comment]
Thanks for the quick answer! I have some reading to do :)
