### ISSUE TITLE
Supercollider server boot kills audio video

### ISSUE THREAD

**Issue by mr-gri3ves** [supercollider/supercollider#4891]
Server.local.boot kills audio and video what can i do?

**Comment by joshpar** [comment]
what system are you on, what version of SuperCollider do you see this with, and what IDE?
(p.s. - If your handle is a Pixies reference, I highly approve)

**Comment by mr-gri3ves** [comment]
I am on ubuntu studio 20.04 , super collider 3.10.0(default ide) supercollider-ide.

**Comment by joshpar** [comment]
Thanks for the info. Are you able to test with 3.11?

**Comment by mr-gri3ves** [comment]
where can I download if for linux? cause I've installed that from ubuntu ppa repositories

**Comment by jamshark70** [comment]
> I am on ubuntu studio 20.04

Have you configured Jack and PulseAudio so that PA plays through Jack instead of connecting to ALSA directly?

This is a very common question. In almost every case, it's a system configuration issue and not a SuperCollider bug (by which I mean, you'll have the same problem with Ardour or other Jack-only audio software).

Many websites explain how to do it. I usually recommend this one first. https://jackaudio.org/faq/pulseaudio_and_jack.html

**Comment by brianlheim** [comment]
closing as stale -- please reopen if you need more help @mr-gri3ves !
