### ISSUE TITLE
scide.EXE has stopped working

### ISSUE THREAD

**Issue by ABCsHub** [supercollider/supercollider#4901]
I tried to start SuperCollider but instead it crashed
Help me Please

Thanks, ABCsHub

SuperCollider-3.11.0
Windows 7

**Comment by jrsurge** [comment]
Hello!

Thanks for the report.

Can you please provide some additional information?
If possible, can you post any error messages, in as much detail as possible, that you see when starting the IDE?

**Comment by ABCsHub** [comment]
![scide error](https://user-images.githubusercontent.com/34779749/80599113-c6503600-8a00-11ea-88ae-0adea760f532.JPG)

sorry i speak that language.

My computer:
```
Windows 7 Home Premium (64 Bits)
Intel(R) 82945G Express Chipset Family
Intel(R) Pentinum(R) Dual CPU E2180 @ 2.00GHz (2 CPUs), ~2.0 GHz
DirectX 11

```

Supercollider:

```

Supercolider version: 3.11.0

Problem Event Name: APPCRASH
File: scide.EXE
Crash Module Name: ig4icd64.dll

```

**Comment by jrsurge** [comment]
Thanks for the details - no need to apologise!

From what I can see, `ig4icd64.dll` is the driver for your Intel integrated graphics card.

If your computer has an additional graphics card, you might be able to try and start scide by:
- Right-click on SuperCollider shortcut
- Run with graphics processor...
- Select something that is not Integrated Graphics

The option to select another graphics card might not be available depending on your computer.

Otherwise, you could try to find an update for your graphics driver.

**Comment by ABCsHub** [comment]
i don't have Run with graphics processor
and which update?

**Comment by jrsurge** [comment]
@ABCsHub - sorry for the delay!

You'll have to search online for a possible update to your graphics driver.

Although SC does run on Windows 7, we don't support it as much as newer versions of Windows.
However, because this looks like a hardware problem I'm afraid there isn't much we can do to help.
