### ISSUE TITLE
Improve disambiguation of methods for method call assist

### ISSUE THREAD

**Issue by jleben** [supercollider/supercollider#491]
Provide a handy way to pick the method of a desired class when triggering method call assist.

**Comment by brianlheim** [comment]
Pinging. @jleben can you or someone else explain this feature request? I don't understand it.

**Comment by jleben** [comment]
@brianlheim When you are typing a method call in the form of `object.method(...`, the IDE provides a list of possible methods for this particular object. The list of methods depends on the class of the object. However, SuperCollider is a dynamically typed language, so the class is not known by the IDE. The IDE therefore looks at methods with a matching name across all classes. The user must then pick one of the possible methods in order to bring up another IDE feature: the list of parameters for that method. This PR is about improving the way the user chooses among the possible methods.

I'm not sure whether this GitHub issue was created before the current implementation was completed. I wonder if someone can think of a better solution that requires less interaction from the user...

**Comment by telephon** [comment]
An idea: 

let's say you have typed `play(` and the long list of classes pops up. Then, instead of having to hit the arrow-down until you have reached the class, you just continue by typing the class name (we can ignore case here, because we know it is a class). The list of choices shrinks accordingly. When you hit enter, the class name you had begun to type is erased and you can continue with the parameters.
