### ISSUE TITLE
View's font getter method returns nil

### ISSUE THREAD

**Issue by tsmtzs** [supercollider/supercollider#5105]
## Environment

* SuperCollider version: 3.11.0
* Operating system: Arch Linux

## Steps to reproduce

```supercollider
w = Window.new.front;

v = View(w, w.bounds.moveToPoint(0@0));

v.font = Font(Font.defaultSansFace);
v.font; // returns nil
```

Using the `getProperty` method returns the instance:

```supercollider
v.properties.includes(\font); // returns true

v.getProperty(\font) === v; // returns true
```

## Expected vs. actual behavior
The method should return the `Font` instance.

**Comment by jamshark70** [comment]
Could I ask, what is the use case for setting a View's font?

`View` doesn't display text, and I'm pretty sure that views inside a View don't inherit the font setting from the container. So, unless I'm mistaken about the latter, there's no point in setting a font here.

**Comment by jamshark70** [comment]
I stand corrected! Child views inside a container View *do* inherit their display from the parent. Sorry for a mistaken assumption.

```
(
v = View(nil, Rect(800, 200, 500, 400))
.font_(Font.default.boldVariant.pixelSize_(48))
.front
.layout_(VLayout(
	StaticText()
	.align_(\center)
	.string_("big or small?")
));
)
```

That's kinda cool actually. (Also undocumented -- View help says "every view has this method" but doesn't explain what good it is for non-text views.)

The problem here is that *some* views' `font_` method assigns the object to the `font` variable, while others (including `View`) don't. That should be made consistent.

It looks like only `View` is missing this, so the fix would be (in View):

```
	font_ { arg aFont;
		this.setProperty( \font, font );
		font = aFont;
	}
```

**Comment by tsmtzs** [comment]
Adding the variable assignment in the `font_` method, was the right choice for me, also. But, as @jamshark70 mentions, there is not a unified approach in the getter and setter methods of `View`'s subclasses. This seemed confusing to me, so I reported the bug.

For example, the `string_` and `string` methods of `StaticText` are defined as

https://github.com/supercollider/supercollider/blob/9ee25b59cc32f0210154df3dda03add6c6e8b5b8/SCClassLibrary/Common/GUI/Base/BasicViews.sc#L215-L216

(Also, note that there is not a `string` instance variable).

On the other hand, the `align_` method of `TextViewBase` is

https://github.com/supercollider/supercollider/blob/9ee25b59cc32f0210154df3dda03add6c6e8b5b8/SCClassLibrary/Common/GUI/Base/BasicViews.sc#L12-L15

Maybe, a "unified" approach to the subclasses of `View` might be either to define the getter methods in the way @jamshark70 mentions, in cases where an instance variable exists (like `font` in this case) or, to  follow the pattern in the `string` case.

**Comment by jamshark70** [comment]
It isn't clear to me why there is a `font` variable at all, since (as you pointed out) `getProperty` works for it. If I had to speculate, I'd guess it's because a Font is a slotted object (which may have garbage collection implications) while a String is a RawArray (basically just a pointer to a C-style array, simpler GC). If that guess is correct, there may be a good reason to retrieve the original Font object from a variable rather than getting it as a property. But there's no record of the design decision that I know of, so I'm just guessing.

`align` needs to be a variable because the property value is not the original symbol (`QAlignment(aSymbol)`) -- getting the property would require decoding in the class library. So it may not be possible to rely 100% on getProperty -- and it's probably overkill to convert them all to variables.

Regardless, the implementation of `font_` is incomplete, for sure.

**Comment by tsmtzs** [comment]
@jamshark70 Thanks for the clarification!
