### ISSUE TITLE
INSTALL ISSUE

### ISSUE THREAD

**Issue by alba21-coder** [supercollider/supercollider#5121]
## Environment

* SuperCollider version: 3.11
* Operating system: Mac OX X El Capitan 2015
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
I CAN'T ISTALL SUPERCOLLIDER 
```

**Comment by alba21-coder** [comment]
I try to install TidalCycles with bootstrap. I try to launch TidalCycles trough Atom but give me a problem. So, I unistall Supercollider for install again but now I can't install, maybe the reason is the terminal but I can't resolve. THANK U

**Comment by jamshark70** [comment]
I've asked for more details in the equivalent forum thread.

I'll go ahead and close this because it wastes effort to have the same question open in two places. @alba21-coder, please continue with the troubleshooting at scsynth dot org -- if that investigation points to a SC bug, we can file a report here at that time.

Sorry that you're having trouble --
