### ISSUE TITLE
support collection.asAscii from wslib as built-in function to handle unicode

### ISSUE THREAD

**Issue by mwinter80** [supercollider/supercollider#5125]
from sc-user recent posting.

including collection.asAscii would allow support for unicode. this problem arose when trying to include an SC listing in Latex with a unicode character given as is.

simple example is an inverse bullet point: ◘
would be great to have [-30, -105, -104].asAscii work without wslib and thus not have to deal with encoding errors when using the .scd file in other contexts.

**Comment by brianlheim** [comment]
thanks for the suggestion @mwinter80 !

it's sad there are still text-processing tools today that don't support Unicode encodings...

my preference would be to solve this the way other languages do, by using hex escape codes in character literals (see [c++](https://en.cppreference.com/w/c/language/string_literal), [java](https://docs.oracle.com/javase/specs/jls/se12/html/jls-3.html#jls-EscapeSequence), [haskell](http://book.realworldhaskell.org/read/characters-strings-and-escaping-rules.html#id690711), [swift](https://docs.swift.org/swift-book/LanguageGuide/StringsAndCharacters.html)). until then, i think that this should remain an extension, because:
- there's decent workarounds, three actually:
  - wslib's `asAscii`
  - `[-30, -105, -104].collect(_.asAscii).as(String)` also works
  - a unicode-supported version of LaTeX called [XeTeX](http://xetex.sourceforge.net/)
- UTF-8 string literals are supported by SC, so this only comes up when interacting with a tool that cannot handle UTF-8 encoded documents

**Comment by mwinter80** [comment]
Great! thanks for the .collect(_.asAscii).as(String) workaround. I am always hesitant to use quarks in code that I distribute to others.

**Comment by brianlheim** [comment]
> I am always hesitant to use quarks in code that I distribute to others.

why? it's easy to communicate your code's dependencies in a readme or some other distribution document. it would definitely be nice if the ecosystem had something more fine grained than these large all-or-nothing 'convenience' packages, but that's not a reason to introduce new methods into the core library.

are you OK with me closing this issue? then i will introduce a new one for the string literal specification change.

**Comment by mwinter80** [comment]
I understand that it may not be a reason to introduce methods into the core library, but I often make programs for people who have ZERO experience with SC. It is almost a task to get them to just execute a code block. There is also a factor of the longevity of the code working and backwards compatibility. I guess I could automate the quark install, but then you are dependent on an internet connection on first launch (that of course, is almost a non-factor these days).

**Comment by brianlheim** [comment]
good points! alright, closing this.
