### ISSUE TITLE
vendored boost_sync is not compatible with boost <= 1.72.0

### ISSUE THREAD

**Issue by dvzrv** [supercollider/supercollider#5255]
Hi! When building the latest develop commit it fails, as boost on Arch Linux is currently still at 1.72.0.
It seems the changes introduces in https://github.com/supercollider/supercollider/pull/5153/commits/9e1fcef98e8442655c86c2071fd78c8c919c21eb made the vendored boost_sync version incompatible with (at least) boost 1.72.0 (maybe also 1.73.0).

Unfortunately we are currently in the rather large python3.9 rebuild cycle and won't be able to upgrade to boost 1.74.0 that super soon.

## Environment

* SuperCollider version: 7c16838b00b0af26314431246e6b68a2a0ce9cc0
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.):
  - boost 1.72.0
  - qt5 5.15.1

## Steps to reproduce

```sh
    export CFLAGS+=" -DNDEBUG"
    export CXXFLAGS+=" -DNDEBUG"
    cmake -DCMAKE_INSTALL_PREFIX='/usr' \
          -DCMAKE_BUILD_TYPE='None' \
          -DFORTIFY=ON \
          -DSC_VIM=OFF \
          -DSYSTEM_ABLETON_LINK=ON \
          -DSYSTEM_BOOST=ON \
          -DSYSTEM_YAMLCPP=ON \
          -Wno-dev \
          -B build \
          -S .
    make VERBOSE=1 -C build
```

## Expected vs. actual behavior

The vendored boost_sync version relies on e.g. `boost/assert/source_location.hpp` which is not (yet) around in boost 1.72.0.

```
cd /build/supercollider-git/src/supercollider/build/external_libraries && /usr/bin/cmake -P CMakeFiles/oscpack.dir/cmake_clean_target.cmake
cd /build/supercollider-git/src/supercollider/build/external_libraries && /usr/bin/cmake -E cmake_link_script CMakeFiles/oscpack.dir/link.txt --verbose=1
In file included from /build/supercollider-git/src/supercollider/external_libraries/boost_sync/include/boost/sync/detail/semaphore/semaphore_posix.hpp:22,
                 from /build/supercollider-git/src/supercollider/external_libraries/boost_sync/include/boost/sync/semaphore.hpp:143,
                 from /build/supercollider-git/src/supercollider/server/scsynth/SC_HiddenWorld.h:36,
                 from /build/supercollider-git/src/supercollider/server/scsynth/SC_ComPort.cpp:22:
/build/supercollider-git/src/supercollider/external_libraries/boost_sync/include/boost/sync/detail/throw_exception.hpp:19:10: fatal error: boost/assert/source_location.hpp: No such file or directory
   19 | #include <boost/assert/source_location.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Here's the full build log:
https://gist.github.com/dvzrv/bd47d943112c92a4fb7d9fbdef98c101

**Comment by brianlheim** [comment]
what would you suggest we do about this? it seems like an edge case that will resolve itself.

**Comment by dvzrv** [comment]
I guess one thing could be to find the minimum supported boost version and let cmake fail on anything below that (that way it would at least be clear that only boost above that is supported).

I believe currently the setup still (falsely) states that it supports >= 1.50.0.

**Comment by dvzrv** [comment]
Also, note that a lot of distributions are far further behind than we are: https://repology.org/project/boost/versions

Depending on when the change is released in a stable version it will have effect on the compatibility promises (unless downstreams then choose to use the vendored boost version).

**Comment by brianlheim** [comment]
that makes sense. i just realized, if we move to c++17 and use shared_mutex we can drop Boost.Sync entirely. so, it may just be easiest to do that instead.

**Comment by dvzrv** [comment]
I don't really know how much work that would be, but I trust that you have a much better overview in regards to that topic than me :laughing: 

I'll try to figure out the minimum supported version for boost_sync in the mean time. Upgrade to 1.74.0 on Arch is currently kinda blocked by our python3.9 rebuild (which will probably still take 1-2 weeks until all the bugs and regressions are solved).

**Comment by brianlheim** [comment]
ah my mistake, it's not shared_mutex that we get from Boost.Sync but rather semaphore.

i just noticed that there's also a semaphore in nova-tt, but it doesn't have the error handling features that Boost.Sync does. @timblechmann i wonder if you could offer some advice here, would you recommend for or against using it? i'm also considering condensing Boost.Sync's semaphore into a less boost-dependent standalone header that we could use instead of the entire Boost.Sync project. the implementations seem straightforward enough that i wouldn't expect them to change much before we move to c++20 and can use std::semaphore instead.

**Comment by timblechmann** [comment]
imho sc should use a specific version of boost and boost.sync and especially not depend on any distro-specific boost version. i know that traditionally linux distros don't encourage so and with c libraries this might have some good reasons. but in the c++ world, this does not necessarily hold: iirc in the past the boost binaries provided by debian were not usable in c++11 code, as the std::string ABI changed between c++03 and c++11 and when a library is mainly header-only there's also no point in updating the library without recompiling the app.
fortunately distros these days figured out that this is a problem and come up with technologies like snap or flatpack to *avoid* coupling the build system of distros with applications

that said:
* i'd strongly recommend to bundle boost and link statically instead of pulling in any distro-provided version
* personally i'd go for boost.sync's semaphores rather than nova-tt. the boost ones are based on the ones in nova-tt, but are more widely used.
* when it comes to `std::semaphore`, it may be some time until it's provided by the run-time libraries. furthermore it might be worth comparing the performance with native semaphores: e.g. on macos system-v, mach and dispatch semaphores all have quite different performance characteristics

**Comment by brianlheim** [comment]
@dvzrv arch is on 1.75 now, am I OK to close this?

**Comment by dvzrv** [comment]
@brianlheim ah, thanks for the reminder. Yes, supercollider has been rebuilt against latest boost on Arch and this can be closed.
