### ISSUE TITLE
Pbindef cannot handle Envs 

### ISSUE THREAD

**Issue by dkmayer** [supercollider/supercollider#5285]
SC 3.11.1 on OS 10.15

Env and Penv are failing here:
```
(
Pbindef(\test,
	\dur, 0.2,
	\midinote, Env([60, 70, 60], [2, 2])
).play
)
-->
ERROR: Message '+' not understood.
RECEIVER:
Instance of Env
```

```
(
Pbindef(\test,
	\dur, 0.2,
	\midinote, Penv([60, 70, 60], [2, 2])
).play
)
-->
ERROR: Message '+' not understood.
RECEIVER:
Instance of Penv
```
As a workaround we can use Pseg and Ptime + Pfunc 
```
Pdef.removeAll

(
Pbindef(\test,
	\dur, 0.2,
	\tm, Ptime(),
	\midinote, Pfunc { |e| Env([60, 70, 60], [2, 2])[e[\tm]] }
).play
)

(
Pbindef(\test,
	\dur, 0.2,
	\midinote, Pseg(Pseq([60, 70, 60]), 2)
).play
)
```

**Comment by telephon** [comment]
the source is in `PatternProxy` `embedInStream`, or rather that `streamArg` treats envelopes like objects rather than patterns.

```supercollider
a = PatternProxy.new;
a.source = Env([60, 70, 60], [2, 2]);
a.asStream.next(Event.default); // NOT OK

a = PatternProxy.new;
a.source = Pseq([1000]);
a.asStream.next(Event.default); // OK

a = PatternProxy.new;
a.source = Env([60, 70, 60], [2, 2]);
a.endless.asStream.next(Event.default); // OK
```

**Comment by telephon** [comment]
This is a good illustration how the type of an object depends on context in smalltalk-style OOP.

In general, there are two behaviours of objects when `asStream` is called:
1. return some kind of generator for values
2. return a static object

The reasoning behind this is that an object is the minimal concept of a stream (just returning itself). Because we have different behaviour of objects when embedded in streams (comparing e.g. `Pbind` and `Pseq`), we need a delegating message like `streamArg` when we want to be able to switch between them (like we do in `PattternProxy`).

Any object that falls under the first "type" should implement `streamArg` more or less like Pattern.

here are the candidates in my current class library:
```supercollider
Class.allClasses.select { |class| class.isKindOf(Pattern).not and:{  class.methods.notNil } and: { class.methods.any { |x| x.name == \asStream } } }.collect { |x| x.name }
// =>

[ BusPlug, Env, Meta_Rest, Object, Pattern, PatternProxy, Pbinop, Pclose, Pcollect, Pfunc, Pif, Pkey, Pnaryop, Preject, Prout, Pselect, Pspawner, Punop, RandomOrbit, ScaleAD ]
```

Most of them are pattern wrappers. `BusPlug` and `Env` seem the most relevant ones.

**Comment by telephon** [comment]
My prediction was that `BusPlug` has the same problem:

```supercollider
g =  BusPlug.control(s);
Pbindef(\x, \ttt, g).trace.play;
```

good! So the fix is clear. 

But I wonder how to document this better.

**Comment by telephon** [comment]
The solution at #5287 is just for this specific case, to keep changes small.

**Comment by dkmayer** [comment]
Yes, it works for Env and Penv now. Thanks for the quick fix !
