### ISSUE TITLE
Is it possible to run supercollider scripts on a server without GUI like CentOS?

### ISSUE THREAD

**Issue by ZacheryGuan** [supercollider/supercollider#5400]
I want to do some non-realtime audio processing on a CentOS server. From the document, I see most of supported systems have GUI interfaces. I guess it is because the IDE needs it. 

Now I just want to deploy my `.scd` scripts on a server: run it in the shell with input_file_path and output_file_path as arguments. Is it available? 

Thanks!

**Comment by brianlheim** [comment]
Yes, on Linux you can either build SC headless or run it with a virtual display. Both scenarios are described in the RPi readme, since this is normally where that requirement comes up: https://github.com/supercollider/supercollider/blob/develop/README_RASPBERRY_PI.md

Btw, for future reference this would be a better question for our user forum: scsynth.org. You'll get faster help there and more people will benefit from the discussion.
