### ISSUE TITLE
Cmd-Period doesn't work with help focussed.

### ISSUE THREAD

**Issue by tommaisey** [supercollider/supercollider#541]
I'm using Qt (I switch to it in startup.rtf) on OSX 10.8.2.

When the docs have focus I have found that Cmd+Period does not stop running synths. This could be confusing to new users, who may not realise they have to switch to the IDE to do this.

**Comment by fmiramar** [comment]
This is still happening under Windows 10 (version 20H2) SuperCollider 3.11.2, but not happening on Mac.

When the help window is focused and I hit `ctrl + .` then a `.` appears on the Help Doc and it does not terminate the server and lang processes. It only terminates the processes when the code editor view is focused. (if the whole of code on the doc is selected, then it will be substituted by a single `.`)

**Comment by dyfer** [comment]
Thanks @fmiramar 
I just checked - I cannot reproduce it on Windows 10. I tried with the help window docked and detached, also with and without code editor focused, and in all cases `ctrl + .` worked for me. 

> then a `.` appears on the Help Doc

Where does it appear?

**Comment by fmiramar** [comment]
Hi @dyfer !Thanks for the maintenance! 

Here is the selection and execution of a line of code from them help browser:

![scgit1](https://user-images.githubusercontent.com/54965070/114609550-4fde2f80-9c75-11eb-931d-ca3e16506ead.png)

This is what happens when I still have this line select and hit `ctrl + .`  (no process terminated on the server):

![scgit3](https://user-images.githubusercontent.com/54965070/114609755-84ea8200-9c75-11eb-9137-a33ae8f2a921.png)

This is what happens when I only have the cursor positioned (no line selection) at the line of the Help code which I've ran and then I hit `ctrl + .` (again no process terminated on the server):

![scgit2](https://user-images.githubusercontent.com/54965070/114609982-caa74a80-9c75-11eb-81cc-bf24d525e66b.png)


BTW: the cursor degradation that I mentioned on  #4726 is still happening. Although now it more likely to have the cursor disappearing than having it degraded.

**Comment by dyfer** [comment]
@fmiramar thanks for the detailed information.
Would you be willing to test whether this still happens on the latest develop build (found on our [download page](https://supercollider.github.io/download))?

**Comment by fmiramar** [comment]
@dyfer thanks! This issue seems to be solved on the latest build x64. 

However I found some new strange behaviour. At the bliking time when running the code on the code docklet, the text is getting decreasingly pixelated... Here is a gif screencast (not sure if allowed on github):

![scgit-gif3](https://user-images.githubusercontent.com/54965070/114920851-42a17c00-9e00-11eb-9a7b-1e452aaab5a8.gif)

**Comment by dyfer** [comment]
Okay, so it seems this has been fixed either in our code, or by (likely) because we updated Qt in the develop build. 
That pixelating behavior looks like some interaction between Qt rendering, antialiasing (?) and possibly system graphics settings. If that turns out to still be a problem in the upcoming 3.12, feel free to open a new issue for it.

**Comment by fmiramar** [comment]
Ok! Thanks!
