### ISSUE TITLE
UnitTest.schelp example is broken

### ISSUE THREAD

**Issue by madskjeldgaard** [supercollider/supercollider#5541]
There are several issues with the `    test_yourMethod ` method in the example in the UnitTest help file that prevents it from compiling:

https://github.com/supercollider/supercollider/blob/8ff17affaf821ea3800b670de6762d1c0afde125/HelpSource/Classes/UnitTest.schelp#L397-L422

- The variable `p` is undefined.
- The `p.register` method fails.
- The test ```this.assertFloatEquals( 4.0 , 1.0 * 4.0 / 4.0  4.0,
            "floating point math should be close to equal");``` has a syntax error (one 4.0 too many?)

**Comment by madskjeldgaard** [comment]
On a related note: The "Writing tests" guide could use a revamp. It is a little bit too sparse IMO. I think it should address how you would incorporate testing in your class writing, what the workflow and mindset is and cover some examples of use. 

https://github.com/supercollider/supercollider/blob/8ff17affaf821ea3800b670de6762d1c0afde125/HelpSource/Guides/WritingTests.schelp

**Comment by capital-G** [comment]
I tried this code

```supercollider
TestYourClass : UnitTest {
	setUp {
		// this will be called before each test
	}
	tearDown {
		// this will be called after each test
	}

	test_yourMethod {
		// every method whose name begins with "test_" will be run
		var bundle;
		var synth;

		this.assert( 6 == 6, "6 should equal 6");

		this.assertEquals( 9, 9, "9 should equal 9");

		this.assertFloatEquals( 4.0 , 1.0 * 4.0 / 4.0, 4.0,
			"floating point math should be close to equal");

		// we are inside a Routine, you may wait
		1.0.wait;

		// this will wait until the server is booted
		this.bootServer;
		// if the server is already booted it will free all nodes
		// and create new allocators, giving you a clean slate

		// check NodeWatcher docs
		// we need to attach to a node before its created
		// with NodeWatcher in order to determine its playing state
		// this can be achieved by sending a bundle to the server
		// which we will create now
		bundle = Server.default.makeBundle(
			time: false,
			func: {
				synth = {SinOsc.ar * 0.1}.play;   //create a node object
				NodeWatcher.register(synth); // register before creating on the server
			},
		);
		// via node we now have a handle for the node that should be playing
		// we now send the bundle to the booted server
		Server.default.listSendBundle(time: nil, msgs: bundle);
		// i try to wait here
		Server.default.sync;

		// will wait until the condition is true
		// will be considered a failure after 10 seconds
		this.wait( { synth.isPlaying }, "waiting for synth to play", 10);
		node.free;
	}
}
```

(which is already quite verbose for an example) and tried to fix this but I stumble upon an error

```supercollider
FAILURE IN SERVER /s_new duplicate node ID
```

Running the same code in interpreted mode works

```supercollider
(
b = s.makeBundle(
	time: false,
	func: {
		a = {SinOsc.ar(200)*0.1}.play;    //create a node object
		NodeWatcher.register(a); // register before creating on the server
    },
);
)

a.isPlaying;
s.listSendBundle(nil, b);
a.isPlaying;
s.freeAll;
```

Regarding the test philosophy: I think the mixing of unit and integration test in sclang is not a good pattern - tests are run rarely because of this as they take a long time and also can't be run on CI/CD / headless systems automatically in a useful manner. Tests should be really made easy to run at all times and currently this is not the case IMO.

In my experience as a software engineer we had an agreement in our team to not exceed the run time of 10 secs for all tests - including mutating and mocking tests. This allows to run the tests anytime a file is saved which is great when going for coverage and branch testing. At the same time it is questionable if best practices from other programming languages apply here as well due to limited resources but at the same time sclang is a programming language as well, so thoughts and concepts about state, especially concerning the server, should be mentioned and introduced - this would also introduce the notion of mocking.

**Comment by telephon** [comment]
Perhaps it would be a good idea to 
- add a method to unit test that tells you how much time it is expected to take. Then you could test selectively, without creating a boundary.
- check the tests again which can be shortened in time

I don't see a way to separate integration and module test, as you say, this is a programming language, so in principle we always have an integration issue.

**Comment by capital-G** [comment]
Back in my Python days we did not call the database directly when doing unit tests as the database has not much to do with logic but introduces just an outside state which is hard to be controlled by the test. On the other hand: integration tests where one is hitting a test-database could be run via docker or in CI/CD starting from a clean state all the time which is set up the environment to make sure tests are running in a deterministic way - but on those only the communication between the services is tested and rarely their logic in order to separate implementation and integration. But this requires that the communication is abstracted unified in a single class which is not the case.

This has the advantage of running the tests quick (e.g. after each save) and also have stateless unit tests as there are no outside dependencies to the test (e.g. tests could fail if the server can not boot which is more a problem of scsynth than of sclang).
Handling states in tested systems is the most problematic thing and where functional programming really shines the most.

The main problem we are facing w/ sclang: it is geared towards controlling scsynth and the communication between is not abstracted in a unified way.
Things like Patterns or any logic which do not rely on a communication with the server can be tested as a unit test quite easily and do not need integration tests. But testing any kind of state management of the server via sclang gets difficult. 

Another problem regarding tests in SC in general: They do not pass on my version (3.11.2) and are pretty verbose and there are deprecations mentioned.
Running `UnitTest.all` on my system gives me the following output.

```supercollider
RUNNING UNIT TEST 'UnitTestScript'
RUNNING UNIT TEST 'TestMovingSum'
Booting server 'localhost' on address 127.0.0.1:57110.

[...]

WARNING: Called from TestMovingSum:test_runningSums, method Object:asInt is deprecated and will be removed.
The definition of 'Object:asInt' is to be found here: '/Applications/SuperCollider.app/Contents/Resources/SCClassLibrary/deprecated/3.11/deprecated-3.11.sc'


FAILURE IN SERVER /s_new duplicate node ID
PASS: a TestMovingSum: test_runningSums - MovingSum
RUNNING UNIT TEST 'ProbingStenoTest'
""
new quelle: "c" with 1 channels
new quelle: "a" with 1 channels
new quelle: "b" with 1 channels
new quelle: "d" with 1 channels
new operator: "*" with 1 channels and arity 2
new operator: "+" with 1 channels and arity 2
new quelle: ">" with 1 channels
new quelle: "1" with 1 channels
new quelle: "a" with 1 channels
new quelle: "d" with 1 channels
new operator: "*" with 1 channels and arity 2
new quelle: "1" with 1 channels
new quelle: ">" with 1 channels
new operator: "+" with 1 channels and arity 2
new quelle: "c" with 1 channels
new quelle: "b" with 1 channels

FAIL: a TestMovingSum: test_runningSums - RunningSum
24000 of 24000 items in array failed to match. Displaying arrays from index of first failure (0) onwards:
FloatArray[ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...etc...
! = 
[ 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,...etc...


""
Safety('localhost') is running, using 'safeClip_2'.
"abcd>"
PASS: a ProbingStenoTest: test_serial_signal_path - serial signals should add up
Is:
	 22.0 
Should be:
	 22
""
"[abcd]>"
PASS: a ProbingStenoTest: test_serial_signal_path - parallel signals should add up
Is:
	 22.0 
Should be:
	 22
""
"{abcd+++}>"
PASS: a ProbingStenoTest: test_serial_signal_path - operator signals should be combined
Is:
	 22.0 
Should be:
	 22
new filter: "c" with 1 channels
new filter: "a" with 1 channels
new filter: "b" with 1 channels
new filter: "d" with 1 channels
releasing old synth with id: Synth('c_-292234408' : 1019)
releasing old synth with id: Synth('a_-292234408' : 1017)
releasing old synth with id: Synth('b_-292234408' : 1018)
releasing old synth with id: Synth('d_-292234408' : 1020)
""
"1a>"
PASS: a ProbingStenoTest: test_serial_signal_path - tesing filter identity
Is:
	 1.0 
Should be:
	 1
------------  1  ------------
0
0
------------  a  ------------
0
0
------------  >  ------------
0
0
server 'localhost' disconnected shared memory interface
'/quit' message sent to server 'localhost'.
Server 'localhost' exited with exit code 0.

UNIT TESTS FOR 'UnitTest' COMPLETED
There were failures:
a TestMovingSum: test_runningSums - RunningSum
24000 of 24000 items in array failed to match. Displaying arrays from index of first failure (0) onwards:
FloatArray[ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...etc...
! = 
[ 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,...etc...
```

This could be avoided if those tests would be running in CI/CD all the time.

Coming back to topic: What is the exact problem on my code above? I can not figure out what the problem is there.

**Comment by telephon** [comment]
> I tried this code

how did you try it?

**Comment by dyfer** [comment]
> This could be avoided if those tests would be running in CI/CD all the time.

Not sure what you mean? The tests are currently run in the CI, see [here](https://github.com/supercollider/supercollider/runs/3330847228?check_suite_focus=true).

About your problem - it seems that you try running test(s) from sc3-plugins (`MovingSum` is in sc3-plugins). It is true that we do not run those in CI, we only run unit tests from the main repo. To run tests from the main repo, you need to add `testsuite/classlibrary` from the repo to the library compilation path, remove temporarily sc3-plugins (to avoid broken tests from there), recompile library and then run `UnitTest.runAll`.
