### ISSUE TITLE
Sample rate issues after updating to Monterey OS

### ISSUE THREAD

**Issue by sloopy2** [supercollider/supercollider#5605]
Hey all, 

I can't seem to figure out what's going on after updating to MontereyOS. Was initially getting a very tinny/ grainy sound thru my headphones when playing buffers and after tweaking the server sample rate in my troubleshooting process, I am receiving this error: 

`Requested sample rate 48000.000000 was not available - attempting to use sample rate of 24000.000000
`

Any suggestions? My headphones are set at 48kHz and prior to this update I never had any issues. 

Thank you!

**Comment by jparmentervf** [comment]
what sound interface are you using? Built in? What kind of Mac?

**Comment by sloopy2** [comment]
Hey @jparmentervf,

Sound interface is built in. I am using Macbook Pro Microphone as Input Device and AirPod Pros as Output Device. MacBook model is the 13' M1 Apple Silicone (2021). Using patched release for Big Sur/ M1 found here: https://scsynth.org/t/announce-new-supercollider-3-11-2-patched-release-available-for-macos-big-sur/3295 

Thanks for looking into this!

**Comment by dyfer** [comment]
Hey @sloopy2, could you please try the 3.12.1 release?

**Comment by sloopy2** [comment]
@dyfer,

I updated to the 3.21.1 release and am still having issues. The sample rate for the AirPod Pros are 48kHz. I tried using a few other outputs such as my MacBook speakers and a pair of AudioTechnica's and am not having the issue so I am wondering if it has to do with the Bluetooth connection. 

How can I leave the sample rate unset? Looking for documentation on that, I only see default rates and set to functions.

Thanks

**Comment by dyfer** [comment]
> I am wondering if it has to do with the Bluetooth connection.

I'm quite certain it does :) but it doesn't necessarily mean it's impossible to use.

I _think_ it's a limitation of bluetooth, that if both the headphone and its microphone is used (i.e. both audio out and in for the BT device), they switch to a lower samplerate due to bandwidth limitations. I don't know if that holds true for the airpods though.


> How can I leave the sample rate unset? Looking for documentation on that, I only see default rates and set to functions.

`Server.default.options.sampleRate_(nil)` or using the global variable convention `s.options.sampleRate_(nil)` 

Generally, there are two parameters that might be at play here: the discrepancy between supported/requested sample rate and supported/requested hardware buffer size (`.options.hardwareBufferSize`). I'd experiment setting different values for both, including `nil` (which means "use the default / use what the hardware provides").

I think `scsynth` uses default hardware buffer size of `512`, I would also test `1024`, `2048` and maybe `256` for bluetooth.

I'd really suggest to try the Aggregate Device method (with both the airpods as well as the built-in mic device). I'd activate "drift correction" for airpods in the aggregate device setup.

**Comment by sloopy2** [comment]
@dyfer 

Ahhhhh!! It worked! I changed the hardware buffer size to 256 and it works perfectly.

Thank you.
Much appreciated!
