### ISSUE TITLE
sin(pi)

### ISSUE THREAD

**Issue by paum3** [supercollider/supercollider#5625]
Calculation of sin(pi) seems wrong? Sould be zero, actually is not.
## Environment

* SuperCollider version: 3.12
* Operating system: archlinux

## Steps to reproduce

```supercollider
sin(pi) // is not zero but  1.2246467991474e-16 ?
```

**Comment by telephon** [comment]
That is fine, just floating point representation.
https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by jamshark70** [comment]
Not only floating point.

Computers necessarily have finite precision. (Even if a computer were made of all the material in the universe, it would still be finite.) Pi, being irrational, is an infinite non-repeating decimal. So there is literally no way for the SC constant `pi` to be exact. Thus, there is no way for `sin(pi)` to be 100% exact either.

But... could it be closer? A: No.

You can check the closest double precision numbers on either side of SC's `pi` (straightforward because the mantissa is in the lowest bits):

```
(
h = pi.high32Bits;
l = pi.low32Bits;

(-1 .. 1).do { |lowBitIncrement|
	var theta = Float.from64Bits(h, l + lowBitIncrement);
	[theta, sin(theta)].postln;
};
)

[ 3.1415926535898, 5.665538897648e-16 ]
[ 3.1415926535898, 1.2246467991474e-16 ]
[ 3.1415926535898, -3.2162452993533e-16 ]
```

Because this is changing only the least significant bits, by an increment of exactly +/-1, we can be certain that there is no floating point number between the numbers being tested -- it's as close as it can get without being equal. True 0 for `sin(x)` would need x in between SC `pi` and SC `pi` plus a teeny tiny bit -- but this x doesn't exist in double precision. The magnitude of `sin(pi + smallestDoublePrecisionInterval)` is greater than the magnitude of `sin(pi)` -- that is, any possible adjustment to SC's `pi` would be worse than the current value.

**Comment by telephon** [comment]
Thank you for the details!

>Thus, there is no way for sin(pi) to be 100% exact either.

While what you say is right in most  other cases, not for this one.

`sin(pi)` is exactly zero, easily representable even in a very tiny universe. It is part of the joy of mathematics that we traverse the infinite and end up in some place next door.

**Comment by paum3** [comment]
Thank you. Really interesting.

**Comment by jamshark70** [comment]
> sin(pi) is exactly zero

That's true for *mathematical* pi.

It isn't true for a double precision floating point approximation of pi, which is the best that SC can reasonably do.

**Comment by telephon** [comment]
I think the main point is that writing `pi` in sclang immediately maps to a floating point number. 

In a different representation, sclang could easily calculate `sin(pi) ` as zero. We could introduce a number system that is represented by multiples of 2pi (call it radians), and you could derive that `Rad(1) == 0` as much as you could say that 1 - 1 == 0`
