### ISSUE TITLE
FlowVar.value returns \unbound if `next` is called more than once on the Routine that is hosting it

### ISSUE THREAD

**Issue by avdrd** [supercollider/supercollider#5660]
## Environment

* SuperCollider version: 3.12.1
* Operating system: all

## Steps to reproduce

```
(
~fv = FlowVar.new;
r = Routine {
	"Routine starts".postln;
	v = ~fv.value + 0.1;
	"Routine got its value % to work with".format(v).postln;
	v.alwaysYield;
};
)


r.next
// Routine starts
// -> hang
r.next
// Routine got its value unbound to work with
// -> unbound
```

## Expected vs. actual behavior

I'd have expected it to hang again until the value of the FlowVar is actually set.

To give a bit more motivation why someone would try something like this: imagine you write a selector Routine that reads data in Unix-select style from several other routines (or streams), meaning some of the latter can return \hang and some not, and your selector routine stops e.g. at the first non-hang (real) data it receives and yields that bit. With that approach it's inevitable that a routine that gave a \hang may be called again while it's still supposed to hanged, but with FlowVar as presently implemented it will return \unbound on subsequent calls.

## Proposed fix (work in progress)

For my use I've changed it like

```
+ FlowVar {
	value {
		while { value == \unbound } { // mod
			condition.wait
		};
		^value
	}
}
```

So now with the above setup it does re-hang multiple times until a value is actually set with `value_`.

```
r.next
//Routine starts
//-> hang
r.next
//-> hang
r.next
//-> hang
~fv.value = 12
// Routine got its value 12.1 to work with
```

Actually that is not entirely a good fix. Because `Condition.wait` will add multiple entries of the same thing to its queue, in that while loop, so thereafter on `Condition.signal` (called by `FlowVar.value_`), the same routine will be scheduled on the clock and then run several times. `alwaysYield` in the above example unfortunately masked this issue, but it becomes apparent if the routine does a `loop { /* side-effect like postln */ something.yield }` instead.  Here's that kind of example:

```
(
~fv = FlowVar.new;
r = Routine { loop {
	"Routine resumes".postln;
	v = ~fv.value + 0.1;
	("Routine got its value:" + v).postln;
	v.yield;
}};
)
```
With the current FlowVar this latter example actually alternates between \hang and \unbound at every `r.next`

Just with the not so great fix I proposed above, it does something like

```
r.next
r.next
~fv.value = 145
// Routine got its value: 145.1
// Routine resumes
// Routine got its value: 145.1
```

I.e. runs twice.

So, we'd need to avoid those duplicate entries somehow, but Condition doesn't make querying its queue terribly easy. I'll have a look at CondVar to see if it makes that kind of management any easier. <s>If it's so, I'll propose a reimplementation of FlowVar using CondVar. </s> Unfortunately, CondVar does nothing about duplicates either. Basically, instead of that Array that Condition uses for `waitingThreads`, it should probably use an IdentitySet. I can't think of a good reason right now to schedule the same thing multiple times in Condition.wait.

**Comment by scztt** [comment]
Seems like changing `Condition` so that uses:
```
waitingThreads = waitingThreads.add(thisThread.threadPlayer);
\hang.yield;
waitingThreads = waitingThreads.remove(thisThread.threadPlayer);
```
... should provide the same guarantee, without using a more complex data structure? I'm not sure how this will interact with the details of `:signal` / `:unhang`, and there are very few unit tests for this class - but it may greatly simplify those implementations as well.

**Comment by avdrd** [comment]
Looks promising, I hadn't thought of that. `remove` does a linear but shouldn't matter too much, I guess.

**Comment by jamshark70** [comment]
It struck me this morning.

There are two uses for threads in SC. One is for scheduling; in this case, the yield values are related to timing. The other is to produce data (and the yield values are the data).

These uses are not mutually compatible. A data-producing routine should not be scheduled (I can't think of any exceptions). It *is* possible to `next` a scheduling thread directly, but then you have access only to the timing values, and no access to the side effects... so this is possible, but not especially interesting.

- Condition: `thread.clock.sched(0, thread);`
- CondVar: `prWakeThread { |t| t.clock.sched(0, t) }`

So these classes are meant to be used for scheduling threads. If data-producing routines shouldn't be scheduled, then it's inappropriate to use these classes with data-producing routines.

FlowVar uses Condition. Therefore, it's inappropriate to use FlowVar with a data-producing routine as well!

I don't think it's incorrect to change CondVar (and even Condition) to prevent duplicate registrations, and I can't think of a case where PR #5671 would be invalid.

But I don't think this is going to solve your stream-selector problem -- because this problem is about data-producing threads, and you're trying to use blocking mechanisms that are meant for scheduling. It's true that the name and description of FlowVar might lead you to expect that it's OK here too, but I think a lot the effort here is trying to turn a hammer into a pair of pliers, and you could get where you're going faster by putting down the hammer.

So I think the real solution is to create an alternate version of FlowVar that just returns the data, without rescheduling.

Here's a quick try. Maybe not everything is right, but:

```supercollider
BlockedData : FlowVar {
	value {
		while { value == \unbound } {
			\hang.yield
		};
		^value
	}
	value_ { |inVal| value = inVal }
}
```

Then:

```supercollider
d = BlockedData.new;

(
r = Routine {
	(d.value + 1).yield;
};
)

r.next;  // hang
r.next;  // hang
r.next;  // hang

d.value = 4;

// ^^ no action from the thread
// why? because *it's not a scheduling thread*

r.next;  // 5, yes!
r.next;  // nil, because the Routine's function ended
```

**Comment by avdrd** [comment]
> FlowVar uses Condition. Therefore, it's inappropriate to use FlowVar with a data-producing routine as well!

It seems to me you're creating an unnecessary dichotomy. If you look at something like Java that has InterruptedException-- that can also wake a thread up when the condition it was waiting for wasn't actually met.

> So I think the real solution is to create an alternate version of FlowVar that just returns the data, without rescheduling.

Class spam. Every class will now get two versions, one that can be scheduled and wait conditions and one that only works in "data producing slave mode".

**Comment by jamshark70** [comment]
> Also your BlockedData won't actually unblock callers when its data is changed.

That's correct... because "imagine you write a selector Routine that reads data in Unix-select style from several other routines (or streams), meaning some of the latter can return \hang and some not, and your selector routine stops e.g. at the first non-hang (real) data it receives and yields that bit" (your words).

You want the sub-streams to be under control of the stream selector. You're saying here that you don't want them to be autonomous.

So what happens when one of these sub-streams unblocks, wakes up on a clock, produces data, and... then where do the data go? In that scenario, they aren't going to the stream selector... but you've said that the stream selector is where you want them to go. The "selector Routine... reads data... from several other routines." Now maybe I don't see what you mean, but if one of these several other routines ends up under control of a clock rather than under control of the selector, it seems to me that this scheme is broken.

It looks to me like the selector stream could be passive (something else requests data from it), or active (running on a clock) -- but the sub-streams *must be passive* or else you have no idea what's going to happen to their data. And if they are passive (only activated by `next` from an interested party), then auto-unblocking is not at all what you need.

I will also add that your last post relies rather heavily on emotionally loaded words and I find it all highly toxic. This is an interesting logic problem. It's supposed to be fun. When you address people like that, it isn't fun anymore.

**Comment by avdrd** [comment]
I don't care about this issue anymore because I don't use this class anymore, having written my own substitute for it, rather than have to explain here over and over why this is desirable. I can see now that's [par for the course](https://github.com/supercollider/supercollider/pull/5394) around here though.

Also, I find the above lecture on civility and toxicity rather bemusing sealioning in view of expressions like "unfocused speculation in this whole inquiry", "obsessiveness of recent activity" and so forth addressed to me by yourself on the forum while discussing this.

Rest assured my "obsessiveness" with making the SC synchronization classes any better has just ended, as I realized I need not bother because they are not used across any noteworthy interfaces, only in the test suite and the like.  So, enjoy your SC synchronization classes as they are and I'll enjoy the ones I've written for myself.

Happy holidays to y'all.
