### ISSUE TITLE
Routine.stop.reset doesn't stop, even though reset has no intrinsic run behavior

### ISSUE THREAD

**Issue by avdrd** [supercollider/supercollider#5664]
## Environment

* SuperCollider version: 3.12.1
* Operating system: all

## Steps to reproduce

```
x = Routine { loop { "Hi".postln; 1.wait } }

x.play

x.stop.reset // keeps going!!

x.stop // this actually stops it
x.reset // ok like this, won't re-run it by itself, by the way
```

## Expected vs. actual behavior
I'd have expected `x.stop.reset` to stop the routine just as well.

**Comment by avdrd** [comment]
As it was helpfully pointed out [on the forum](https://scsynth.org/t/beware-of-routine-stop-reset/5100/2), if one increases the rescheduling interval to a few seconds, then even a well-time manual sequence of separate commands like

```
x.stop // hit right after a "Hi" message is posted
x.reset // and this one soon thereafter
```
 will cause the problem to occur, meaning that `reset` "eats" the stop.

**Comment by jamshark70** [comment]
> It's been suggested that there should be instant removal from clock and other queues, buut this seems to me hard to do, e.g. queues like the Condition ones are not clock queues

That's a fair point -- a Routine couldn't remove itself from a clock (or CondVar) because it doesn't know where it's referenced. ... which might lead to the conclusion that JMc's design was actually quite good (or at least reasonable) and that these edge cases need to be handled in a different way.

I'd have to say that I'm only in partial agreement with the thrust of some of these threading-related bug reports and forum threads. The assumption seems to be that it is always good for sclang to make it illegal to do any sort of thing with Routines that will lead to inconsistent or puzzling behavior. This would seem to be self-evident -- "well of course sclang should protect the integrity of core objects" -- but on the other, I'm not sure a computer language exists anywhere that prevents the user from making *all* types of mistakes. (E.g., it has always been possible to f...oul up the timing of a thread by double-scheduling it. But SC relies on users to simply not do that, just as, say, the manufacturer of a set of home weights relies on users not to break bones by dropping 15 kg onto their feet.)

A more relevant question might be, how easy is it to avoid (by users' free will) problematic edge cases? If it were hard, SC would have been unusable and wouldn't have survived 25+ years.

**Comment by avdrd** [comment]
I'm not sure your "just don't do that" approach is reasonable in the ".stop.reset" case.  Because it's a rather normal idiom try to do.  I can even show you it being [done](https://github.com/supercollider/supercollider/search?q=.stop.reset&type=code) in the Test suite, although apparently it doesn't break anything there, even though it probably doesn't quite work as someone hoped it does.

**Comment by avdrd** [comment]
But, yeah, after looking at the simplicity of the state machine code in PyrPrimitive, I don't see this realistically ever being fixed in SC3, so self-closing.

**Comment by jamshark70** [comment]
> I'm not sure your "just don't do that" approach is reasonable in the ".stop.reset" case. Because it's a rather normal idiom try to do.

Since this is closed and nobody will look at it, I won't develop the argument fully here, but a radical alternative viewpoint is that `Routine:reset` is never needed, and that it should be preferred to create a new Routine instead. This is probably contentious, but to outline the argument, a Routine is either disposable (one-shot) or persistent. If it's disposable, then there is no need to preserve any state, hence, no benefit to resetting it over creating a new one. If it's persistent (you need to preserve the Routine's state independent of play/stop/blocked status), then it makes sense to isolate the Routine's execution state from its state of being scheduled or blocked = PauseStream / Task.

> I can even show you it being done in the Test suite

Yeah, those should be changed to fork new routines in each case. Those are perfect examples of what I would call a "disposable" thread.
