### ISSUE TITLE
[BUG?] Missing access to backtrace for logging and debugging purposes

### ISSUE THREAD

**Issue by jreus** [supercollider/supercollider#5752]
Hey all, I am a bit confused as to the workings of the error/backtrace system in sclang.
Quite often I need to run sclang headless, for example in long-running installations, and need to be able to create log files and remote notification systems for informing me of any errors that might occur.

For example, I've implemented a few useful debug/logging features [in this repository](https://github.com/jreus/RemoteTools/blob/main/RemoteTools.sc) - including a `FileLogger` inspired by python's rather nice `logging` module, and various pseudo-ugens for monitoring error conditions on the server like bad values, signal out-of-bounds, and silence. 

However, one thing that is very frustrating is the inability to read stack backtrace when handling language errors/exceptions. The [Debugging Guide](https://doc.sccode.org/Guides/Debugging-tips.html) suggests using the dumpBackTrace method. However, methods such as `Object: dumpBackTrace` and `Exception:postProtectedBacktrace` seem to completely bypass any access via language methods! This makes it impossible to build any kind of reasonably informative logging system around the basic exception handling capabilities of SC.

This issue is a continuation of [this discussion](https://scsynth.org/t/how-to-log-sclang-errors-including-stack-trace/5595) on scsynth.org

**Comment by telephon** [comment]
Yes, I've run into this, too. `dumpBackTrace` calls this https://github.com/supercollider/supercollider/blob/b92a9073bce1c7871553e089bbf1bf58381fcaf4/lang/LangSource/PyrInterpreter3.cpp#L3224-L3247

And you'd suspect `getBackTrace` to give you the string, but it doesn't do that.

Do you have a list of all error related primitives that print idirectly nstead of calling back sclang?

**Comment by JordanHendersonMusic** [comment]
The way to do this right now is to call `this.getBackTrace` which returns a `DebugFrame` inside of `Exception:reportError`. From the `DebugFrame` you can query the functionDef to get the source code, all the vars and args are there and you can see if the context is null to get the calling function.

While you can't accesses the existing backtrack, you can easily recreate your own.

I am slowly working on changing all the error message to do this because it allows you to find (with high probability) exactly where the user made the mistake.
