### ISSUE TITLE
libsndfile version 1.1.0 breaks building from source

### ISSUE THREAD

**Issue by StratosBichakis** [supercollider/supercollider#5756]
## Environment

* SuperCollider version: b92a9073bce1c7871553e089bbf1bf58381fcaf4
* Operating system:Mac OS X Monterey 12.2.1
* Other details (Qt version, audio driver, etc.): libsndfile v1.1.0 from Homebrew

## Steps to reproduce
```
cmake --build . --target install --config RelWithDebInfo 
```

## Expected vs. actual behavior

```
In file included from /Users/stratosbichakis/workspaces/learn/SuperCollider/server/scsynth/SC_CoreAudio.cpp:23:
In file included from /Users/stratosbichakis/workspaces/learn/SuperCollider/server/scsynth/SC_SequencedCommand.h:35:
In file included from /Users/stratosbichakis/workspaces/learn/SuperCollider/common/SC_SndFileHelpers.hpp:35:
/usr/local/opt/libsndfile/include/sndfile.h:356:31: error: typedef redefinition with different types ('struct sf_private_tag' vs 'struct SNDFILE_tag')
typedef struct sf_private_tag   SNDFILE ;
                                ^
In file included from /Users/stratosbichakis/workspaces/learn/SuperCollider/server/scsynth/SC_CoreAudio.cpp:23:
In file included from /Users/stratosbichakis/workspaces/learn/SuperCollider/server/scsynth/SC_SequencedCommand.h:32:
In file included from /Users/stratosbichakis/workspaces/learn/SuperCollider/include/plugin_interface/SC_World.h:31:
/Users/stratosbichakis/workspaces/learn/SuperCollider/include/plugin_interface/SC_SndBuf.h:25:28: note: previous definition is here
typedef struct SNDFILE_tag SNDFILE;
```

**Comment by StratosBichakis** [comment]
### suggested solution:
Change [SC_SndBuf.h:25](https://github.com/supercollider/supercollider/blob/develop/include/plugin_interface/SC_SndBuf.h):

from:
```
typedef struct SNDFILE_tag SNDFILE;
```
to: 
```
typedef struct sf_private_tag SNDFILE;
```

**Comment by StratosBichakis** [comment]
### Alternative Solution:
### Downgrade libsndfile to 1.31.0 using Homebrew
```
brew uninstall --ignore-dependencies libsndfile
brew tap-new $USER/local-libsndfile 
brew extract --version=1.0.31 libsndfile $USER/local-libsndfile
brew developer off
brew install libsndfile@1.0.31

```
https://cmichel.io/how-to-install-an-old-package-version-with-brew/

#### add the cmake  configuration option for libsndfile location 
```
cmake -G Xcode -DCMAKE_PREFIX_PATH=`brew --prefix qt5` -DSNDFILE_INCLUDE_DIR='/usr/local/opt/libsndfile@1.0.31/include' -DSNDFILE_LIBRARY='/usr/local/opt/libsndfile@1.0.31/lib/libsndfile.dylib' ..
```

for Intel
`-DSNDFILE_INCLUDE_DIR='/usr/local/opt/libsndfile@1.0.31/include' -DSNDFILE_LIBRARY='/usr/local/opt/libsndfile@1.0.31/lib/libsndfile.dylib'`

for M1
`-DSNDFILE_INCLUDE_DIR='/opt/homebrew/opt/libsndfile@1.0.31/include'`
`-DSNDFILE_LIBRARY='opt/homebrew/opt/libsndfile@1.0.31/lib/libsndfile.dylib'`

**Comment by dyfer** [comment]
Thanks @StratosBichakis 
That struct is declared inside our plugin interface and thus will possibly affect 3rd-party plugins, right? I'm not sure what the correct solution is. if we want to support the newer library version, we will likely need to also support <=1.31.0 for a while as well. Would that even be possible while maintaining plugin compatibility? (@joshpar @Spacechild1 ...help? :) )

**Comment by Spacechild1** [comment]
> The https://github.com/libsndfile/libsndfile/pull/706 claims it doesn't break the API for the users, but we do include this struct in our code...

We *are* libsndfile users. `SndBuf ` contains a `SNDFILE` *pointer*;  it doesn't matter what `SNDFILE` actually is, as we never work with the concrete type. `SNDFILE *` is basically just an opaque handle. That's what the libsndfile devs mean when they say it doesn't break the ABI/API for users.

---

Going back to the actual problem: `SndBuf.h` manually (re)defines a typedef from the `sndfile.h` header, so that plugins don't need to include `sndfile.h`. As we have seen, this is rather brittle and breaks once the library authors decide to change the underlying type.

A simple and bullet-proof solution would be to just define the `sndfile` member of `SndBuf` as a `void *`. To avoid verbose casts in the server code and in the disk I/O ugens, we can add a simple macro:
```
// SndBuf.h:
#define GetSndFile(x) ((SNDFILE *)x->sndfile)

// old usage:
count = buf->sndfile ? sf_readf_float(buf->sndfile, buf->data + mPos * buf->channels, mFrames) : 0;
// new usage:
count = buf->sndfile ? sf_readf_float(GetSndFile(buf), buf->data + mPos * buf->channels, mFrames) : 0;
```

---
Alternatively, we could get the type of `SNDFILE` directly from `<sndfile.h>` if it has been included before `SndBuf.h`, and otherwise define it as `void`.
```
// SndBuf.h:
// header
#ifndef SNDFILE_1
#define SNDFILE void
#endif

// footer
#ifdef SNDFILE
#undef SNDFILE
#endif
```
This would just require changing some #include orders in few files.

**Comment by dyfer** [comment]
Thanks for the explanation @Spacechild1!

IIUC the first solution would constitute a plugin API change. How about the second one? Are there pros/cons for changing it one way or another (aside from the API change, if that's the case)?

**Comment by Spacechild1** [comment]
> IIUC the first solution would constitute a plugin API change.

It wouldn't. The `sndfile` member isn't meant to be used by (external) plugins and changing `SNDFILE *` to `void *` doesn't affect the struct layout, since both are just pointers.

> How about the second one?

For (external) plugins there is no difference sinc in both options `sndfile` would be `void *`. The second option just avoids a cast (or macro) in those files that do need to access the `sndfile` member, but it's a bit hacky I have to admit :-)

I don't really have a preference...

**Comment by dyfer** [comment]
> > IIUC the first solution would constitute a plugin API change.
> 
> It wouldn't!

So do you mean that both "old usage" and "new usage" in your example would be valid?

**Comment by Spacechild1** [comment]
> So do you mean that both "old usage" and "new usage" in your example would be valid?

I just means that some parts of the Server code would need to be updated if `sndfile` becomes `void *`. We need to cast it back to `SNDFILE *` before passing it to `sndfile_*` functions, either with `(SNDFILE *)buf->sndfile` or with a convenience macro like `GetSndBuf(x)`.

The second option (checking for `SNDFILE_1`) tries to avoid this, but it's not exactly beautiful either, because it requires that `sndfile.h` gets included first.

I guess I slightly tend towards the first option because (sometimes) explict is better than implicit :-)

**Comment by dyfer** [comment]
Oh got it. So the change would need to be only in the server, not in the plugins, right?

**Comment by dyfer** [comment]
> > Oh got it. So the change would need to be only in the server, not in the plugins, right?
> 
> In the Server and in the DiskIO plugins (= the only plugins that use the `sndfile` member).

Hm, I don't thing we can guarantee that others don't use it, right? There's (defunct? but still) [NovaDiskIO](https://github.com/supercollider/sc3-plugins/tree/main/source/NovaDiskIO) in sc3-plugins. Someone also was asking on the forum about linking with libsndfile recently. Or are the external plugins not supposed to use this pointer and import `<sndfile.h>` instead?

**Comment by Spacechild1** [comment]
> Hm, I don't thing we can guarantee that others don't use it, right?

We can't guarantee it, but AFAICT it's really meant for internal use only. After all, there is no guarantee that the Server and the plugin link to the same libsndfile version!

> There's (defunct? but still) [NovaDiskIO](https://github.com/supercollider/sc3-plugins/tree/main/source/NovaDiskIO) in sc3-plugins.

It doesn't use the `sndfile` member. In fact, it doesn't use Buffers at all and rather has its own cueing mechanism.

As a side note, (ab)using Buffers for Disk I/O can have some nasty side effects: https://github.com/supercollider/supercollider/issues/5511

**Comment by dyfer** [comment]
Great, thank you again for in-depth explanations. I'll plan on preparing a PR with your first solution (unless you'd like to do that).

**Comment by dyfer** [comment]
I started working on this, but encountered some issues. Question: should [these](https://github.com/supercollider/supercollider/blob/develop/server/scsynth/SC_HiddenWorld.h#L121-L122) be replaced by macros (with appropriate changes whenever they are called), similarly to changes in `SC_SndBuf.h`, or is there some other way to address this? Should we add `sndfile.h` include in `SC_HiddenWorld.h`?

**Comment by dyfer** [comment]
Also, should sndfile become a `void` pointer [here](https://github.com/supercollider/supercollider/blob/develop/include/plugin_interface/SC_SndBuf.h#L148) or do we need to add `sndfile.h` include?
```c++
    SNDFILE* sndfile; // used by disk i/o
```

**Comment by Spacechild1** [comment]
@dyfer The only place where we would need to change `SNDFILE *` to `void *` is in the (public) `SndBuf` struct!

In all other cases, such as `HiddenWorld`, we just need to include `sndfile.h` (unless `NO_LIBSNDFILE` is defined).
