### ISSUE TITLE
scsynth not producing sound when booted with -Z 0

### ISSUE THREAD

**Issue by sonoro1234** [supercollider/supercollider#5788]
## Environment

* SuperCollider version: 3.12.12
* Operating system: windows 10

## Steps to reproduce

booting scsynth with -Z 0 (default buffer size) makes portaudio no capable of sound output

cause seems to be https://github.com/supercollider/supercollider/blob/18c4aad363c49f29e866f884f5ac5bd35969d828/server/scsynth/scsynth_main.cpp#L232 with NEXTPOWEROFTWO which makes it take value 1?

It does not happen in supernova.

I was previously using -Z -1 to achieve a value of 0 but something must have changed so that NEXTPOWEROFTWO(-1)=1

**Comment by dyfer** [comment]
I don't believe that hardware buffer size of 0 (`-Z 0`) ever meant "use default buffer size" for scsynth. It should just be unset in order to use the default value.

Currently, unset buffer size causes PortAudio to choose the `defaultLow(...)Latency` parameter, as you can see [here](https://github.com/supercollider/supercollider/blob/develop/server/scsynth/SC_PortAudio.cpp#L330-L335).

I believe that years ago - maybe after your suggestion @sonoro1234 ? - I looked whether we could introduce `-1` as a parameter for `defaultHigh(...)Latency` PortAudio setting, but that seemed impractical, since we [store that value as an unsigned integer](https://github.com/supercollider/supercollider/blob/develop/include/server/SC_WorldOptions.h#L68) in the API and changing that is a hurdle AFAIU. So `-Z -1` is just invalid in the current implementation.

_Maybe_ (I'm just speculating) if we checked for a value of 0 when parsing the argument, we could make this work, but the current behavior ("don't specify -Z to get the default buffer size") has been in scsynth for years.

**Comment by sonoro1234** [comment]
> current behavior ("don't specify -Z to get the default buffer size") has been in scsynth for years.

I am using that in Lua2SC. 
Perhaps it can be closed. Thanks.
