### ISSUE TITLE
Ppar does not accept Rest

### ISSUE THREAD

**Issue by kasparsj** [supercollider/supercollider#5853]
## Environment

* SuperCollider version: 3.12.2
* Operating system: MacOs
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
Ppar([Pbind(), Pseq([Rest(3), Pbind(\freq, 800)])]).play
```

## Expected vs. actual behavior

**It should start playing higher pitch note together with default after 3 seconds, instead errors:**

```
ERROR: Message 'asEvent' not understood.
Perhaps you misspelled 'even', or meant to call 'asEvent' on another receiver?
RECEIVER:
Instance of Rest {    (0x7f86885aab88, gc=28, fmt=00, flg=00, set=02)
  instance variables [1]
    value : Integer 3
}
ARGS:
PATH: /Users/kasparsj/Nextcloud/SuperCollider/projects/grusgrus/sketches/restart.scd
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = <instance of Rest>
		arg selector = 'asEvent'
		arg args = [*0]
	< FunctionDef in Method Ppar:embedInStream >
		arg j = 0
		var outval = <instance of Event>
		var stream = <instance of Routine>
		var nexttime = 0.0
		var now = 0.0
	Integer:do
		arg this = 1
		arg function = <instance of Function>
		var i = 0
	Ppar:embedInStream
		arg this = <instance of Ppar>
		arg inval = <instance of Event>
		var assn = nil
		var priorityQ = <instance of PriorityQueue>
	Routine:prStart
		arg this = <instance of Routine>
		arg inval = <instance of Event>
^^ ERROR: Message 'asEvent' not understood.
Perhaps you misspelled 'even', or meant to call 'asEvent' on another receiver?
RECEIVER: Rest(3)
```

## Fix

The fix should be simple, like, for example, adding `asEvent` method to Rest class:

```supercollider
asEvent {
	^(dur: this.dur, amp: 0);
}
```

**Comment by jamshark70** [comment]
I don't object to asEvent here, but:

```
	asEvent {
		^(dur: value, type: \rest);
	}
```

- Rest's variable is called `value` because it is not always used in a duration stream. (But, when a Rest is embedded directly in an event stream, we assume that the value represents a duration -- but this is the `dur:` keyword part, not the data-access part.)
- `amp: 0` does not represent a rest! A rest means *nothing* is done. `amp: 0` will play a synth, but silently. Playing a silent synth isn't the same as doing nothing.

FWIW I'm not sure if Rests should be considered interchangeable with Events, but we allow it outside of Ppar so we should allow it in Ppar too.

**Comment by smrg-lm** [comment]
Since Ppar embeds event streams user code can be fixed like this:

```sclang
Ppar([Pbind(), Pseq([(dur: Rest(3)), Pbind(\freq, 800)])]).play;
```

It would be more clear code. Pseq can sequentially embed event patterns because event can be treated as values as long as the values are processed as events in the resulting stream.

However, it also can be fixed with number that respond to asEvent with a Rest:

```
Ppar([Pbind(), Pseq([3, Pbind(\freq, 800)])]).play;
```

And Rest is an Operand that expect a numeric value, so Rest.asEvent could be added. I'm not saying no, just meant to clarify. Embedding event streams with Pseq is very common but isn't documented in the Pseq help file, maybe a note about these traits could be added.

**Comment by telephon** [comment]
I think that number.asEvent shouldn't return a rest of that number, because it results in errors that are hard to find. It happens easily that a number like the above sneaks in and in a larger composition, it could go undetected.

With `Rest.asEvent`, I am undecided, I think it could be OK.

**Comment by jamshark70** [comment]
> With Rest.asEvent, I am undecided, I think it could be OK.

I think we kind of have to, because:

```
// no problem
(
p = Pseq([
	Rest(2),
	Pbind.new
], 1).play;
)

p.stop;

// failed
(
p = Ppar([
	Pseq([
		Rest(2),
		Pbind.new
	], 1)
]).play;
)
```

With the first Pbind example, that ship has sailed -- we already allow Rest to act like a rest Event -- just, not *everywhere*. Inconsistent handling is not ideal.

**Comment by telephon** [comment]
OK, so `Rest(x).asEvent` should return `Event.silent(x)`. Also semantically makes sense.

**Comment by dyfer** [comment]
Fixed in https://github.com/supercollider/supercollider/pull/5882
