### ISSUE TITLE
Cannot boot Supernova on Windows

### ISSUE THREAD

**Issue by Spacechild1** [supercollider/supercollider#5994]
## Environment

* SuperCollider version: SC 3.13.0
* Operating system: Windows 10
* Other details (Qt version, audio driver, etc.): default audio devices

## Steps to reproduce

```
Server.supernova;
s.boot;
```

## Expected vs. actual behavior
```
Booting server 'localhost' on address 127.0.0.1:57110.
Supernova booting
Server 'localhost' exited with exit code -1073741676.
```

Can anyone confirm this?

**Comment by dyfer** [comment]
> Can anyone confirm this?

I think so. #5899

**Comment by Spacechild1** [comment]
D'oh. I actually particapted in that thread, but completely forgot about it :facepalm: Will have a look.

**Comment by zeos** [comment]
Same with my experience trying to boot Supernova.

system:
Windows 10, x64
SuperCollider 3.13 x64 (also tried with 3.14.dev)
MOTU UltraLight mk5

I got the same error:  
`Server 'localhost' exited with exit code -1073741676`

Any advice?

**Comment by dyfer** [comment]
Hi @zeos 
I'm afraid we don't have any updates on this. Until someone looks into specifics of compatibility between supernova and MSVC 2019 (and later), it might not boot on Windows in most cases.

**Comment by zeos** [comment]
Hi @dyfer , looks like ver. 3.8.0 / 3.8.0 beta 1 are the last releases that work on windows with supernova, back from 2016. That is kind of sad. Is it possible to compile 3.13 with VS2017 build tools including supernova?

**Comment by dyfer** [comment]
> That is kind of sad.

Just FYI, supernova used to not compile at all with Visual Studio and quite a bit of effort has been done to make it build with VS and thus bring it back on Windows in version 3.12. The 3.8 release was compiled with mingw/gcc and happened way before we had build automation in GitHub Actions (and even before Travis/AppVeyor I think). We can't build whole SC with mingw since QtWebEngine is not available there. Also, the developers decided to support VS as the preferred compiler for a variety of reasons a while back.

> Is it possible to compile 3.13 with VS2017 build tools including supernova?

GitHub Actions runners don't provide VS2017 anymore, so practically the answer is no.

The way forward is to find the bugs in the current build and fix them. BTW I wonder if one of the 3.12 release candidates was still built with VS2017 and thus runs properly?

**Comment by zeos** [comment]
Dear @dyfer, I highly appreciate all the amazing work that all devs are doing to keep SC going!
Concerning, the supernova, my question was related to building it from source with VS2017 locally on my Windows PC. I have built SC on Linux systems with supernova many, many times and it is straight forward, however, now I need to built it for windows x64.

**Comment by dyfer** [comment]
Thank you for clarifying, @zeos ! I appreciate it.
Yes, building locally should absolutely work. The instructions in the Windows readme should be helpfule, albeit might be at times outdates. Particularly, I don't think we tried using libsndfile from the (more recent) github releases, though in principle I don't see why would be an issue. Another "gotcha" is readline - if you'd like to build with it (to be able to use sclang from the command line interactively) then you need to use vcpkg, which is only mentioned at the end of the readme. 
Especially if you have previous experience building SC, by all means go ahead and try it and feel free to report any updates that need to be made to the Windows readme!
