### ISSUE TITLE
Reduce CI on forks

### ISSUE THREAD

**Issue by capital-G** [supercollider/supercollider#6036]
## Motivation

Everyone who has a recent fork of SuperCollider also clones its CI pipeline, which is convenient for development but also a waste of resources, as there are weekly builds that consume over 1 day of CI time (see https://github.com/capital-G/supercollider/actions/runs/5034978486). I also get an email every week with a failed Windows build.

## Description of Proposed Feature

Github CI allows to access the current repository via [`github.repository`](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) and each job or step can have an additional if condition where this job/step is run if the if condition holds.

I'd recommend to skip all matrix builds within a fork and only run e.g. linting and a test pipeline and running the full build pipeline only when creating a PR against `supercollider/supercollider`.
I like the idea of making life *harder* for Microsoft, but even though Azure uses green energy according to their marketing material, we should not waste resources.

## Plan for Implementation

I could take care of this once it is agreed upon which CI steps to skip in forks and which not to skip.

**Comment by dyfer** [comment]
Thanks @capital-G 

I have certainly thought about limiting CI in general, but when this was discussed in the dev meetings, the feedback I got was typically to keep it running so that we can catch problems early.

Also, the typical run is not 1 day, but rather 30-45 mintues. It seems that you haven't updated your `develop` branch and the outdated linux build holds up the suite for one day. Also, it's not Windows builds that typically fail, but one of the tests.

The weekly builds are there to refresh cache (particularly the one for homebrew universal binaries) so that builds on non-default branch can use that; without the automated build, the cache for the repository grows really quickly beyond 10GB.

Also, it's not feasible with the current GHA and our matrix structure to only build one linux build and run tests, unfortunately there's no conditional (AFAIK) to run selected jobs from the matrix. The only solution IIUC is to created matrix dynamically, and makes the whole workflow file even less readable.

----
In any case, I'm open to making the build matrix more configurable, but I think each repository should be able to make a decision when to run the builds (scheduled, every push, every push on protected branches, PRs only etc). I _think_ one way to implement this would be to use secrets in conditions for each scenario, which then can be set individually in different repos.

**Comment by dyfer** [comment]
@capital-G I forgot to mention that you can also disable all CI on your fork, if you don't need it (e.g. if you only need it for PRs to the main repo). However, all my previous points still stand, particularly the one about updating the `develop` branch on your fork.

**Comment by capital-G** [comment]
Lets do some maths :)
SC has currenty 700 forks (although many of them probably pre-github-actions).

The latest CI pipeline on main had an aggregated runtime of 3 hours: https://github.com/supercollider/supercollider/actions/runs/5300817821/usage

I am unsure about the server load on each step, but build steps are normally really maxing out the CPU, but probably GitHubCI does not give access to the whole CPU, so lets use 800 Watt/h (but this could also be also around 400?)

$$
700~\text{forks} \cdot \frac{3~\text{hours}}{\text{fork}} \cdot \frac{\approx 0.8~\text{kW}} {\text{hour}} \cdot \frac{1}{\text{week}} \approx \frac{1,680~\text{kW}}{\text{week}}
$$

In Germany its around [385 g of  CO2 per kwH](https://www.statista.com/statistics/1290224/carbon-intensity-power-sector-germany/), so the pipeline emits $\approx 650~\frac{\text{kg CO}_2}{\text{week}}$ in a worst case scenario (all forks are using an github-ci commit state and the server is consuming 800 Watt/h), which is about a 300 KM drive with a car, which sums up to 15000 KM in a year.

Even if Microsoft would use "carbon-free energy" on their servers, nonetheless its a waste of energy IMO that could have been used instead to replace non-carbon-free energy as power is always a limited resource.

I still don't follow why running the CI only when doing a PR shouldn't be sufficient for most use cases.
The main repo should run as much CI as it wants b/c in the end it really helps developing, but forks could use PRs (e.g. draft) to trigger CI builds which then also allows to catch errors early through the CI.

**Comment by dyfer** [comment]
Thanks for all the calculations, it's good to have such reference.

> The latest CI pipeline on main had an aggregated runtime of 3 hours:

Not sure what changed recently, but typically it should be around 2 hours: https://github.com/supercollider/supercollider/actions/runs/4904305550/usage
That's still a lot and I do acknowledge all your points about considering the resources

However, since you seem to be keen on accuracy, I'd like to point out that you did not acknowledge or correct the erroneous statement in your original message ("1 day of CPU time" and "failed Windows build").

> I still don't follow why running the CI only when doing a PR shouldn't be sufficient for most use cases.

There are two issues here:
1. other developers' preference to run on every push
2. updating the cache using the weekly build, so that macOS builds don't take extra 20-40 minutes for each build _and_ extra 1.5GB of cache space (arguably, this is needed only when running _other_ builds, i.e. on the main repo - for PRs -  and for developers who want/need CI)

Re: 1. I personally feel it would be enough to run CI on PRs and on main/protected branches, but in the dev meetings other devs expressed the desire to keep the CI running on all pushes. 

Re: 2. This came up when we moved to universal binary builds and for that we are assembling universal binaries of Qt5 (and some other libraries, but Qt5 is the "worst offender", size-wise). The cache from just that is ~1.3GB for the main macOS build, on top of homebrew download cache, build caches, etc etc. With this in mind, a single complete build for all platforms takes about 2.5GB (or even more, I haven't tallied it up exactly) between build caches, Qt caches, homebrew downloads cache and homebrew "universal binary" cache.
Cache for homebrew universal binary and homebrew downloads is almost 2GB between all the builds. If cache is not refreshed weekly, this will be stored in cache for every push on a new branch. So effectively we reach you'd reach the cache limit after just 4 builds on different branches that happen within a week. So, a weekly build on a fork saves caching time and space.
BTW once we move to Qt6 we'll be able to use official Qt (available as universal build), so the worst offender of the caching will go away, potentially removing the need for refreshing the cache and thus the weekly builds.

I'm still happy to consider changes to this, but I want to make sure that everybody understands the tradeoffs. 
Again, for your own for, you can just disable GitHub actions if you only need them for PRs - it will run once PR is submitted to the main repo.

The important part here is that we should consider runs on pushes to non-protected branches and the weekly CI under one "condition". I'm open to consider disabling this for forks, but I think that if we do so, it should be configurable (e.g. using secrets).

**Comment by capital-G** [comment]
> However, since you seem to be keen on accuracy, I'd like to point out that you did not acknowledge or correct the erroneous statement in your original message ("1 day of CPU time" and "failed Windows build").

Sorry, you are indeed right about this :) Just updated my main branch, thanks for the hint.


> The important part here is that we should consider runs on pushes to non-protected branches and the weekly CI under one "condition". I'm open to consider disabling this for forks, but I think that if we do so, it should be configurable (e.g. using secrets).

I think an opt-in through secrets would be indeed a very good choice?

> Thanks for all the calculations, it's good to have such reference.

I am not sure if this is serious or with a light smirk because I feel always uncomfortable using numbers as arguments because they suggest some kind of objectivity.
But nonetheless, I had no clue about the actual footprint myself and found it one way to try to estimate the actual impact.

Maybe a solution could be to discuss a switch to an opt-in ci through secrets for forks in regards to the footprint on the next dev meeting? If this doesn't find full support there is nothing that can be done and we keep it as is.

BTW, thanks for maintaining the pipeline, I know that CI pipeline is very valuable but not the nicest thing to maintain :)

**Comment by dyfer** [comment]
> I am not sure if this is serious or with a light smirk because I feel always uncomfortable using numbers as arguments because they suggest some kind of objectivity.

90% serious, 10% smirk :) 
I genuinely value the data reference and I was curious myself about the resource footprint (though never enough to follow up and do the math). The smirk part was due to some missed assumptions - e.g.  GH disables CI after some period of inactivity on the repo (30 or 60 days?), so likely most old forks are not a problem here. Only the few (few dozen?) that are updated semi-regularly.

> I think an opt-in through secrets would be indeed a very good choice?

Yes, I like that too.

I'll do my best to remember to discuss it at the next meeting. I hope to send out a poll about that soon for a possible meeting this coming weekend. As always, everyone is welcome to attend :) if you find the time.

**Comment by capital-G** [comment]
Closed via https://github.com/supercollider/supercollider/pull/6518
