### ISSUE TITLE
Supercollider ignores system volume and disables system sounds

### ISSUE THREAD

**Issue by Wallby** [supercollider/supercollider#6078]
## Environment

* SuperCollider version: 3.12.2
* Operating system: Ubuntu 23.04 (x86-64)
* Other details (Qt version, audio driver, etc.): Qt version 5.15.8

## Steps to reproduce

Any sound really, I used the following with `ctrl` + `enter` on the server first and then the generator.
```supercollider
s.boot;

(
{
  SinOsc.ar()!2;
}.play;
)
```

## Expected vs. actual behavior

There's two issues..
* the sound produced by supercollider is unaffected by changing the system volume, even muting the system volume completely doesn´t effect the sound produced by supercollider
* all system sounds (such as the sound played upon increasing/decreasing the system volume using the keyboard) don't play while the server is running

I expect that..
* the sound produced by supercollider is scaled by the system volume and muted if the system volume is muted
* all system sounds play as normal if the supercollider server is running

The following seems related.. On booting the server the speakers output in the sound app is removed and a "dummy output" added..
![image](https://github.com/supercollider/supercollider/assets/13614975/2ee24a28-540b-41e2-83b5-944a2d4a300f)
Before booting the server and after shutting down the server there is no dummy output but the following speakers output.. 
![image](https://github.com/supercollider/supercollider/assets/13614975/e00641d3-e660-46aa-91bc-ea959de645cb)

Here is the output from booting the server..
```
-> localhost
Booting server 'localhost' on address 127.0.0.1:57110.
jackdmp 1.9.21
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2022 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 1024
JackDriver: connected  system:capture_1 to SuperCollider:in_1
JackDriver: connected  system:capture_2 to SuperCollider:in_2
JackDriver: connected  SuperCollider:out_1 to system:playback_1
JackDriver: connected  SuperCollider:out_2 to system:playback_2
SuperCollider 3 server ready.
JackDriver: max output latency 42.7 ms
Requested notification messages from server 'localhost'
localhost: server process's maxLogins (1) matches with my options.
localhost: keeping clientID (0) as confirmed by server process.
Shared memory server interface initialized
```

**Comment by dyfer** [comment]
Hello, this has to do with jack vs pulse audio servers - SC uses jack as the audio backend, and it seems that jack is set up on your system to take over the audio device. This pertains to all jack apps, so it's not _technically_ a SC issue. You may want to look up some jack vs pulseaudio online resources... sorry this is not straightforward, but this is not SC's fault.

**Comment by SimonDeplat** [comment]
Historically, on Linux, Music Software tend not to use the default audio interface, Pulse Audio, but to connect to an other interface which is called [jack](https://jackaudio.org/).

This is a command line program, which can be painful to use. Most of user use QJackCtl, a graphical interface to configure jack. You can get it with : 

`sudo apt install qjackctl`

This will allow you to start jack, and to interconnect several musical softwares together using a graphical interface.

Please note that SuperCollider launches jack when you boot the server, and QJackCtl might not detect the jack instance that SC started. So you should start jack first, using QJackCtl, then boot the SuperCollider server (which will detect jack automatically). This also prevents some issues when you changed your hardware interfaces.

When jack is started, if you only have one output source, then Pulse Audio has not way to output sound. This prevents Firefox from playing sound for example, because it does not connect to jack directly. But you can reroute Pulse Audio sound into Jack : see [this thread](https://askubuntu.com/questions/572120/how-to-use-jack-and-pulseaudio-alsa-at-the-same-time-on-the-same-audio-device).

**Comment by JordanHendersonMusic** [comment]
Could this issue be closed as supercollider cannot alter this without supporting pulseaudio?

**Comment by JordanHendersonMusic** [comment]
Closing. Supporting pulseaudio could be raised as another issue.
