### ISSUE TITLE
command FIFO Full again

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#613]
At least in the cocoa version of SCapp, the (good old) problem is, after a while of idling:

`command FIFO Full`

This can only be stopped by restarting the app (not by recompiling).

**Comment by telephon** [comment]
Feel free to reopen if it happens again.

**Comment by quarklark** [comment]
I'm also getting this same issue in 3.14.1 on mac - seems to happen every time for me if I leave my computer for a few hours.

**Comment by kamidev** [comment]
I had this a few times, too. Running 3.14.1 on MacOS 15. Leave the IDE open, close the lid, come back after few hours. Post window fills up with "command FIFO full".

**Comment by jamshark70** [comment]
Grepping the sources: `ProcessOSCPacket()` does `result = driver->SendOscPacketMsgToEngine(fifoMsg);` and if this is zero, that's when `scprintf("command FIFO full\n");` happens. (But, in CoreAudio.cpp only, so non-mac users won't see this.)

If the issue occurs when processing incoming OSC, and the queue is getting full, then I'd I guess it's probably because of a large number of messages being sent to the server too fast for them to be processed. A reasonable guess is that the language may be trying to catch up on the activity it thinks it should have been doing while the computer was asleep. So, upon waking up, it floods the server with '/status' messages. If `aliveThreadPeriod` is the default 0.7 seconds, then one hour = 3600 seconds divided by 0.7 seconds/message = 5142 messages.

Messages are popped out of the queue in the audio thread (`Run()`). So another factor could be if it takes a shorter amount of time for the language to wake up than the server. If that guess is correct, then the sequence of events would be:

1. System wake-up.
2. Language goes "omg! threads are behind schedule, catch up catch up catch up catch up now now now!!" = slamming the server with messages.
3. If audio hasn't awakened quickly, `Run()` isn't being called and nothing is taking messages out of the queue.

As for a solution, I'm not sure. What is the desired behavior when waking the language from sleep? *Should* it try to "catch up"? Or, maybe the language needs to get sleep and wake signals from the system, and on that basis, stop or play the server's aliveThread.

(FWIW I've always assumed that a complicated, timing-sensitive application like SC may have problems after suspend, so I tend to not leave it open at that time.)

**Comment by JordanHendersonMusic** [comment]
Someone could add some logging code so we know what osc messages are clogging things up
