### ISSUE TITLE
[sclang] Recursive method call crash

### ISSUE THREAD

**Issue by smrg-lm** [supercollider/supercollider#628]
Hi

This recursive method call crashes sclang

// class file
TestRec {
        var parent;
        var <count = 1;

```
    *new { arg parent;
            ^super.new.init(parent);
    }

    init { arg p;
            parent = p;
            if(parent.notNil) {
                    count = parent.count + 1;
            } {
                    count = 1;
            };
    }

    rec {
            ^if(parent.notNil) {
                    (count + parent.rec); // this ops seems to crash
                    count.postln;
            } {
                    count.postln;
            }
    }
```

}

// test file
(
r = [TestRec.new];
1000000.do({ // >= 512 crahes sclang
        r = r.add(TestRec.new(r.last));
});
)
r.last.rec;

I have no further idea about this but it should not stop the lang I guess.

**Comment by brianlheim** [comment]
Closing per discussion.

**Comment by smrg-lm** [comment]
@brianlheim what? Is not to discussing the point here?

**Comment by smrg-lm** [comment]
but... it still crashes :'-(

**Comment by brianlheim** [comment]
@smrg-lm Multiple people agreed that this (meaning stack overflow) is reasonable behavior and that the problem is in your code. I'm not sure what there is to discuss?

**Comment by smrg-lm** [comment]
@brianlheim ok, I don't get it but is ok.

**Comment by telephon** [comment]
I try to explain: when you do recursion without tail call optimization, your depth is limited to the current thread's stack size - in the default thread it is `512` (see Thread.sc).

There are two strategies to make possible what you want:

1. design your code so that it can be tail call optimized (recursion call last in function)
2. run your code in a `Routine` that has a very large stack. You can create one that is large enough by passing the `stackSize` argument in. There is a method `forkIfNeeded` that you can use inside your recursion and it'll only crate a routine if there is none already. It takes `stackSize` as an argument.

**Comment by miguel-negrao** [comment]
> I try to explain: when you do recursion without tail call optimization, your depth is limited to the current thread's stack size

Worth noting this is true in any language, from C to Haskell, it has nothing to do with SuperCollider...

**Comment by smrg-lm** [comment]
I guess there is no way for sclang to prevent the crash in those cases. Thanks for the explanations and hints, they are needed.

**Comment by jamshark70** [comment]
> design your code so that it can be tail call optimized (recursion call last in function)

And, if you're going to rely on this, check the byte codes carefully.

One thing that is tricky about this is that recursive functions must have an exit branch -- at minimum, you have to have `if(condition)`, and one of the branches contains the recursive call while the other returns a value. *Fortunately*, when SC inlines an `if`, it *does* apply tail call optimization to both branches!

```
f = { |n|
	if(n > 1) {
		n * f.value(n - 1)
	} {
		1
	}
};

f.def.dumpByteCodes
BYTECODES: (19)
  0   30		 PushTempZeroVar 'n'
  1   64       PushSpecialValue 1
  2   E9       SendSpecialBinaryArithMsg '>'
  3   F8 00 0B JumpIfFalse 11  (17)
  6   30		 PushTempZeroVar 'n'
  7   17       PushInstVar 'f'
  8   30		 PushTempZeroVar 'n'
  9   61       PushOneAndSubtract
 10   C2 06    SendSpecialMsg 'value'
 12   B0       TailCallReturnFromFunction
 13   E2       SendSpecialBinaryArithMsg '*'
 14   FC 00 01 JumpFwd 1  (18)
 17   64       PushSpecialValue 1
 18   F2       BlockReturn
```

Bytecode 12 is part of the *true* branch. Lexically, this is not the last thing in the function, but in fact, if execution goes into this branch, it *is* the return value, so this is correct. (I wasn't sure it would do this -- the SC compiler is smarter than I expected.)

*BUT* the recursion is not stack-optimized. The return value is the result of the multiplication, *not* the recursive call directly. So `f.value(300000)` crashes (I tried it).

But if you rejigger it to pass the product down the recursive chain, then `f.value` can be the last thing in the true branch. `f.value(300000)` now returns a garbage result because it exceeds numeric precision, but it doesn't crash.

```
f = { |n, product|
	if(n > 1) {
		product = (product ?? { 1 }) * n;
		f.value(n - 1, product)
	} {
		product
	}
};
```
