### ISSUE TITLE
`brew_install_universal` script and `verify_app`

### ISSUE THREAD

**Issue by dyfer** [supercollider/supercollider#6480]
There have been some issues in macOS universal build lately so I wanted to clarify the currently used mechanisms so that we can choose the best path forward.

## `brew_install_unviersal` script

The reason for having this [script](https://gist.github.com/dyfer/6c83905d4593750105897e51e87ec345) is to get arm64/x86_64 libraries (`Qt`, as well as `portaudio`, `fftw`, `readline`, `libsndfile` and its dependencies) on macOS x86_64 runners. Official Qt5 does not provide arm64 binaries, so there was no easy alternative way to get the arm64 binaries on an Intel machine. Other libraries can be cross-compiled, e.g. with `vcpkg`, which we did originally.
The script was created before arm64 runners were available. More details can be found in the original PRs: #5869 and #5953. The script is definitely a "hack" or a "workaround": it may in some cases create libraries with inconsistent versions; it also takes a relatively long time to process the libraries.
This was the only way I could think of at the time of creating either arm64 or "universal" macOS builds.

## verify_app

This is part of CMake's [BundleUtilities](https://cmake.org/cmake/help/latest/module/BundleUtilities.html) and we use it to make sure that the macOS bundle includes all the linked libraries. What creates our application bundle on macOS is Qt's `macdeployqt` utility. It sometimes misses libraries and these need to be patched manually, see [here](https://github.com/supercollider/supercollider/blob/develop/editors/sc-ide/CMakeLists.txt#L499-L512). `Verify_app` also doesn't seem to properly process `@rpath`s in the loading paths, potentially falsely reporting them as missing dependencies. This can be observed with the official Qt5 libraries, as they use rpaths, thus (as of Qt5 builds) `verify_app` is disabled on the macOS legacy build ([more details in this PR](https://github.com/supercollider/supercollider/issues/5294)). Qt5 from homebrew does not use rpaths and verify_app works fine with it. That might be changing with Qt6 in homebrew, I'm still investigating this.

## recently failing `verify_app`

The failures that lead to [disabling verify_app in CI](https://github.com/supercollider/supercollider/pull/6358) happened because something was off with the "universal" libraries prepared by the `brew_install_universal` script. I believe the issue was addressed by running homebrew install for all packages first and re-enabling checking for updated dependents, before assembling the "universal" binaries (#6469). 
If verify_app fails, it likely means that the build won't run (aside from the situation when rpaths are used, as described above). 

## path forward

Now that arm64 runners are available, creating arm64 builds is much more feasible. Additionally, official Qt6 libraries for macOS come as "universal" x86_64/arm64 binaries, so these can also be used to create the app in either architecture. However, in order to create a "universal" app, we still need to have "universal" version of `libsndfile`, `fftw`, `portaudio`, and `readline`. I have experimented with using `vcpkg` for this, but unfortunately not all of the dependencies of the libraries that we use can be built in vcpkg as universal (vcpkg does not officially support making multi-architecture binaries; it works only for some packages). 

Eventually we should probably stop using this script. I am preparing another issue to discuss provided builds and supported OSs and I'd like to discuss the future build approach there. 

If there's anything I can clarify further about the script, or (to some extent) verify_app, let me know.

**Comment by capital-G** [comment]
Thanks so much for sharing your expertise on these topics, especially all the work and maintenance that you put into this, much appreciated!

> However, in order to create a "universal" app, we still need to have "universal" version of `libsndfile`, `fftw`, `portaudio`, and `readline`. I have experimented with using `vcpkg` for this, but unfortunately not all of the dependencies of the libraries that we use can be built in vcpkg as universal (vcpkg does not officially support making multi-architecture binaries; it works only for some packages).

We could use MacPorts for this, they provide universal builds for all these libraries (except Qt), and my CI tests with MacPorts worked [somehow well](https://github.com/capital-G/supercollider/actions/runs/10848960432/job/30107205221) by using https://github.com/melusina-org/setup-macports - see

* https://ports.macports.org/port/libsndfile/details/
* https://ports.macports.org/port/fftw-3/details/
* https://ports.macports.org/port/portaudio/details/
* https://ports.macports.org/port/readline/details/

While this introduces *yet another* tool into our CI I think it seems like a clean way to obtain universal builds?

In general, I think it would also be fine to do separate builds arm64 and x64_86 builds for macOS as universal builds seem like a delicate thing and maybe time is better spend on other things?
Also have in mind that [macOS-14 runners are only available for arm](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories), so instead of spending time on x64->arm cross compilation we should focus on arm->x64 cross compilation (assuming apple supports this).

**Comment by dyfer** [comment]
> While this introduces _yet another_ tool into our CI I think it seems like a clean way to obtain universal builds?

Yeah, I want to be definitely careful about _yet another tool_. I don't rule this out though. More in a separate issue.

> so instead of spending time on x64->arm cross compilation we should focus on arm->x64 cross compilation (assuming apple supports this).

Both ways should be fine. If we do separate builds, I'd do x64 on macOS 13 and arm64 and macOS 14, for the time being. More in a separate issue.

**Comment by capital-G** [comment]
Isn't the native version of cmakes `verify_app` simply

```shell
codesign --verify --deep --strict --verbose=2 build/Install/SuperCollider/SuperCollider.app
```

Why not use this?

**Comment by dyfer** [comment]
In https://github.com/supercollider/supercollider/pull/6489 I plan to remove universal builds and introduce separate ones for x64 and arm64. I think #6489 will close this issue.
