### ISSUE TITLE
revamping supercollider IDE UI using QML

### ISSUE THREAD

**Issue by tmm88** [supercollider/supercollider#6517]
# revamping supercollider IDE UI using QML

## Motivation
**supercollider UI has not seen any updates for over 10 years**

## Description of Proposed Feature
**my goal is to propose:**
- *supercollider UI revamping*
- *this shall be done in QT*
- *primitives for the UI should be implemented from scratch using QML*
- *they should look stunning*

## Plan for Implementation

- *just talk with tim blechmann from native instruments, and scott wilson from beast, and discuss the possibility to do this*
- *it shouldn't take more long then 1 or 2 weeks*

**Comment by JordanHendersonMusic** [comment]
Qml doesn't really have anything to do with revamping with ide - there are benefits, but it doesn't bring about a better design automatically. Revamping the ide can be done now. IMO, what is lacking is someone to identify ui issues and design solutions - implementing most gui code is pretty trivial.

**Comment by tmm88** [comment]
***if you take a look at tools like YECO (the ableton 3rd party frontend), and the software tools developed by imaginando, as a quite great example of fairly decent UIs prototyped and developed and integrated with QML, you sort of grasp the idea of what i am talking about***

**Comment by JordanHendersonMusic** [comment]
Yes but a new tool does not just give you a new design... you have to actually do the design work. If it turns out the new designs are only possible or significantly easier in QML, then (IMO) it might be worth considering it. 

As it stands, I think this issue should be closed and a series of new issues opened that explicitly state what is lacking in the current design and suggest/discuss fixes.

**Comment by tmm88** [comment]
feel free to close this thread. I feel like this is important for the future of supercollider development. but I acknowledge that the supercollider community may not acknowledge some of my perspectives about the future of supercollider development, not only because of a certain set of measures related to trends in c++ qt based software development policies, but also within certain regards, because of a whole set of things, that have more like something to do within the stability of the software on the longer run, avoiding errors, crashes, bugs, and collapses, and a whole set of other things

**Comment by JordanHendersonMusic** [comment]
> stability of the software on the longer run, avoiding errors, crashes, bugs

What you are proposing here is not simply using QML to implement GUI, but to use QML **and** Qt widgets. That is double the instability, errors, crashes, and the bugs. Additionally, the current system has been extensively tested over decades whereas the new one won't be. 

If we were starting from scratch, QML would probably be the correct choice as it is great — but we aren't. 

I'm going to close this, not because QML doesn't have value, but because the goal is to improve the IDE's UI. This should be done by first identifying what is wrong, discussing and proposing new designs, and only finally considering what technology is used to implement it — this issue has this in reverse. 

@tmm88 I appreciate where the intention behind this issues comes from —the IDE **does** need some love!— but I think it would be more beneficial to focus on specifics first. A great way to contribute to this would be by opening issues that deal with the intricacies of the design and proposing new idea, even if they are not perfect, as creating a conversation about this would be highly valuable. You might even consider doing this over on scsynth where more users hangout. I have recently done this myself but on the topic of patterns, and have made a few (albeit small) PRs based on what people have said.

**Comment by capital-G** [comment]
I think the question is *who* is going to do *what* and *why*. Just moving our code base to a new framework seems a bit pointless to me, since I found the IDE code on the easier side of this project to dig into.
Also, I think everyone is fine with answering questions about their code implementations, but imposing volunteers to do additional work is not considered a nice move and may leave a sour taste.

On the other hand, feel free to organize an agreement within the community *what* should be changed and implement and propose those changes via a PR. I think nobody will hold off any improvements, but until then I'll close this issue.
