### ISSUE TITLE
ScIDE class has no help doc

### ISSUE THREAD

**Issue by danstowell** [supercollider/supercollider#670]
The "ScIDE" class has no help doc. It has some methods... I would like to learn what I can do by invoking those methods...

**Comment by LFSaw** [comment]
I started to fill in some of the methods to eventually put together a PR on this. However I got stuck pretty soon because of this ominous "id" which is used to communicate with the seemingly central primitive in `ScIDE:*prSend`. 
@timblechmann, AFAIK, you were part of the team writing this class (correct me if I'm wrong), could you help us here? Thanks!

**Comment by snappizz** [comment]
#2434
