### ISSUE TITLE
Auto-generated link at top of tutorials eg "Tutorials>Getting-Started" should be two links not one, reflecting the navigation hierarchy

### ISSUE THREAD

**Issue by danstowell** [supercollider/supercollider#692]
Go to the home page, click the link to the gettingstarted tutorial. At the very top there's a link "Tutorials>Getting-Started" but it's a single link, whereas "Tutorials" should link to the list of tutorials, and "Getting-Started" should link to the listing of that tutorial.

**Comment by patrickdupuis** [comment]
I noticed that if you change the categories at the beginning of `SinOsc.schelp` from

`categories::  UGens>Generators>Deterministic` 
to
`categories::  UGens,Generators,Deterministic` 

you get a separate link for each element. Looks like the issue here is that many help files are written incorrectly.

**Comment by snappizz** [comment]
@patrickdupuis i think that's because by using commas, you are putting it separately in the top-level categories "UGens", "Generators", and "Deterministic"

**Comment by brianlheim** [comment]
The relevant code is here: https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/SCDoc/SCDocRenderer.sc#L146-L153

**Comment by patrickdupuis** [comment]
I see what happens now. SinOsc only appears in those top-level categories, and not in UGens -> Generators -> Deterministic.

Thanks for pointing to the relevant code @brianlheim!
