### ISSUE TITLE
plugins: review error handling of memory allocations

### ISSUE THREAD

**Issue by timblechmann** [supercollider/supercollider#782]
many plugins don't perform null pointer checks to ensure that rt memory allocation actually succeeds. instead of a nice error message, the effect is usually a server crash

**Comment by vivid-synth** [comment]
We may need a few people to split the work up of identifying these UGens (I'll volunteer to be one!). This actually is important work: server crash under high memory use is no good.

**Comment by snappizz** [comment]
There's also hella ground to cover in sc3-plugins.

**Comment by vivid-synth** [comment]
Good point1 I created https://github.com/supercollider/sc3-plugins/issues/110 . I'd personally be happy to start by covering this repo's UGens: the plugins have a little less expectation of always working.

**Comment by snappizz** [comment]
I grepped for RTAlloc and looked at each instance for like 10 seconds to check for an `if` statement. Here are the files I checked and the offenders I found:

- **Convolution.cpp:** Convolution, Convolution2, Convolution2L, StereoConvolution2L, Convolution3
- **DelayUGens.cpp:** MaxLocalBufs (?), Pitch, PitchShift
- **DemandUGens.cpp:** none
- **FeatureDetection.cpp:** PV_OnsetDetectionBase, RunningSum
- **FFT_UGens.cpp:** FFT, IFFT
- **FilterUGens.cpp:** Normalizer, Limiter
- **GendynUGens.cpp:** Gendy1, Gendy2, Gendy3
- **GrainUGens.cpp:** GrainIn, GrainSin, GrainFM, GrainBuf
- **IOUGens.cpp:** AudioControl, LagControl, OffsetOut, LocalIn
- **PartitionedConvolution.cpp:** PartConv, PreparePartConv function
- **PV_UGens.cpp:** PV_RandComb, PV_RandWipe, PV_Diffuser, PV_MagFreeze, PV_BinScramble
- **ReverbUGens.cpp:** GVerb
- **TriggerUGens.cpp:** none

There may be false positives, and a few that are missed because they're buried in macros.

I think it's all a matter of laziness because this is the boilerplate necessary to implement that check:

    if (unit->buf == NULL) {
        SETCALC(ft->fClearUnitOutputs);
        ClearUnitOutputs(unit, 1);

        if(unit->mWorld->mVerbosity > -2) {
            Print("Failed to allocate memory for FooBar ugen.\n");
        }

        return;
    }

We should reduce this to a macro or function to make it easier to add the check.

**Comment by vivid-synth** [comment]
@snappizz awesome, this looks very doable.

**Comment by snappizz** [comment]
I should really put this in a PR, but how does this look? I'm sure SC_PlugIn.h needs more macros like I need a hole in the head...

    // Sets unit outputs to zero and displays a standard error message. Use if RTAlloc failed.
    #define RTALLOC_FAILED(name) \
        SETCALC(ft->fClearUnitOutputs); \
        ClearUnitOutputs(unit, 1); \
        if (unit->mWorld->mVerbosity > -2) { \
            printf("Real-time memory allocation failed in UGen '%s'.\nThe server has most likely run out of memory.",
                (name)); \
        }

    // Returns out of the current function if mem is a null pointer.
    // Use this if you're immediately inside the Ctor function.
    #define RTALLOC_CHECK(mem, name) \
        if (mem == NULL) { \
            RTALLOC_FAILED(name) \
            return; \
        }

**Comment by vivid-synth** [comment]
Maybe this should be the default ```RTALLOC``` macro, and we can name the other "RTALLOC_NO_CHECK"? This way, when people reach for ```RTALLOC``` they're reaching for the "correct" behavior by default?

**Comment by vivid-synth** [comment]
Or alternately, we get rid of "RTALLOC" and instead only have "RTALLOC_CHECK" and "RTALLOC_NO_CHECK", to clarify authors' intentions?

**Comment by snappizz** [comment]
We definitely shouldn't tamper with `RTAlloc`. That would break a lot of code.

I'm coming at this as an inexperienced C++ developer, but complex macros introduce problems. The more stuff you put in them, the less portable and the more awkward they become. For example, `RTALLOC_CHECK` only works if you're immediately inside the Ctor function. It's a tradeoff between convenience and robustness.

I recommend that we leave it at `RTALLOC_FAILED`, since it provides a standardized error message.

**Comment by snappizz** [comment]
Coming back to this, my macro proposal is a pretty poor idea. Maybe there is a better solution using `std::exception`.

**Comment by mtmccrea** [comment]
@snappizz I'm in favor of this addition.

I often see in this check for failed allocation that `mDone` is also set to `true`. I'm a bit unclear of the circumstances where `mDone` is actually used (other than triggering `doneActions`), but should this be included in `RTALLOC_FAILED`?

Any plans on building this type of check into `SCUnit` while it's still "young"?
