### ISSUE TITLE
SC-IDE: minor detail: add space after colon in autocompletion of method calls

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#831]
When adding keywords in autocompleting method- and function calls, a space between the colon and the insertion point would be good style.

Example:

Pbind(\freq, 460).play(quant:1);

Pbind(\freq, 460).play(quant: 1);

**Comment by patrickdupuis** [comment]
We need to add a space after the colon in line 1125 of autocompleter.cpp

`text.append(": ");`

However, this causes the cursor to move further to the right every time you press TAB to cycle through the arg names. I'm not sure what the correct fix is. Maybe we need to use text.lenght instead of argNameToken->length on line 1131?

` cursor.setPosition(pos + text.lenght, QTextCursor::KeepAnchor);`

**Comment by telephon** [comment]
Maybe move the cursor forward not when the `TAB` is cycled, but when the next key is pressed? You may need to keep a flag around for that like `insertSpace = true`.
