### ISSUE TITLE
regions in regions: outermost one is always chosen

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#832]
I'm not sure whether this is intentional, but it is surprising for others, too.
When you evaluate a region in a region, you'll get the outermost region. In SC, often one has programs with subprograms, where you can choose whether to evaluate just a part or the whole.
Are there reasons for not doing this?
```supercollider
(
"I didn't want to evaluate this".postln;

(
5 + 4; // evaluate region applies here to the whole
"But only this" + "region"
)

)
```

**Comment by scztt** [comment]
I suppose I would say - outer region is the only thing that's reasonable. Anything that's not an outermost region could be simply parentheses for grouping / method call purposes (which, of course, wouldn't execute). The outermost are the only ones guaranteed, by convention at least, to be an executable code block. Even a special keyboard shortcut for executing inner paren regions would be weird and inconsistant, since it could easily fail to work depending on the exact placement of your cursor.

**Comment by telephon** [comment]
In the current conventions of code formatting in sclang, parentheses which are positioned after/before a newline respectively (i.e. ````\n(```` and ````)\n```` are taken as a ````region````. Fully navigating nested regions isn't necessary, we only need the possibility to distinguish between outermost and innermost region.

**Comment by telephon** [comment]
>Even a special keyboard shortcut for executing inner paren regions would be weird and inconsistant, since it could easily fail to work depending on the exact placement of your cursor.

what would be an example (supposing that you take only parentheses in combination with the newlines)?

**Comment by brianlheim** [comment]
Closing due to lack of consensus. However, referenced [here](https://github.com/supercollider/supercollider/projects/3).
