### ISSUE TITLE
SCDoc shows getters where there are only setters

### ISSUE THREAD

**Issue by muellmusik** [supercollider/supercollider#837]
Or so it would seem. For example NetAddr:useDoubles_ shows up in the help as a getter/setter pair, although there's only a setter. Don't know if that happens in reverse as well.

**Comment by jamshark70** [comment]
Hm, any way to push up the priority on this? This isn't a common case, but it's serious.

There is accidentally wrong information in an unknown number of correctly-written help files, and *no way to suppress the wrong information* (because it's generated by the renderer).

E.g.,

```
MultiSliderView.findRespondingMethodFor(\thumbSize_);
-> MultiSliderView:thumbSize_

MultiSliderView.findRespondingMethodFor(\thumbSize);
-> nil
```

But MultiSliderView help shows:

> -thumbSize
> -thumbSize = float
> Sets both -indexThumbSize and -valueThumbSize to the argument.

This leads unsuspecting users to believe they can do `myMultiSlider.thumbSize` and get a meaningful result, but instead they get a DoesNotUnderstand error.
