### ISSUE TITLE
QView doesn't receive all key down actions

### ISSUE THREAD

**Issue by telephon** [supercollider/supercollider#918]
The attempt to respond to a combination of a modifier and a key down action fails with QView. This means that we can't implement cmd-period on sclang.

    (
    w = Window("test").front;
    w.view.keyDownAction = { |v, key, mod| 
                                 [v, key, mod.isCmd].postln;      
                                 if(mod.isCmd) { "received cmd" + k } 
    };
    )

**Comment by scztt** [comment]
Cmd+Period currently works in sclang, as do cmd+____ combinations (at least, ones that don't already get caught by the window manager). The OP example code behaves weirdly because trying to print an ascii 0 character screws up subsequent postln's - that behavior is fixed with #1492, which avoids passing the ascii 0 at all. We may consider it a bug that printing ascii 0 behaves strangely - but I don't really know what the appropriate behavior is in that case, so I'm more inclined to simply say "don't do that".

**Comment by scztt** [comment]
@telephon - wanna close?
